SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Sssh!\n"
    .string "Can't you see I'm hiding?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "Huh? TEAM CORPUS is gone?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "TEAM CORPUS has taken control of\n"
    .string "SILPH CO.!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "Fwahahaha!\n"
    .string "My BOSS has been after this place!$"

SilphCo_4F_Text_RodneyIntro::
    .string "My DAEMONS is my loyal servant.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Darn! You weak DAEMON!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "The doors are electronically\n"
    .string "locked.\p"
    .string "It takes a CARD KEY to open the\n"
    .string "doors here.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "Intruder spotted!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "Who are you?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "I better tell the BOSS on 11F!$"

SilphCo_4F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "4F$"

