SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Sssh!\n"
    .string "Can't you see I'm hiding?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "Huh? TEAM CORPUS is gone?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "CORPUS has acquired SILPH CO. as\n"
    .string "of today!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "Regrettable.$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "This was on our roadmap for some\n"
    .string "time!$"

SilphCo_4F_Text_RodneyIntro::
    .string "My DAEMONS are my loyal soldiers!$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Darn! You weak DAEMON!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "The doors are electronically\n"
    .string "locked.\p"
    .string "It takes a CARD KEY to open the\n"
    .string "doors here.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "Unbadged visitor!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "Are you with us?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "I'll raise this with 11F.$"

SilphCo_4F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "4F$"

