SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "…Wait! Don't say a word!\p"
    .string "You wanted this!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} received TM29 from MR.\n"
    .string "CONSTRUE.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "You already know, don't you? TM29\n"
    .string "is CONSTRUE.\p"
    .string "It's an attack that may also lower\n"
    .string "the target's special stats.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Where do you plan to put this?\n"
    .string "You've no room.$"

