CeladonCity_Condominiums_1F_Text_Meowth::
    .string "COOKIE: Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "You shouldn't spend all your money\n"
    .string "on drinks.\p"
    .string "Try this instead.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nothing beats thirst like some hot\n"
    .string "TEA.\p"
    .string "It really is the best.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "My dear DAEMON keep me company.\n"
    .string "COOKIE even brings money home!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
	.string "Oh, hello, dearie. Did you enjoy\n"
	.string "my TEA?\p"
	.string "A girl from BLANCHE TOWN, VERA,\n"
	.string "comes in for TEA.\p"
	.string "VERA says CRYSTAL's instruments\n"
	.string "are very good.\p"
	.string "And that she prefers to look.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "ANOMALY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "FORK: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "VERDIGRIS MANSION\n"
    .string "Manager's Suite$"

