CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "INTERRUPT wakes DAEMON with a\n"
    .string "sound that only they can hear!$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "I rode uphill on CYCLING ROAD from\n"
    .string "LURID!$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "If I had a BIKE, I would go to\n"
    .string "CYCLING ROAD!$"

