Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "I'm on a relaxing ride on my new\n"
    .string "bike with my girlfriend.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "We're going riding together on our\n"
    .string "new bikes.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "Looked into the binoculars.\p"
    .string "It's the VERDIGRIS DEPT. STORE!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a long path over water far\n"
    .string "away.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "Hi! Remember me? I'm one of\n"
    .string "CRYSTAL CLEAR's AIDES.\p"
    .string "If your INDEX has complete data\n"
    .string "on 40 species, I'm supposed to give\l"
    .string "you a reward.\p"
    .string "CRYSTAL CLEAR entrusted me with an\n"
    .string "AMULET COIN for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "40 kinds of DAEMONS?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "Great! You have bound or owned\n"
    .string "{STR_VAR_3} kinds of DAEMONS!\p"
    .string "Congratulations! Here you go!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER} received the AMULET COIN\n"
    .string "from the AIDE.$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "An AMULET COIN is an item to be\n"
    .string "held by a DAEMON.\p"
    .string "If the DAEMON appears in a winning\n"
    .string "battle, you will earn more money.$"

