FuchsiaCity_Text_DidYouTrySafariGame::
    .string "Did you try the SAFARI GAME?\p"
    .string "There are some rare DAEMON that\n"
    .string "can only be bound there.$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "The SAFARI ZONE has a zoo in front\n"
    .string "of the entrance.\p"
    .string "Out back is the SAFARI GAME for\n"
    .string "binding DAEMONS.$"

FuchsiaCity_Text_WheresSara::
    .string "ERIK: Where's SARA?\n"
    .string "I said I'd meet her here.$"

FuchsiaCity_Text_ItemBallInThere::
    .string "That item ball in there… Were you\n"
    .string "wanting that?\p"
    .string "Me, too! …Huh? That's a DAEMON?$"

FuchsiaCity_Text_CitySign::
    .string "LURID CITY Behold! It's Passion\n"
    .string "Pink!$"

FuchsiaCity_Text_SafariZoneSign::
    .string "DAEMON PARADISE SAFARI ZONE$"

FuchsiaCity_Text_SafariGameSign::
    .string "SAFARI GAME DAEMON-U-CATCH!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "SAFARI ZONE\n"
    .string "WARDEN'S HOME$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "DAEMON PARADISE! Welcome to the\n"
    .string "SAFARI ZONE! SAFARI ZONE OFFICE$"

FuchsiaCity_Text_GymSign::
    .string "LURID CITY DAEMON GYM LEADER:\n"
    .string "KOGA The Poisonous Ninja Master$"

FuchsiaCity_Text_ChanseySign::
    .string "Name: CHANSEY\n"
    .string "Catching one is all up to chance.$"

FuchsiaCity_Text_VoltorbSign::
    .string "Name: VOLTORB\n"
    .string "The very image of a POKé BALL.$"

FuchsiaCity_Text_KangaskhanSign::
    .string "Name: KANGASKHAN\p"
    .string "A maternal DAEMON that raises its\n"
    .string "young in a pouch on its belly.$"

FuchsiaCity_Text_SlowpokeSign::
    .string "Name: SLOWPOKE\n"
    .string "Friendly and very slow moving.$"

FuchsiaCity_Text_LaprasSign::
    .string "Name: LAPRAS\n"
    .string "AKA the king of the seas.$"

FuchsiaCity_Text_OmanyteSign::
    .string "Name: OMANYTE An extremely rare\n"
    .string "DAEMON that was regenerated from a\l"
    .string "fossil.$"

FuchsiaCity_Text_KabutoSign::
    .string "Name: KABUTO An extremely rare\n"
    .string "DAEMON that was regenerated from a\l"
    .string "fossil.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Aww, I wish I was a KANGASKHAN\n"
    .string "baby.\p"
    .string "I'd love to be a substitute for the\n"
    .string "baby…\p"
    .string "And snuggle in the mother\n"
    .string "KANGASKHAN's belly pouch.\p"
    .string "But only DAEMON can use the\n"
    .string "technique SUBSTITUTE…\p"
    .string "Want me to teach SUBSTITUTE to\n"
    .string "one of your DAEMON?$"

Text_SubstituteDeclined::
    .string "Oh, really?\n"
    .string "SUBSTITUTE seems so fun…$"

Text_SubstituteWhichMon::
    .string "Which DAEMON wants to learn\n"
    .string "SUBSTITUTE?$"

Text_SubstituteTaught::
    .string "Boy, what I'd give to crawl inside\n"
    .string "a KANGASKHAN belly pouch…$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "My father is the GYM LEADER of\n"
    .string "this town.\p"
    .string "I'm training to use POISON DAEMON\n"
    .string "as well as my father.$"

