CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "It's a photo of BLAINE and\n"
    .string "MR. FUJI.\p"
    .string "They're standing shoulder to\n"
    .string "shoulder with big grins.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "We study DAEMONS extensively every\n"
    .string "day.\p"
    .string "People often bring us rare DAEMON\n"
    .string "for examination.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "A photo of the LAB's founder…\n"
    .string "DR. FUJI?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "DAEMON LAB Meeting Room$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "DAEMON LAB R & D Room$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "DAEMON LAB Testing Room$"

