SevenIsland_TrainerTower_Text_DarioIntro::
    .string "I sensed your approach.$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "Give up…$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "In your future, I sense that you\n"
    .string "will meet many others.\p"
    .string "I think you will be linked to each\n"
    .string "other by a strange power.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "Somewhere on this island, peculiar\n"
    .string "DAEMONS are sleeping.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "What an amazing USER!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "Somewhere on this island, peculiar\n"
    .string "DAEMONS are sleeping.\p"
    .string "Could it be that they're waiting for\n"
    .string "you?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "USER TOWER ENTRANCE Rise to the\n"
    .string "Challenge, USERS!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "USER TOWER AHEAD$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"

