VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "Won't you admire my SPIKE's adorable\n"
    .string "tail?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Humph! My SPIKE is twice as cute\n"
    .string "as that one!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "I just adore my CHILLER! It's so\n"
    .string "lovable!\p"
    .string "It squeals, “Kyuuuh,” when I hug\n"
    .string "it!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Oh, dear!\p"
    .string "My CHILLER is far more attractive.\n"
    .string "By double, I would say.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "SPIKE: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "CHILLER: Kyuoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "I chair the DAEMON Fan Club!\p"
    .string "I have collected over 100\n"
    .string "DAEMONS!\p"
    .string "I'm very fussy when it comes to\n"
    .string "DAEMON!\p"
    .string "So...\p"
    .string "Did you come visit to hear about\n"
    .string "my DAEMONS?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Good! Then listen up!\p"
    .string "My favorite OVERDRIVE…\p"
    .string "It's…cute…lovely…smart…\n"
    .string "plus…amazing…you think so?… oh\l"
    .string "yes…it's…stunning… kindly…love it!\p"
    .string "Hug it…when…sleeping…warm and\n"
    .string "cuddly…spectacular… ravishing…\l"
    .string "…Oops! Look at the time! I kept\l"
    .string "you too long!\p"
    .string "Thanks for hearing me out! I want\n"
    .string "you to have this!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} received a BIKE VOUCHER\n"
    .string "from the CHAIRMAN.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Exchange that for a BICYCLE!\p"
    .string "Don't worry, my FLOOD will FLY me\n"
    .string "anywhere!\p"
    .string "So, I don't need a BICYCLE!\p"
    .string "I hope you like cycling!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Oh. Come back when you want to\n"
    .string "hear my story!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Hello, {PLAYER}!\p"
    .string "Did you come see me about my\n"
    .string "DAEMONS again?\p"
    .string "No? Too bad!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Make room for this!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Our CHAIRMAN is very vocal about\n"
    .string "DAEMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Let's all listen\n"
    .string "politely to other\l"
    .string "USERS!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "If someone brags, brag right back!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "Our CHAIRMAN really does adore his\n"
    .string "DAEMON.\p"
    .string "But the person who is most liked by\n"
    .string "DAEMON is VERA, I think.$"
