Route7_EastEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Gee, I'm thirsty, though!\p"
    .string "Oh, wait there, the road's closed.$"

Route7_EastEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, that TEA…\n"
    .string "It looks awfully tasty…$"

Route7_EastEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have this drink? Gee,\n"
    .string "thanks! … … Glug, glug… … … Gulp…\l"
    .string "If you want to go to BRAZEN CITY…\l"
    .string "… … You can go on through.\p"
    .string "I'll share this TEA with the other\n"
    .string "guards!$"

Route7_EastEntrance_Text_HiHowsItGoing::
    .string "Hi, how's it going?$"

