PokemonTower_7F_Text_Grunt1Intro::
    .string "Are you here about the site?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "Conceding.$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "This will be in my notes.$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "A member of the public raised a\n"
    .string "concern about our methods.\p"
    .string "We're resolving it internally!$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Withdrawing the objection.$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "DAEMONS are an asset class.\p"
    .string "Nothing personal!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "There's nothing here to save.$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "Don't obstruct CORPUS.$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "This will be escalated.$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "MR. FUJI: Heh? You came to save\n"
    .string "me?\p"
    .string "Thank you. But, I came here of my\n"
    .string "own free will.\p"
    .string "I came to calm the spirit of\n"
    .string "CUBONE's mother.\p"
    .string "I think MAROWAK's spirit has finally\n"
    .string "left us.\p"
    .string "I must thank you for your kind\n"
    .string "concern.\p"
    .string "Follow me to my home, DAEMON\n"
    .string "HOUSE, at the foot of this tower.$"

