SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "Dance, dance! UPTIME Dance!\p"
    .string "You join in, too! Dance, dance!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "Would you like to dance?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "Come on, dance!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .string "{PLAYER} danced the UPTIME Dance!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "Ahahahaha!\p"
    .string "There, you're all chipper now!\n"
    .string "Lucky!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .string "UPTIME: Chansi! Chansi!$"
