VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "I'm getting my PACKET to fly a\n"
    .string "letter to BRAZEN in the north!$"

VermilionCity_House3_Text_Pidgey::
    .string "PACKET: Kurukkoo!$"

@  T-324, DRAFT.
VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear PIPPI,\n"
    .string "Come and see me soon.\p"
    .string "They say BRAZEN is full of\n"
    .string "TEAM CORPUS. ARDOR is quiet.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "I want to exchange MAIL with all\n"
    .string "sorts of people.\p"
    .string "I send my PACKET to a UNION ROOM\n"
    .string "to exchange MAIL for me.$"

