VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "I'm getting my PACKET to fly a\n"
    .string "letter to BRAZEN in the north!$"

VermilionCity_House3_Text_Pidgey::
    .string "PACKET: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear PIPPI, I hope to see you\n"
    .string "soon.\p"
    .string "I heard BRAZEN has problems with\n"
    .string "TEAM CORPUS.\p"
    .string "ARDOR appears to be safe.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "I want to exchange MAIL with all\n"
    .string "sorts of people.\p"
    .string "I send my PACKET to a UNION ROOM\n"
    .string "to exchange MAIL for me.$"

