Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Many DAEMONS live only in forests\n"
    .string "and caves.\p"
    .string "You need to look everywhere to get\n"
    .string "different kinds!$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Have you noticed the skinny trees\n"
    .string "on the roadside?\p"
    .string "They can be cut down by a special\n"
    .string "DAEMON move, I hear.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Do you know the evolution-cancel\n"
    .string "technique?\p"
    .string "When a DAEMON is evolving, you can\n"
    .string "stop the process.\p"
    .string "It's a technique for raising DAEMONS\n"
    .string "the way they are.$"

