SilphCo_2F_Text_ConnorIntro::
    .string "Help!\n"
    .string "I'm a SILPH employee.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "How did you know I was CORPUS?$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "I work for both SILPH and TEAM\n"
    .string "CORPUS!$"

SilphCo_2F_Text_JerryIntro::
    .string "It's off-limits here!\n"
    .string "Go home!$"

SilphCo_2F_Text_JerryDefeat::
    .string "You're good.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "Can you solve the maze in here?\n"
    .string "It's not easy, I tell you!$"

SilphCo_2F_Text_Grunt1Intro::
    .string "This floor is badged access.\p"
    .string "Do you have a MARK?$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Escalated.$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Diamond tiles are transport pads.\p"
    .string "Facilities put them in. Very\n"
    .string "efficient!$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Do you have a meeting on this\n"
    .string "floor?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "My error.$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "SILPH CO. is joining the CORPUS\n"
    .string "family!\p"
    .string "Exciting times!$"

Text_ThunderWaveTeach::
    .string "Eeek! No! Stop! Help!\p"
    .string "Oh, you're not with TEAM CORPUS. I\n"
    .string "thought... I'm sorry. Here, please\l"
    .string "take this!$"

Text_ThunderWaveDeclined::
    .string "Oh…\n"
    .string "But THUNDER WAVE is convenient…$"

Text_ThunderWaveWhichMon::
    .string "Which DAEMON should I teach\n"
    .string "THUNDER WAVE?$"

Text_ThunderWaveTaught::
    .string "THUNDER WAVE causes paralysis in\n"
    .string "the target DAEMON.\p"
    .string "A paralyzed DAEMON may be unable\n"
    .string "to move in battle.\p"
    .string "It's an ELECTRIC-type move, so it\n"
    .string "won't work on some DAEMONS.$"

SilphCo_2F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "2F$"

