FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Fwahahaha!\p"
    .string "A mere child like you dares to\n"
    .string "challenge me?\p"
    .string "The very idea makes me shiver with\n"
    .string "mirth!\p"
    .string "Very well, I shall show you true\n"
    .string "terror as a ninja master.\p"
    .string "Poison brings steady doom. Sleep\n"
    .string "renders remote helpless.\p"
    .string "Despair to the creeping horror of\n"
    .string "POISON-type DAEMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Humph! You have proven your\n"
    .string "worth!\p"
    .string "Here! Take the SKEW MARK!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "When afflicted by TOXIC, a DAEMON\n"
    .string "suffers more and more.\p"
    .string "It suffers worsening damage as the\n"
    .string "battle wears on!\p"
    .string "It will surely terrorize remote!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Now that you have the SKEW MARK,\n"
    .string "the DEFENSE of your DAEMON\l"
    .string "increases!\p"
    .string "It also lets you SURF outside of\n"
    .string "battle!\p"
    .string "Ah! Take this too!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} received TM06\n"
    .string "from KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "Sealed within that TM06 lies\n"
    .string "TOXIC!\p"
    .string "It is a secret technique dating\n"
    .string "back some four hundred years.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Make space for this, child!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "Strength isn't the key for DAEMON.\n"
    .string "Do you understand this?\p"
    .string "DAEMON is about strategy!\p"
    .string "I'll show you how strategy can beat\n"
    .string "brute strength.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "What?\n"
    .string "Extraordinary!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "So, you mix brawn with brains?\n"
    .string "Good strategy!\p"
    .string "That's remarkable for a child USER.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "I was a magician once upon a time.\p"
    .string "But I dreamt of becoming a ninja,\n"
    .string "so I joined this GYM.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "I'm done for!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Even though I've lost, I will keep\n"
    .string "training according to the teachings\l"
    .string "of KOGA, my ninja master.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Let's see you beat my special\n"
    .string "techniques!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "You had me fooled!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "I like poison and sleep techniques,\n"
    .string "as they linger after battle!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Stop right there!\p"
    .string "The famed invisible walls of LURID\n"
    .string "GYM have you frustrated?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Whoa!\n"
    .string "You've got it!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "You impressed me!\n"
    .string "Here's a hint!\p"
    .string "Look very closely for gaps in the\n"
    .string "invisible walls!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "I also study the way of the ninja\n"
    .string "with Master KOGA!\p"
    .string "Ninja have a long history of using\n"
    .string "animals!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "I still have much to learn.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Master KOGA comes from a long line\n"
    .string "of ninjas.\p"
    .string "What did you descend from?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "You're more skilled than I'd\n"
    .string "thought!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Where there is light, there is\n"
    .string "shadow!\p"
    .string "Light and shadow!\n"
    .string "Which do you choose?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Yo! Champ in making!\p"
    .string "LURID GYM is riddled with invisible\n"
    .string "walls!\p"
    .string "KOGA might appear close, but he's\n"
    .string "blocked off!\p"
    .string "You have to find gaps in the walls\n"
    .string "to reach him!$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "It's amazing how ninja can terrify,\n"
    .string "even now!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "LURID DAEMON GYM LEADER: KOGA\p"
    .string "WINNING USERS: {RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "LURID DAEMON GYM LEADER: KOGA\p"
    .string "WINNING USERS: {RIVAL}, {PLAYER}$"

