SafariZone_West_Text_RestHouse::
    .string "IDLE HOUSE$"

@  T-324, DRAFT.
SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "REQUEST NOTICE\p"
    .string "The WARDEN has lost his TOKEN\n"
    .string "somewhere out here.\p"
    .string "Reward offered!\n"
    .string "Contact: WARDEN$"

@  T-324, DRAFT.
SafariZone_West_Text_SearchForSecretHouse::
    .string "USER TIPS\p"
    .string "ZONE EXPLORATION CAMPAIGN!\p"
    .string "The SECRET HOUSE is out here.\n"
    .string "Nobody will say where.$"

SafariZone_West_Text_AreaSign::
    .string "AREA 3\n"
    .string "EAST: CENTER AREA$"

