CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "MUSAI can evolve into 1 of 3 kinds\n"
    .string "of DAEMONS.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "There's an e-mail message!\p"
    .string "...\p"
    .string "The 3 legendary bird DAEMONS are\n"
    .string "ORPHEUS, ASCLEPIUS and\l"
    .string "PROMETHEUS.\p"
    .string "Their whereabouts are unknown.\p"
    .string "We plan to explore the cavern\n"
    .string "close to DOLDRUM.\p"
    .string "From: DAEMON RESEARCH TEAM\p"
    .string "...$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "An amber pipe!$"

