PokemonLeague_BrunosRoom_Text_Intro::
	.string "I am CHOLERIC.\n"
	.string "Second of the REVIEW BOARD!\p"
	.string "Every battle is an argument, and I\n"
	.string "have never lost one!\p"
	.string "I've lived and trained with my\n"
	.string "LOGIC daemons! And that will\l"
	.string "never change!\p"
	.string "{PLAYER}!\p"
	.string "Premise: we are stronger.\n"
	.string "Conclusion: you lose!\p"
	.string "Hoo hah!$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
	.string "I am CHOLERIC.\n"
	.string "Second of the REVIEW BOARD!\p"
	.string "I have gone over our last battle.\n"
	.string "My reasoning was sound!\p"
	.string "I've lived and trained with my\n"
	.string "LOGIC daemons! And that will\l"
	.string "never change!\p"
	.string "{PLAYER}!\p"
	.string "Premise: we are stronger.\n"
	.string "Conclusion: you lose!\p"
	.string "Hoo hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
	.string "Why?\n"
	.string "My reasoning was sound!$"

PokemonLeague_BrunosRoom_Text_PostBattle::
	.string "My job is done.\p"
	.string "I will go over that battle until\n"
	.string "I find the flaw.\p"
	.string "Go face your next challenge.$"

