SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "CAPTAIN: Ooargh…\n"
    .string "I feel hideous…\l"
    .string "Urrp! Seasick…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} rubbed the CAPTAIN's\n"
    .string "back!\p"
    .string "Rub-rub…\n"
    .string "Rub-rub…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "CAPTAIN: Whew! Thank you! I'm\n"
    .string "feeling much better now.\p"
    .string "You want to see my hidden CUT\n"
    .string "technique?\p"
    .string "I could show you my prized CUT\n"
    .string "technique if I weren't so ill…\p"
    .string "I know! You can have this! This\n"
    .string "HIDDEN MACHINE!\p"
    .string "Teach CUT to your DAEMON, and you\n"
    .string "can see it CUT anytime!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} obtained HM01\n"
    .string "from the CAPTAIN!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Using CUT, you can chop down small\n"
    .string "trees.\p"
    .string "Why not try it with the trees\n"
    .string "around ARDOR CITY?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "CAPTAIN: …Whew!\p"
    .string "Now that I'm not sick anymore, I\n"
    .string "guess it's time.\p"
    .string "The S.S. ANNE will set sail soon!\p"
    .string "Farewell, until our return to ARDOR\n"
    .string "CITY!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Oh, no!\n"
    .string "You have no room for this!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Yuck!\n"
    .string "Shouldn't have looked!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "How to Conquer Seasickness…\n"
    .string "The CAPTAIN's reading this!$"

