SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "I wonder if FOUNDRY is finished…$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "Thanks for saving us!$"

SilphCo_8F_Text_Grunt1Intro::
    .string "This is as far as your MARK will\n"
    .string "take you.$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "Under resourced.$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "If you continue I will have to\n"
    .string "raise a ticket.$"

SilphCo_8F_Text_ParkerIntro::
    .string "You're causing us problems!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "Huh?\n"
    .string "I lost?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "So, what do you think of FOUNDRY\n"
    .string "BUILDING's maze?$"

SilphCo_8F_Text_Grunt2Intro::
    .string "Third of four on this account!$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "Handing off.$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "I'll leave this with the team.$"

SilphCo_8F_Text_FloorSign::
    .string "FOUNDRY CO. HEAD OFFICE 8F$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
	.string "SCORN isn't cruel. He fixed our\n"
	.string "payroll in a week.\p"
	.string "He knows everyone's name. He just\n"
	.string "never asks what any of us are for.$"
