SSAnne_2F_Room4_Text_LamarIntro::
    .string "Which do you find more worthy, a\n"
    .string "strong or a rare DAEMON?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "I must salute you!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "Personally, I prefer strong and\n"
    .string "rare DAEMON.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "I don't believe I saw you at the\n"
    .string "party?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "Take it easy!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "Oh, I adore your strong DAEMON!\n"
    .string "Oh, how I envy you for them!$"

