CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "LONG SUPPRESS keeps weak DAEMON\n"
    .string "at bay…\p"
    .string "Hmm, it's a more powerful SUPPRESS.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "For long outings, you should buy\n"
    .string "RESTART.$"

@  T-324, DRAFT.
CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "2F: USER'S MARKET\p"
    .string "Everything a USER needs,\n"
    .string "and some things they don't.$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
	.string "SANGUINE comes in now and then.\n"
	.string "He never buys what he came for.\p"
	.string "He says the other thing was more\n"
	.string "interesting.$"
