CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "LONG SUPPRESS keeps weak DAEMON\n"
    .string "at bay…\p"
    .string "Hmm, it's a more powerful SUPPRESS.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "For long outings, you should buy\n"
    .string "RESTART.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "Top Grade Items\n"
    .string "for USERS!\p"
    .string "2F: USER'S\n"
    .string "MARKET$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
	.string "SANGUINE comes in now and then.\n"
	.string "He never buys what he came for.\p"
	.string "He says the other thing was more\n"
	.string "interesting.$"
