SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "TEAM CORPUS is in an uproar over\n"
    .string "some intruder. That's you right?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "TEAM CORPUS took off! You're our\n"
    .string "hero! Thank you!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "Reception logged an unbadged\n"
    .string "visitor.$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "Noted.$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "Disputes with CORPUS go to\n"
    .string "arbitration.\p"
    .string "We draft the terms!$"

SilphCo_5F_Text_BeauIntro::
    .string "We study BOX technology on this\n"
    .string "floor!$"

SilphCo_5F_Text_BeauDefeat::
    .string "Dang!\n"
    .string "Blast it!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "We worked on the ultimate BOX\n"
    .string "which would bind anything!$"

SilphCo_5F_Text_DaltonIntro::
    .string "Whaaat?\p"
    .string "There shouldn't be any children\n"
    .string "here!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "Oh, goodness!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "You're only on 5F.\n"
    .string "It's a long way to my BOSS!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "Please observe CORPUS values on\n"
    .string "this floor.$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "Taking a moment.$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Unrelated:\p"
    .string "KOFFING evolves into WEEZING.\p"
    .string "Sharing is caring!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "It's a DAEMON REPORT!\p"
    .string "DAEMON LAB created PORYGON, the\n"
    .string "first virtual-reality DAEMON.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "It's a DAEMON REPORT!\p"
    .string "Over 160 DAEMONS techniques have\n"
    .string "been confirmed.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "It's a DAEMON REPORT!\p"
    .string "4 DAEMONS evolve only when traded\n"
    .string "by link-cable.$"

SilphCo_5F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "5F$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "Those thugs that took over our\n"
    .string "building…\p"
    .string "Their BOSS said he was looking for\n"
    .string "strong DAEMON.\p"
    .string "I hope our PRESIDENT managed to\n"
    .string "avoid trouble…$"
