LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "I'm searching for items that raise\n"
    .string "the stats of DAEMON.\p"
    .string "They're effective over the course\n"
    .string "of a single battle.\p"
    .string "X ATTACK, X DEFEND, X SPEED, and\n"
    .string "X SPECIAL are what I'm after.\p"
    .string "Do you know where I can get them?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "You know REVIVE? It revives any\n"
    .string "HALTED DAEMON!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "Sometimes, a USER duo will\n"
    .string "challenge you with two DAEMONS at\l"
    .string "the same time.\p"
    .string "If that happens, you have to send\n"
    .string "out two DAEMONS to battle, too.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"
