Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Let's see… Uh-oh! You have bound\n"
	.string "only {STR_VAR_3} kinds of DAEMONS!\p"
	.string "You need {STR_VAR_1} kinds if you want\n"
	.string "the {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Oh. I see.\p"
	.string "When you get {STR_VAR_1} kinds of\n"
	.string "DAEMONS, come back for the\l"
	.string "{STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Oh! I see you don't have any\n"
	.string "room for the {STR_VAR_2}.$"
