gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CRYSTAL CLEAR RESEARCH LAB\n"
	.string "BLANCHE TOWN$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I wanted one record that left\n"
	.string "nothing out.\p"
	.string "I have most of one.$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}She does not look like much.\p"
	.string "That is the first thing anyone\n"
	.string "says about her. Every time.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}She lives with her grandchildren,\n"
	.string "VERA and {RIVAL}.\p"
	.string "She had a son. Nobody brings him\n"
	.string "up.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}She has taken an interest in you,\n"
	.string "I hear.\p"
	.string "She was formidable once.\p"
	.string "People say that as if it were\n"
	.string "kind.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There was to be a lecture series.\p"
	.string "It was announced twice.\p"
	.string "Neither time did it happen.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}If you show VERA your DAEMON, she\n"
	.string "can tell how much it likes you.\p"
	.string "Occasionally, she will even groom a\n"
	.string "DAEMON for you.$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}But the person who is most liked by\n"
	.string "DAEMON is VERA, I think.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}She was gently grooming DAEMON…\n"
	.string "She was a little angel.\p"
	.string "That little girl's name… I think it\n"
	.string "was VERA.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CRYSTAL CLEAR reportedly lives\n"
	.string "with her grandchildren, VERA and\l"
	.string "{RIVAL}.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A girl from BLANCHE TOWN, VERA,\n"
	.string "she enjoys TEA every day.\p"
	.string "She visits the VERDIGRIS DEPT.\n"
	.string "STORE to buy some TEA.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The Spring DAEMON CONTEST's Grand\n"
	.string "Champion is VERA CRYSTAL CLEAR of\l"
	.string "BLANCHE TOWN!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SLATE CITY DAEMON GYM LEADER:\n"
	.string "CAIRN. He writes it all down.$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Old formats. Still readable.\p"
	.string "People take that for a limitation.\p"
	.string "It is the only thing that is not.$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Most USERS here are hobbyists.\p"
	.string "CAIRN is not most USERS.\p"
	.string "He has never once been casual\n"
	.string "about anything.$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He is not the strongest leader.\p"
	.string "He is the one whose records you\n"
	.string "can check.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I dig CORES out of DEADSTACK.\p"
	.string "CAIRN comes down some weekends.\p"
	.string "He labels everything twice.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He does not laugh often.\p"
	.string "I have seen it twice. Both times\n"
	.string "he had to sit down.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}DOLDRUM CITY DAEMON GYM LEADER:\n"
	.string "BASIN The Tomboyish Mermaid!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My policy is an all-out offensive\n"
	.string "with FLOW-type DAEMON!$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BASIN is a USER who's going to keep\n"
	.string "improving.\p"
	.string "She won't lose to someone like you!$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Strong USERS and WATER DAEMONS\n"
	.string "are common sights in these parts.\p"
	.string "They say that BASIN of the\n"
	.string "DOLDRUM GYM trains here.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This cape is a famous date spot.\p"
	.string "BASIN, the GYM LEADER, has high\n"
	.string "hopes about this place.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BASIN is said to worship\n"
	.string "PHLEGMATIC of the REVIEW BOARD.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARDOR CITY DAEMON GYM LEADER: LT.\n"
	.string "GAUGE The Lightning American!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I tell you, kid, electric DAEMON\n"
	.string "saved me during the war!$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When I was in the Army, GAUGE\n"
	.string "was my strict CO.\p"
	.string "He was a hard taskmaster.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}GAUGE was always famous for\n"
	.string "his cautious nature in the Army.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}GAUGE installed the traps in\n"
	.string "the GYM himself.\p"
	.string "He set up double locks everywhere.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}GAUGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by DAEMON to power his plane.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}VERDIGRIS CITY DAEMON GYM\n"
	.string "LEADER: TRELLIS The Nature-Loving\l"
	.string "Princess!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am a student of the art of\n"
	.string "flower arranging.\p"
	.string "My DAEMONS are solely of the\n"
	.string "GROWTH type.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER TRELLIS might be quiet,\n"
	.string "but she's famous around here.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We only use GROWTH-type DAEMON at\n"
	.string "our GYM.\p"
	.string "Why? We also use them for making\n"
	.string "flower arrangements!$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I would never collect DAEMONS if\n"
	.string "they were unattractive.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Rumor has it that if you peek into\n"
	.string "VERDIGRIS GYM, you can often see\l"
	.string "TRELLIS snoozing.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LURID CITY DAEMON GYM LEADER:\n"
	.string "TILT The Poisonous Ninja Master$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Despair to the creeping horror of\n"
	.string "CORRUPT-type DAEMON!$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Even though I've lost, I will keep\n"
	.string "training according to the teachings\l"
	.string "of TILT, my ninja master.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My father is the GYM LEADER of\n"
	.string "this town.\p"
	.string "I'm training to use POISON DAEMON\n"
	.string "as well as my father.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TILT is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his DAEMON to health.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The SAFARI ZONE's huge, wouldn't\n"
	.string "you say?\p"
	.string "LURID's GYM LEADER, TILT, patrols\n"
	.string "the grounds every so often.\p"
	.string "Thanks to him, we can play here\n"
	.string "knowing that we're safe.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRAZEN CITY DAEMON GYM LEADER:\n"
	.string "MATTE The Master of CONSTRUE\l"
	.string "DAEMON!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You know about a girl GYM LEADER\n"
	.string "in BRAZEN CITY?\p"
	.string "She uses CONSTRUE-type DAEMON,\n"
	.string "right?$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I have had psychic powers since\n"
	.string "I was a child.\p"
	.string "It started when a spoon I\n"
	.string "carelessly tossed, bent.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I dislike battling, but if you wish,\n"
	.string "I will show you my powers!$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}People say that MATTE can\n"
	.string "communicate with her DAEMON during\l"
	.string "battle without speaking.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MATTE just wiped out the KARATE\n"
	.string "MASTER next door.$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}QUICKSILVER ISLAND DAEMON GYM\n"
	.string "LEADER: ANNEAL The Hotheaded Quiz\l"
	.string "Master!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My fiery DAEMONS are all rough and\n"
	.string "ready with intense heat!\p"
	.string "They incinerate all challengers!$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER, ANNEAL, became lost in\n"
	.string "the mountains but good.\p"
	.string "Night fell when a fiery bird DAEMON\n"
	.string "appeared.\p"
	.string "Its light allowed ANNEAL to find\n"
	.string "his way down safely.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}QUICKSILVER GYM's ANNEAL is quite\n"
	.string "the odd fellow.\p"
	.string "He's lived on the island since way\n"
	.string "before the LAB was built.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It's a photo of ANNEAL and INIT.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ANNEAL is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am PHLEGMATIC.\nFourth of the REVIEW BOARD.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}No one can best me when it comes\n"
	.string "to icy DAEMON.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where was this person born?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We've had a great and powerful\n"
	.string "USER grow up on this island.\p"
	.string "I bet even you'd know her. It's\n"
	.string "PHLEGMATIC of the REVIEW BOARD!$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Known for her logical, calculated,\n"
	.string "and cool style, PHLEGMATIC\l"
	.string "has a surprising secret!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Did you know that PHLEGMATIC has\n"
	.string "lots and lots of stuffed dolls?\p"
	.string "Every time she comes back to FOUR\n"
	.string "ISLAND, her collection grows!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The FERRY she has, I imagine it to\n"
	.string "be the one she met as a child.\p"
	.string "I believe it was in ICEFALL CAVE\n"
	.string "that she bound it.\p"
	.string "Perhaps that DAEMON has been with\n"
	.string "her ever since.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am CHOLERIC.\nSecond of the REVIEW BOARD!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I've lived and trained with my\n"
	.string "LOGIC daemons!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CHOLERIC apparently joined the\n"
	.string "REVIEW BOARD out of his burning\l"
	.string "ambition to battle the best USERS.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CHOLERIC, who's a senior ahead of\n"
	.string "me, visits the SPA on occasion.\p"
	.string "He comes to rehab injuries, both\n"
	.string "his own and his DAEMON's.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's one of the REVIEW BOARD. His\n"
	.string "name is CHOLERIC.\p"
	.string "He went away disappointed when he\n"
	.string "found out that they were all sold\l"
	.string "out of Rage Candybars.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Even CHOLERIC…\n"
	.string "He trained with a fellow by the\l"
	.string "name of BRAWLY before.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am MELANCHOLIC.\nThird of the REVIEW BOARD.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MELANCHOLIC's LATENT daemons are\n"
	.string "horrifically terrifying in toughness.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That old lady's also got a really\n"
	.string "short fuse, too.\p"
	.string "It doesn't take anything to get\n"
	.string "that scary lady hollering.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In her youth, MELANCHOLIC and\n"
	.string "CRYSTAL CLEAR were rivals who vied\l"
	.string "for supremacy as USERS.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear CRYSTAL CLEAR's taken a lot\n"
	.string "of interest in you, child.\p"
	.string "That old duff was once tough and\n"
	.string "striking.\p"
	.string "But that was decades ago. She's a\n"
	.string "shadow of her former self.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Take MELANCHOLIC, for example.\p"
	.string "She set a record for being the\n"
	.string "oldest-ever REVIEW BOARD member.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I lead the REVIEW BOARD.\p"
	.string "You can call me SANGUINE\n"
	.string "the dragon USER.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You know that dragons are mythical\n"
	.string "DAEMON.\p"
	.string "They're hard to bind and raise, but\n"
	.string "their powers are superior.\p"
	.string "They're virtually indestructible.\n"
	.string "There's no being clever with them.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He stands for justice!\n"
	.string "He's cool, and yet passionate!\l"
	.string "He's the greatest, SANGUINE!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We have a customer, SANGUINE, who\n"
	.string "occasionally comes.\p"
	.string "He always buys capes.\p"
	.string "I wonder… Does he have many\n"
	.string "identical capes at home?$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SANGUINE's grandfather is\n"
	.string "thought to be the elder of a\l"
	.string "famous clan of dragon masters.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}From what I've heard, SANGUINE has\n"
	.string "a cousin who's a GYM LEADER\l"
	.string "somewhere far away.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He built the storage system.\p"
	.string "Everything you have ever put away\n"
	.string "is inside something he made.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He does not keep many.\p"
	.string "He says he knows what it is like\n"
	.string "in there.$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He took things apart as a boy.\p"
	.string "He put most of them back.$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The first one he bound is still\n"
	.string "in his party.\p"
	.string "He has never said which.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He works alone at DEADSTACK's far\n"
	.string "end.\p"
	.string "People visit. He is always glad.\p"
	.string "Nobody stays long.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}They say the machine could not\n"
	.string "tell which one to send back.\p"
	.string "He does not discuss it.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's really kind.\p"
	.string "He looks after abandoned and\n"
	.string "orphaned DAEMON.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This old guy marched right up to\n"
	.string "our HIDEOUT.\p"
	.string "Then, he starts ranting about how\n"
	.string "TEAM CORPUS's abusing DAEMON.\p"
	.string "So, we're just talking it over as\n"
	.string "adults.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}DAEMON FAN MAGAZINE Monthly Grand\n"
	.string "Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! It's been clipped out.\n"
	.string "Someone must have applied already.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear that INIT's not from these\n"
	.string "parts originally, either.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It's a photo of ANNEAL and INIT.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Editor: The shy INIT turned down\n"
	.string "our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in HALFTONE TOWN.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM CORPUS captures DAEMON from\n"
	.string "around the world.\p"
	.string "They're important tools for keeping\n"
	.string "our criminal enterprise going.\p"
	.string "I am the leader, SCORN!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of DAEMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Those thugs that took over our\n"
	.string "building…\p"
	.string "Their BOSS said he was looking for\n"
	.string "strong DAEMON.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM CORPUS's BOSS is terribly\n"
	.string "cruel!\p"
	.string "To him, DAEMONS are just tools to\n"
	.string "be used.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Welcome to my hideout!\p"
	.string "It shall be so until I can restore\n"
	.string "TEAM CORPUS to its former glory.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Blow me away! SCORN was the GYM\n"
	.string "LEADER of CALLOW?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You… You're not SCORN's kid, are\n"
	.string "you?\p"
	.string "No, that can't be right. SCORN's kid\n"
	.string "has red hair.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}CRYSTAL CLEAR$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: CRYSTAL CLEAR To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Why do DAEMON compete and battle\n"
	.string "so hard for you?\p"
	.string "They do so because they can see\n"
	.string "the love and trust you have\l"
	.string "towards DAEMON.\p"
	.string "Never forget that.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}VERA$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: VERA To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}While I was comfortably enjoying\n"
	.string "my tea breaks, you've grown very\l"
	.string "skilled and powerful.\p"
	.string "I hope you'll remain a good rival\n"
	.string "to my little brother.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}CAIRN$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: CAIRN To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In this big world of ours, there\n"
	.string "must be many tough USERS.\p"
	.string "Let's both keep training and making\n"
	.string "ourselves stronger!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BASIN$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BASIN\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm going to keep training here at\n"
	.string "this GYM.\p"
	.string "When I get better, I'd love to hit\n"
	.string "the road and travel.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GAUGE$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: GAUGE To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, kid! You electrified me in our\n"
	.string "battle!\p"
	.string "I didn't know that there were gutsy\n"
	.string "USERS like you.\p"
	.string "It made me change my mind about\n"
	.string "you!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}TRELLIS$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: TRELLIS To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am so glad that there are strong\n"
	.string "USERS like you.\p"
	.string "That awareness alone inspires and\n"
	.string "motivates me to try harder.\p"
	.string "Please visit me again. Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}TILT$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: TILT\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You and I, we must both set our\n"
	.string "sights higher and work towards\l"
	.string "meeting our challenges.\p"
	.string "Now, I must go train my daughter.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MATTE$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MATTE To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The love you have towards your\n"
	.string "DAEMON…\p"
	.string "It was a power that was never\n"
	.string "bested by my psychic power.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ANNEAL$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: ANNEAL To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My fire DAEMON! They'll become\n"
	.string "even more powerful!\p"
	.string "And now, a quiz. How many kinds of\n"
	.string "ENTROPY-type DAEMONS are there?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PHLEGMATIC$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: PHLEGMATIC\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I needed to thank you for your\n"
	.string "help.\p"
	.string "But that has nothing to do with our\n"
	.string "battles.\p"
	.string "You'd better watch out next time!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}CHOLERIC$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: CHOLERIC To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The super power of your DAEMON\n"
	.string "and you I've experienced myself.\p"
	.string "Next time, maybe I should show you\n"
	.string "how to train yourself.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MELANCHOLIC$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MELANCHOLIC To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When you grow older, don't you dare\n"
	.string "go soft like that coot\l"
	.string "CRYSTAL CLEAR!\p"
	.string "Be like me and keep battling on!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SANGUINE$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: SANGUINE To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm considering going back to my\n"
	.string "hometown.\p"
	.string "I want to retrain my EMERGENT-type\n"
	.string "DAEMON and strengthen them.\p"
	.string "I'd like to invite you to my\n"
	.string "hometown one day.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}HOLT$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: HOLT To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, there! CELIO had nothing but\n"
	.string "praise for you.\p"
	.string "Hearing that makes me happy.\p"
	.string "When you bind some rare DAEMONS,\n"
	.string "come show me, okay? Promise!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}INIT$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: INIT To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Instead of hoping for the happiness\n"
	.string "of just your DAEMON…\p"
	.string "…Can I get you to wish for the\n"
	.string "happiness of all DAEMONS?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SCORN$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: SCORN To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There is nothing that I wish to say\n"
	.string "to you.\p"
	.string "I will concentrate solely on\n"
	.string "bettering myself, and none other.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "BLANCHE TOWN$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "CALLOW CITY$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "DAEMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "ARDOR CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "WATER LABYRINTH$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "CALLOW CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "VERDIGRIS MANSION$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "SLATE CITY$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "SLATE GYM$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "SLATE CITY$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "ROUTE 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "DEADSTACK$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "SLATE MUSEUM$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "DOLDRUM CITY$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "DOLDRUM GYM$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "DOLDRUM GYM$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "GLAUCOUS ISLES$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "DOLDRUM CAPE$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "DOLDRUM CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "ARDOR CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "ARDOR GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "ARDOR GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "ARDOR GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "ARDOR GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "ARDOR CITY$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "VERDIGRIS CITY$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "VERDIGRIS GYM$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "VERDIGRIS GYM$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "VERDIGRIS GYM$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "VERDIGRIS GYM$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "VERDIGRIS MANSION$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "LURID CITY$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "LURID GYM$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "LURID GYM$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "LURID CITY$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "LURID CITY$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "SAFARI ZONE$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "BRAZEN CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "THREE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "BRAZEN GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "BRAZEN GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "BRAZEN CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "BRAZEN GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "QUICKSILVER ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "QUICKSILVER GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "QUICKSILVER GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "QUICKSILVER ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "QUICKSILVER GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "RESORT GORGEOUS$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "DAEMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "DAEMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "FIVE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "DAEMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "DAEMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "BRAZEN CITY$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "JITTER SPA$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "TWO ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "SEVAULT CANYON$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "DAEMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "UMBRA PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "UMBRA PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "SEVEN ISLAND$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "DAEMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "SIX ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "DAEMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "DAEMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "BRAZEN CITY$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "VERDIGRIS DEPT.$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "UMBRA PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "UMBRA PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "DOLDRUM CITY$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "DOLDRUM CITY$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "LURID CITY$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "HALFTONE TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "DAEMON TOWER$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "HALFTONE TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "HALFTONE TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "QUICKSILVER GYM$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "QUICKSILVER ISLAND$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "CORPUS HIDEOUT$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "FOUNDRY CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "FOUNDRY CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "CALLOW GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "CALLOW GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "CORPUS WAREHOUSE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "CRYSTAL CLEAR$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "MELANCHOLIC$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "CAIRN$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "BOY$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "BASIN$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "DAME$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "GAUGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "TRELLIS$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "TRELLIS$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "TILT$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "MATTE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "MATTE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "ANNEAL$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "PHLEGMATIC$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "PHLEGMATIC$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "CHOLERIC$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "CHOLERIC$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "MELANCHOLIC$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "MELANCHOLIC$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "SANGUINE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "SANGUINE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "LITTLE BOY$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "TEAM CORPUS$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "MAGAZINE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "DAEMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "SCORN$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "SCORN$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: SLATE GYM LEADER\n"
	.string "CAIRN!\p"
	.string "CAIRN rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: DOLDRUM GYM\n"
	.string "LEADER BASIN!\p"
	.string "BASIN is said to worship\n"
	.string "PHLEGMATIC of the REVIEW BOARD.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: ARDOR GYM LEADER\n"
	.string "GAUGE!\p"
	.string "GAUGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by DAEMON to power his plane.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: VERDIGRIS GYM\n"
	.string "LEADER TRELLIS!\p"
	.string "Rumor has it that if you peek into\n"
	.string "VERDIGRIS GYM, you can often see\l"
	.string "TRELLIS snoozing.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: LURID GYM LEADER\n"
	.string "TILT!\p"
	.string "TILT is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his DAEMON to health.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: BRAZEN GYM\n"
	.string "LEADER MATTE!\p"
	.string "People say that MATTE can\n"
	.string "communicate with her DAEMON during\l"
	.string "battle without speaking.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: QUICKSILVER GYM\n"
	.string "LEADER ANNEAL!\p"
	.string "ANNEAL is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: REVIEW BOARD's\n"
	.string "PHLEGMATIC!\p"
	.string "Known for her logical, calculated,\n"
	.string "and cool style, PHLEGMATIC\l"
	.string "has a surprising secret!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: REVIEW BOARD's\n"
	.string "CHOLERIC!\p"
	.string "CHOLERIC apparently joined the\n"
	.string "REVIEW BOARD out of his burning\l"
	.string "ambition to battle the best USERS.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: REVIEW\n"
	.string "BOARD's MELANCHOLIC!\p"
	.string "In her youth, MELANCHOLIC and\n"
	.string "CRYSTAL CLEAR were rivals who\l"
	.string "vied for supremacy as USERS.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: REVIEW\n"
	.string "BOARD's SANGUINE!\p"
	.string "SANGUINE's grandfather is\n"
	.string "thought to be the elder of a\l"
	.string "famous clan of dragon masters.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: CRYSTAL CLEAR,\n"
	.string "the DAEMON Researcher!\p"
	.string "CRYSTAL CLEAR reportedly lives\n"
	.string "with her grandchildren VERA and\l"
	.string "{RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "This is a DAEMON JOURNAL from\n"
	.string "years ago…\p"
	.string "DAEMON JOURNAL CONTEST Special!\p"
	.string "The Spring DAEMON CONTEST's Grand\n"
	.string "Champion is VERA CRYSTAL CLEAR of\l"
	.string "BLANCHE TOWN!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "DAEMON JOURNAL\p"
	.string "Special Feature: INIT of DAEMON\n"
	.string "HOUSE!\p"
	.string "Editor: The shy INIT turned down\n"
	.string "our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in HALFTONE TOWN.$"
