Help_Text_WhatShouldIDo::
	.string "What should I do in this situation?$"

Help_Text_HowDoIDoThis::
	.string "How do I do this?$"

Help_Text_WhatDoesThisTermMean::
	.string "What does this term mean?$"

Help_Text_AboutThisGame::
	.string "About this game$"

Help_Text_TypeMatchupList::
	.string "Type Matchup List$"

Help_Text_Exit::
	.string "EXIT$"

Help_Text_Cancel::
	.string "CANCEL$"

Help_Text_TryDoingItOnYourOwn::
	.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo::
	.string "Select to obtain hints for getting\n"
	.string "over challenging situations.$"

Help_Text_DescHowDoIDoThis::
	.string "Detailed instructions are given for\n"
	.string "various operations.$"

Help_Text_DescWhatDoesThisTermMean::
	.string "Detailed descriptions are given for\n"
	.string "terms that appear in the game.$"

Help_Text_DescAboutThisGame::
	.string "Detailed descriptions are given\n"
	.string "about this game.$"

Help_Text_DescTypeMatchupList::
	.string "The matchups of DAEMON types and ROUTINES\n"
	.string "are listed.$"

Help_Text_DescExit::
	.string "Select to exit the HELP System.$"

Help_Text_Greetings::
	.string "Greetings! This is the HELP System.\n"
	.string "Call me up whenever and wherever you\l"
	.string "need by pressing the L or R Button.\l"
	.string "The help messages change to suit the\l"
	.string "situation, so check them often, please.$"

Help_Text_PlayingForFirstTime::
	.string "I'm playing for the first time. Help!$"

Help_Text_WhatShouldIBeDoing::
	.string "What should I be doing?$"

Help_Text_CantGetOutOfRoom::
	.string "I can't get out of a room!$"

Help_Text_CantFindPersonIWant::
	.string "I can't find the person I want.$"

Help_Text_TalkedToEveryoneNowWhat::
	.string "I've talked to everyone. Now what?$"

Help_Text_SomeoneBlockingMyWay::
	.string "There's someone blocking my way!$"

Help_Text_ICantGoOn::
	.string "I can't go on!$"

Help_Text_OutOfThingsToDo::
	.string "I'm out of things to do.$"

Help_Text_WhatHappenedToItemIGot::
	.string "What happened to the item I got?$"

Help_Text_WhatAreMyAdventureBasics::
	.string "What are the basics of my adventure?$"

Help_Text_HowAreRoadsForestsDifferent::
	.string "How are roads and forests different?$"

Help_Text_HowAreCavesDifferent::
	.string "How are caves different?$"

Help_Text_HowDoIProgress::
	.string "How do I progress?$"

Help_Text_WhenCanIUseItem::
	.string "When can I use items?$"

Help_Text_WhatsABattle::
	.string "What's a battle?$"

Help_Text_HowDoIPrepareForBattle::
	.string "How do I prepare for battle?$"

Help_Text_WhatIsAMonsVitality::
	.string "What is a DAEMON's vitality?$"

Help_Text_MyMonsAreHurt::
	.string "My DAEMONS are hurt!$"

Help_Text_WhatIsStatusProblem::
	.string "What is a status problem?$"

Help_Text_WhatHappensIfAllMyMonsFaint::
	.string "What happens if all my DAEMONS HALT?$"

Help_Text_CantCatchMons::
	.string "I can't bind DAEMONS!$"

Help_Text_RanOutOfPotions::
	.string "I ran out of RESTORE.$"

Help_Text_CanIBuyPokeBalls::
	.string "Can I buy BOXES?$"

Help_Text_WhatsATrainer::
	.string "What's a USER?$"

Help_Text_HowDoIWinAgainstTrainer::
	.string "How do I win against a USER?$"

Help_Text_WhereDoMonsAppear::
	.string "Where do DAEMONS appear?$"

Help_Text_WhatAreMoves::
	.string "What are DAEMON ROUTINES?$"

Help_Text_WhatAreHiddenMoves::
	.string "What are HIDDEN ROUTINES?$"

Help_Text_WhatMovesShouldIUse::
	.string "What ROUTINES should I invoke?$"

Help_Text_WantToAddMoreMoves::
	.string "I want to add more ROUTINES.$"

Help_Text_WantToMakeMonStronger::
	.string "I want to make my DAEMONS stronger.$"

Help_Text_FoeMonsTooStrong::
	.string "The foe DAEMONS are too strong!$"

Help_Text_WhatDoIDoInCave::
	.string "What do I do in a cave?$"

Help_Text_NothingIWantToKnow::
	.string "There's nothing that I want to know!$"

Help_Text_WhatsPokemonCenter::
	.string "What's a CHECKPOINT?$"

Help_Text_WhatsPokemonMart::
	.string "What's a REPO?$"

Help_Text_WantToEndGame::
	.string "I want to end the game.$"

Help_Text_WhatsAMon::
	.string "What's a DAEMON?$"

Help_Text_WhatIsThatPersonLike::
	.string "What is that person like?$"

Help_Text_WhatDoesHiddenMoveDo::
	.string "What does a HIDDEN ROUTINE do?$"

Help_Text_WhatDoIDoInSafari::
	.string "What do I do in a SAFARI GAME?$"

Help_Text_WhatAreSafariRules::
	.string "What are the SAFARI GAME rules?$"

Help_Text_WantToEndSafari::
	.string "I want to end this SAFARI GAME!$"

Help_Text_WhatIsAGym::
	.string "What is a GYM?$"

Help_Text_AnswerPlayingForFirstTime::
	.string "You become the main character,\n"
	.string "exploring the world of DAEMON. By\l"
	.string "talking to people and solving mysteries,\l"
	.string "new paths will open to you. Strive for\l"
	.string "the goal together with your wonderful\l"
	.string "DAEMON.$"

Help_Text_AnswerWhatShouldIBeDoing::
	.string "When you come across another person,\n"
	.string "go up to them and press the A Button.\l"
	.string "That will get them to talk and interact\l"
	.string "with your character. You may also\l"
	.string "examine various items and objects in\l"
	.string "the same way. Talk to people and check\l"
	.string "things often to obtain information.$"

Help_Text_AnswerCantGetOutOfRoom::
	.string "On the stairs or the exits of a\n"
	.string "building is a red mat. Move your\l"
	.string "character to stand on top of the\l"
	.string "red mat. Press the {PLUS} Control Pad \l"
	.string "toward the stairs or the exit to\l"
	.string "advance.$"

Help_Text_AnswerCantFindPersonIWant::
	.string "This isn't something you should worry about\n"
	.string "too much. Talk to other people, check signs,\l"
	.string "check things, and so on. Sometimes, you may\l"
	.string "need to just move to a new town or\l"
	.string "place.$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
	.string "Try moving on to a new road, town, or\n"
	.string "place.$"

Help_Text_AnswerSomeoneBlockingMyWay::
	.string "There could be something in the town\n"
	.string "or inside a building that is the cause.\l"
	.string "Try talking to the people in the area\l"
	.string "again. If there is a problem that they\l"
	.string "need solved, you may have to help.\l"
	.string "Afterwards, try talking to the person\l"
	.string "blocking your way again.$"

Help_Text_AnswerICantGoOn::
	.string "Try talking to people by going up to\n"
	.string "them and pressing the A Button.\l"
	.string "Also, try checking things like odd trees\l"
	.string "and strange rocks with the A Button.\l"
	.string "Press the {PLUS} Control Pad and try going\l"
	.string "to places that look impassable, too.$"

Help_Text_AnswerOutOfThingsToDo::
	.string "Try going to places where you \n"
	.string "haven't visited yet.\l"
	.string "Also, check everything that looks\l"
	.string "suspicious by pressing the A Button.$"

Help_Text_AnswerWhatHappenedToItemIGot::
	.string "Any item that you are given by another\n"
	.string "character goes in your BAG.\l"
	.string "The item is automatically sorted and\l"
	.string "placed in one of three pockets.\l"
	.string "For instructions on the BAG's use,\l"
	.string "please refer to the HELP System's\l"
	.string "“How do I do this?” heading.$"

Help_Text_AnswerWhatAreMyAdventureBasics::
	.string "If DAEMONS are hurt in battle, take\n"
	.string "them to a CHECKPOINT and have them\l"
	.string "healed by the staff. Get in the habit\l"
	.string "of saving your game and recording your\l"
	.string "progress. Stock up on healing items at\l"
	.string "REPOS before traveling far.$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
	.string "Forests are basically the same as\n"
	.string "roads but they can be like mazes.\l"
	.string "All forests have a way out, so don't\l"
	.string "give up if you get lost.$"

Help_Text_AnswerHowAreCavesDifferent::
	.string "Caves are dark and dangerous. Wild\n"
	.string "DAEMON can appear anywhere in them. If\l"
	.string "there is an emergency, rush to a\l"
	.string "CHECKPOINT or use items. New towns\l"
	.string "await discovery beyond some caves, so\l"
	.string "don't give up.$"

Help_Text_AnswerHowDoIProgress::
	.string "The object of the game is to train\n"
	.string "your DAEMON and move forward. You must\l"
	.string "collect info and solve problems. For\l"
	.string "example, what do you need to get\l"
	.string "around an obstacle? What would get\l"
	.string "that impeding person out of the way?$"

Help_Text_AnswerWhenCanIUseItem::
	.string "There are several kinds of items.\n"
	.string "Some can be used only on the field.\l"
	.string "Some are only for use during battle.\l"
	.string "Some can be used anytime.\l"
	.string "Try using an item - if it can't be used,\l"
	.string "you will be alerted.$"

Help_Text_AnswerWhatsABattle::
	.string "In a battle, DAEMON try to reduce one\n"
	.string "another's vitality, expressed as HP. If\l"
	.string "a DAEMON's HP falls to zero, it HALTS,\l"
	.string "and the other DAEMONS wins. By winning\l"
	.string "a battle, DAEMON earn EXP. Points,\l"
	.string "which help them level up (grow\l"
	.string "stronger).$"

Help_Text_AnswerHowDoIPrepareForBattle::
	.string "First, fully heal the DAEMON in your\n"
	.string "party (the DAEMON with you) at any\l"
	.string "CHECKPOINT. You should also buy\l"
	.string "healing items for emergencies at a\l"
	.string "REPO.$"

Help_Text_AnswerWhatIsAMonsVitality::
	.string "A DAEMON's vitality is expressed in HP.\n"
	.string "If a DAEMON is hurt in battle, HP is\l"
	.string "subtracted. If its HP drops to zero,\l"
	.string "the DAEMON HALTS. Heal hurt or HALTED\l"
	.string "DAEMON at a CHECKPOINT or by using\l"
	.string "items.$"

Help_Text_AnswerMyMonsAreHurt::
	.string "A CHECKPOINT is like an inn for DAEMON.\n"
	.string "It will fully heal DAEMON of any status\l"
	.string "problems and fully restore their HP\l"
	.string "using a special machine. This service is\l"
	.string "free, so get in the habit of healing\l"
	.string "your DAEMON often.$"

Help_Text_AnswerWhatIsStatusProblem::
	.string "A status problem refers to an ailment\n"
	.string "that is inflicted on a DAEMON by its\l"
	.string "foe's attack. These include\l"
	.string "throttling, leaking, suspension, and\l"
	.string "overheating and hanging. Heal\l"
	.string "them at a CHECKPOINT or with the\l"
	.string "appropriate item.$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
	.string "If all the DAEMONS in your party (all\n"
	.string "the DAEMON with you) HALT, you lose\l"
	.string "some MONEY, and you are returned home\l"
	.string "or to a CHECKPOINT. To reduce that\l"
	.string "chance, visit CHECKPOINTS often. Also,\l"
	.string "get in the habit of saving often.$"

Help_Text_AnswerCantCatchMons::
	.string "If a wild DAEMON escapes from a POKé\n"
	.string "BOX, it's obviously still feisty. Try\l"
	.string "reducing its HP some more, and try to\l"
	.string "throttle it or suspend it\l"
	.string "before trying to bind it. If the POKé\l"
	.string "BOX rocks for a while, the quarry is\l"
	.string "close to being bound!$"

Help_Text_AnswerRanOutOfPotions::
	.string "There are shops, known as REPOS, that\n"
	.string "sell items. You will not find REPOS on\l"
	.string "roads, in forests, or in caves. Stock up\l"
	.string "on needed items while you are visiting\l"
	.string "a town with a REPO.$"

Help_Text_AnswerCanIBuyPokeBalls::
	.string "You may buy BOXES at any REPO in\n"
	.string "any town. You will not find REPOS on\l"
	.string "roads, in forests, or in caves. Stock up\l"
	.string "on BOXES while you are visiting a\l"
	.string "town with a REPO.$"

Help_Text_AnswerWhatsATrainer::
	.string "A USER is a person who raises DAEMON\n"
	.string "through battling. USERS will challenge\l"
	.string "you wherever they are - it could be on\l"
	.string "a road, in forests, caves, anywhere. If\l"
	.string "your eyes meet, you have to accept\l"
	.string "their challenge. So be careful!$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
	.string "To beat a USER in battle, use DAEMON\n"
	.string "that have type advantages over the\l"
	.string "foe's DAEMON. You may also use\l"
	.string "highly trained DAEMON with overwhelming\l"
	.string "power. Outnumbering the foe's DAEMON\l"
	.string "is another obvious tactic.$"

Help_Text_AnswerWhereDoMonsAppear::
	.string "Wild DAEMON will appear in tall grass,\n"
	.string "on roads, and in forests. They will\l"
	.string "appear anywhere in dark caves. There\l"
	.string "are no wild DAEMONS or USERS in towns,\l"
	.string "so they are safe places.$"

Help_Text_AnswerWhatAreMoves::
	.string "DAEMON may learn up to four different\n"
	.string "techniques, or ROUTINES. There is a great\l"
	.string "variety of ROUTINES including attacks and\l"
	.string "those with special effects. The kinds of\l"
	.string "ROUTINES that can be learned vary for each\l"
	.string "DAEMON. Some ROUTINES can be learned from\l"
	.string "machines.$"

Help_Text_AnswerWhatAreHiddenMoves::
	.string "HIDDEN ROUTINES are those that are\n"
	.string "especially important for your adventure. To\l"
	.string "invoke such a ROUTINE outside of battle,\l"
	.string "open the “DAEMON” MENU and make the DAEMON\l"
	.string "that knows the ROUTINE invoke it. A HALTED\l"
	.string "DAEMON may invoke a HIDDEN ROUTINE outside\l"
	.string "battle.$"

Help_Text_AnswerWhatMovesShouldIUse::
	.string "Select “INVOKE,” and the MENU of\n"
	.string "routines will appear. Consider the\l"
	.string "type matchups, and use the most\l"
	.string "effective ones. You can check the\l"
	.string "effects of a routine by opening\l"
	.string "“DAEMON,” picking one, opening\l"
	.string "“SUMMARY,” then “DAEMON SKILLS.”$"

Help_Text_AnswerWantToAddMoreMoves::
	.string "The most a DAEMON can learn is four\n"
	.string "ROUTINES. They are learned as the DAEMON\l"
	.string "levels up. It can also be taught a ROUTINE\l"
	.string "using a TM (Technical Machine) or HM (Hidden\l"
	.string "Machine). There are also people who teach\l"
	.string "ROUTINES.$"

Help_Text_AnswerWantToMakeMonStronger::
	.string "The key to making your DAEMON strong is\n"
	.string "to battle and win often. The EXP.\l"
	.string "(Experience) Points earned by winning\l"
	.string "battles accumulate to level up DAEMON\l"
	.string "that participated in them. Battle wild\l"
	.string "DAEMON often to level up your party.$"

Help_Text_AnswerFoeMonsTooStrong::
	.string "If your foe are too strong, try\n"
	.string "leveling up your DAEMON some more. Go\l"
	.string "back the way you came and battle wild\l"
	.string "DAEMON to level up your party. You\l"
	.string "may also battle USERS whom you have\l"
	.string "not battled before.$"

Help_Text_AnswerWhatDoIDoInCave::
	.string "Unlike roads and forests, wild DAEMON\n"
	.string "can appear anywhere in caves. If your\l"
	.string "DAEMONS are hurt in a cave, rush to a\l"
	.string "CHECKPOINT or use items to heal them\l"
	.string "right away. It is very dangerous to\l"
	.string "force your luck in caves.$"

Help_Text_AnswerNothingIWantToKnow::
	.string "Trust your own knowledge and power.\n"
	.string "Believe in yourself and find your way!$"

Help_Text_AnswerWhatsPokemonCenter::
	.string "A CHECKPOINT is identified by its red\n"
	.string "roof and a “P.C” sign. Every\l"
	.string "CHECKPOINT offers such services as\l"
	.string "fully healing DAEMON and free PORT\l"
	.string "use, making it essential for your\l"
	.string "travels. On the upper floor are\l"
	.string "facilities for linking with friends and\l"
	.string "others.$"

Help_Text_AnswerWhatsPokemonMart::
	.string "A REPO is identified by its blue roof\n"
	.string "and a “MART” sign. Items can be bought\l"
	.string "and sold at any REPO. Some MARTS carry\l"
	.string "items that are available only in their\l"
	.string "towns.$"

Help_Text_AnswerWantToEndGame::
	.string "You can safely end your game by\n"
	.string "selecting “SAVE” on the MENU.\l"
	.string "Once you have saved, the game can be\l"
	.string "safely turned off. When the game is\l"
	.string "turned back on, you can resume from\l"
	.string "where you last saved.$"

Help_Text_AnswerWhatsAMon::
	.string "DAEMONS are living beings about which\n"
	.string "many mysteries still remain. You may\l"
	.string "see them in grass, the sea, and caves.\l"
	.string "They appear to obey the wishes of the\l"
	.string "USERS that bound them.$"

Help_Text_AnswerWhatIsThatPersonLike::
	.string "Use the HEARSAY among the KEY ITEMS\n"
	.string "in your BAG. It may give you a hint, so\l"
	.string "try it out.$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
	.string "A HIDDEN ROUTINE is taught to a DAEMON\n"
	.string "using an HM (Hidden Machine). A HIDDEN\l"
	.string "ROUTINE is important for helping your\l"
	.string "adventure. For example, one is used to light\l"
	.string "up dark caves. Another cuts down small\l"
	.string "trees. There is one for traveling on water,\l"
	.string "and so on.$"

Help_Text_AnswerWhatDoIDoInSafari::
	.string "Try to bind wild DAEMON by throwing the\n"
	.string "special GUESTBOXES. You may keep any\l"
	.string "item you find, too.$"

Help_Text_AnswerWhatAreSafariRules::
	.string "Your SAFARI GAME ends once you have\n"
	.string "traveled a certain distance or thrown\l"
	.string "all your GUESTBOXES. Open the MENU to\l"
	.string "check the remaining number of steps and\l"
	.string "GUESTBOXES.$"

Help_Text_AnswerWantToEndSafari::
	.string "If you would like to cut your SAFARI\n"
	.string "GAME short, open the MENU and select\l"
	.string "“RETIRE” at the top of the list.$"

Help_Text_AnswerWhatIsAGym::
	.string "DAEMON GYMS are operated by the\n"
	.string "DAEMON LEAGUE and are training\l"
	.string "facilities for USERS. They are all\l"
	.string "across the land in cities and towns.\l"
	.string "Each one is headed by a LEADER, who is\l"
	.string "a very skilled USER. Beat the LEADER\l"
	.string "to collect a MARK.$"

Help_Text_UsingPokedex::
	.string " Using “INDEX”$"

Help_Text_UsingPokemon::
	.string " Using “DAEMON”$"

Help_Text_UsingSummary::
	.string "  Using “SUMMARY”$"

Help_Text_UsingSwitch::
	.string "  Using “SWITCH”$"

Help_Text_UsingItem::
	.string "  Using “ITEM”$"

Help_Text_UsingBag::
	.string " Using “BAG”$"

Help_Text_UsingAnItem::
	.string "  Using an item$"

Help_Text_UsingKeyItem::
	.string "  Using a key item$"

Help_Text_UsingPokeBall::
	.string "  Using a POKé BOX$"

Help_Text_UsingPlayer::
	.string " Using “{PLAYER}”$"

Help_Text_UsingSave::
	.string " Using “SAVE”$"

Help_Text_UsingOption::
	.string " Using “OPTION”$"

Help_Text_UsingPotion::
	.string "    Using a RESTORE$"

Help_Text_UsingTownMap::
	.string "    Using the SITEMAP$"

Help_Text_UsingTM::
	.string "    Using a TM$"

Help_Text_UsingHM::
	.string "    Using an HM$"

Help_Text_UsingMoveOutsideOfBattle::
	.string "Invoking a ROUTINE outside of battle$"

Help_Text_RidingBicycle::
	.string "    Riding the BICYCLE$"

Help_Text_EnteringName::
	.string "Entering a name$"

Help_Text_UsingPC::
	.string "Using a PORT$"

Help_Text_UsingBillsPC::
	.string " Using “{STR_VAR_1}'S PORT”$"

Help_Text_UsingWithdraw::
	.string "  Using “EDDY”$"

Help_Text_UsingDeposit::
	.string "  Using “DEPOSIT”$"

Help_Text_UsingMove::
	.string "  Using “MOVE”$"

Help_Text_MovingItems::
	.string "  Moving items$"

Help_Text_UsingPlayersPC::
	.string " Using “{PLAYER}'s PORT”$"

Help_Text_UsingWithdrawItem::
	.string "  Using “EDDY ITEM”$"

Help_Text_UsingDepositItem::
	.string "  Using “DEPOSIT ITEM”$"

Help_Text_UsingMailbox::
	.string "  Using “MAILBOX”$"

Help_Text_UsingProfOaksPC::
	.string " Using “CRYSTAL CLEAR'S PORT”$"

Help_Text_OpeningMenu::
	.string "Opening the MENU$"

Help_Text_UsingFight::
	.string " Using “INVOKE”$"

Help_Text_UsingPokemon2::
	.string " Using “DAEMON”$"

Help_Text_UsingShift::
	.string "  Using “SHIFT”$"

Help_Text_UsingSummary2::
	.string "  Using “SUMMARY”$"

Help_Text_UsingBag2::
	.string " Using “BAG”$"

Help_Text_ReadingPokedex::
	.string " Reading the “INDEX”$"

Help_Text_UsingHomePC::
	.string "Using the PORT at home$"

Help_Text_UsingItemStorage::
	.string "Using the Item Storage System$"

Help_Text_UsingWithdrawItem2::
	.string "  Using “EDDY ITEM”$"

Help_Text_UsingDepositItem2::
	.string "  Using “DEPOSIT ITEM”$"

Help_Text_UsingMailbox2::
	.string "Using the MAILBOX$"

Help_Text_UsingRun::
	.string " Using “RUN”$"

Help_Text_RegisterKeyItem::
	.string "  “REGISTER” a key item$"

Help_Text_UsingBall::
	.string " Using “BOX”$"

Help_Text_UsingBait::
	.string " Using “BAIT”$"

Help_Text_UsingRock::
	.string " Using “ROCK”$"

Help_Text_UsingHallOfFame::
	.string " Using “HALL OF FAME”$"

Help_Text_HowToUsePokedex::
	.string "{CIRCLE_1} Select “INDEX” on the MENU.\n"
	.string "{CIRCLE_2} Choose DAEMON using commands such\n"
	.string "   as “DAEMON LIST,”\n"
	.string "   “HABITATS OF DAEMON,” and\n"
	.string "   “SEARCH.”\n"
	.string "{CIRCLE_3} Select a DAEMON to obtain detailed\n"
	.string "   information.$"

Help_Text_HowToUsePokemon::
	.string "{CIRCLE_1} Select “DAEMON” on the MENU.\n"
	.string "{CIRCLE_2} Choose a DAEMON in your party.\n"
	.string "{CIRCLE_3} Select “SUMMARY,” “SWITCH,”\n"
	.string "   or “ITEM.”$"

Help_Text_HowToUseSummary::
	.string "{CIRCLE_1} Select “SUMMARY.”\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the information:\n"
	.string "   “DAEMON INFO”\n"
	.string "   “DAEMON SKILLS”\n"
	.string "   “KNOWN ROUTINES”$"

Help_Text_HowToUseSwitch::
	.string "{CIRCLE_1} Choose the DAEMON you want to\n"
	.string "   switch around.\n"
	.string "{CIRCLE_2} Select “SWITCH.”\n"
	.string "{CIRCLE_3} Select the DAEMON to switch with\n"
	.string "   the first one.\n"
	.string "The DAEMON at the left of the screen\n"
	.string "will be the first one out in a battle.$"

Help_Text_HowToUseItem::
	.string "{CIRCLE_1} Select “ITEM.”\n"
	.string "{CIRCLE_2} Select whether you want to “GIVE”\n"
	.string "   an item to the DAEMON to hold,\n"
	.string "   or “TAKE” an item it is holding.\n"
	.string "A DAEMON can hold no more than one\n"
	.string "item!$"

Help_Text_HowToUseBag::
	.string "{CIRCLE_1} Select “BAG” on the MENU.\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the data headings:\n"
	.string "   “ITEMS”\n"
	.string "   “KEY ITEMS”\n"
	.string "   “BOXES”\n"
	.string "   Press up or down to select an item.$"

Help_Text_HowToUseAnItem::
	.string "{CIRCLE_1} Select the “ITEMS” POCKET.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select an item.\n"
	.string "{CIRCLE_3} Select “USE” to use the selected\n"
	.string "   item.\n"
	.string "Some items may not be used depending\n"
	.string "on the place and/or situation.$"

Help_Text_HowToUseKeyItem::
	.string "{CIRCLE_1} Select the “KEY ITEMS” POCKET.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select a key item.\n"
	.string "{CIRCLE_3} Select “USE” to use the selected\n"
	.string "   key item.$"

Help_Text_HowToUsePokeBall::
	.string "{CIRCLE_1} While battling a wild DAEMON,\n"
	.string "   select the BAG's “BOXES”\n"
	.string "   POCKET.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select a POKé BOX.\n"
	.string "{CIRCLE_3} Select “USE” to throw the selected\n"
	.string "   POKé BOX.$"

Help_Text_HowToUsePlayer::
	.string "{CIRCLE_1} Select “{PLAYER}” on the MENU.\n"
	.string "{CIRCLE_2} Your USER CARD is displayed face\n"
	.string "   up with basic information. Press the\n"
	.string "   A Button to turn the CARD over.\n"
	.string "{CIRCLE_3} A variety of data can be found on\n"
	.string "   the reverse side of the CARD.$"

Help_Text_HowToUseSave::
	.string "{CIRCLE_1} Select “SAVE” on the MENU.\n"
	.string "{CIRCLE_2} Select “YES” and your progress is\n"
	.string "   recorded in the save file.\n"
	.string "Once the game is saved, you may turn\n"
	.string "off the game. Your game can be resumed\n"
	.string "from where you saved.$"

Help_Text_HowToUseOption::
	.string "{CIRCLE_1} Select “OPTION” on the MENU.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select an optional item, then\n"
	.string "   press left or right to alter the\n"
	.string "   settings.\n"
	.string "{CIRCLE_3} Select “CANCEL” or press the\n"
	.string "   B Button after making changes.$"

Help_Text_HowToUsePotion::
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad and select “BAG.”\n"
	.string "{CIRCLE_3} Select “RESTORE” in the “ITEMS”\n"
	.string "   POCKET.\n"
	.string "{CIRCLE_4} Select “USE.”\n"
	.string "{CIRCLE_5} Select the DAEMON to be healed.$"

Help_Text_HowToUseTownMap::
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad and select “BAG.”\n"
	.string "{CIRCLE_3} Press left or right to open the\n"
	.string "   “KEY ITEMS” POCKET, then press\n"
	.string "   up or down to select “SITEMAP.” \n"
	.string "{CIRCLE_4} Select “USE” to open the SITEMAP.$"

Help_Text_HowToUseTM::
	.string "{CIRCLE_1} Open the MENU. {CIRCLE_2} Open the “KEY ITEMS”\n"
	.string "POCKET in the “BAG.” {CIRCLE_3} “OPEN” the TM CASE.\l"
	.string "{CIRCLE_4} Select and “USE” a TM. {CIRCLE_5} Select a\l"
	.string "DAEMON that can learn the ROUTINE in the\l"
	.string "TM.$"

Help_Text_HowToUseHM::
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Open the “KEY ITEMS” POCKET in the\n"
	.string "   “BAG.”\n"
	.string "{CIRCLE_3} “OPEN” the TM CASE.\n"
	.string "{CIRCLE_4} Select and “USE” an HM.\n"
	.string "{CIRCLE_5} Select a DAEMON that can learn it.\n"
	.string "HMs are hard to remove, so be careful!$"

Help_Text_HowToUseMoveOutsideOfBattle::
	.string "{CIRCLE_1} Open the MENU. {CIRCLE_2} Select “DAEMON.” {CIRCLE_3}\n"
	.string "Select a DAEMON that knows an HM ROUTINE.\l"
	.string "The usable HM ROUTINE(s) will be shown in\l"
	.string "blue. Select and invoke the desired ROUTINE\l"
	.string "destroy an obstacle, fly, surf, etc.$"

Help_Text_HowToRideBicycle::
	.string "{CIRCLE_1} Open the MENU. Open the\n"
	.string "   “KEY ITEMS” POCKET in the “BAG”\n"
	.string "   and select the “BICYCLE.”\n"
	.string "{CIRCLE_2} The BICYCLE can be ridden by\n"
	.string "   selecting “USE.” You may also\n"
	.string "   “REGISTER” it for instant use by\n"
	.string "   pressing SELECT.$"

Help_Text_HowToEnterName::
	.string "{CIRCLE_1} Move the cursor to the letter you\n"
	.string "   want with the {PLUS} Control Pad, then\n"
	.string "   press the A Button to enter it.\n"
	.string "{CIRCLE_2} Press the B Button to back up.\n"
	.string "{CIRCLE_3} Press SELECT to switch between\n"
	.string "   uppercase and lowercase letters.\n"
	.string "{CIRCLE_4} Press the A Button on “OK.”$"

Help_Text_HowToUsePC::
	.string "{CIRCLE_1} Go to any CHECKPOINT, go up to\n"
	.string "   the PORT and press the A Button.$"

Help_Text_HowToUseBillsPC::
	.string "{CIRCLE_1} Select “{STR_VAR_1}'S PORT” on the PORT.\n"
	.string "{CIRCLE_2} Select from one of the top three\n"
	.string "   MENU items to access the DAEMON\n"
	.string "   Storage System.\n"
	.string "If you bind a DAEMON when you have\n"
	.string "six in your party, the DAEMON is sent\n"
	.string "automatically to a BOX in the System!$"

Help_Text_HowToUseWithdraw::
	.string "{CIRCLE_1} Select a DAEMON in the open BOX\n"
	.string "   with the {PLUS} Control Pad.\n"
	.string "{CIRCLE_2} Select “EDDY” to remove the\n"
	.string "   DAEMON from the BOX and add it to\n"
	.string "   your party.\n"
	.string "You may not withdraw a DAEMON if you\n"
	.string "already have six DAEMONS with you!$"

Help_Text_HowToUseDeposit::
	.string "{CIRCLE_1} Select a DAEMON in your party with\n"
	.string "   the {PLUS} Control Pad.\n"
	.string "{CIRCLE_2} Select “DEPOSIT.”\n"
	.string "{CIRCLE_3} Select the BOX, then press the\n"
	.string "   A Button to store the DAEMON.\n"
	.string "If you have only one DAEMON with you,\n"
	.string "it may not be stored!$"

Help_Text_HowToUseMove::
	.string "{CIRCLE_1} Select a DAEMON in the open BOX.\n"
	.string "{CIRCLE_2} Pick up the DAEMON by selecting\n"
	.string "   “MOVE” and move it anywhere with\n"
	.string "   the {PLUS} Control Pad.\n"
	.string "{CIRCLE_3} Move the DAEMON to the BOX name\n"
	.string "   and press left or right to move it\n"
	.string "   to another BOX.$"

Help_Text_HowToMoveItems::
	.string "{CIRCLE_1} Faintly shown DAEMON can be made\n"
	.string "   to hold an item by selecting it and\n"
	.string "   pressing the A Button.\n"
	.string "{CIRCLE_2} Clearly shown DAEMON can be made\n"
	.string "   to give the item they are holding to\n"
	.string "   another DAEMON, or return the item\n"
	.string "   to the BAG with the A Button.$"

Help_Text_HowToUsePlayersPC::
	.string "{CIRCLE_1} Select “{PLAYER}'s PORT” on the PORT.\n"
	.string "{CIRCLE_2} Select either “ITEM STORAGE” or\n"
	.string "   “MAILBOX.”\n"
	.string "You may store things in your own PORT\n"
	.string "if your BAG is full. You may also\n"
	.string "withdraw items stored in your PORT.$"

Help_Text_HowToUseWithdrawItem::
	.string "{CIRCLE_1} Select “EDDY ITEM.”\n"
	.string "{CIRCLE_2} Select the item to be withdrawn.\n"
	.string "{CIRCLE_3} The item can be withdrawn and\n"
	.string "   placed in the BAG's ITEMS POCKET.\n"
	.string "   It may also be directly given to a\n"
	.string "   DAEMON to hold.$"

Help_Text_HowToUseDepositItem::
	.string "{CIRCLE_1} Select “DEPOSIT ITEM.”\n"
	.string "{CIRCLE_2} Select the item in the BAG to be\n"
	.string "   deposited using the {PLUS} Control Pad.\n"
	.string "{CIRCLE_3} If there is more than one \n"
	.string "   item to be deposited, enter the\n"
	.string "   quantity with the {PLUS} Control Pad,\n"
	.string "   then press the A Button.$"

Help_Text_HowToUseMailbox::
	.string "When MAIL is taken from a DAEMON,\n"
	.string "it is moved to the MAILBOX. If it has\n"
	.string "no MAIL, the MAILBOX can't be used.\n"
	.string "{CIRCLE_1} Select “{PLAYER}'S PORT” on the PORT.\n"
	.string "{CIRCLE_2} Select “MAILBOX” to read MAIL or\n"
	.string "   make a DAEMON hold MAIL.$"

Help_Text_HowToUseProfOaksPC::
	.string "{CIRCLE_1} Select “CRYSTAL CLEAR'S PORT”\n"
	.string "   on the PORT.\n"
	.string "{CIRCLE_2} CRYSTAL CLEAR will evaluate\n"
	.string "   your INDEX.\n"
	.string "Her evaluations should give you hints\n"
	.string "for binding more DAEMONS!$"

Help_Text_HowToOpenMenu::
	.string "{CIRCLE_1} Press START.\n"
	.string "{CIRCLE_2} The MENU will open on the right.\n"
	.string "{CIRCLE_3} Depending on the situation, the MENU\n"
	.string "   may feature different headings.\n"
	.string "The MENU will not open in certain\n"
	.string "situations such as when talking, doing\n"
	.string "something, battling, etc.$"

Help_Text_HowToUseFight::
	.string "{CIRCLE_1} Select “INVOKE.” {CIRCLE_2} Select one of the\n"
	.string "ROUTINES shown, and that ROUTINE will be\l"
	.string "used!$"

Help_Text_HowToUsePokemon2::
	.string "{CIRCLE_1} Select “DAEMON.”\n"
	.string "{CIRCLE_2} Select the DAEMON in your party\n"
	.string "   that you want to use.\n"
	.string "{CIRCLE_3} If you have two or more DAEMONS\n"
	.string "   with you, they may be switched by\n"
	.string "   selecting “SHIFT.” Check DAEMON\n"
	.string "   data by selecting “SUMMARY.”$"

Help_Text_HowToUseShift::
	.string "This command switches the DAEMON in\n"
	.string "battle with another one in your party.\n"
	.string "{CIRCLE_1} Select the DAEMON to be sent out.\n"
	.string "{CIRCLE_2} Select “SHIFT.”\n"
	.string "{CIRCLE_3} The selected DAEMON will switch\n"
	.string "   places with the DAEMON in battle!$"

Help_Text_HowToUseSummary2::
	.string "{CIRCLE_1} Select “SUMMARY.”\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the information:\n"
	.string "   “DAEMON INFO”\n"
	.string "   “DAEMON SKILLS”\n"
	.string "   “KNOWN ROUTINES”$"

Help_Text_HowToUseBag2::
	.string "{CIRCLE_1} Select “BAG.”\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the data headings:\n"
	.string "   “ITEMS”\n"
	.string "   “KEY ITEMS”\n"
	.string "   “BOXES”\n"
	.string "   Press up or down to select an item.$"

Help_Text_HowToReadPokedex::
	.string "{CIRCLE_1} DAEMON that you have bound are\n"
	.string "   identified by a POKé BOX mark on\n"
	.string "   the INDEX list.\n"
	.string "{CIRCLE_2} A bound DAEMON will provide a\n"
	.string "   large amount of data.\n"
	.if REVISION < 1
	.string "{CIRCLE_3} Select “AREA” to display the TOWN\n"
	.string "   MAP with the DAEMON's habitat(s).$"
	.else
	.string "{CIRCLE_3} Select “NEXT DATA” to display the\n"
	.string "   SITEMAP with its habitat(s).$"
	.endif

Help_Text_HowToUseHomePC::
	.string "{CIRCLE_1} Go up to the PORT at home, then\n"
	.string "   press the A Button.\n"
	.string "{CIRCLE_2} The PORT will turn on.\n"
	.string "{CIRCLE_3} Select either “ITEM STORAGE” or\n"
	.string "   “MAILBOX.”$"

Help_Text_HowToUseItemStorage::
	.string "{CIRCLE_1} Select “EDDY ITEM” to withdraw\n"
	.string "   an item stored on your PORT.\n"
	.string "{CIRCLE_2} Select “DEPOSIT ITEM” to put an\n"
	.string "   item from your BAG into the PORT.$"

Help_Text_HowToUseWithdrawItem2::
	.string "{CIRCLE_1} Select “EDDY ITEM.”\n"
	.string "{CIRCLE_2} Select the item to be withdrawn.\n"
	.string "{CIRCLE_3} The item can be withdrawn and\n"
	.string "   placed in the BAG's ITEMS POCKET.\n"
	.string "   It may also be directly given to a\n"
	.string "   DAEMON to hold.$"

Help_Text_HowToUseDepositItem2::
	.string "{CIRCLE_1} Select “DEPOSIT ITEM.”\n"
	.string "{CIRCLE_2} Select the item in the BAG to be\n"
	.string "   deposited using the {PLUS} Control Pad.\n"
	.string "{CIRCLE_3} If there is nothing in the BAG, this\n"
	.string "   command can't be used!$"

Help_Text_HowToUseMailbox2::
	.string "When MAIL is taken from a DAEMON,\n"
	.string "it is moved to the MAILBOX. If it has\n"
	.string "no MAIL, the MAILBOX can't be used.\n"
	.string "{CIRCLE_1} Select MAIL by name to read it or\n"
	.string "   make a DAEMON hold it.$"

Help_Text_HowToUseRun::
	.string "You may not “RUN” from a USER\n"
	.string "battle!\n"
	.string "{CIRCLE_1} You may “RUN” from a wild DAEMON.\n"
	.string "{CIRCLE_2} Your chance of escape is improved\n"
	.string "   if your DAEMON in battle is fast.$"

Help_Text_HowToRegisterKeyItem::
	.string "You may “REGISTER” a key item for\n"
	.string "instant use by pressing SELECT!\n"
	.string "{CIRCLE_1} Open the “KEY ITEMS” POCKET.\n"
	.string "{CIRCLE_2} Select the key item, then select\n"
	.string "   “REGISTER.”$"

Help_Text_HowToUseBall::
	.string "{CIRCLE_1} Select to throw the special POKé\n"
	.string "   BOX used only in the SAFARI ZONE.\n"
	.string "When wild DAEMONS appear, throw lots\n"
	.string "of GUESTBOXES to bind them!$"

Help_Text_HowToUseBait::
	.string "{CIRCLE_1} Select to throw the special food\n"
	.string "   used only in the SAFARI ZONE.\n"
	.string "It is DAEMON food rolled up into\n"
	.string "a box for easy eating. When BAIT is\n"
	.string "thrown, the wild DAEMON may get\n"
	.string "attracted by it, and may not DETACH!$"

Help_Text_HowToUseRock::
	.string "{CIRCLE_1} Select to throw a rock lying on\n"
	.string "   the ground in the SAFARI ZONE.\n"
	.string "Throwing a rock at a DAEMON may \n"
	.string "make it run away, but it becomes easier\n"
	.string "to bind!$"

Help_Text_HowToUseHallOfFame::
	.string "{CIRCLE_1} Select “HALL OF FAME” on the PORT.\n"
	.string "{CIRCLE_2} The DAEMON that have entered the\n"
	.string "   HALL OF FAME can be examined.$"

Help_Text_HP::
	.string "HP$"

Help_Text_EXP::
	.string "EXP. {LEFT_PAREN}EXP. Points{RIGHT_PAREN}$"

Help_Text_Moves::
	.string "ROUTINES$"

Help_Text_Attack::
	.string "ATTACK$"

Help_Text_Defense::
	.string "DEFENSE$"

Help_Text_SpAtk::
	.string "SP. ATK$"

Help_Text_SpDef::
	.string "SP. DEF$"

Help_Text_Speed::
	.string "SPEED$"

Help_Text_Level::
	.string "Lv. {LEFT_PAREN}Level{RIGHT_PAREN}$"

Help_Text_Type::
	.string "TYPE$"

Help_Text_OT::
	.string "OT$"

Help_Text_Item::
	.string "ITEM$"

Help_Text_Ability::
	.string "ABILITY$"

Help_Text_Money::
	.string "MONEY$"

Help_Text_MoveType::
	.string "ROUTINE TYPE$"

Help_Text_Nature::
	.string "NATURE$"

Help_Text_IDNo::
	.string "ID No.$"

Help_Text_PP::
	.string "MP$"

Help_Text_Power::
	.string "POWER$"

Help_Text_Accuracy::
	.string "ACCURACY$"

Help_Text_FNT::
	.string "FNT$"

Help_Text_Items::
	.string "ITEMS$"

Help_Text_KeyItems::
	.string "KEY ITEMS$"

Help_Text_PokeBalls::
	.string "BOXES$"

Help_Text_Pokedex::
	.string "INDEX$"

Help_Text_PlayTime::
	.string "PLAY TIME$"

Help_Text_Badges::
	.string "MARKS$"

Help_Text_TextSpeed::
	.string "TEXT SPEED$"

Help_Text_BattleScene::
	.string "BATTLE SCENE$"

Help_Text_BattleStyle::
	.string "BATTLE STYLE$"

Help_Text_Sound::
	.string "SOUND$"

Help_Text_ButtonMode::
	.string "BUTTON MODE$"

Help_Text_Frame::
	.string "FRAME$"

Help_Text_Cancel2::
	.string "CANCEL$"

Help_Text_TM::
	.string "TM$"

Help_Text_HM::
	.string "HM$"

Help_Text_HMMove::
	.string "HM ROUTINE$"

Help_Text_Evolution::
	.string "EVOLUTION$"

Help_Text_StatusProblem::
	.string "STATUS PROBLEM$"

Help_Text_Pokemon::
	.string "DAEMON$"

Help_Text_IDNo2::
	.string "ID No.$"

Help_Text_Money2::
	.string "MONEY$"

Help_Text_Badges2::
	.string "MARKS$"

Help_Text_DefineHP::
	.string "HP indicates a DAEMON's vitality. If a\n"
	.string "DAEMON's HP drops to zero, it HALTS and\l"
	.string "is unable to battle. So, the key in\l"
	.string "battle is to try to reduce the foe's HP\l"
	.string "to zero. If your DAEMONS are hurt,\l"
	.string "restore their HP at a CHECKPOINT or\l"
	.string "use items.$"

Help_Text_DefineEXP::
	.string "EXP. Points stands for “Experience\n"
	.string "Points.” DAEMON gain EXP. Points by\l"
	.string "participating in winning battles. When a\l"
	.string "DAEMON accumulates sufficient EXP.\l"
	.string "Points, it levels up. The EXP. Bar\l"
	.string "indicates accumulated EXP. Points. It\l"
	.string "returns to zero upon leveling up.$"

Help_Text_DefineMoves::
	.string "DAEMON may learn up to four different\n"
	.string "ROUTINES. There are many kinds of ROUTINES\l"
	.string "including attacks and those with special\l"
	.string "effects. The kinds of ROUTINES that can be\l"
	.string "learned vary for each DAEMON. Some\l"
	.string "ROUTINES can be learned from items.$"

Help_Text_DefineAttack::
	.string "ATTACK indicates the power of an offensive\n"
	.string "ROUTINE. The higher this stat, the more\l"
	.string "powerful the ROUTINE. It is applied for the\l"
	.string "following ROUTINE types: CONTENT, CORRUPT,\l"
	.string "STRATUM, VECTOR, SWARM, LOGIC, LEGACY,\l"
	.string "LATENT and HARDENED.$"

Help_Text_DefineDefense::
	.string "DEFENSE indicates the resistance a\n"
	.string "DAEMON has against physical attacks.\l"
	.string "The higher this stat, the less damage\l"
	.string "sustained from a foe's physical hit.$"

Help_Text_DefineSpAtk::
	.string "SP. ATK (Special Attack) indicates the power\n"
	.string "of a special attack ROUTINE. The higher this\l"
	.string "stat, the more powerful the special attack\l"
	.string "ROUTINE. It is applied for the following\l"
	.string "ROUTINE types: ENTROPY, FLOW, SIGNAL,\l"
	.string "GROWTH, FROZEN, CONTEXT, EMERGENT and\l"
	.string "OPAQUE.$"

Help_Text_DefineSpDef::
	.string "SP. DEF (Special Defense) indicates the\n"
	.string "resistance a DAEMON has against special\l"
	.string "attacks. The higher this stat, the less\l"
	.string "damage sustained from a foe's special\l"
	.string "attack.$"

Help_Text_DefineSpeed::
	.string "SPEED indicates the agility of a DAEMON. If\n"
	.string "this stat exceeds the foe's in battle, the\l"
	.string "DAEMON can make a ROUTINE before its slower\l"
	.string "opponent.$"

Help_Text_DefineLevel::
	.string "Lv. (Level) indicates the growth and\n"
	.string "strength of a DAEMON. In general, when a\l"
	.string "DAEMON levels up, its stats such as HP,\l"
	.string "ATTACK, and DEFENSE rise, making it\l"
	.string "stronger. DAEMON may learn a new ROUTINE\l"
	.string "upon leveling up.$"

Help_Text_DefineType::
	.string "DAEMON and ROUTINES are classified by type.\n"
	.string "Every type has advantageous and\l"
	.string "disadvantageous matchups against other\l"
	.string "types. For example, like a rock-\l"
	.string "paper-scissors game, the FLOW type is strong\l"
	.string "against the ENTROPY type and weak against\l"
	.string "the GROWTH type.$"

Help_Text_DefineOT::
	.string "OT stands for “Original USER,” the first\n"
	.string "USER to have bound the selected\l"
	.string "DAEMON. Even if the DAEMON is traded,\l"
	.string "the OT name will remain unchanged.$"

Help_Text_DefineItem::
	.string "All DAEMONS can be made to hold one\n"
	.string "item each. Some items will be used by\l"
	.string "the DAEMON automatically in certain\l"
	.string "situations. To make a DAEMON hold an\l"
	.string "item, select the item from the BAG and\l"
	.string "“GIVE” it to the DAEMON.$"

Help_Text_DefineAbility::
	.string "All DAEMONS have a special ABILITY.\n"
	.string "There are many different kinds of these\l"
	.string "abilities, some used in battle, some\l"
	.string "elsewhere. The abilities differ from\l"
	.string "species to species. Some species may\l"
	.string "have more than one kind of ability.$"

Help_Text_DefineMoney::
	.string "Whenever you win a battle against a\n"
	.string "USER, you are given prize money. Save\l"
	.string "up your prize money so you can enjoy\l"
	.string "shopping at REPOS!$"

Help_Text_DefineMoveType::
	.string "ROUTINES are also classified by types. If a\n"
	.string "DAEMON of a certain type invokes a ROUTINE\l"
	.string "of the same type, the ROUTINE's power is\l"
	.string "boosted. If the ROUTINE's type has a\l"
	.string "matchup advantage against the target, its\l"
	.string "effectiveness is also boosted.$"

Help_Text_DefineNature::
	.string "All DAEMONS have a personality, or\n"
	.string "“NATURE.” The DAEMON's nature appears\l"
	.string "to affect how the DAEMON will grow\l"
	.string "upon leveling up.$"

Help_Text_DefineIDNo::
	.string "The ID No. is a special number assigned\n"
	.string "specifically to you as a USER.\l"
	.string "Together with the OT name, the ID No.\l"
	.string "is used to precisely identify the\l"
	.string "Original USER. The ID No. does not\l"
	.string "change even if the DAEMON is traded.$"

Help_Text_DefinePP::
	.string "MP stands for “Power Points.” It\n"
	.string "indicates the number of times a certain\l"
	.string "ROUTINE can be invoked in battle. Like\l"
	.string "HP, MP can be restored by visiting a\l"
	.string "CHECKPOINT or using certain items.$"

Help_Text_DefinePower::
	.string "POWER indicates the strength of an\n"
	.string "attack. The higher this number, the\l"
	.string "greater the damage that can be\l"
	.string "inflicted on the foe!$"

Help_Text_DefineAccuracy::
	.string "ACCURACY indicates the probability of the\n"
	.string "ROUTINE hitting the foe. The higher this\l"
	.string "number, the more likely the ROUTINE will\l"
	.string "strike the target.$"

Help_Text_DefineFNT::
	.string "FNT stands for “HALTED.” A DAEMON\n"
	.string "HALTS if its HP is reduced to zero. It\l"
	.string "becomes incapable of taking part in\l"
	.string "battle. Restore a HALTED DAEMON at a\l"
	.string "CHECKPOINT, or use an item.$"

Help_Text_DefineItems::
	.string "Ordinary items bought at any DAEMON\n"
	.string "MART are placed in the ITEMS POCKET.\l"
	.string "Items may be used, given to a DAEMON\l"
	.string "to hold, or tossed out as garbage.$"

Help_Text_DefineKeyItems::
	.string "Important items that you find or \n"
	.string "receive from people are placed in the\l"
	.string "KEY ITEMS POCKET.\l"
	.string "Key items may be used, or registered\l"
	.string "for use instantly with SELECT. Once\l"
	.string "registered, the item can be used\l"
	.string "without opening the MENU and BAG.$"

Help_Text_DefinePokeBalls::
	.string "BOXES, which are used for binding\n"
	.string "wild DAEMONS, are placed in the POKé\l"
	.string "BOXES POCKET. BOXES may be\l"
	.string "bought at REPOS. They may be used,\l"
	.string "given to a DAEMON to hold, or tossed\l"
	.string "out as garbage.$"

Help_Text_DefinePokedex::
	.string "This indicates the number of species of\n"
	.string "DAEMON you have bound and/or evolved\l"
	.string "to fill the INDEX. Try hard to bind all\l"
	.string "sorts of DAEMONS!$"

Help_Text_DefinePlayTime::
	.string "This is the total amount of time that\n"
	.string "you have played this game.$"

Help_Text_DefineBadges::
	.string "The DAEMON LEAGUE MARKS that you have\n"
	.string "won are registered and shown. Earn\l"
	.string "MARKS by outscoring GYM LEADERS in\l"
	.string "various cities and towns.$"

Help_Text_DefineTextSpeed::
	.string "You can adjust how quickly the text is\n"
	.string "displayed. Choose one: SLOW, MID,\l"
	.string "or FAST.$"

Help_Text_DefineBattleScene::
	.string "You can choose to turn the battle\n"
	.string "animation ON or OFF.$"

Help_Text_DefineBattleStyle::
	.string "You can choose whether or not a USER\n"
	.string "can switch a DAEMON after it has made\l"
	.string "its foe HALT. Set to “SHIFT” if you\l"
	.string "would like the chance to switch a\l"
	.string "DAEMON after it has made its foe\l"
	.string "HALT.$"

Help_Text_DefineSound::
	.string "You can choose between MONO and\n"
	.string "STEREO sound output.$"

Help_Text_DefineButtonMode::
	.string "Set to “HELP” to display help messages\n"
	.string "by pressing the L or R Button. Set to\l"
	.string "“LR” to enable the switching of the\l"
	.string "INDEX pages and BAG POCKETS using the\l"
	.string "L and R Buttons. Set to “L=A” to make\l"
	.string "the L Button work the same as the A\l"
	.string "Button.$"

Help_Text_DefineFrame::
	.string "You may choose the design of the frame\n"
	.string "around certain menus. Try them out and\l"
	.string "see what you like.$"

Help_Text_DefineCancel2::
	.string "The settings will be changed to the\n"
	.string "selections shown in red, and you will\l"
	.string "return to the MENU.$"

Help_Text_DefineTM::
	.string "A TM (Technical Machine) is a device used to\n"
	.string "teach a ROUTINE to a DAEMON. There are\l"
	.string "many different kinds. ROUTINES can be taught\l"
	.string "only to those DAEMONS capable of using\l"
	.string "them. A TM breaks after a single use.$"

Help_Text_DefineHM::
	.string "An HM (Hidden Machine) is a device used to\n"
	.string "teach a HIDDEN ROUTINE to a DAEMON. A\l"
	.string "HIDDEN ROUTINE can be taught only to those\l"
	.string "DAEMONS capable of using it. Unlike a TM, an\l"
	.string "HM can be used over and over. A HIDDEN\l"
	.string "ROUTINE can be tough for a DAEMON to\l"
	.string "forget.$"

Help_Text_DefineHMMove::
	.string "HIDDEN ROUTINES are those that are\n"
	.string "especially important for your adventure. To\l"
	.string "invoke such a ROUTINE outside of battle,\l"
	.string "open the “DAEMON” MENU and make the DAEMON\l"
	.string "that knows the ROUTINE invoke it. A HALTED\l"
	.string "DAEMON may invoke a HIDDEN ROUTINE outside\l"
	.string "battle.$"

Help_Text_DefineEvolution::
	.string "Among DAEMON, there are some that undergo\n"
	.string "major changes (evolution) upon growing to\l"
	.string "certain levels. Evolution causes a DAEMON to\l"
	.string "alter form, change its name, and perhaps\l"
	.string "change the ROUTINES it may learn. Some\l"
	.string "DAEMONS evolve due to reasons other than\l"
	.string "leveling up.$"

Help_Text_DefineStatusProblem::
	.string "Status problems include: Suspension: Can't\n"
	.string "invoke ROUTINES. LEAKING: steady HP loss.\l"
	.string "Throttling: May prevent ROUTINES.\l"
	.string "Overheating: HP loss, less ATTACK. Hang:\l"
	.string "Can't invoke ROUTINES. These can be healed\l"
	.string "with items, etc.$"

Help_Text_DefinePokemon::
	.string "DAEMON is a name given to describe\n"
	.string "wondrous creatures that inhabit all\l"
	.string "corners of this world. People raise\l"
	.string "DAEMONS to be their pets, use them for\l"
	.string "battling, and so on.$"

Help_Text_DefineIDNo2::
	.string "The ID No. is a special number assigned\n"
	.string "specifically to you as a USER.\l"
	.string "Together with the OT name, the ID No.\l"
	.string "is used to precisely identify the\l"
	.string "Original USER. The ID No. does not\l"
	.string "change even if the DAEMON is traded.$"

Help_Text_DefineMoney2::
	.string "Whenever you win a battle against a\n"
	.string "USER, you are given prize money. Save\l"
	.string "up your prize money so you can enjoy\l"
	.string "shopping at REPOS!$"

Help_Text_DefineBadges2::
	.string "This indicates the number of DAEMONS\n"
	.string "LEAGUE MARKS that you have won. Earn\l"
	.string "MARKS by outscoring GYM LEADERS in\l"
	.string "various cities and towns.$"

Help_Text_TheHelpSystem::
	.string "The HELP System$"

Help_Text_TheGame::
	.string "The game$"

Help_Text_WirelessAdapter::
	.string "Wireless Adapter$"

Help_Text_GameFundamentals1::
	.string "Game fundamentals 1$"

Help_Text_GameFundamentals2::
	.string "Game fundamentals 2$"

Help_Text_GameFundamentals3::
	.string "Game fundamentals 3$"

Help_Text_WhatArePokemon::
	.string "What are DAEMON?$"

Help_Text_DescTheHelpSystem::
	.string "The help messages change depending on\n"
	.string "how much you have progressed in the\l"
	.string "game. They are designed to support you\l"
	.string "when you need them. If there is\l"
	.string "anything that you don't understand,\l"
	.string "please look up the HELP System!$"

Help_Text_DescTheGame::
	.string "You become the main character to\n"
	.string "explore the world of DAEMON! By\l"
	.string "talking to people and solving mysteries,\l"
	.string "new paths will open to you. Strive for\l"
	.string "the goal together with your wonderful\l"
	.string "DAEMON!$"

Help_Text_DescWirelessAdapter::
	.string "This game communicates over a wireless\n"
	.string "link using the Wireless Adapter.\p"
	.string "Go wireless anywhere, anytime, and\n"
	.string "with anybody!\p"
	.string "Try playing with the Wireless Adapter\n"
	.string "always attached!$"

Help_Text_DescGameFundamentals1::
	.string "Visit every city and town, travel every\n"
	.string "road, explore every cave, and face\l"
	.string "every challenge as you strive to\l"
	.string "become the greatest USER of DAEMON!$"

Help_Text_DescGameFundamentals2::
	.string "On your adventure, you will be faced\n"
	.string "with many obstacles. Every obstacle\l"
	.string "can be overcome by doing something\l"
	.string "or by solving mysteries. Some obstacles\l"
	.string "are affected by something that happens\l"
	.string "far away.$"

Help_Text_DescGameFundamentals3::
	.string "Some of the obstacles in your way can be\n"
	.string "removed once your DAEMON learn specific\l"
	.string "ROUTINES.$"

Help_Text_DescWhatArePokemon::
	.string "DAEMONS are wondrous creatures that\n"
	.string "are shrouded in mystery. You may meet\l"
	.string "them all over the world…in tall grass,\l"
	.string "caves, the sea, and more. They appear\l"
	.string "to grow obedient to the USERS that\l"
	.string "bound them.$"

Help_Text_UsingTypeMatchupList::
	.string "Using the Type Matchup List$"

Help_Text_OwnMoveDark::
	.string "Own ROUTINE type: OPAQUE$"

Help_Text_OwnPokemonDark::
	.string "Own DAEMON type: OPAQUE$"

Help_Text_OwnMoveRock::
	.string "Own ROUTINE type: LEGACY$"

Help_Text_OwnPokemonRock::
	.string "Own DAEMON type: LEGACY$"

Help_Text_OwnMovePsychic::
	.string "Own ROUTINE type: CONTEXT$"

Help_Text_OwnPokemonPsychic::
	.string "Own DAEMON type: CONTEXT$"

Help_Text_OwnMoveFighting::
	.string "Own ROUTINE type: LOGIC$"

Help_Text_OwnPokemonFighting::
	.string "Own DAEMON type: LOGIC$"

Help_Text_OwnMoveGrass::
	.string "Own ROUTINE type: GROWTH$"

Help_Text_OwnPokemonGrass::
	.string "Own DAEMON type: GROWTH$"

Help_Text_OwnMoveGhost::
	.string "Own ROUTINE type: LATENT$"

Help_Text_OwnPokemonGhost::
	.string "Own DAEMON type: LATENT$"

Help_Text_OwnMoveIce::
	.string "Own ROUTINE type: FROZEN$"

Help_Text_OwnPokemonIce::
	.string "Own DAEMON type: FROZEN$"

Help_Text_OwnMoveGround::
	.string "Own ROUTINE type: STRATUM$"

Help_Text_OwnPokemonGround::
	.string "Own DAEMON type: STRATUM$"

Help_Text_OwnMoveElectric::
	.string "Own ROUTINE type: SIGNAL$"

Help_Text_OwnPokemonElectric::
	.string "Own DAEMON type: SIGNAL$"

Help_Text_OwnMovePoison::
	.string "Own ROUTINE type: CORRUPT$"

Help_Text_OwnPokemonPoison::
	.string "Own DAEMON type: CORRUPT$"

Help_Text_OwnMoveDragon::
	.string "Own ROUTINE type: EMERGENT$"

Help_Text_OwnPokemonDragon::
	.string "Own DAEMON type: EMERGENT$"

Help_Text_OwnMoveNormal::
	.string "Own ROUTINE type: CONTENT$"

Help_Text_OwnPokemonNormal::
	.string "Own DAEMON type: CONTENT$"

Help_Text_OwnMoveSteel::
	.string "Own ROUTINE type: HARDENED$"

Help_Text_OwnPokemonSteel::
	.string "Own DAEMON type: HARDENED$"

Help_Text_OwnMoveFlying::
	.string "Own ROUTINE type: VECTOR$"

Help_Text_OwnPokemonFlying::
	.string "Own DAEMON type: VECTOR$"

Help_Text_OwnMoveFire::
	.string "Own ROUTINE type: ENTROPY$"

Help_Text_OwnPokemonFire::
	.string "Own DAEMON type: ENTROPY$"

Help_Text_OwnMoveWater::
	.string "Own ROUTINE type: FLOW$"

Help_Text_OwnPokemonWater::
	.string "Own DAEMON type: FLOW$"

Help_Text_OwnMoveBug::
	.string "Own ROUTINE type: SWARM$"

Help_Text_OwnPokemonBug::
	.string "Own DAEMON type: SWARM$"

Help_Text_HowToUseTypeMatchupList::
	.string "Depending on the matchup of the ROUTINE\n"
	.string "type and the target DAEMON's type, the\l"
	.string "ROUTINE's effectiveness varies: {CIRCLE_DOT}:\l"
	.string "Super effective! {TRIANGLE}: Not very\l"
	.string "effective {BIG_MULT_X}: Not effective at all (No\l"
	.string "changes for other matchups.)$"

Help_Text_TypeMatchupOwnMoveDark::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: CONTEXT, LATENT\p"
	.string "   {TRIANGLE}: LOGIC, OPAQUE, HARDENED$"

Help_Text_TypeMatchupOwnPokemonDark::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: LOGIC, SWARM\p"
	.string "   {TRIANGLE}: LATENT, OPAQUE\p"
	.string "   {BIG_MULT_X}: CONTEXT$"

Help_Text_TypeMatchupOwnMoveRock::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: ENTROPY, FROZEN, VECTOR, SWARM\p"
	.string "   {TRIANGLE}: LOGIC, STRATUM, HARDENED$"

Help_Text_TypeMatchupOwnPokemonRock::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: FLOW, GROWTH, LOGIC,\n"
	.string "       STRATUM, HARDENED\p"
	.string "   {TRIANGLE}: CONTENT, ENTROPY, CORRUPT,\n"
	.string "       VECTOR$"

Help_Text_TypeMatchupOwnMovePsychic::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: LOGIC, CORRUPT\p"
	.string "   {TRIANGLE}: CONTEXT, HARDENED\p"
	.string "   {BIG_MULT_X}: OPAQUE$"

Help_Text_TypeMatchupOwnPokemonPsychic::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: SWARM, LATENT, OPAQUE\p"
	.string "   {TRIANGLE}: LOGIC, CONTEXT$"

Help_Text_TypeMatchupOwnMoveFighting::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: CONTENT, FROZEN, LEGACY,\n"
	.string "       OPAQUE, HARDENED\p"
	.string "   {TRIANGLE}: CORRUPT, VECTOR, CONTEXT,\n"
	.string "       SWARM\p"
	.string "   {BIG_MULT_X}: LATENT$"

Help_Text_TypeMatchupOwnPokemonFighting::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: VECTOR, CONTEXT\p"
	.string "   {TRIANGLE}: SWARM, LEGACY, OPAQUE$"

Help_Text_TypeMatchupOwnMoveGrass::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: FLOW, STRATUM, LEGACY\p"
	.string "   {TRIANGLE}: ENTROPY, GROWTH, CORRUPT,\n"
	.string "       VECTOR, \n"
	.string "       SWARM, EMERGENT, HARDENED$"

Help_Text_TypeMatchupOwnPokemonGrass::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: ENTROPY, FROZEN, CORRUPT,\n"
	.string "       VECTOR, SWARM\p"
	.string "   {TRIANGLE}: FLOW, SIGNAL, GROWTH, STRATUM$"

Help_Text_TypeMatchupOwnMoveGhost::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: CONTEXT, LATENT\p"
	.string "   {TRIANGLE}: OPAQUE, HARDENED\p"
	.string "   {BIG_MULT_X}: CONTENT$"

Help_Text_TypeMatchupOwnPokemonGhost::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: LATENT, OPAQUE\p"
	.string "   {TRIANGLE}: CORRUPT, SWARM\p"
	.string "   {BIG_MULT_X}: CONTENT, LOGIC$"

Help_Text_TypeMatchupOwnMoveIce::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: GROWTH, STRATUM, VECTOR,\n"
	.string "       EMERGENT\p"
	.string "   {TRIANGLE}: ENTROPY, FLOW, FROZEN,\n"
	.string "       HARDENED$"

Help_Text_TypeMatchupOwnPokemonIce::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: ENTROPY, LOGIC, LEGACY,\n"
	.string "       HARDENED\p"
	.string "   {TRIANGLE}: FROZEN$"

Help_Text_TypeMatchupOwnMoveGround::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: ENTROPY, SIGNAL, CORRUPT,\n"
	.string "       LEGACY, \n"
	.string "       HARDENED\p"
	.string "   {TRIANGLE}: GROWTH, SWARM\n"
	.string "   {BIG_MULT_X}: VECTOR$"

Help_Text_TypeMatchupOwnPokemonGround::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: FLOW, GROWTH, FROZEN\p"
	.string "   {TRIANGLE}: CORRUPT, LEGACY\p"
	.string "   {BIG_MULT_X}: SIGNAL$"

Help_Text_TypeMatchupOwnMoveElectric::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: FLOW, VECTOR\p"
	.string "   {TRIANGLE}: SIGNAL, GROWTH, EMERGENT\p"
	.string "   {BIG_MULT_X}: STRATUM$"

Help_Text_TypeMatchupOwnPokemonElectric::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: STRATUM\p"
	.string "   {TRIANGLE}: SIGNAL, VECTOR, HARDENED$"

Help_Text_TypeMatchupOwnMovePoison::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: GROWTH\p"
	.string "   {TRIANGLE}: CORRUPT, STRATUM, LEGACY,\n"
	.string "       LATENT\p"
	.string "   {BIG_MULT_X}: HARDENED$"

Help_Text_TypeMatchupOwnPokemonPoison::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: STRATUM, CONTEXT\p"
	.string "   {TRIANGLE}: GROWTH, LOGIC, CORRUPT, SWARM$"

Help_Text_TypeMatchupOwnMoveDragon::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: EMERGENT\p"
	.string "   {TRIANGLE}: HARDENED$"

Help_Text_TypeMatchupOwnPokemonDragon::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: FROZEN, EMERGENT\p"
	.string "   {TRIANGLE}: ENTROPY, FLOW, SIGNAL, GROWTH$"

Help_Text_TypeMatchupOwnMoveNormal::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {TRIANGLE}: LEGACY, HARDENED\p"
	.string "   {BIG_MULT_X}: LATENT$"

Help_Text_TypeMatchupOwnPokemonNormal::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: LOGIC\p"
	.string "   {BIG_MULT_X}: LATENT$"

Help_Text_TypeMatchupOwnMoveSteel::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: FROZEN, LEGACY\p"
	.string "   {TRIANGLE}: ENTROPY, FLOW, SIGNAL,\n"
	.string "       HARDENED$"

Help_Text_TypeMatchupOwnPokemonSteel::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: ENTROPY, LOGIC, STRATUM\n"
	.string "   {TRIANGLE}: CONTENT, GROWTH, FROZEN,\n"
	.string "       VECTOR, \l"
	.string "       CONTEXT, SWARM, LEGACY, LATENT,\l"
	.string "       EMERGENT, OPAQUE, HARDENED\l"
	.string "   {BIG_MULT_X}: CORRUPT$"

Help_Text_TypeMatchupOwnMoveFlying::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: GROWTH, LOGIC, SWARM\p"
	.string "   {TRIANGLE}: SIGNAL, LEGACY, HARDENED$"

Help_Text_TypeMatchupOwnPokemonFlying::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: SIGNAL, FROZEN, LEGACY\p"
	.string "   {TRIANGLE}: GROWTH, LOGIC, SWARM\p"
	.string "   {BIG_MULT_X}: STRATUM$"

Help_Text_TypeMatchupOwnMoveFire::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: GROWTH, FROZEN, SWARM,\n"
	.string "       HARDENED\p"
	.string "   {TRIANGLE}: ENTROPY, FLOW, LEGACY,\n"
	.string "       EMERGENT$"

Help_Text_TypeMatchupOwnPokemonFire::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: FLOW, STRATUM, LEGACY\p"
	.string "   {TRIANGLE}: ENTROPY, GROWTH, FROZEN,\n"
	.string "       SWARM, HARDENED$"

Help_Text_TypeMatchupOwnMoveWater::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: ENTROPY, STRATUM, LEGACY\p"
	.string "   {TRIANGLE}: FLOW, GROWTH, EMERGENT$"

Help_Text_TypeMatchupOwnPokemonWater::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: SIGNAL, GROWTH\p"
	.string "   {TRIANGLE}: ENTROPY, FLOW, FROZEN,\n"
	.string "       HARDENED$"

Help_Text_TypeMatchupOwnMoveBug::
	.string "Effect on the opposing DAEMON:\p"
	.string "   {CIRCLE_DOT}: GROWTH, CONTEXT, OPAQUE\p"
	.string "   {TRIANGLE}: ENTROPY, LOGIC, CORRUPT,\n"
	.string "       VECTOR, LATENT, HARDENED$"

Help_Text_TypeMatchupOwnPokemonBug::
	.string "Effect of foe's ROUTINE on own DAEMON:\p"
	.string "   {CIRCLE_DOT}: ENTROPY, VECTOR, LEGACY\p"
	.string "   {TRIANGLE}: GROWTH, LOGIC, STRATUM$"

