Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "POKé DUDE: The speedier of the\n"
	.string "battlers gets to attack first.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "It looks like my NIBBLE was faster\n"
	.string "than the PACKET.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "The battlers take turns attacking\n"
	.string "and reducing each other's HP.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "My NIBBLE reduced the foe's HP\n"
	.string "to zero, so it wins!\p"
	.string "The DAEMON that took part in the\n"
	.string "battle get EXP. Points.\p"
	.string "When a DAEMON collects enough\n"
	.string "EXP. Points, it levels up.\p"
	.string "Leveling up makes your DAEMON\n"
	.string "stronger than before.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "POKé DUDE: Uh-oh… My NIBBLE has\n"
	.string "been poisoned…\p"
	.string "If a DAEMON is poisoned, it loses\n"
	.string "HP steadily.$"

Pokedude_Text_HealStatusRightAway::
	.string "If a DAEMON develops a status\n"
	.string "problem, heal it right away.$"

Pokedude_Text_UsingItemTakesTurn::
	.string "Using an item on a DAEMON uses up\n"
	.string "one turn, though.\p"
	.string "Now, it's the opponent's turn!$"

Pokedude_Text_YayWeManagedToWin::
	.string "Yay!\n"
	.string "We managed to win!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "POKé DUDE: The move BUBBLE is a\n"
	.string "WATER-type attack.\p"
	.string "The targeted ODDISH is a\n"
	.string "GRASS/POISON-type DAEMON.\p"
	.string "The WATER-type attack is absorbed\n"
	.string "by the GRASS-type DAEMON…\p"
	.string "As a result, the move becomes not\n"
	.string "very effective, and inflicts only\l"
	.string "half the usual damage.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Uh-oh, this is not good!\p"
	.string "The ABSORB attack you just saw is\n"
	.string "a GRASS-type move.\p"
	.string "POLIWAG is a WATER-type DAEMON.\p"
	.string "So, ABSORB becomes super\n"
	.string "effective, doubling the damage.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "It's not going to be easy to win\n"
	.string "with this matchup…\p"
	.string "Let's try shifting DAEMON!$"

Pokedude_Text_ShiftingUsesTurn::
	.string "Shifting DAEMON in and out uses up\n"
	.string "one turn.\p"
	.string "Now, it's the opponent's turn.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "INDEXER is a BUG/FLYING-type\n"
	.string "DAEMON.\p"
	.string "Against this DAEMON, a GRASS- type\n"
	.string "attack…\p"
	.string "…inflicts only half the usual\n"
	.string "damage on a BUG-type DAEMON…\p"
	.string "…And, it also causes only half the\n"
	.string "damage on a FLYING-type DAEMON.\p"
	.string "Therefore, INDEXER, being a\n"
	.string "BUG/FLYING DAEMON, only takes one\l"
	.string "quarter of the usual damage.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "ODDISH is a GRASS/POISON-type\n"
	.string "DAEMON.\p"
	.string "A FLYING- or PSYCHIC-type attack\n"
	.string "is super effective against it.\p"
	.string "One of those types of attacks will\n"
	.string "inflict double the usual damage.\p"
	.string "Okay, here we go!$"

Pokedude_Text_YeahWeWon::
	.string "Yeah!\n"
	.string "We won!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "POKé DUDE: When you're trying to\n"
	.string "bind a DAEMON, don't throw any POKé\l"
	.string "BOXES right away.\p"
	.string "First, you need to weaken it by\n"
	.string "reducing its HP.$"

Pokedude_Text_BestIfTargetStatused::
	.string "Okay, that should be good enough.\p"
	.string "But, if it's possible, it would be\n"
	.string "best if the target has a status\l"
	.string "problem.\p"
	.string "For instance, it would be easier to\n"
	.string "bind if it were asleep or\l"
	.string "paralyzed.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "This will make the DAEMON a lot\n"
	.string "easier to bind!\p"
	.string "Oh, yes. If you paralyze a\n"
	.string "DAEMON, you can't make it fall\l"
	.string "asleep on top of paralysis.\p"
	.string "In other words, you can't double up\n"
	.string "status problems, okay?$"

Pokedude_Text_LetMeThrowBall::
	.string "Okay! Let me throw my POKé BOX!$"

Pokedude_Text_PickBestKindOfBall::
	.string "Before you throw a POKé BOX,\n"
	.string "consider the condition and the type\l"
	.string "of DAEMON, and pick the kind of\l"
	.string "BOX that would work best.$"
