Text_FirstShouldRestoreMonsHealth::
	.string "First, you should restore your\n"
	.string "DAEMON to full health.$"

Text_MonsHealedShouldBuyPotions::
	.string "Your DAEMONS have been healed to\n"
	.string "perfect health.\p"
	.string "If your DAEMON's energy, HP, is\n"
	.string "down, please come see us.\p"
	.string "If you're planning to go far in the\n"
	.string "field, you should buy some POTIONS\l"
	.string "at the DAEMON MART.\p"
	.string "We hope you excel!$"

Text_MonsHealed::
	.string "Your DAEMONS have been healed to\n"
	.string "perfect health.\p"
	.string "We hope you excel!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "MOM: {PLAYER}!\n"
	.string "Welcome home.\p"
	.string "It sounds like you had quite\n"
	.string "an experience.\p"
	.string "Maybe you should take a quick\n"
	.string "rest.$"

Text_MomExplainHPGetPotions::
	.string "MOM: Oh, good! You and your\n"
	.string "DAEMONS are looking great.\p"
	.string "I just heard from CRYSTAL CLEAR.\p"
	.string "She said that DAEMON's energy is\n"
	.string "measured in HP.\p"
	.string "If your DAEMON lose their HP, you\n"
	.string "can restore them at any DAEMON\l"
	.string "CENTER.\p"
	.string "If you're going to travel far away,\n"
	.string "the smart USER stocks up on\l"
	.string "POTIONS at the DAEMON MART.\p"
	.string "Make me proud, honey!\p"
	.string "Take care!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} is out of usable DAEMON!\p"
	.string "{PLAYER} panicked and lost\n"
	.string "¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_WhitedOut::
	.string "{PLAYER} is out of usable DAEMON!\p"
	.string "{PLAYER} whited out!$"
