LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Do you believe in ghosts?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Really?\n"
    .string "So there are believers…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, I guess not.\p"
    .string "That white hand on your shoulder…\n"
    .string "I'm just imagining it.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "This town is known as the grave\n"
    .string "site of DAEMON.\p"
    .string "Memorial services are held in\n"
    .string "DAEMON TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "GHOSTs appeared in DAEMON TOWER.\p"
    .string "I think they're the spirits of\n"
    .string "DAEMON that the CORPUS killed.$"

LavenderTown_Text_TownSign::
    .string "HALFTONE TOWN\n"
    .string "The Noble Purple\l"
    .string "Town$"

LavenderTown_Text_SilphScopeNotice::
    .string "New RESOLVER!\p"
    .string "Make the Invisible Plain to See!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "HALFTONE VOLUNTEER\n"
    .string "DAEMON HOUSE$"

LavenderTown_Text_PokemonTowerSign::
    .string "DAEMON TOWER Becalm the Spirits of\n"
    .string "DAEMON$"

