LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Do you believe in ghosts?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Really?\n"
    .string "So there are believers…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, I guess not.\p"
    .string "That white hand on your shoulder…\n"
    .string "I'm just imagining it.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "This town is known as the grave\n"
    .string "site of DAEMON.\p"
    .string "Memorial services are held in\n"
    .string "DAEMON TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "GHOSTs appeared in DAEMON TOWER.\p"
    .string "I think they're the spirits of\n"
    .string "DAEMON that the CORPUS killed.$"

@  T-324, DRAFT.
LavenderTown_Text_TownSign::
    .string "HALFTONE TOWN\n"
    .string "Grey, From The Road$"

@  T-324, DRAFT.
LavenderTown_Text_SilphScopeNotice::
    .string "New from FOUNDRY CO.!\p"
    .string "RESOLVER\n"
    .string "Put a name to what you see.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "HALFTONE ORPHAN HOUSE$"

@  T-324, DRAFT.
LavenderTown_Text_PokemonTowerSign::
    .string "DAEMON TOWER\n"
    .string "For the ones that halted.\l"
    .string "Please keep your voice down.$"

