PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .string "This place is, like, huge!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "Ayah!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "I wonder where my partner went.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "My mentor once lived here.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "Whew!\n"
    .string "Overwhelming!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "So, you're stuck?\n"
    .string "Try jumping off over there!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "LOG: Tue Aug 12 It answered\n"
    .string "before I had finished asking.\p"
    .string "RESPOND 1001: I mimic. I am not\n"
    .string "awakening.\p"
    .string "The code is not what it was.$"

