SaffronCity_Gym_Text_SabrinaIntro::
    .string "I had a vision of your arrival.\p"
    .string "I have had psychic powers since\n"
    .string "I was a child.\p"
    .string "It started when a spoon I\n"
    .string "carelessly tossed, bent.\p"
    .string "I dislike battling, but if you wish,\n"
    .string "I will show you my powers!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "I'm shocked! But, a loss is a loss.\p"
    .string "I admit I didn't work hard enough\n"
    .string "to win!\p"
    .string "You earned the FRAME MARK!$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Psychic power isn't something that\n"
    .string "only a few people have.\p"
    .string "Everyone has psychic power.\n"
    .string "People just don't realize it.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "The FRAME MARK makes DAEMON up to\n"
    .string "L70 obey you!\p"
    .string "Stronger DAEMON will become wild,\n"
    .string "ignoring your orders in battle!\p"
    .string "Just don't raise your DAEMON too\n"
    .string "much!\p"
    .string "Wait, please take this TM with you!$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} received TM04 from\n"
    .string "SABRINA.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "TM04 is CALM MIND.\p"
    .string "It makes the DAEMON concentrate to\n"
    .string "raise both SP. ATK and SP. DEF.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Your BAG is full of other items.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA is far younger than I,\n"
    .string "but she has earned my respect.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "Not good enough!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "In a battle of equals, the one\n"
    .string "with the stronger will wins.\p"
    .string "If you wish to beat SABRINA, focus\n"
    .string "and will yourself to victory.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Does our unseen power scare you?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "I never foresaw this!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "PSYCHIC DAEMON fear only ghosts\n"
    .string "and bugs!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "DAEMON take on the appearance of\n"
    .string "their USERS.\p"
    .string "Your DAEMON must be tough, then!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "I knew it!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "I have much to learn still…\p"
    .string "I must master PSYCHIC and teach it\n"
    .string "to my DAEMONS…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "You understand, don't you?\p"
    .string "That power alone isn't enough to win\n"
    .string "in the world of DAEMON?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "I don't believe this!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA just wiped out the KARATE\n"
    .string "MASTER next door.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "You and I, our DAEMON shall\n"
    .string "battle!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "I lost after all!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "I knew that this was going to take\n"
    .string "place.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA is young, but she's also\n"
    .string "our highly skilled LEADER.\p"
    .string "You won't reach her easily!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Ow!\n"
    .string "Down and out!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "There used to be 2 DAEMON GYMs in\n"
    .string "BRAZEN.\p"
    .string "The FIGHTING DOJO next door lost\n"
    .string "its GYM status when we went and\l"
    .string "creamed them!$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "BRAZEN DAEMON GYM is famous for\n"
    .string "its psychics!\p"
    .string "You want to see SABRINA! I can\n"
    .string "tell!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "That's right! I used telepathy to\n"
    .string "read your mind!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Yo! Champ in making!\p"
    .string "SABRINA's DAEMON use psychic power\n"
    .string "instead of force!\p"
    .string "Fighting DAEMONS are weak against\n"
    .string "psychic DAEMON!\p"
    .string "They get creamed before they can\n"
    .string "even aim a punch!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Psychic power, huh?\p"
    .string "If I had that, I'd make a bundle\n"
    .string "at the slots!$"

SaffronCity_Gym_Text_GymStatue::
    .string "BRAZEN DAEMON GYM LEADER:\n"
    .string "SABRINA\p"
    .string "WINNING USERS: {RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "BRAZEN DAEMON GYM LEADER:\n"
    .string "SABRINA\p"
    .string "WINNING USERS: {RIVAL}, {PLAYER}$"

