VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "There are evil people who will use\n"
    .string "DAEMON for criminal acts.\p"
    .string "TEAM CORPUS traffics in rare\n"
    .string "DAEMON.\p"
    .string "They also abandon DAEMON that\n"
    .string "they consider not to be popular or\l"
    .string "useful.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "I think DAEMON can be good or\n"
    .string "evil. It depends on the USER.$"

