VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "TEAM CORPUS buys up rare DAEMON.\n"
    .string "Pays well, too.\p"
    .string "The ones that don't test well,\n"
    .string "they let go out the back.\p"
    .string "Very polite about it. That's the\n"
    .string "part I can't get past.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "I think DAEMON can be good or\n"
    .string "evil. It depends on the USER.$"

