VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "There are wicked people who will\n"
    .string "use DAEMON for criminal acts.\p"
    .string "TEAM CORPUS traffics in rare\n"
    .string "DAEMON, for example.\p"
    .string "They also abandon DAEMON that\n"
    .string "they consider unpopular or useless.\p"
    .string "That's the sort of horrid people\n"
    .string "they are, TEAM CORPUS.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "I think DAEMON can be good or bad.\n"
    .string "It depends on the USER.$"

