SixIsland_Text_IslandSign::
    .string "SIX ISLAND\n"
    .string "Old things, and people\l"
    .string "who did not move away$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
    .string "Keep on and the path gets wet.\p"
    .string "Keep on after that and it stops\n"
    .string "being a path.$"

SixIsland_Text_SkyAtNightIsFantastic::
    .string "When you're this far away from the\n"
    .string "city, the sky at night is fantastic.$"

