CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "DAEMON stat enhancers can be\n"
    .string "bought only here.\p"
    .string "MEMORY increases the base HP of a\n"
    .string "DAEMON.\p"
    .string "BANDWIDTH raises the base SP. ATK\n"
    .string "stat of one DAEMON.\p"
    .string "INSULATION boosts the base SP.\n"
    .string "DEF stat of one DAEMON.\p"
    .string "CLOCK RATE enhances the base\n"
    .string "SPEED stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "I'm here for DAEMON stat enhancers.\p"
    .string "WATTAGE increases the base ATTACK\n"
    .string "power.\p"
    .string "SHIELDING increases the base\n"
    .string "DEFENSE stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: DRUGSTORE$"

