SilphCo_7F_Text_HaveMonForSavingUs::
    .string "Oh! Hi! You're not a CORPUS! You\n"
    .string "came to save us? Why, thank you!\p"
    .string "I want you to have this DAEMON for\n"
    .string "saving us.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER} obtained a LAPRAS from\n"
    .string "the SILPH employee!$"

SilphCo_7F_Text_ExplainLapras::
    .string "It's a LAPRAS. It's a very\n"
    .string "intelligent DAEMON.\p"
    .string "We kept it in our lab, but it will\n"
    .string "be much better off with you.\p"
    .string "I think you will be a good USER\n"
    .string "for LAPRAS!\p"
    .string "It's a good swimmer. It'll give you\n"
    .string "a lift across water!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "TEAM ROCKET's BOSS went to the\n"
    .string "boardroom!\p"
    .string "Is our PRESIDENT okay?\n"
    .string "I'm worried.$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "TEAM CORPUS was after the MASTER\n"
    .string "BALL, which binds any DAEMON.$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "We canceled the MASTER BALL\n"
    .string "project because of TEAM CORPUS.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "It would be bad if TEAM CORPUS\n"
    .string "took over SILPH or our DAEMON.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "Wow!\p"
    .string "You chased off TEAM CORPUS all by\n"
    .string "yourself?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "You!\n"
    .string "It's really dangerous here!\p"
    .string "You came to save me?\n"
    .string "You can't!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "Thank you so much!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "Uh-oh!\n"
    .string "I smell a little mouse!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "Lights out!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "You won't find my BOSS by just\n"
    .string "scurrying around!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "Heheh!\p"
    .string "You mistook me for a SILPH worker?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "I'm done!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "Despite your age, you are a\n"
    .string "skilled USER!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "I am one of the four CORPUS\n"
    .string "BROTHERS!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "Aack!\n"
    .string "Brothers, I lost!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "Doesn't matter.\n"
    .string "My brothers will repay the favor!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "A child intruder?\n"
    .string "That must be you!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "Fine!\n"
    .string "I lost!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "Go on home before my BOSS gets\n"
    .string "ticked off!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: What kept you, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: Hahaha! I thought you'd\n"
    .string "turn up if I waited here!\p"
    .string "I guess TEAM CORPUS slowed you\n"
    .string "down! Not that I care!\p"
    .string "I saw you in BRAZEN, so I decided\n"
    .string "to see if you got better!$"

SilphCo_7F_Text_RivalDefeat::
    .string "Oh, man! So, you are ready for\n"
    .string "BOSS CORPUS!$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .string "Well, {PLAYER}! I'm moving on up and\n"
    .string "ahead!\p"
    .string "By checking my INDEX, I'm starting\n"
    .string "to see what's strong and how they\l"
    .string "evolve!\p"
    .string "Am I a genius or what?\p"
    .string "I'm going to the DAEMON LEAGUE to\n"
    .string "boot out the ELITE FOUR.\p"
    .string "I'll become the world's most\n"
    .string "powerful USER!\p"
    .string "{PLAYER}, well, good luck to you!\n"
    .string "Don't sweat it! Smell ya!$"

SilphCo_7F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "7F$"

