ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha! Welcome to my hideout!\p"
    .string "It shall be so until I can restore\n"
    .string "TEAM CORPUS to its former glory.\p"
    .string "But, you have found me again. So\n"
    .string "be it. This time, I'm not holding\l"
    .string "back!\p"
    .string "Once more, you shall face\n"
    .string "GIOVANNI, the greatest USER!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha!\n"
    .string "That was a truly intense fight.\l"
    .string "You have won!\p"
    .string "As proof, here is the EARTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Having lost in this fashion, I can't\n"
    .string "face my followers. I have betrayed\l"
    .string "their trust.\p"
    .string "As of today, TEAM CORPUS is\n"
    .string "finished forever!\p"
    .string "As for myself, I shall dedicate my\n"
    .string "life to training again.\p"
    .string "Let us meet again someday!\n"
    .string "Farewell!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "The EARTHBADGE makes DAEMON of\n"
    .string "any level obey without question.\p"
    .string "It is evidence of your mastery as\n"
    .string "a DAEMON USER.\p"
    .string "With it, you can challenge the\n"
    .string "DAEMON LEAGUE.\p"
    .string "Also, take this TM.\p"
    .string "Consider it a gift for your DAEMON\n"
    .string "LEAGUE challenge.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} received TM26\n"
    .string "from GIOVANNI.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 contains EARTHQUAKE.\p"
    .string "It is a powerful attack that causes\n"
    .string "a massive tremor.\p"
    .string "I made it when I ran the GYM here,\n"
    .string "far too long ago… $"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "You do not have space for this!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\n"
    .string "You must be running out of steam\l"
    .string "by now!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "I ran out of gas!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "You'll need power to keep up with\n"
    .string "our GYM LEADER.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrroar!\n"
    .string "I'm working myself into a rage!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "I'm still not worthy!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "DAEMON and I, we make wonderful\n"
    .string "music together!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "You are in perfect harmony!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Do you know the identity of our\n"
    .string "GYM LEADER?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate is the ultimate form of\n"
    .string "martial arts!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "If my DAEMONS were as good at\n"
    .string "karate as I…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "The truly talented win with style.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "I lost my grip!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "The LEADER will scold me for\n"
    .string "losing this way…$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "I'm the KARATE KING!\n"
    .string "Your fate rests with me!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "The DAEMON LEAGUE? You? Don't get\n"
    .string "cocky!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "Your DAEMON will cower at the\n"
    .string "crack of my whip!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Yowch!\n"
    .string "Whiplash!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Wait!\n"
    .string "I was just careless!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "CALLOW GYM was closed for a long\n"
    .string "time.\p"
    .string "But now, our LEADER is back!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "I was beaten?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "You can go on to the DAEMON\n"
    .string "LEAGUE only by defeating our GYM\l"
    .string "LEADER!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Yo! Champ in the making!\p"
    .string "Even I don't know the CALLOW\n"
    .string "LEADER's identity.\p"
    .string "But one thing's certain. This will be\n"
    .string "the toughest of all the GYM\l"
    .string "LEADERS.\p"
    .string "Also, I heard that the USERS here\n"
    .string "like GROUND-type DAEMON.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Blow me away! GIOVANNI was the\n"
    .string "GYM LEADER of CALLOW?$"

ViridianCity_Gym_Text_GymStatue::
    .string "CALLOW DAEMON GYM LEADER: ?\p"
    .string "WINNING USERS: {RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "CALLOW DAEMON GYM LEADER:\n"
    .string "GIOVANNI\p"
    .string "WINNING USERS: {RIVAL}, {PLAYER}$"

