SixIsland_PokemonCenter_1F_Text_SomethingHiddenOnThisIsland::
    .string "For ten years, I've searched for\n"
    .string "RUINS.\p"
    .string "No, make that twenty years.\p"
    .string "I get this feeling that there's\n"
    .string "something hidden on this island.$"

SixIsland_PokemonCenter_1F_Text_SomeMonsEvolveByTradingWithHeldItem::
    .string "You know of DAEMON that evolve\n"
    .string "only upon trading, yes?\p"
    .string "But did you know that there are\n"
    .string "still others?\p"
    .string "Some DAEMONS evolve only when\n"
    .string "traded while holding specific items.$"

SixIsland_PokemonCenter_1F_Text_RivalImpossibleToGetAllMonsAroundHere::
    .string "{RIVAL}: {PLAYER}. How full is your\n"
    .string "INDEX?\p"
    .string "You cannot get all of them around\n"
    .string "here. I checked.\p"
    .string "There are DAEMONS somewhere else.\n"
    .string "Somewhere far off.\p"
    .string "… … … … … … … … …\p"
    .string "If I cannot do it, you cannot.\p"
    .string "I am not going to get desperate\n"
    .string "about it.\p"
    .string "I will keep binding them at my own\n"
    .string "pace, and training them.\p"
    .string "So there is no reason to stay. I\n"
    .string "am going home.\p"
    .string "That is that.$"

