SafariZone_North_Text_RestHouse::
    .string "IDLE HOUSE$"

@  T-324, DRAFT.
SafariZone_North_Text_SecretHouseStillAhead::
    .string "USER TIPS\p"
    .string "The SECRET HOUSE is further\n"
    .string "in. Keep going.$"

SafariZone_North_Text_Area2::
    .string "AREA 2$"

@  T-324, DRAFT.
SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "USER TIPS\p"
    .string "Daemons hide in tall grass.\p"
    .string "Walk it back and forth to\n"
    .string "flush them out.$"

@  T-324, DRAFT.
SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "USER TIPS\p"
    .string "Find the SECRET HOUSE and a\n"
    .string "DRIVER is yours to keep.$"

