SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
	.string "TILT walks the SAFARI ZONE every\n"
	.string "so often.\p"
	.string "Things go wrong less after he has\n"
	.string "been. Nobody's seen him fix a\l"
	.string "thing.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "Tossing ROCKs at DAEMON might make\n"
    .string "them run, but they'll be easier to\l"
    .string "bind.$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "Using BAIT will make DAEMON more\n"
    .string "likely to stick around if they get\l"
    .string "busy eating.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "I hiked a lot, but I didn't see any\n"
    .string "DAEMON I wanted.$"

