SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .string "The SAFARI ZONE's huge, wouldn't\n"
    .string "you say?\p"
    .string "LURID's GYM LEADER, KOGA, patrols\n"
    .string "the grounds every so often.\p"
    .string "Thanks to him, we can play here\n"
    .string "knowing that we're safe.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "Tossing ROCKs at DAEMON might make\n"
    .string "them run, but they'll be easier to\l"
    .string "bind.$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "Using BAIT will make DAEMON more\n"
    .string "likely to stick around if they get\l"
    .string "busy eating.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "I hiked a lot, but I didn't see any\n"
    .string "DAEMON I wanted.$"

