FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "PHLEGMATIC: Put them back.\p"
    .string "I was raised on the other side\n"
    .string "of that wall.\p"
    .string "I know what is in there.\n"
    .string "You do not.$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Aww, shut it, lady, and leave\n"
    .string "us be.\p"
    .string "Don't let your glasses get all\n"
    .string "steamed up!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
	.string "PHLEGMATIC: {PLAYER}?! What\n"
    .string "are you doing here?\p"
    .string "No, we can talk later. Right\n"
    .string "now, I need your help.\p"
    .string "Help me kick these poachers out\n"
    .string "before they do anything else.\p"
    .string "They've been binding DAEMONS\n"
    .string "here, then selling them off!\p"
    .string "Are you ready? You take that\n"
    .string "one, please!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "W-what?!\p"
    .string "Who says we can't do what we want\n"
    .string "with the DAEMON we bind?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "We didn't plan on this!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "PHLEGMATIC: That was quick.\p"
    .string "Where have you taken the ones\n"
    .string "you already have?\p"
    .string "I am not asking twice.$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "N-no way!\n"
    .string "I'm not telling you that!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
	.string "PHLEGMATIC: If you won't\n"
    .string "confess, we'll deep-hang you.\p"
    .string "My FERRY is furious for what\n"
    .string "you've done to its friends.\p"
    .string "Go, FERRY! FREEZE…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "Wawaah! Okay! I'll talk!\p"
    .string "The DAEMONS are in the CORPUS\n"
    .string "WAREHOUSE on FIVE ISLAND.\p"
    .string "There! I said it! We'll be going\n"
    .string "now!\p"
    .string "…But I doubt you'll ever make it\n"
    .string "into the CORPUS WAREHOUSE!\p"
    .string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, thank you.\n"
    .string "But this is awful…\p"
    .string "I was born and raised here on\n"
    .string "these islands.\p"
    .string "I had no idea that those horrible\n"
    .string "criminals were loose here…$"

