CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "CORPUS did this!\p"
    .string "Look what they did here!\p"
    .string "They stole a TM for teaching\n"
    .string "DAEMON how to DIG holes!\p"
    .string "That cost me a bundle, it did!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "I figure what's lost is lost.\p"
    .string "I decided to teach DIGLETT how to\n"
    .string "DIG without a TM.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "TEAM CORPUS must be trying to DIG\n"
    .string "their way into no good!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "TEAM CORPUS left a way out!$"

