SilphCo_1F_Text_WelcomePresidentInBoardroom::
    .string "Welcome.\p"
    .string "The PRESIDENT is in the boardroom\n"
    .string "on 11F.$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile::
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "1F$"

SilphCo_1F_Text_Engraving::
    .string "Cast into the floor, worn smooth.\p"
    .string "WHEN A MEASURE BECOMES A TARGET,\n"
    .string "IT CEASES TO BE A GOOD MEASURE$"
