LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "CORPUS did it. I hate them.\p"
    .string "That poor CUBONE's mother...\p"
    .string "It was killed trying to escape from\n"
    .string "TEAM CORPUS!$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "The ghost of DAEMON TOWER is\n"
    .string "gone!\p"
    .string "Someone must have soothed its\n"
    .string "restless spirit!$"

