SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…Thank you for writing.\n"
    .string "I hope to see you soon!\p"
    .string "…Hey!\n"
    .string "Don't look at my letter!$"

SaffronCity_House_Text_Pidgey::
    .string "PACKET: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "The COPYCAT is cute! I'm getting\n"
    .string "her a DECOY!$"

@  T-324, DRAFT.
SaffronCity_House_Text_ExplainPPUp::
    .string "I was given an MP UP.\p"
    .string "It gives a ROUTINE more uses.\p"
    .string "Best spent on a strong one\n"
    .string "that runs out fast.$"

