SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…Thank you for writing.\n"
    .string "I hope to see you soon!\p"
    .string "…Hey!\n"
    .string "Don't look at my letter!$"

SaffronCity_House_Text_Pidgey::
    .string "PACKET: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "The COPYCAT is cute! I'm getting\n"
    .string "her a POKé DOLL!$"

SaffronCity_House_Text_ExplainPPUp::
    .string "I was given a MP UP as a gift.\p"
    .string "It's used to increase the MP of a\n"
    .string "DAEMON's move.\p"
    .string "I should use it on a powerful move\n"
    .string "with only a few MP.$"

