FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
	.string "PHLEGMATIC: There's something\n"
    .string "weighing heavily on my mind.\p"
    .string "If anything were to happen on\n"
    .string "the island where I was born…\p"
    .string "I wouldn't know about it if I\n"
    .string "were in the DAEMON LEAGUE.\p"
    .string "I wonder if that would make\n"
    .string "me irresponsible to my home…$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
	.string "PHLEGMATIC: So, you managed to\n"
    .string "solve all the problems here?\p"
    .string "That's wonderful.\p"
    .string "That means there isn't any reason\n"
    .string "for me to be here all the time.\p"
    .string "Thank you…\p"
    .string "I'll return to the DAEMON LEAGUE\n"
    .string "in a short while.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "I don't know what will happen in\n"
    .string "the future, but…\p"
    .string "I will do what I can here and now.\n"
    .string "That's all I can do.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "Stuffed DAEMON dolls galore!$"

