VermilionCity_Text_GrimerMultipliesInSludge::
    .string "Afternoon. One man, on his own.\p"
    .string "Left a door open. That is all it\n"
    .string "was.\p"
    .string "A white rabbit sat there after.\n"
    .string "Just sat.\p"
    .string "Below where the roof went in.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Did you see the S.S. ANNE moored\n"
    .string "in the harbor?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "So, the S.S. ANNE has departed?\p"
    .string "She'll be back in ARDOR about this\n"
    .string "time next year.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "I'm putting up a building on this\n"
    .string "plot of land. I own it all.\p"
    .string "My DAEMON is tamping the land to\n"
    .string "lay the foundation.$"

VermilionCity_Text_Machop::
    .string "MACHOP: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "A MACHOP is stomping the land flat.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "S.S.ANNE is a famous luxury cruise\n"
    .string "ship.\p"
    .string "We visit ARDOR once a year.$"

VermilionCity_Text_CitySign::
    .string "ARDOR CITY\n"
    .string "The Port of\l"
    .string "Exquisite Sunsets$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "NOTICE!\p"
    .string "ROUTE 12 may be blocked off by a\n"
    .string "sleeping DAEMON.\p"
    .string "Detour through THE BLACKOUT to\n"
    .string "HALFTONE TOWN.\p"
    .string "ARDOR POLICE$"

VermilionCity_Text_PokemonFanClubSign::
    .string "DAEMON FAN CLUB\n"
    .string "All DAEMONS fans\l"
    .string "welcome!$"

VermilionCity_Text_GymSign::
    .string "ARDOR CITY\n"
    .string "DAEMON GYM\l"
    .string "LEADER: LT.SURGE\p"
    .string "The Lightning\n"
    .string "American!$"

VermilionCity_Text_VermilionHarbor::
    .string "ARDOR HARBOR$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Welcome to the S.S. ANNE!\p"
    .string "Excuse me, do you have a ticket?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} flashed the S.S. TICKET!\p"
    .string "{FONT_MALE}Great!\n"
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER} doesn't have the needed\n"
    .string "S.S. TICKET.\p"
    .string "{FONT_MALE}Sorry!\p"
    .string "You need a ticket to get aboard.$"

VermilionCity_Text_TheShipSetSail::
    .string "The ship set sail.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Ah, you have a TRI-PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Okay, everything's in order.\p"
    .string "SEAGALLOP HI-SPEED 7 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Ah, you have a RAINBOW PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Oh! That's a MYSTICTICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "NAVEL ROCK anytime.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Oh! That's an AURORATICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "BIRTH ISLAND anytime.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 10 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 12 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Oh, hello, {PLAYER}! How are you\n"
    .string "doing?\p"
    .string "It's me, one of CRYSTAL CLEAR's\n"
    .string "AIDES.\p"
    .string "Did you meet the other AIDE?\p"
    .string "He had a package from\n"
    .string "CRYSTAL CLEAR for you, {PLAYER}.\p"
    .string "He said he'd look for you around\n"
    .string "ROUTE 2, {PLAYER}.\p"
    .string "If you're in the ROUTE 2 area,\n"
    .string "please look for him.$"

