PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "DAEMON learn new techniques as\n"
    .string "they grow.\p"
    .string "But some moves must be taught to\n"
    .string "them by people.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "A DAEMON becomes easier to bind if\n"
    .string "it has a status problem.\p"
    .string "Sleep, poison, burn, or paralysis…\n"
    .string "Those are all effective.\p"
    .string "But binding DAEMONS is never a sure\n"
    .string "thing!$"

