PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "DAEMON learn new techniques as\n"
    .string "they grow!\p"
    .string "But, some moves must be taught by\n"
    .string "the USER!$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "A DAEMON becomes easier to bind if\n"
    .string "it has a status problem.\p"
    .string "Sleep, poison, burn, or paralysis…\n"
    .string "Those are all effective.\p"
    .string "But binding DAEMONS is never a sure\n"
    .string "thing!$"

