PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Welcome to the DAEMON LEAGUE.\p"
    .string "I am LORELEI of the ELITE FOUR.\p"
    .string "No one can best me when it comes\n"
    .string "to icy DAEMON.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your DAEMON will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha! Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Welcome to the DAEMON LEAGUE.\p"
    .string "I, LORELEI of the ELITE FOUR,\n"
    .string "have returned!\p"
    .string "You know how it goes. No one can\n"
    .string "best me when it comes to icy\l"
    .string "DAEMON.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your DAEMON will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha! Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Things shouldn't be this way!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "You're better than I thought. Go on\n"
    .string "ahead.\p"
    .string "You only got a taste of the DAEMON\n"
    .string "LEAGUE's power.$"

