PokemonLeague_LoreleisRoom_Text_Intro::
	.string "Welcome to the DAEMON LEAGUE.\p"
	.string "I am PHLEGMATIC.\n"
	.string "Fourth of the REVIEW BOARD.\p"
	.string "There is no hurry. There never is.\p"
	.string "Freezing ROUTINES are powerful.\p"
	.string "Your DAEMON will be at my mercy\n"
	.string "when they are hung solid.\p"
	.string "Whenever you are ready.{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
	.string "Welcome to the DAEMON LEAGUE.\p"
	.string "I, PHLEGMATIC of the REVIEW\n"
	.string "BOARD, am here again.\p"
	.string "There is still no hurry.\p"
	.string "Freezing ROUTINES are powerful.\p"
	.string "Your DAEMON will be at my mercy\n"
	.string "when they are hung solid.\p"
	.string "Whenever you are ready.{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
	.string "…There.\n"
	.string "That was not slow at all.$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
	.string "Go on ahead.\p"
	.string "Take the next one slowly.\n"
	.string "It will not go anywhere.$"

