PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Welcome to the DAEMON LEAGUE.\p"
    .string "I am PHLEGMATIC.\nFourth of the REVIEW BOARD.\p"
    .string "No one can best me when it comes\n"
    .string "to icy DAEMON.\p"
    .string "Freezing ROUTINES are powerful.\p"
    .string "Your DAEMON will be at my mercy\n"
    .string "when they are hung solid.\p"
    .string "Hahaha! Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
	.string "Welcome to the DAEMON LEAGUE.\p"
    .string "I, PHLEGMATIC of the REVIEW\n"
    .string "BOARD, have returned!\p"
    .string "You know how it goes. No one\n"
    .string "can best me when it comes to\l"
    .string "icy DAEMON.\p"
    .string "Freezing ROUTINES are powerful.\p"
    .string "Your DAEMON will be at my\n"
    .string "mercy when they are hung solid.\p"
    .string "Hahaha! Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Things shouldn't be this way!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "You're better than I thought. Go on\n"
    .string "ahead.\p"
    .string "You only got a taste of the DAEMON\n"
    .string "LEAGUE's power.$"

