CeladonCity_Gym_Text_ErikaIntro::
    .string "Hello. Lovely weather isn't it? It's\n"
    .string "so pleasant.\p"
    .string "...Oh dear... I must have dozed\n"
    .string "off. Welcome.\p"
    .string "My name is ERIKA. I am the LEADER\n"
    .string "of VERDIGRIS GYM.\p"
    .string "I teach the art of flower\n"
    .string "arranging. My DAEMONS are of the\l"
    .string "grass-type.\p"
    .string "Oh, I'm sorry, I had no idea that\n"
    .string "you wished to challenge me.\p"
    .string "Very well, but I shall not lose.$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Oh! I concede the score.\p"
    .string "You are remarkably strong.\p"
    .string "I must confer you the FIT MARK.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "You are cataloging DAEMON? I must\n"
    .string "say I'm impressed.\p"
    .string "I would never collect DAEMONS if\n"
    .string "they were unattractive.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "The FIT MARK will make DAEMON up\n"
    .string "to L50 obey.\p"
    .string "It also allows DAEMON to use\n"
    .string "STRENGTH in and out of battle.\p"
    .string "Please also take this with you.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} received TM19\n"
    .string "from ERIKA.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "TM19 contains GIGA DRAIN.\p"
    .string "Half the damage it inflicts is\n"
    .string "drained to heal your DAEMON.\p"
    .string "Wouldn't you agree that it's a\n"
    .string "wonderful move?$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "You should make room for this.$"

CeladonCity_Gym_Text_KayIntro::
    .string "I should tell you about this GYM.\p"
    .string "Only real ladies are allowed in\n"
    .string "here!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "You're too rough!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "Bleaah!\n"
    .string "I hope ERIKA wipes you out!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Oh, welcome.\n"
    .string "I was getting bored.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "My makeup!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "Grass-type DAEMONS are tough\n"
    .string "against the water-type!\p"
    .string "They also have an edge on rock\n"
    .string "and ground DAEMON!$"

CeladonCity_Gym_Text_TinaIntro::
    .string "…Weren't you peeking in here\n"
    .string "earlier?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "You're an eye-opener!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Oh, you were looking at ERIKA…\n"
    .string "You weren't looking at me…$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "Look, look! See my DAEMONS!\p"
    .string "I like the GRASS type. I like how\n"
    .string "they're easy to raise.$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "No!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "We only use GRASS-type DAEMON at\n"
    .string "our GYM.\p"
    .string "Why? We also use them for making\n"
    .string "flower arrangements!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Oh, hey!\p"
    .string "We don't like BUG- or FIRE-type\n"
    .string "DAEMON in here!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Oh!\n"
    .string "You!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "Our LEADER ERIKA might be quiet,\n"
    .string "but she's famous around here.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Pleased to meet you. My hobby is\n"
    .string "DAEMON training.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Oh!\n"
    .string "Splendid!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "I have a blind date coming up.\n"
    .string "I have to learn to be polite,\l"
    .string "especially if I have to battle.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "Welcome to VERDIGRIS GYM!\p"
    .string "You better not underestimate girl\n"
    .string "power!$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "Oh!\n"
    .string "Beaten!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "I didn't bring my best DAEMONS. Wait\n"
    .string "until next time!$"

CeladonCity_Gym_Text_GymStatue::
    .string "VERDIGRIS DAEMON GYM LEADER:\n"
    .string "ERIKA\p"
    .string "WINNING USERS: {RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "VERDIGRIS DAEMON GYM LEADER:\n"
    .string "ERIKA\p"
    .string "WINNING USERS: {RIVAL}, {PLAYER}$"

