SSAnne_1F_Room2_Text_TylerIntro::
    .string "I love DAEMON! Do you?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "Wow! \n"
    .string "You're great!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "Listen, listen! Let me be your\n"
    .string "friend, okay?\p"
    .string "Then we can trade DAEMONS and do\n"
    .string "stuff.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "I collected these DAEMONS from all\n"
    .string "around the world!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "Oh, no!\n"
    .string "I went around the world for these!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "You hurt my poor DAEMON!\p"
    .string "I demand that you heal them at a\n"
    .string "DAEMON CENTER!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "We are cruising around the world,\n"
    .string "my children and I.$"

