IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo! Champ in the making!\p"
    .string "At the DAEMON LEAGUE, you will\n"
    .string "face the REVIEW BOARD all in a\l"
    .string "row.\p"
    .string "If you lose, you have to start all\n"
    .string "over again!\p"
    .string "This is it! Go for it!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "From here on, you face the ELITE\n"
    .string "FOUR one by one!\p"
    .string "If you win, a door opens to the\n"
    .string "next USER! Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "I am so sorry, but you've wasted\n"
    .string "your time coming here.\p"
    .string "PHLEGMATIC of the REVIEW BOARD is\n"
    .string "absent, you see.\p"
    .string "As a result, the DAEMON LEAGUE is\n"
    .string "closed for the time being.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
	.string "MELANCHOLIC's LATENT daemons\n"
	.string "don't look like much until they\l"
	.string "do.\p"
	.string "I went in confident. She let me.\p"
	.string "Then she beat me, and asked after\n"
	.string "my mother.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
	.string "SANGUINE lets his DAEMON pick\n"
	.string "their own ROUTINES sometimes.\p"
	.string "It loses him battles. He says it\n"
	.string "wins him surprises.$"

