IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo! Champ in the making!\p"
    .string "At the DAEMON LEAGUE, you will\n"
    .string "face the REVIEW BOARD all in a\l"
    .string "row.\p"
    .string "If you lose, you have to start all\n"
    .string "over again!\p"
    .string "This is it! Go for it!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "From here on, you face the ELITE\n"
    .string "FOUR one by one!\p"
    .string "If you win, a door opens to the\n"
    .string "next USER! Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "I am so sorry, but you've wasted\n"
    .string "your time coming here.\p"
    .string "PHLEGMATIC of the REVIEW BOARD is\n"
    .string "absent, you see.\p"
    .string "As a result, the DAEMON LEAGUE is\n"
    .string "closed for the time being.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "MELANCHOLIC's LATENT daemons are\n"
    .string "horrifically terrifying in toughness.\p"
    .string "I took my FIGHTING-type DAEMON\n"
    .string "and raised them to the max.\p"
    .string "I went at MELANCHOLIC feeling\n"
    .string "confident, but she whupped us.\p"
    .string "That old lady's also got a really\n"
    .string "short fuse, too.\p"
    .string "It doesn't take anything to get that\n"
    .string "scary lady hollering.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
	.string "Maybe becoming an REVIEW\n"
    .string "BOARD member is in the blood.\p"
    .string "From what I've heard, SANGUINE\n"
    .string "has a cousin who's a GYM\l"
    .string "LEADER somewhere far away.$"

