Text_MetronomeTeach::
    .string "Tch-tch-tch! I'll teach you a nifty\n"
    .string "move.\p"
    .string "Teach it to a DAEMON, and watch\n"
    .string "the fun unfold!\p"
    .string "It's a move called METRONOME. Does\n"
    .string "it strike your fancy?$"

Text_MetronomeDeclined::
    .string "I tell you, it's a lot of fun!$"

Text_MetronomeWhichMon::
    .string "Okay! Which DAEMON should I\n"
    .string "teach?$"

Text_MetronomeTaught::
    .string "Tch-tch-tch! That's the sound of a\n"
    .string "METRONOME.\p"
    .string "It tweaks your DAEMON's brain into\n"
    .string "using moves it doesn't even know.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "Hiya!\p"
    .string "I am important doctor. Yes, very\n"
    .string "much so, indeed.\p"
    .string "Here, I study rare DAEMON fossils.\n"
    .string "All the time, I study.\p"
    .string "You! Have you a fossil for me?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "No!\n"
    .string "Is too bad!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "You late.\n"
    .string "Where were you?\p"
    .string "Your fossil is back to life!\n"
    .string "It was {STR_VAR_1} like I think!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the doctor.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "Oh! That is {STR_VAR_2}, it is!\p"
    .string "It is fossil of {STR_VAR_1}, a DAEMON\n"
    .string "that is already extinct!\p"
    .string "My Resurrection Machine will make\n"
    .string "that DAEMONS live again!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "So!\n"
    .string "You hurry and give me that!\p"
    .string "{FONT_NORMAL}{PLAYER} handed over the\n"
    .string "{STR_VAR_2} to the weird doctor.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "I take a little time!\n"
    .string "You go for walk a little while!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "Aiyah!\n"
    .string "You come again!$"

