CinnabarIsland_Text_DoorIsLocked::
    .string "The door is locked…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "QUICKSILVER GYM's BLAINE is quite\n"
    .string "the odd fellow.\p"
    .string "He's lived on the island since way\n"
    .string "before the LAB was built.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Scientists conduct experiments in\n"
    .string "the burned-out building.\p"
    .string "You know, the one they call the\n"
    .string "DAEMON MANSION.$"

CinnabarIsland_Text_IslandSign::
    .string "QUICKSILVER ISLAND The Fiery Town\n"
    .string "of Burning Desire$"

CinnabarIsland_Text_PokemonLab::
    .string "DAEMON LAB$"

CinnabarIsland_Text_GymSign::
    .string "QUICKSILVER ISLAND DAEMON GYM\n"
    .string "LEADER: BLAINE The Hotheaded Quiz\l"
    .string "Master!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "Huh?\n"
    .string "Hey, if it isn't {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Look, it's me, HOLT. Long time no\n"
    .string "see!\p"
    .string "I hope you're still using my PC\n"
    .string "system.\p"
    .string "Well, listen, since we met up here,\n"
    .string "how about spending time with me?\p"
    .string "There's this little island in the far\n"
    .string "south called ONE ISLAND.\p"
    .string "A friend invited me, so I'm on my\n"
    .string "way out there.\p"
    .string "How about it? Do you feel like\n"
    .string "coming with me?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "All right, then.\n"
    .string "Let's go!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "What, are you too busy?\p"
    .string "Well, all right. The boat hasn't\n"
    .string "arrived yet anyway.\p"
    .string "I'll be waiting at the DAEMON\n"
    .string "CENTER over there.\p"
    .string "Come see me when you're done with\n"
    .string "your business here.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Looks like my pal's boat arrived,\n"
    .string "too.\p"
    .string "He sent it specially here to\n"
    .string "QUICKSILVER to pick me up.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Hey, wasn't that a long cruise?\p"
    .string "My buddy CELIO seemed to enjoy\n"
    .string "your company.\p"
    .string "I'm sure he'd welcome you if you\n"
    .string "were to visit him again.\p"
    .string "If you have a TRI-PASS, you can\n"
    .string "always take a ferry there from\l"
    .string "ARDOR PORT.\p"
    .string "All right, thanks for your company!$"

