CinnabarIsland_Text_DoorIsLocked::
    .string "The door is locked…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "QUICKSILVER GYM's BLAINE is an odd\n"
    .string "man who has lived here for\l"
    .string "decades.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "That burned out building still has\n"
    .string "its new sign.\p"
    .string "Gold leaf, dated. You can see the\n"
    .string "old name under it.$"

CinnabarIsland_Text_IslandSign::
    .string "QUICKSILVER\n"
    .string "The Metal That\l"
    .string "Will Not Set$"

CinnabarIsland_Text_PokemonLab::
    .string "SCORN SOLUTIONS\p"
    .string "Gold leaf, laid over something.\p"
    .string "Where it has lifted, the older\n"
    .string "letters show.\p"
    .string "CLEAR LABORATORY$"

CinnabarIsland_Text_GymSign::
    .string "QUICKSILVER\n"
    .string "DAEMON GYM\l"
    .string "LEADER: BLAINE\p"
    .string "The Hot-Headed\n"
    .string "Quiz Master!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "Huh?\n"
    .string "Hey, if it isn't {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Look, it's me, HOLT. Long time no\n"
    .string "see!\p"
    .string "I hope you're still using my PC\n"
    .string "system.\p"
    .string "Well, listen, since we met up here,\n"
    .string "how about spending time with me?\p"
    .string "There's this little island in the far\n"
    .string "south called ONE ISLAND.\p"
    .string "A friend invited me, so I'm on my\n"
    .string "way out there.\p"
    .string "How about it? Do you feel like\n"
    .string "coming with me?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "All right, then.\n"
    .string "Let's go!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "What, are you too busy?\p"
    .string "Well, all right. The boat hasn't\n"
    .string "arrived yet anyway.\p"
    .string "I'll be waiting at the DAEMON\n"
    .string "CENTER over there.\p"
    .string "Come see me when you're done with\n"
    .string "your business here.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Looks like my pal's boat arrived,\n"
    .string "too.\p"
    .string "He sent it specially here to\n"
    .string "QUICKSILVER to pick me up.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Hey, wasn't that a long cruise?\p"
    .string "My buddy CELIO seemed to enjoy\n"
    .string "your company.\p"
    .string "I'm sure he'd welcome you if you\n"
    .string "were to visit him again.\p"
    .string "If you have a TRI-PASS, you can\n"
    .string "always take a ferry there from\l"
    .string "ARDOR PORT.\p"
    .string "All right, thanks for your company!$"

