SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "CORPUS came and took over the\n"
    .string "building!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "Well, better get back to work.$"

SilphCo_6F_Text_HelpMePlease::
    .string "Oh dear, oh dear.\n"
    .string "Help me, please!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "We got engaged.\n"
    .string "Heheh!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "That man next to me…\n"
    .string "He's such a coward!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "He's so helpless, he needed\n"
    .string "someone like me to look after him.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "CORPUS wants every DAEMON on their\n"
    .string "books!$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "TEAM CORPUS ran because of you!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "They must have targeted SILPH for\n"
    .string "our DAEMON products.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "Come work for SILPH when you\n"
    .string "get older.$"

SilphCo_6F_Text_Grunt1Intro::
    .string "I'm one of four on this account!$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "Deprioritised.$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "No matter. My colleagues will\n"
    .string "follow up.$"

SilphCo_6F_Text_TaylorIntro::
    .string "That rotten PRESIDENT!\p"
    .string "Serves him right for shipping me\n"
    .string "off to the TIKSI BRANCH!\p"
    .string "That's why TEAM CORPUS came after\n"
    .string "us, I'm sure of it!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "Shoot!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "TIKSI BRANCH?\n"
    .string "It's in Russian no-man's-land!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "Are you aligned with CORPUS?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "Not aligned.$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "Standing for one thing means\n"
    .string "leaving another.\p"
    .string "That's synergy!$"

SilphCo_6F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "6F$"

