ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "Urrrrrrrrgggghhhh…\n"
    .string "Kwaaaaah!\p"
    .string "…It's useless! I can't make this\n"
    .string "spoon bend with my mind.\p"
    .string "Maybe I really don't have any\n"
    .string "psychic powers.$"

ThreeIsland_House2_Text_IAdmireSabrina::
	.string "Everybody over in BRAZEN says\n"
	.string "MATTE works for the company.\p"
	.string "Everybody over in BRAZEN works\n"
	.string "for the company.$"

