FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "You can't become a good USER with\n"
    .string "just one strong DAEMON.\p"
    .string "But raising many DAEMONS evenly is\n"
    .string "no easy task, either.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "There's a narrow trail west of\n"
    .string "CALLOW CITY.\p"
    .string "It goes to DAEMON LEAGUE HQ. The\n"
    .string "HQ governs all USERS.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "If you're working on a INDEX, visit\n"
    .string "the SAFARI ZONE.\p"
    .string "All sorts of rare DAEMON breed\n"
    .string "there.$"

