CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "That HOLT!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare DAEMON!$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Have you heard about HOLT?\p"
    .string "Everyone calls him an ARCHIVIST!\p"
    .string "I think people are just jealous of\n"
    .string "HOLT, though.\p"
    .string "Who wouldn't want to boast about\n"
    .string "their DAEMON?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "HOLT has lots of DAEMONS! He\n"
    .string "collects rare ones, too!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Why don't you go upstairs and try\n"
    .string "trading DAEMONS with your friends?\p"
    .string "You could get a lot more variety\n"
    .string "by trading.\p"
    .string "The DAEMON you get in trades grow\n"
    .string "quickly, too.$"

