SaffronCity_Text_WhatDoYouWantGetLost::
    .string "What do you want?\n"
    .string "Get lost!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "BOSS said he'll take this town in\n"
    .string "the name of TEAM CORPUS!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "Don't get defiant!\n"
    .string "Or I'll have to hurt you!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "BRAZEN belongs to TEAM CORPUS!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "My life as a criminal makes me feel\n"
    .string "so alive!$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "Ow!\n"
    .string "Watch where you're walking!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "With SILPH under control, we can\n"
    .string "exploit DAEMON around the world!\p"
    .string "We'll get stinking rich, yeahah!$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "You beat TEAM CORPUS all alone?\n"
    .string "That's amazing!$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "Yeah! TEAM CORPUS is gone! It's\n"
    .string "safe to go out again!$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "People should be flocking back to\n"
    .string "BRAZEN now.$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "I flew here on my BROADCAST when\n"
    .string "I read about SILPH.\p"
    .string "It's already over? I missed the\n"
    .string "media action.$"

SaffronCity_Text_Pidgeot::
    .string "BROADCAST: Bibii!$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "I saw CORPUS BOSS escaping SILPH's\n"
    .string "building.$"

SaffronCity_Text_ImASecurityGuard::
    .string "I'm a security guard.\p"
    .string "Suspicious kids I don't allow in!$"

SaffronCity_Text_HesTakingASnooze::
    .string "…\n"
    .string "Snore…\p"
    .string "Hah! He's taking a snooze!$"

SaffronCity_Text_CitySign::
    .string "BRAZEN CITY\n"
    .string "Shining, Golden\l"
    .string "Land of Commerce$"

SaffronCity_Text_FightingDojo::
    .string "FIGHTING DOJO$"

SaffronCity_Text_GymSign::
    .string "BRAZEN CITY\n"
    .string "DAEMON GYM\l"
    .string "LEADER: SABRINA\p"
    .string "The Master of\n"
    .string "Psychic DAEMON!$"

SaffronCity_Text_FullHealCuresStatus::
    .string "USER TIPS\p"
    .string "FULL HEAL cures all ailments like\n"
    .string "sleep and burns.\p"
    .string "It costs a bit more, but it's more\n"
    .string "convenient.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "USER TIPS\p"
    .string "New ADMINBOX offers improved\n"
    .string "capture rates.\p"
    .string "Try it on those hard-to-bind\n"
    .string "DAEMONS.$"

SaffronCity_Text_SilphCoSign::
    .string "SILPH CO. OFFICE BUILDING$"

SaffronCity_Text_MrPsychicsHouse::
    .string "MR. PSYCHIC'S HOUSE$"

SaffronCity_Text_SilphsLatestProduct::
    .string "CORPUS NOTICE REVIEW SCORES\p"
    .string "Three at 30/100. One at 94/100.\p"
    .string "Congratulations to our top\n"
    .string "performer!$"

SaffronCity_Text_TrainerFanClubSign::
    .string "DAEMON USER FAN CLUB\p"
    .string "Many USERS have scribbled their\n"
    .string "names on this sign.$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "This FAN CLUB…\n"
    .string "No one here has a clue!\p"
    .string "How could they not recognize\n"
    .string "the brilliance that is LANCE?\p"
    .string "He stands for justice!\n"
    .string "He's cool, and yet passionate!\l"
    .string "He's the greatest, LANCE!$"

