CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Only skilled USERS can collect\n"
    .string "DAEMONS MARKS.\p"
    .string "I see you have at least one.\p"
    .string "Those MARKS have amazing secrets,\n"
    .string "did you know?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Now then…\p"
    .string "Which of the eight MARKS should I\n"
    .string "describe?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Come visit me anytime you wish.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "The ATTACK stat of all your\n"
    .string "DAEMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "FLASH outside of battle.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "DAEMON up to Lv. 30 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "DAEMON of higher levels will be\n"
    .string "unruly in battle, however.\p"
    .string "It also lets you use the move CUT\n"
    .string "outside of battle.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "The SPEED stat of all your DAEMON\n"
    .string "increases a little bit.\p"
    .string "It also lets you use the move FLY\n"
    .string "outside of battle.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "DAEMON up to Lv. 50 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "DAEMON of higher levels will be\n"
    .string "unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "STRENGTH outside of battle.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "The DEFENSE stat of all your\n"
    .string "DAEMON increases a little bit.\p"
    .string "It also lets you use the move SURF\n"
    .string "outside of battle.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "DAEMON up to Lv. 70 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "DAEMON of higher levels will be\n"
    .string "unruly in battle, however.\p"
    .string "It also lets you use the move ROCK\n"
    .string "SMASH outside of battle.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "The SP. ATK and SP. DEF stats of\n"
    .string "all your DAEMON rise a little bit.\p"
    .string "It also lets you use the move\n"
    .string "WATERFALL outside of battle.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "All DAEMONS will obey you!$"

