ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "There's a DAEMON CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't be\n"
    .string "shy about healing DAEMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "DAEMON CENTERS heal your tired,\n"
    .string "hurt, or HALTED DAEMON.\p"
    .string "They make all DAEMONS completely\n"
    .string "healthy.$"

