Route3_Text_TunnelFromCeruleanTiring::
    .string "Whew... I better take a rest...\n"
    .string "Groan...\p"
    .string "That tunnel from DOLDRUM takes a\n"
    .string "lot out of you!$"

Route3_Text_ColtonIntro::
    .string "Hey! I met you in THE UNDERTONE!$"

Route3_Text_ColtonDefeat::
    .string "You beat me again!$"

Route3_Text_ColtonPostBattle::
    .string "There are other kinds of DAEMONS\n"
    .string "than those found in the forest!$"

Route3_Text_BenIntro::
    .string "Hi!\n"
    .string "I like shorts!\p"
    .string "They're delightfully comfy and\n"
    .string "easy to wear!$"

Route3_Text_BenDefeat::
    .string "I don't believe it!$"

Route3_Text_BenPostBattle::
    .string "Are you storing your DAEMON on PC?\n"
    .string "Each BOX can hold 20 DAEMONS!$"

Route3_Text_JaniceIntro::
    .string "Excuse me!\n"
    .string "You looked at me, didn't you?$"

Route3_Text_JaniceDefeat::
    .string "You're mean!$"

Route3_Text_JanicePostBattle::
    .string "You shouldn't be staring if you don't\n"
    .string "want to engage!$"

Route3_Text_GregIntro::
    .string "Are you a USER? Let's fight!$"

Route3_Text_GregDefeat::
    .string "If I had new DAEMON, I would've\n"
    .string "won!$"

Route3_Text_GregPostBattle::
    .string "If a DAEMON BOX on the PC gets\n"
    .string "full, just switch to another BOX.$"

Route3_Text_SallyIntro::
    .string "That look you gave me…\n"
    .string "It's so intriguing!$"

Route3_Text_SallyDefeat::
    .string "Be nice!$"

Route3_Text_SallyPostBattle::
    .string "You can avoid battles by not\n"
    .string "letting USERS see you.$"

Route3_Text_CalvinIntro::
    .string "Hey! You're not wearing shorts!\n"
    .string "What's wrong with you?$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "I always wear shorts, even in\n"
    .string "winter. That's my policy.$"

Route3_Text_JamesIntro::
    .string "I'll battle you with the DAEMON I\n"
    .string "just bound.$"

Route3_Text_JamesDefeat::
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle::
    .string "Trained DAEMONS are stronger than\n"
    .string "the wild ones!$"

Route3_Text_RobinIntro::
    .string "Eek!\n"
    .string "Did you touch me?$"

Route3_Text_RobinDefeat::
    .string "That's it?$"

Route3_Text_RobinPostBattle::
    .string "ROUTE 4 is at the foot of\n"
    .string "MT. MOON.$"

Route3_Text_RouteSign::
    .string "ROUTE 3\n"
    .string "MT.MOON AHEAD\p"
    .string "Painted beneath:\n"
    .string "ASHFALL$"

