SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
    .string "DAEMONS have personalities of their\n"
    .string "own, just like people.\p"
    .string "My SPIKE has a HASTY nature, so it\n"
    .string "grew to be a speedy DAEMON.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
    .string "Okay, preparations are complete\n"
    .string "for me to explore the RUINS.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
    .string "I need to fish on SEVEN ISLAND.\p"
    .string "That will complete my fishing tour\n"
    .string "of the SEVII ISLANDS.\p"
    .string "I'd better stock up on some POKé\n"
    .string "BOXES first, though.$"

