ViridianForest_Text_FriendsItchingToBattle::
    .string "I came here with some friends to\n"
    .string "bind us some BUG DAEMON!\p"
    .string "They're all itching to get into some\n"
    .string "DAEMONS battles!$"

ViridianForest_Text_RickIntro::
    .string "Hey! You have DAEMONS! Come on!\n"
    .string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat::
    .string "No! CRAWLER can't hack it!$"

ViridianForest_Text_RickPostBattle::
    .string "Ssh! You'll scare the bugs away.\n"
    .string "Another time, okay?$"

ViridianForest_Text_DougIntro::
    .string "Yo! You can't jam out if you're a\n"
    .string "DAEMON USER!$"

ViridianForest_Text_DougDefeat::
    .string "Huh? I ran out of DAEMON!$"

ViridianForest_Text_DougPostBattle::
    .string "That totally stinks! I'm going to\n"
    .string "bind some stronger ones!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, wait up!\n"
    .string "What's the hurry? Why the rush?$"

ViridianForest_Text_SammyDefeat::
    .string "I give!\n"
    .string "You're good at this!$"

ViridianForest_Text_SammyPostBattle::
    .string "Sometimes, you can find stuff on\n"
    .string "the ground.\p"
    .string "I'm looking for the stuff I\n"
    .string "dropped. Can you help me?$"

ViridianForest_Text_AnthonyIntro::
    .string "I might be little, but I won't like\n"
    .string "it if you go easy on me!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Oh, boo.\n"
    .string "Nothing went right.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "I lost some of my allowance…$"

ViridianForest_Text_CharlieIntro::
    .string "Did you know that DAEMONS evolve?$"

ViridianForest_Text_CharlieDefeat::
    .string "Oh!\n"
    .string "I lost!$"

ViridianForest_Text_CharliePostBattle::
    .string "BUG DAEMONS evolve quickly.\n"
    .string "They're a lot of fun!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "I was throwing POKé BALLS to bind\n"
    .string "DAEMONS, and I ran out.\p"
    .string "That's why you can never have too\n"
    .string "many POKé BALLS.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "USER TIPS\p"
    .string "If your DAEMONS are weak and you\n"
    .string "want to avoid battles, stay away\l"
    .string "from grassy areas!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "For poison, use ANTIDOTE! Get it\n"
    .string "at DAEMON MARTS!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "USER TIPS\p"
    .string "Contact CRYSTAL CLEAR via a PC to\n"
    .string "get your INDEX evaluated!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "USER TIPS\p"
    .string "You can't bind a DAEMON that\n"
    .string "belongs to someone else.\p"
    .string "Throw POKé BALLS only at wild\n"
    .string "DAEMON to bind them!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "USER TIPS\p"
    .string "Weaken DAEMON before attempting\n"
    .string "capture!\p"
    .string "When healthy, they may escape!$"

ViridianForest_Text_LeavingViridianForest::
    .string "LEAVING CALLOW FOREST SLATE CITY\n"
    .string "AHEAD$"

