MtMoon_B2F_Text_MiguelIntro::
    .string "Hey, stop!\p"
    .string "I found these fossils!\n"
    .string "They're both mine!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Okay!\n"
    .string "I'll share!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "We'll each take a fossil!\n"
    .string "No being greedy!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "All right.\n"
    .string "Then this fossil is mine!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Far away, on QUICKSILVER, there's\n"
    .string "a DAEMON LAB.\p"
    .string "They do research on regenerating\n"
    .string "fossils.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "We're monetising the fossil layer!\p"
    .string "Ground floor opportunity!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Noted. Escalating.$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "I've flagged you internally.\p"
    .string "CORPUS has a process for this.$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "CORPUS is a people-first\n"
    .string "organisation!\p"
    .string "The DAEMONS are inventory.$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "Missed target.$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "I'll be raising this at standup.$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "This site is under review!\p"
    .string "Please respect the cordon!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "Strong performance.$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "Any fossils you recover belong to\n"
    .string "CORPUS. Thanks!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "You are not on the access list!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "That's disappointing.$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "DAEMONS lived here long before we\n"
    .string "opened the site.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Do you want the DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Do you want the HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Obtained the HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Obtained the DOME FOSSIL!$"

