SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "PRESIDENT: Oh, dear friend!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "PRESIDENT: Oh, dear friend!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} obtained a ROOTBOX from\n"
    .string "the PRESIDENT!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENT: You can't buy that\n"
    .string "anywhere!\p"
    .string "It's our secret prototype ROOTBOX!\p"
    .string "It will bind any DAEMON without\n"
    .string "fail!\p"
    .string "You should be quiet about using it,\n"
    .string "though.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "You have no room for this.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SECRETARY: Thank you for rescuing\n"
    .string "all of us.\p"
    .string "We, from the PRESIDENT down,\n"
    .string "are indebted to you.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "Ah, {PLAYER}!\n"
    .string "So we meet again!\p"
    .string "The PRESIDENT and I are discussing\n"
    .string "a vital business proposition.\p"
    .string "Keep your nose out of grown-up\n"
    .string "matters…\p"
    .string "Or, experience a world of pain!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "Arrgh!!\n"
    .string "I lost again!?$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "Blast it all! You ruined our plans\n"
    .string "for SILPH!\p"
    .string "But, TEAM CORPUS will never fall!\p"
    .string "{PLAYER}! Never forget that all\n"
    .string "DAEMONS exist for TEAM CORPUS!\p"
    .string "I must go, but I shall return!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Please wait here. Someone will be\n"
    .string "with you shortly.$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Don't…\n"
    .string "Please!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "You'd like to see the BOSS.$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Do you have an appointment with\n"
    .string "the BOSS?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Off the roadmap.$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Mind how you go. The BOSS sets a\n"
    .string "high bar.$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "The monitor has DAEMON on it!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "11F$"

