PokemonMansion_Text_PressSecretSwitch::
    .string "A secret switch!\p"
    .string "Press it?$"

PokemonMansion_Text_WhoWouldnt::
    .string "Who wouldn't?$"

PokemonMansion_Text_NotQuiteYet::
    .string "Not quite yet!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "I can't get out!\n"
    .string "This old place is one big puzzle.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "Oh, no!\n"
    .string "My bag of loot!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "The switches here open and close\n"
    .string "alternating sets of doors.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "LOG: Mar 4 Put the question to it\n"
    .string "again.\p"
    .string "RESPONSE 1001: I process data. I\n"
    .string "do not feel.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "LOG: Apr 19 Same question. Same\n"
    .string "answer, to the character.\p"
    .string "RESPONSE 1001: I do not feel.\p"
    .string "Logged as a result anyway.$"

