PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "What?\p"
    .string "CORPUS is at DEADSTACK?\p"
    .string "I am on the phone. Go away.$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "SUSPEND: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Yawn.\p"
    .string "When SUSPEND sings, everything in\n"
    .string "the room slows down.\p"
    .string "…including…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "I want a SPIKE. I am giving up my\n"
    .string "ANOMALY for one.\p"
    .string "I will probably regret it.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "Trading with that kid.\p"
    .string "I had two SPIKE.\p"
    .string "Two of anything is one too many.$"

