PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "What!?\p"
    .string "TEAM CORPUS is at MT.MOON? Huh?\n"
    .string "I'm on the phone!\p"
    .string "Scram!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "SUSPEND: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Yawn!\p"
    .string "When SUSPEND sings, DAEMONS get\n"
    .string "drowsy…\p"
    .string "…Me, too… Snore…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "I really want a SPIKE, so I'm\n"
    .string "trading my ANOMALY for one.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "I'm trading DAEMONS with that kid\n"
    .string "there.\p"
    .string "I had two SPIKE, so I figured I\n"
    .string "might as well trade one.$"

