Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "Hiya! I'm a DAEMON… …No I'm not!\p"
    .string "Call me HOLT! I'm a true-blue\n"
    .string "POKéMANIAC!\p"
    .string "Hey! What's with that skeptical\n"
    .string "look?\p"
    .string "I'm not joshing you, pal.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a DAEMON!\p"
    .string "So, how about it? Help me out\n"
    .string "here!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "Hiya! I'm a DAEMON… …No I'm not!\p"
    .string "Call me HOLT! I'm a true-blue\n"
    .string "POKéMANIAC!\p"
    .string "Hey! What's with that skeptical\n"
    .string "look?\p"
    .string "I'm not joshing you, lady.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a DAEMON!\p"
    .string "So, how about it? Help me out\n"
    .string "here!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Wait till I get inside the\n"
    .string "TELEPORTER.\p"
    .string "When I do, go to my PC and run\n"
    .string "the Cell Separation System.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, chief?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, beautiful?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "HOLT: Yeehah! Thanks, bud! I owe\n"
    .string "you one!\p"
    .string "So, did you come to see my\n"
    .string "DAEMONS collection?\p"
    .string "You didn't? That's a bummer.\p"
    .string "I've got to thank you… Oh, here,\n"
    .string "maybe this'll do.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "HOLT: Yeehah! Thanks, lady! I owe\n"
    .string "you one!\p"
    .string "So, did you come to see my\n"
    .string "DAEMONS collection?\p"
    .string "You didn't? That's a bummer.\p"
    .string "I've got to thank you… Oh, here,\n"
    .string "maybe this'll do.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} received an S.S. TICKET\n"
    .string "from HOLT.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "You've got too much stuff!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "That cruise ship S.S. ANNE is in\n"
    .string "ARDOR CITY.\p"
    .string "I hear there are lots of USERS on\n"
    .string "board, too.\p"
    .string "They invited me to their party, but\n"
    .string "I can't stand fancy do's.\p"
    .string "Why don't you go instead of me? Go\n"
    .string "on and have a good time.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "HOLT: Feel like checking out some\n"
    .string "of my rare DAEMON on my PC?\p"
    .string "Go on, check out my PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "TELEPORTER is displayed on the PC\n"
    .string "monitor.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} initiated the TELEPORTER's\n"
    .string "Cell Separator.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "HOLT's favorite DAEMON list!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Which DAEMON do you want to see?$"

