@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "My DAEMONS's ashes are stored in\n"
    .string "DAEMON TOWER.\p"
    .string "You can have this TM. I don't need\n"
    .string "it any more...$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "My DAEMONS's ashes are stored in\n"
    .string "DAEMON TOWER.\p"
    .string "You can have this TM. I don't need\n"
    .string "it anymore…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "{PLAYER} received TM27\n"
    .string "from the little girl.$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .string "TM27 is a move called RETURN…\p"
    .string "If you treat your DAEMON good, it\n"
    .string "will return your love by working\l"
    .string "its hardest in battle.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "You don't have room for this.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a man fishing!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's DAEMON TOWER!$"

