@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "My DAEMONS's ashes are stored in\n"
    .string "DAEMON TOWER.\p"
    .string "You can have this PATCH. I don't\n"
    .string "need it any more...$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "My DAEMONS's ashes are stored in\n"
    .string "DAEMON TOWER.\p"
    .string "You can have this PATCH. I don't\n"
    .string "need it anymore…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "{PLAYER} received PATCH27 from the\n"
    .string "little girl.$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .string "PATCH27 is a ROUTINE called\n"
    .string "RAPPORT…\p"
    .string "If you treat your DAEMON good, it\n"
    .string "will return your love by working\l"
    .string "its hardest in battle.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "You don't have room for this.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a man fishing!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's DAEMON TOWER!$"

