PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: Hey, {PLAYER}! What brings\n"
    .string "you here? Is your DAEMON dead?\p"
    .string "Hey! It's alive!\p"
    .string "I can at least make them HALT!\n"
    .string "Let's go!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "What?\n"
    .string "You stinker!\p"
    .string "I took it easy on you, too!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "How's your INDEX coming, pal? I\n"
    .string "just bound a CUBONE!\p"
    .string "I can't find the grown-up MAROWAK\n"
    .string "yet!\p"
    .string "I doubt there are any left! Well,\n"
    .string "I better get going! I've got a lot\l"
    .string "to accomplish, pal!\p"
    .string "Smell ya later!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Even we could not identify the\n"
    .string "wayward GHOSTs!\p"
    .string "A RESOLVER might be able to unmask\n"
    .string "them.$"

