CeruleanCity_Gym_Text_MistyIntro::
    .string "Hi, you're a new face!\p"
    .string "USERS who want to turn pro have to\n"
    .string "have a policy about DAEMON!\p"
    .string "What is your approach when you\n"
    .string "bind DAEMONS?\p"
    .string "My policy is an all-out offensive\n"
    .string "with water-type DAEMON!$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 teaches WATER PULSE.\p"
    .string "Use it on an aquatic DAEMON!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "The SLOPE MARK makes all DAEMONS\n"
    .string "up to L30 obey!\p"
    .string "That includes even outsiders!\p"
    .string "There's more, you can now use CUT\n"
    .string "any time!\p"
    .string "You can CUT down small bushes to\n"
    .string "open new paths!\p"
    .string "You can also have my favorite TM!$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} received TM03\n"
    .string "from MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "You better make room for this!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Wow! You're too much!\p"
    .string "All right!\p"
    .string "You can have the SLOPE MARK to\n"
    .string "show you beat me!$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "What? You?\n"
    .string "I'm more than good enough for you!\p"
    .string "MISTY won't have to be bothered.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "You overwhelmed me!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "You have to face other USERS to\n"
    .string "find out how good you really are.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Splash!\p"
    .string "I'm first up!\n"
    .string "Let's do it!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "That can't be!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY is a USER who's going to keep\n"
    .string "improving.\p"
    .string "She won't lose to someone like you!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Yo! Champ in the making!\p"
    .string "Let me give you some advice!\p"
    .string "The LEADER, MISTY, is a pro who\n"
    .string "uses WATER-type DAEMON.\p"
    .string "You can drain all their water with\n"
    .string "GRASS-type DAEMON.\p"
    .string "Or, you might use ELECTRIC-type\n"
    .string "DAEMON and zap them!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "You beat MISTY!\n"
    .string "See, what'd I tell ya?\p"
    .string "You and me, kid, we make a pretty\n"
    .string "darn-good team!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "DOLDRUM DAEMON GYM LEADER: MISTY\p"
    .string "WINNING USERS: {RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "DOLDRUM DAEMON GYM LEADER: MISTY\p"
    .string "WINNING USERS: {RIVAL}, {PLAYER}$"

