FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Uh… Oh, yes, I'm the MOVE DELETER.\p"
    .string "I can make DAEMON forget their\n"
    .string "ROUTINES.\p"
    .string "Would you like me to do that?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "Which DAEMON should forget a\n"
    .string "ROUTINE?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "Which ROUTINE should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} seems to know only one\n"
    .string "ROUTINE…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That ROUTINE should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Come again if there are other\n"
    .string "ROUTINES to be forgotten.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "What?\n"
    .string "No EGG should know any ROUTINES.$"

