Text_DreamEaterTeach::
    .string "Yawn! I must have dozed off in the\n"
    .string "sun.\p"
    .string "I had this weird dream about a\n"
    .string "DROWZEE eating my dream.\p"
    .string "And… I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a DAEMON so I\n"
    .string "can forget about it!$"

Text_DreamEaterDeclined::
    .string "…Snore…$"

Text_DreamEaterWhichMon::
    .string "Which DAEMON wants to learn DREAM\n"
    .string "EATER?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "Morning, it happened. Six people\n"
    .string "signed in.\p"
    .string "Coolant failure, I was told.\p"
    .string "Purple thing. All flat faces, like\n"
    .string "cut glass.\p"
    .string "West side of the building.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "There aren't many serious DAEMON\n"
    .string "USERS here!\p"
    .string "They're all like BUG CATCHERs, but\n"
    .string "SLATE GYM's CAIRN is totally into\l"
    .string "it!$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Did you check out the MUSEUM?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Weren't those fossils from MT. MOON\n"
    .string "amazing?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Really?\n"
    .string "You absolutely have to go!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "This is it, the MUSEUM.\p"
    .string "You have to pay to get in, but it's\n"
    .string "worth it. See you around!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "That's right!\n"
    .string "It's hard work!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "I'm spraying REPEL to keep wild\n"
    .string "DAEMON out of my garden!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "You're a USER right? CAIRN's looking\n"
    .string "for new challengers! Follow me!$"

PewterCity_Text_GoTakeOnBrock::
    .string "If you have the right stuff, go\n"
    .string "take on CAIRN!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "USER TIPS\p"
    .string "Any DAEMON that takes part in\n"
    .string "battle, however short, earns EXP!$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "NOTICE!\p"
    .string "Thieves have been\n"
    .string "stealing DAEMON\l"
    .string "fossils at MT.\l"
    .string "MOON! Please call\l"
    .string "SLATE POLICE\l"
    .string "with any info!$"

PewterCity_Text_MuseumOfScience::
    .string "SLATE MUSEUM\n"
    .string "OF SCIENCE$"

PewterCity_Text_GymSign::
    .string "SLATE CITY DAEMON GYM LEADER:\n"
    .string "CAIRN\p"
    .string "The Rock Solid DAEMON USER!$"

PewterCity_Text_CitySign::
    .string "SLATE CITY\n"
    .string "A Stone Gray\l"
    .string "City$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "I'm glad I bound up to you. I'm\n"
    .string "CRYSTAL CLEAR's AIDE.\p"
    .string "I've been asked to deliver this, so\n"
    .string "here you go.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} received the\n"
    .string "RUNNING SHOES from the AIDE.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} switched shoes with the\n"
    .string "RUNNING SHOES.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Press the B Button to run.\n"
    .string "But only where there's room to run!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Well, I must be going back to\n"
    .string "the LAB.\p"
    .string "Bye-bye!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "There's a letter attached…\p"
    .string "Dear {PLAYER},\p"
    .string "Here is a pair of RUNNING SHOES\n"
    .string "for my beloved challenger.\p"
    .string "Remember, I'll always cheer for\n"
    .string "you! Don't ever give up!\p"
    .string "From Mom$"

