Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "Hi! Remember me? I'm one of\n"
    .string "CRYSTAL CLEAR's AIDES.\p"
    .string "If your INDEX has complete data\n"
    .string "on {STR_VAR_1} species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "CRYSTAL CLEAR entrusted me with\n"
    .string "the {STR_VAR_2} for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "{STR_VAR_1} kinds of DAEMONS?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "Great! You have bound or owned\n"
    .string "{STR_VAR_3} kinds of DAEMONS!\p"
    .string "Congratulations! Here you go!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "{PLAYER} received the {STR_VAR_2}\n"
    .string "from the AIDE.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "EXP. SHARE is an item to be held\n"
    .string "by a DAEMON.\p"
    .string "The DAEMON will receive a share of\n"
    .string "the EXP. Points without having to\l"
    .string "battle.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "A large, shining bird is flying\n"
    .string "toward the sea.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It looks like a small island on\n"
    .string "the horizon!$"

