SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "You look tired.\n"
    .string "You should take a quick nap.$"

SilphCo_9F_Text_DontGiveUp::
    .string "Don't give up!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Thank you so much.$"

SilphCo_9F_Text_Grunt1Intro::
    .string "Your DAEMONS seem engaged.\p"
    .string "Ours are resources.$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "Logged.$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "If I had started as a USER at your\n"
    .string "age...$"

SilphCo_9F_Text_EdIntro::
    .string "Your DAEMONS have weak points! I\n"
    .string "can nail them!$"

SilphCo_9F_Text_EdDefeat::
    .string "You hammered me!$"

SilphCo_9F_Text_EdPostBattle::
    .string "Exploiting weak spots does work.\n"
    .string "Think about type advantages.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "Last of four on this account!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "That's the account, then.$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "Someone will pick this up.$"

SilphCo_9F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "9F$"

