ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "We're the GAMUT RIDER FEDERATION!\n"
    .string "Vroom! Vavavavooom! Vroom!\p"
    .string "My bike's wimpy, so I have to\n"
    .string "make exhaust noises myself!$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "Hey, hey, lady!\n"
    .string "Fork over some spending money!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "Aiyeeh!\p"
    .string "Wh-who are you?!\n"
    .string "I… I'll call the police!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "Those COURIER… Are they gone?\p"
    .string "Oh, thank goodness! They certainly\n"
    .string "had me terrified!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "Those COURIER ran off, and\n"
    .string "LOSTELLE was found safe.\p"
    .string "Everything turned out for the best!$"

