PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Yo {PLAYER}! Gran isn't\n"
    .string "around!$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Gran! I'm fed up with\n"
    .string "waiting!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Hey! Gran! What about\n"
    .string "me?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Heh, I don't need to be\n"
    .string "greedy like you. I'm mature!\p"
    .string "Go ahead and choose, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: I'll take this one, then!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} received the {STR_VAR_1} from\n"
    .string "CRYSTAL CLEAR!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: My DAEMONS looks a lot\n"
    .string "tougher than yours.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Wait, {PLAYER}! Let's check\n"
    .string "out our DAEMON!\p"
    .string "Come on, I'll take you on!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "WHAT? Unbelievable! I picked the\n"
    .string "wrong DAEMON!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: Yeah!\n"
    .string "Am I great or what?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: Okay! I'll make my\n"
    .string "DAEMONS fight to toughen it up!\p"
    .string "{PLAYER}! Gran! Smell you later!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Gran!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: I almost forgot!\n"
    .string "What did you call me for?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: All right, Gran! Leave it\n"
    .string "all to me!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{RIVAL}: Alright Gran! Leave it\n"
    .string "all to me!\p"
    .string "{PLAYER}, I hate to say it, but I\n"
    .string "don't need you!\p"
    .string "I know! I'll borrow a TOWN MAP from\n"
    .string "my sis!\p"
    .string "I'll tell her not to lend you one,\n"
    .string "{PLAYER}! Hahaha!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "CRYSTAL: {RIVAL}? Let me think...\p"
    .string "Oh, that's right, I told you to\n"
    .string "come! Just wait!\p"
    .string "Here, {PLAYER}!\p"
    .string "There are 3 DAEMONS here!\p"
    .string "Haha!\p"
    .string "They are running on the BOXes.\p"
    .string "When I was young, I was a serious\n"
    .string "DAEMON USER!\p"
    .string "In my old age, I have only 3 left,\n"
    .string "but you can have one! Choose!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "CRYSTAL: Be patient! {RIVAL}, you\n"
    .string "can have one too!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "CRYSTAL: Now, {PLAYER}.\p"
    .string "Inside those three POKé BOXES are\n"
    .string "DAEMON.\p"
    .string "Which one will you choose for\n"
    .string "yourself?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "CRYSTAL: Hey! Don't go away yet!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Ah! LABL is your choice. You\n"
    .string "should raise it patiently.\p"
    .string "So, {PLAYER}, you're claiming the\n"
    .string "FIRE DAEMON LABL?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Hm! CLUSTR is your choice. It's one\n"
    .string "worth raising.\p"
    .string "So, {PLAYER}, you've decided on the\n"
    .string "WATER DAEMON CLUSTR?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "I see! ROVERCUB is your choice.\n"
    .string "It's very easy to raise.\p"
    .string "So, {PLAYER}, you want to go with\n"
    .string "the GRASS DAEMON ROVERCUB?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "This DAEMON is really quite\n"
    .string "energetic!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} received the {STR_VAR_1} from\n"
    .string "CRYSTAL CLEAR!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "CRYSTAL: If a wild DAEMON appears,\n"
    .string "your DAEMON can battle it.\p"
    .string "With it at your side, you should be\n"
    .string "able to reach the next town.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "CRYSTAL: {PLAYER}, raise your young\n"
    .string "DAEMON by making it fight!$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "CRYSTAL: Oh, {PLAYER}!\p"
    .string "How is my old DAEMON?\p"
    .string "Well, it seems to like you a lot.\p"
    .string "You must be talented as a DAEMON\n"
    .string "USER!\p"
    .string "What? You have something for me?\p"
    .string "{PLAYER} delivered the CC-7.$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} delivered the COGNITIVE\n"
    .string "CLARIFIER.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah. The module. Thank you.$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "CRYSTAL: Oh right! I have a\n"
    .string "request of you two.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "On the desk there is my invention,\n"
    .string "INDEX!\p"
    .string "It automatically records data on\n"
    .string "DAEMON you've seen or bound!\p"
    .string "It's a hi-tech encyclopedia!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "CRYSTAL: {PLAYER} and {RIVAL}!\n"
    .string "Take these with you!\p"
    .string "{PLAYER} got INDEX from CRYSTAL!$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} received the INDEX from\n"
    .string "CRYSTAL CLEAR.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "CRYSTAL: You can't get detailed\n"
    .string "data on DAEMON by just seeing\l"
    .string "them.\p"
    .string "You must bind them! Use these to\n"
    .string "capture wild DAEMON.\p"
    .string "{PLAYER} got 5 USERBOXes!$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} received five POKé BOXES.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "When a wild DAEMON appears, it's\n"
    .string "fair game.\p"
    .string "Just throw a USERBOX at it and try\n"
    .string "to bind it!\p"
    .string "This won't always work, though.\p"
    .string "A healthy DAEMON could escape.\n"
    .string "You have to be lucky!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "To make a complete guide on all\n"
    .string "the DAEMON in the world…\p"
    .string "That was my dream!\p"
    .string "But, I'm too old. I can't get the\n"
    .string "job done.\p"
    .string "So, I want you two to fulfill my\n"
    .string "dream for me.\p"
    .string "Get moving, you two.\p"
    .string "This is a great undertaking in\n"
    .string "DAEMON history!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "DAEMON around the world wait for\n"
    .string "you, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}! How is your INDEX\n"
    .string "shaping up?\p"
    .string "{RIVAL} has already bound some\n"
    .string "DAEMONS and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your INDEX.\p"
    .string "…What's the matter? You've added no\n"
    .string "new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "CRYSTAL: Come see me sometimes.\p"
    .string "I want to know how your INDEX is\n"
    .string "coming along.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "It's like an encyclopedia, but the\n"
    .string "pages are blank.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Those are BOXes. DAEMONS run on\n"
    .string "them.$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "That's CRYSTAL's last DAEMON!$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Press START to open the MENU!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "The SAVE option is on the MENU.\n"
    .string "Use it regularly.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "All DAEMONS types have strong and\n"
    .string "weak points against others.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "There's an e-mail message here.\p"
    .string "…\p"
    .string "Finally! The ultimate USERS of the\n"
    .string "DAEMON LEAGUE are ready to take\l"
    .string "on all comers!\p"
    .string "Bring your best DAEMONS and see\n"
    .string "how you rate as a USER!\p"
    .string "DAEMON LEAGUE HQ UMBRA PLATEAU\p"
    .string "CRYSTAL CLEAR, please visit us! …$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "I study DAEMON as CRYSTAL's AIDE.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your DAEMON.\p"
    .string "By the way, did you know about\n"
    .string "DAISY?\p"
    .string "If you show DAISY your DAEMON,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom a\n"
    .string "DAEMON for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "CRYSTAL CLEAR is going to have her\n"
    .string "own radio show soon.\p"
    .string "The program will be called CRYSTAL\n"
    .string "CLEAR's DAEMON SEMINAR.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "CRYSTAL CLEAR is the authority on\n"
    .string "DAEMON!\p"
    .string "Many DAEMONS USERS hold her in\n"
    .string "high regard!$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Recently, there have been sightings\n"
    .string "of many rare DAEMON species.\p"
    .string "I'm talking about DAEMON that have\n"
    .string "never been seen in KANTO.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, I heard that!\p"
    .string "Gran, what's with favoring {PLAYER}\n"
    .string "over me all the time?\p"
    .string "I went and collected more DAEMONS,\n"
    .string "and faster, too.\p"
    .string "You should just let me handle\n"
    .string "everything.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "CRYSTAL: I know, I know. Of course\n"
    .string "I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "INDEXES.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "CRYSTAL CLEAR took both INDEX\n"
    .string "units.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … … … … …\p"
    .string "… … … … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more DAEMONS.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}'s INDEX was upgraded!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your INDEXES.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in DAEMON history!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Gran, calm down. Don't get\n"
    .string "so excited.\p"
    .string "I'll get the INDEX completed, don't\n"
    .string "you worry about a thing.\p"
    .string "I think I'll try looking around ONE\n"
    .string "ISLAND first…\p"
    .string "Anyways, I'm outta here!$"

