FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "Somebody from this island sits\n"
    .string "on the REVIEW BOARD now.\p"
    .string "You would know the name.\n"
    .string "I knew the child.\p"
    .string "When PHLEGMATIC was just a\n"
    .string "tyke, I taught her about DAEMON.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "THE MARGINS are warm,\n"
    .string "people say, and they are.\p"
    .string "All but one room of them.\p"
    .string "STILLFALL CAVE is frigid because\n"
    .string "of the DAEMON that live in it.$"

