FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "We've had a great and powerful\n"
    .string "USER grow up on this island.\p"
    .string "I bet even you'd know her. It's\n"
    .string "LORELEI of the ELITE FOUR!\p"
    .string "When LORELEI was just a tyke, I\n"
    .string "taught her about DAEMON.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "The SEVII ISLANDS are in a warm\n"
    .string "region overall.\p"
    .string "But there is one exception you\n"
    .string "need to know about.\p"
    .string "The ICEFALL CAVE is frigid because\n"
    .string "of the DAEMON that live in it.$"

