FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
	.string "We've had a great and powerful\n"
    .string "USER grow up on this island.\p"
    .string "I bet even you'd know her. It's\n"
    .string "PHLEGMATIC of the REVIEW BOARD!\p"
    .string "When PHLEGMATIC was just a\n"
    .string "tyke, I taught her about DAEMON.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "The SEVII ISLANDS are in a warm\n"
    .string "region overall.\p"
    .string "But there is one exception you\n"
    .string "need to know about.\p"
    .string "STILLFALL CAVE is frigid because\n"
    .string "of the DAEMON that live in it.$"

