@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "Don't you think it's hard to think up\n"
    .string "good names for DAEMON?\p"
    .string "Especially if you've bound a whole\n"
    .string "bunch?\p"
    .string "In HALFTONE TOWN, there's a man\n"
    .string "who rates DAEMON nicknames.\p"
    .string "He can even help you rename your\n"
    .string "DAEMON, too.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "If you're aiming to reach HALFTONE\n"
    .string "TOWN, take ROCK TUNNEL.\p"
    .string "You can get to ROCK TUNNEL from\n"
    .string "DOLDRUM CITY.$"

