@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "When you bind lots of DAEMONS, isn't\n"
    .string "it hard to think up names?\p"
    .string "In HALFTONE TOWN, there's a man\n"
    .string "who rates DAEMON nicknames.\p"
    .string "He'll help you rename them too!$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "If you're aiming to reach HALFTONE\n"
    .string "TOWN, take ROCK TUNNEL.\p"
    .string "You can get to ROCK TUNNEL from\n"
    .string "DOLDRUM CITY.$"

