CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "REPEL not only keeps bugs away, it\n"
    .string "also works on weak DAEMON.\p"
    .string "Put your strongest DAEMON at the\n"
    .string "left of the DAEMON LIST.\p"
    .string "If your first DAEMON is strong,\n"
    .string "REPEL's effect is boosted.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Do you know about RARE CANDY?\n"
    .string "They don't sell it in shops.\p"
    .string "I think it makes DAEMONS grow very\n"
    .string "quickly all of a sudden.$"

