CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "SUPPRESS not only keeps bugs away,\n"
    .string "it also works on weak DAEMON.\p"
    .string "Put your strongest DAEMON at the\n"
    .string "left of the DAEMON LIST.\p"
    .string "If your first DAEMON is strong,\n"
    .string "SUPPRESS's effect is boosted.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Do you know about INCREMENT? They\n"
    .string "don't sell it in shops.\p"
    .string "I think it makes DAEMONS grow very\n"
    .string "quickly all of a sudden.$"

