Route11_Text_HugoIntro::
    .string "Win, lose, or draw!$"

Route11_Text_HugoDefeat::
    .string "Atcha!\n"
    .string "Didn't go my way!$"

Route11_Text_HugoPostBattle::
    .string "DAEMON is life! And to live is to\n"
    .string "play games!$"

Route11_Text_JasperIntro::
    .string "Competition!\n"
    .string "I can't get enough!$"

Route11_Text_JasperDefeat::
    .string "I had a chance!$"

Route11_Text_JasperPostBattle::
    .string "You can't be a coward in the world\n"
    .string "of DAEMON!$"

Route11_Text_EddieIntro::
    .string "Let's go, but don't cheat!$"

Route11_Text_EddieDefeat::
    .string "Huh?\n"
    .string "That's not right!$"

Route11_Text_EddiePostBattle::
    .string "I did my best.\n"
    .string "I have no regrets.$"

Route11_Text_BraxtonIntro::
    .string "Careful!\n"
    .string "I'm laying down some cables!$"

Route11_Text_BraxtonDefeat::
    .string "That was electric!$"

Route11_Text_BraxtonPostBattle::
    .string "Spread the word to save energy!$"

Route11_Text_DillonIntro::
    .string "I just became a USER. But, I think\n"
    .string "I can win.$"

Route11_Text_DillonDefeat::
    .string "My DAEMONS couldn't win… Haven't\n"
    .string "they grown enough?$"

Route11_Text_DillonPostBattle::
    .string "What now?\n"
    .string "Leave me alone!$"

Route11_Text_DirkIntro::
    .string "Fwahaha!\n"
    .string "I have never lost!$"

Route11_Text_DirkDefeat::
    .string "My first loss!$"

Route11_Text_DirkPostBattle::
    .string "You were just lucky, that's all.$"

Route11_Text_DarianIntro::
    .string "I have never won before…$"

Route11_Text_DarianDefeat::
    .string "I saw this coming…$"

Route11_Text_DarianPostBattle::
    .string "I was unlucky, as always.$"

Route11_Text_YasuIntro::
    .string "I'm the best in my class.\n"
    .string "I train every morning.$"

Route11_Text_YasuDefeat::
    .string "Darn! My DAEMONS need to be\n"
    .string "stronger!$"

Route11_Text_YasuPostBattle::
    .string "There's a fat DAEMON that comes\n"
    .string "down from the mountains.\p"
    .string "I bet it'd be strong if you can bind\n"
    .string "it.$"

Route11_Text_BernieIntro::
    .string "Watch out for live wires!$"

Route11_Text_BernieDefeat::
    .string "Whoa!\n"
    .string "You spark plug!$"

Route11_Text_BerniePostBattle::
    .string "Well, better get back to work.$"

Route11_Text_DaveIntro::
    .string "I raised my DAEMONS carefully.\n"
    .string "They should be ready by now!$"

Route11_Text_DaveDefeat::
    .string "Bye-bye!\n"
    .string "Thank you, and good-bye!$"

Route11_Text_DavePostBattle::
    .string "Tch…\n"
    .string "I better go find stronger ones!$"

Route11_Text_DiglettsCave::
    .string "DIGLETT'S CAVE$"

