ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Whew! I'm trying to memorize all my\n"
    .string "notes.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Be sure to read what's on the\n"
    .string "blackboard carefully!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "POKé BALLS are used to bind\n"
    .string "DAEMONS.\p"
    .string "Up to six DAEMONS can be carried\n"
    .string "in your party.\p"
    .string "People who raise and battle with\n"
    .string "DAEMONS are called USERS.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Second page…\p"
    .string "A healthy DAEMON may be hard to\n"
    .string "bind, so weaken it first.\p"
    .string "Poison, burn, or cause another\n"
    .string "status problem to weaken it.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Third page…\p"
    .string "DAEMON USERS seek others to\n"
    .string "engage in DAEMON battles.\p"
    .string "To USERS, the taste of victory is\n"
    .string "sweet, indeed.\p"
    .string "Battles are constantly waged at\n"
    .string "DAEMON GYMS everywhere.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fourth page…\p"
    .string "The ultimate goal for all DAEMONS\n"
    .string "USERS is simple.\p"
    .string "It is to defeat the top eight\n"
    .string "DAEMONS GYM LEADERS.\p"
    .string "Do so to earn the right to face…\p"
    .string "The ELITE FOUR of the DAEMON\n"
    .string "LEAGUE!$"

ViridianCity_School_Text_TurnThePage::
    .string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "GIRL: Hey!\n"
    .string "Don't look at my notes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "The blackboard lists DAEMON STATUS\n"
    .string "problems during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Which topic do you want to read?$"

ViridianCity_School_Text_ExplainSleep::
    .string "A DAEMON can't attack if it's asleep.\p"
    .string "DAEMON will stay asleep even after\n"
    .string "battles.\p"
    .string "Use AWAKENING to awaken one from\n"
    .string "sleep.$"

ViridianCity_School_Text_ExplainBurn::
    .string "A burn reduces ATTACK power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use BURN HEAL to cure a burn.$"

ViridianCity_School_Text_ExplainPoison::
    .string "When poisoned, a DAEMON's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles. Use an\n"
    .string "ANTIDOTE to cure poison!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "A frozen DAEMON becomes helplessly\n"
    .string "immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use ICE HEAL to thaw out the\n"
    .string "suffering DAEMON.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Paralysis reduces SPEED and may\n"
    .string "prevent the DAEMON from moving.\p"
    .string "Paralysis remains after battles. Use\n"
    .string "PARLYZ HEAL for treatment.$"

