Route10_Text_MarkIntro::
    .string "Wow, are you an ARCHIVIST too?\n"
    .string "Want to see my collection?$"

Route10_Text_MarkDefeat::
    .string "Humph.\n"
    .string "I'm not angry!$"

Route10_Text_MarkPostBattle::
    .string "I have more rare DAEMON at home!$"

Route10_Text_ClarkIntro::
    .string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-haha!\n"
    .string "Not laughing!\l"
    .string "Ha-hay fever! Haha-ha-choo!$"

Route10_Text_ClarkPostBattle::
    .string "Haha-ha-choo!\n"
    .string "Ha-choo!\l"
    .string "Snort! Snivel!$"

Route10_Text_HermanIntro::
    .string "Hi kid, want to see my DAEMONS?$"

Route10_Text_HermanDefeat::
    .string "Oh no! My DAEMONS!$"

Route10_Text_HermanPostBattle::
    .string "I don't like you.\n"
    .string "I don't like anyone better than me!$"

Route10_Text_HeidiIntro::
    .string "I've been out at a DAEMON GYM a\n"
    .string "few times.\p"
    .string "…But I always lose.$"

Route10_Text_HeidiDefeat::
    .string "Ohh!\n"
    .string "After all my training!$"

Route10_Text_HeidiPostBattle::
    .string "I noticed some ARCHIVISTS prowling\n"
    .string "around.$"

Route10_Text_TrentIntro::
    .string "Ah!\n"
    .string "This mountain air is delicious!$"

Route10_Text_TrentDefeat::
    .string "That cleared my head!$"

Route10_Text_TrentPostBattle::
    .string "I feel bloated on mountain air!$"

Route10_Text_CarolIntro::
    .string "I'm feeling a bit HALT. I haven't\n"
    .string "hiked in some time.$"

Route10_Text_CarolDefeat::
    .string "I'm too tired.\n"
    .string "I wasn't up for it.$"

Route10_Text_CarolPostBattle::
    .string "The DAEMON here in the mountains\n"
    .string "are so chunky…\p"
    .string "I wish there were pink DAEMON with\n"
    .string "a floral pattern!$"

Route10_Text_RockTunnelDetourToLavender::
    .string "ROCK TUNNEL Detour to HALFTONE\n"
    .string "TOWN$"

Route10_Text_RockTunnel::
    .string "THE BLACKOUT$"

Route10_Text_PowerPlant::
    .string "POWER PLANT$"

