LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
	.string "I recently moved to this town.\p"
	.string "INIT takes in every DAEMON left\n"
	.string "at his door.\p"
	.string "Some folks say he just makes it\n"
	.string "easier to leave them.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "That's odd, INIT isn't here. Where'd\n"
    .string "he go?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "INIT had been praying alone for\n"
    .string "ARTEFACT's mother.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
	.string "This is really INIT's house.\p"
	.string "He's really kind. He looks after\n"
	.string "DAEMONS nobody came back for.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "It's so warm! DAEMONS are so nice\n"
    .string "to hug!$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "PREDICTOR: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "FAULT: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "INIT: {PLAYER}…\p"
    .string "Your INDEX quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for DAEMON, your\n"
    .string "quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} received an INTERRUPT\n"
    .string "from INIT.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Upon hearing INTERRUPT, suspended\n"
    .string "DAEMON will spring awake.\p"
    .string "It works on all sleeping DAEMONS.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "INIT: Has my INTERRUPT helped\n"
    .string "you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
	.string "INIT's house is full again. Please\n"
	.string "do not leave DAEMONS on the step.\p"
	.string "Underneath, someone has written:\n"
	.string "then where?$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "DAEMON magazines line the shelf.\p"
    .string "DAEMON INSIDER…\p"
    .string "DAEMON FAN…$"

