LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "I recently moved to this town.\p"
    .string "I hear that INIT's not from these\n"
    .string "parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "That's odd, INIT isn't here. Where'd\n"
    .string "he go?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "INIT had been praying alone for\n"
    .string "RELIC's mother.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "This is really INIT's house.\p"
    .string "He's really kind.\p"
    .string "He looks after abandoned and\n"
    .string "orphaned DAEMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "It's so warm! DAEMONS are so nice\n"
    .string "to hug!$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "PREDICTOR: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "FAULT: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "INIT: {PLAYER}…\p"
    .string "Your INDEX quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for DAEMON, your\n"
    .string "quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} received a INTERRUPT\n"
    .string "from INIT.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Upon hearing INTERRUPT, suspended\n"
    .string "DAEMON will spring awake.\p"
    .string "It works on all sleeping DAEMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "INIT: Has my INTERRUPT helped\n"
    .string "you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "DAEMON FAN MAGAZINE Monthly Grand\n"
    .string "Prize Drawing!\p"
    .string "The application form is…\p"
    .string "Gone! It's been clipped out.\n"
    .string "Someone must have applied already.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "DAEMON magazines line the shelf.\p"
    .string "DAEMON INSIDER…\p"
    .string "DAEMON FAN…$"

