TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "I'm the DAEMON MOVE MANIAC.\p"
    .string "I know every single ROUTINE that\n"
    .string "DAEMON learn growing up.\p"
    .string "I'm also a mushroom maniac.\p"
    .string "Bring me two TINYMUSHROOMS, or one\n"
    .string "BIG MUSHROOM.\p"
    .string "If you do that for me, I'll teach a\n"
    .string "ROUTINE to one DAEMON.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Sniff, sniff… Hm! You smell of\n"
    .string "MUSHROOMS!\p"
    .string "Do you want me to teach a ROUTINE\n"
    .string "to a DAEMON of yours?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Which DAEMON needs tutoring?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Which ROUTINE should I teach?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "ROUTINE I can teach that DAEMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Then, I'll need a MUSHROOM or two.\n"
    .string "What are you going to give me?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} handed over two\n"
    .string "TINYMUSHROOMS in exchange.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} handed over one\n"
    .string "BIG MUSHROOM in exchange.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "If your DAEMON need to learn a\n"
    .string "ROUTINE, I need a MUSHROOM or\l"
    .string "two.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Hunh? There isn't a single ROUTINE\n"
    .string "that I can teach an EGG.$"

