Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi! I work at a DAEMON MART.\p"
    .string "It's a convenient shop, so please\n"
    .string "visit us in CALLOW CITY.\p"
    .string "I know, I'll give you a sample!\n"
    .string "Here you go!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "We also carry USERBOXes for\n"
    .string "binding DAEMON!$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

Route1_Text_CanJumpFromLedges::
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to BLANCHE TOWN\n"
    .string "quicker that way.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "BLANCHE TOWN -\l"
    .string "CALLOW CITY\p"
    .string "Painted beneath:\n"
    .string "THE BLEED$"

