Route1_Text_WorkAtPokeMartTakeSample::
    .string "I work at the REPO in CALLOW.\p"
    .string "Take a sample. Everyone does\n"
    .string "eventually.$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "We carry USERBOXes as well.\p"
    .string "You will want more than one.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the RESTORE in the\n"
    .string "ITEMS POCKET.$"

Route1_Text_CanJumpFromLedges::
    .string "The ledges along the road.\p"
    .string "You can drop down them. You cannot\n"
    .string "climb back up.\p"
    .string "It is quicker going home than it is\n"
    .string "coming out.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "BLANCHE TOWN -\l"
    .string "CALLOW CITY\p"
    .string "Painted beneath:\n"
    .string "THE BLEED$"

