CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "I know everything about the world\n"
    .string "of DAEMON in your GAME BOY!\p"
    .string "Get together with your friends and\n"
    .string "trade DAEMONS!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} obtained a MUSAI!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "DAEMON Lecture\p"
    .string "Playing with the Wireless Adapter$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "Which heading do you want to read?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "The DAEMON WIRELESS CLUB is\n"
    .string "upstairs at any CHECKPOINT.\p"
    .string "Visit one to link up with friend(s)\n"
    .string "using your Wireless Adapter.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "To link only with a friend, go to\n"
    .string "the DIRECT CORNER.\p"
    .string "It is the right counter at the\n"
    .string "DAEMON WIRELESS CLUB.\p"
    .string "Go into the TRADE CORNER or the\n"
    .string "COLOSSEUM with your friend.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "To link and communicate with\n"
    .string "anyone, go to the UNION ROOM.\p"
    .string "It is the left counter at the\n"
    .string "DAEMON WIRELESS CLUB.\p"
    .string "Go to the UNION ROOM and enjoy\n"
    .string "meeting other USERS.$"

@  T-324, DRAFT.
CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "A FOUNDRY CO. pamphlet on\n"
    .string "PLUGINS.\p"
    .string "Fifty in all. Each one\n"
    .string "installs once.\p"
    .string "DRIVERS install again\n"
    .string "and again.$"

