SilphCo_10F_Text_GruntIntro::
    .string "Welcome to 10F! So glad you could\n"
    .string "make it!$"

SilphCo_10F_Text_GruntDefeat::
    .string "Unexpected.$"

SilphCo_10F_Text_GruntPostBattle::
    .string "The boardroom is one floor up.\p"
    .string "Do go through!$"

SilphCo_10F_Text_TravisIntro::
    .string "Enough of your silly games!$"

SilphCo_10F_Text_TravisDefeat::
    .string "No continues left!$"

SilphCo_10F_Text_TravisPostBattle::
    .string "Are you satisfied with beating me?\n"
    .string "Then go on home!$"

SilphCo_10F_Text_WaaaImScared::
    .string "Waaaaa!\n"
    .string "I'm scared!$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "About me crying…\n"
    .string "Please keep it a secret.$"

SilphCo_10F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "10F$"

