PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOM: Right. Everyone goes, sooner\n"
    .string "or later.\p"
    .string "CRYSTAL CLEAR next door was\n"
    .string "asking after you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOM: …Right. You have been ready\n"
    .string "for a while.\p"
    .string "CRYSTAL CLEAR next door was\n"
    .string "asking after you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOM: {PLAYER}.\p"
    .string "Sit down for a minute.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOM: You both look well.\p"
    .string "Go on, then.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "There is a film on.\p"
    .string "Four kids are walking along a\n"
    .string "railway line.\p"
    .string "…I should go too.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "There is a film on.\p"
    .string "A girl is walking up a road made\n"
    .string "of brick.\p"
    .string "…I should go too.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Wrong side.$"

