SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .string "DAEMON growth rates differ from\n"
    .string "species to species.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .string "SILPH CO. is widely known to all.\p"
    .string "It's a victim of its own fame - it\n"
    .string "attracted TEAM CORPUS.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "Sigh… Wouldn't this be great?\p"
    .string "If the ELITE FOUR came and\n"
    .string "stomped TEAM CORPUS?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .string "TEAM CORPUS took off! We can go\n"
    .string "out safely again! That's great!$"

