Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "The element types of DAEMONS make\n"
    .string "them stronger than some types and\l"
    .string "weaker than others!$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "A NUGGET is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "I heard that ghosts haunt HALFTONE\n"
    .string "TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}! I've been looking for\n"
    .string "you!\p"
    .string "It's me, one of the ever-present\n"
    .string "AIDES to CRYSTAL CLEAR.\p"
    .string "If your INDEX has complete data\n"
    .string "on twenty species, I'm supposed to\l"
    .string "give you a reward from CRYSTAL\l"
    .string "CLEAR.\p"
    .string "She entrusted me with this\n"
    .string "EVERSTONE.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "twenty kinds of DAEMONS?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Great! You have bound or owned\n"
    .string "{STR_VAR_3} kinds of DAEMONS!\p"
    .string "Congratulations! Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} received the EVERSTONE\n"
    .string "from the AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "Making DAEMONS evolve certainly\n"
    .string "can add to the INDEX.\p"
    .string "However, at times, you may not\n"
    .string "want a certain DAEMON to evolve.\p"
    .string "In that case, give the EVERSTONE\n"
    .string "to that DAEMON.\p"
    .string "It will prevent evolution according\n"
    .string "to the PROFESSOR.$"

