#include "global.h"
#include "battle.h"
#include "palette.h"
#include "pokemon.h"
#include "daemon_streaks.h"
#include "constants/moves.h"
#include "constants/pokemon.h"
#include "constants/rgb.h"
#include "constants/species.h"

// The streaks (vision.md 9.4, amended 2026-09-17; T-132). Generated by tools/genstreaks.py: each
// type's streak colour, and which species the build gave streaks.
#include "data/pokemon/streaks.h"

// A move slot with nothing in it gives its streak nothing to be, and the streak disappears into the
// body: it takes the body ramp's MID step, which is palette index 3.
#define BODY_MID_INDEX 3

// A move type's streak depends on the BODY it is drawn on: its light step, or its dark step where the
// light one would vanish into that body. genstreaks.py measured every pair; the body is the species'
// first type, which is the type its ramp was built from.
static u16 StreakColour(const u16 *palette, u16 species, u16 move)
{
    u8 body, type;

    if (move == MOVE_NONE || move >= MOVES_COUNT)
        return palette[BODY_MID_INDEX];
    body = gSpeciesInfo[species].types[0];
    type = gBattleMoves[move].type;
    if (body >= NUMBER_OF_MON_TYPES || type >= NUMBER_OF_MON_TYPES)
        return gStreakBlank;
    return gStreakColours[body][type];
}

void Streaks_ApplyToBuffer(u16 *palette, u16 species, const u16 *moves)
{
    s32 i;

    if (species >= NUM_SPECIES || !gSpeciesHasStreaks[species] || moves == NULL)
        return;
    for (i = 0; i < MAX_MON_MOVES; i++)
        palette[STREAK_FIRST_INDEX + i] = StreakColour(palette, species, moves[i]);
}

void Streaks_ApplyToLoaded(u16 paletteOffset, u16 species, const u16 *moves)
{
    s32 i;

    if (species >= NUM_SPECIES || !gSpeciesHasStreaks[species] || moves == NULL)
        return;
    for (i = 0; i < MAX_MON_MOVES; i++)
    {
        u16 colour = StreakColour(&gPlttBufferUnfaded[paletteOffset], species, moves[i]);

        gPlttBufferUnfaded[paletteOffset + STREAK_FIRST_INDEX + i] = colour;
        gPlttBufferFaded[paletteOffset + STREAK_FIRST_INDEX + i] = colour;
    }
}

void Streaks_MovesOfMon(struct Pokemon *mon, u16 *moves)
{
    s32 i;

    for (i = 0; i < MAX_MON_MOVES; i++)
        moves[i] = GetMonData(mon, MON_DATA_MOVE1 + i, NULL);
}

void Streaks_MovesOfBoxMon(struct BoxPokemon *boxMon, u16 *moves)
{
    s32 i;

    for (i = 0; i < MAX_MON_MOVES; i++)
        moves[i] = GetBoxMonData(boxMon, MON_DATA_MOVE1 + i, NULL);
}

void Streaks_MovesOfBattler(u8 battlerId, u16 *moves)
{
    s32 i;

    for (i = 0; i < MAX_MON_MOVES; i++)
        moves[i] = gBattleMons[battlerId].moves[i];
}
