#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("A physical attack\ndelivered with a\nlong tail or a\nforeleg, etc.");
const u8 gMoveDescription_KarateChop[] = _("The remote is\nattacked with a\nsharp chop. It has\na high critical-hit\nratio.");
const u8 gMoveDescription_DoubleSlap[] = _("The remote is\nslapped\nrepeatedly, back\nand forth, two to\nfive times.");
const u8 gMoveDescription_CometPunch[] = _("The remote is hit\nwith a flurry of\npunches that strike\ntwo to five times.");
const u8 gMoveDescription_MegaPunch[] = _("The remote is\nslugged by a\npunch thrown with\nmuscle-packed\npower.");
const u8 gMoveDescription_PayDay[] = _("Numerous coins are\nhurled at the\nremote. Money is\nearned after\nbattle.");
const u8 gMoveDescription_FirePunch[] = _("The remote is\npunched with a\nfiery fist. It may\nleave the remote\nwith a burn.");
const u8 gMoveDescription_IcePunch[] = _("The remote is\npunched with an\nicy fist. It may\nleave the remote\nfrozen.");
const u8 gMoveDescription_ThunderPunch[] = _("The remote is\npunched with an\nelectrified fist.\nIt may leave the\nremote paralyzed.");
const u8 gMoveDescription_Scratch[] = _("Hard, pointed, and\nsharp claws rake\nthe remote.");
const u8 gMoveDescription_ViceGrip[] = _("Huge, impressive\npincers grip and\nsqueeze the\nremote.");
const u8 gMoveDescription_Guillotine[] = _("A vicious tearing attack with\npincers. The remote will HALT\nif it hits.");
const u8 gMoveDescription_RazorWind[] = _("Blades of wind hit\nthe remote on the\n2nd turn. It has a\nhigh critical-hit\nratio.");
const u8 gMoveDescription_SwordsDance[] = _("A frenetic dance of\nfighting. It sharply\nraises the ATTACK\nstat.");
const u8 gMoveDescription_Cut[] = _("A basic attack.\nIt can be used to\ncut down thin trees\nand grass.");
const u8 gMoveDescription_Gust[] = _("Strikes the remote\nwith a gust of wind\nwhipped up by\nwings.");
const u8 gMoveDescription_WingAttack[] = _("The remote is\nstruck with large,\nimposing wings\nspread wide.");
const u8 gMoveDescription_Whirlwind[] = _("The remote is made\nto switch out with\nan ally. In the\nwild, the battle\nends.");
const u8 gMoveDescription_Fly[] = _("A 2-turn move that\nhits on the 2nd\nturn. Use it to fly\nto any known town.");
const u8 gMoveDescription_Bind[] = _("A long body or\ntentacles are used\nto bind the remote\nfor two to five\nturns.");
const u8 gMoveDescription_Slam[] = _("The remote is\nstruck with a\nlong tail, vines,\netc.");
const u8 gMoveDescription_VineWhip[] = _("The remote is\nstruck with\nslender, whip- like\nvines.");
const u8 gMoveDescription_Stomp[] = _("The remote is\nstomped with a big\nfoot. It may make\nthe remote flinch.");
const u8 gMoveDescription_DoubleKick[] = _("Two legs are used\nto quickly kick the\nremote twice in\none turn.");
const u8 gMoveDescription_MegaKick[] = _("The remote is\nattacked by a kick\nfired with\nmuscle-packed\npower.");
const u8 gMoveDescription_JumpKick[] = _("The user jumps up\nhigh, then kicks.\nIf it misses, the\nuser hurts itself.");
const u8 gMoveDescription_RollingKick[] = _("A quick kick from a\nrolling spin. It\nmay make the\nremote flinch.");
const u8 gMoveDescription_SandAttack[] = _("A lot of sand is\nhurled in the\nremote's face,\nreducing its\naccuracy.");
const u8 gMoveDescription_Headbutt[] = _("The user sticks its\nhead out and rams.\nIt may make the\nremote flinch.");
const u8 gMoveDescription_HornAttack[] = _("The remote is\njabbed with a\nsharply pointed\nhorn to inflict\ndamage.");
const u8 gMoveDescription_FuryAttack[] = _("The remote is\njabbed repeatedly\nwith a horn or beak\ntwo to five times.");
const u8 gMoveDescription_HornDrill[] = _("The horn is rotated like a drill to\nram. The remote will HALT if it\nhits.");
const u8 gMoveDescription_Tackle[] = _("A physical attack\nin which the user\ncharges, full body,\ninto the remote.");
const u8 gMoveDescription_BodySlam[] = _("The user drops its\nfull body on the\nremote. It may\nleave the remote\nparalyzed.");
const u8 gMoveDescription_Wrap[] = _("A long body or\nvines are used to\nwrap the remote\nfor two to five\nturns.");
const u8 gMoveDescription_TakeDown[] = _("A reckless, full-\nbody charge attack\nthat also hurts the\nuser a little.");
const u8 gMoveDescription_Thrash[] = _("The user rampages\nabout for two to\nthree turns, then\nbecomes confused.");
const u8 gMoveDescription_DoubleEdge[] = _("A reckless, life-\nrisking tackle that\nalso hurts the user\na little.");
const u8 gMoveDescription_TailWhip[] = _("The user wags its\ntail cutely, making\nthe remote lower\nits DEFENSE stat.");
const u8 gMoveDescription_PoisonSting[] = _("The remote is\nstabbed with a\ntoxic barb, etc.\nIt may poison the\nremote.");
const u8 gMoveDescription_Twineedle[] = _("The remote is\nstabbed twice with\nforeleg stingers.\nIt may poison the\nremote.");
const u8 gMoveDescription_PinMissile[] = _("Sharp pins are shot\nat the remote and\nhit two to five\ntimes at once.");
const u8 gMoveDescription_Leer[] = _("The remote is given\nan intimidating look\nthat lowers its\nDEFENSE stat.");
const u8 gMoveDescription_Bite[] = _("The user bites with\nvicious fangs. It\nmay make the\nremote flinch.");
const u8 gMoveDescription_Growl[] = _("The user growls in\na cute way, making\nthe remote lower\nits ATTACK stat.");
const u8 gMoveDescription_Roar[] = _("The remote is made\nto switch out with\nan ally. In the\nwild, the battle\nends.");
const u8 gMoveDescription_Sing[] = _("A soothing song in\na calming voice\nlulls the remote\ninto a deep\nslumber.");
const u8 gMoveDescription_Supersonic[] = _("The user generates\nodd sound waves.\nIt may confuse the\nremote.");
const u8 gMoveDescription_SonicBoom[] = _("The remote is hit\nwith a shock wave\nthat always\ninflicts 20- HP\ndamage.");
const u8 gMoveDescription_Disable[] = _("For a few turns, it\nprevents the remote\nfrom using the move\nit last used.");
const u8 gMoveDescription_Acid[] = _("The remote is\nsprayed with a\nharsh, hide-\nmelting acid that\nmay lower DEFENSE.");
const u8 gMoveDescription_Ember[] = _("The remote is\nattacked with small\nflames. The remote\nmay suffer a burn.");
const u8 gMoveDescription_Flamethrower[] = _("The remote is\nscorched with\nintense flames. The\nremote may suffer a\nburn.");
const u8 gMoveDescription_Mist[] = _("The ally party is\nprotected by a\nmist that prevents\nstat reductions.");
const u8 gMoveDescription_WaterGun[] = _("The remote is\nstruck with a lot\nof water expelled\nforcibly from the\nmouth.");
const u8 gMoveDescription_HydroPump[] = _("A high volume of\nwater is blasted at\nthe remote under\ngreat pressure.");
const u8 gMoveDescription_Surf[] = _("A big wave crashes\ndown on the\nremote. Can also\nbe used for\ncrossing water.");
const u8 gMoveDescription_IceBeam[] = _("The remote is\nstruck with an icy\nbeam. It may\nfreeze the remote\nsolid.");
const u8 gMoveDescription_Blizzard[] = _("The remote is\nblasted with a\nblizzard. It may\nfreeze the remote\nsolid.");
const u8 gMoveDescription_Psybeam[] = _("A peculiar ray is\nshot at the\nremote. It may\nleave the remote\nconfused.");
const u8 gMoveDescription_BubbleBeam[] = _("A spray of bubbles\nstrikes the remote.\nIt may lower the\nremote's SPEED\nstat.");
const u8 gMoveDescription_AuroraBeam[] = _("A rainbow-colored\nattack beam. It\nmay lower the\nremote's ATTACK\nstat.");
const u8 gMoveDescription_HyperBeam[] = _("A severely damaging\nattack that makes\nthe user rest on\nthe next turn.");
const u8 gMoveDescription_Peck[] = _("The remote is\njabbed with a\nsharply pointed\nbeak or horn.");
const u8 gMoveDescription_DrillPeck[] = _("A corkscrewing\nattack with the\nsharp beak acting\nas a drill.");
const u8 gMoveDescription_Submission[] = _("A reckless, full-\nbody throw attack\nthat also hurts the\nuser a little.");
const u8 gMoveDescription_LowKick[] = _("A low, tripping kick\nthat inflicts more\ndamage on heavier\nremote.");
const u8 gMoveDescription_Counter[] = _("A retaliation move\nthat counters any\nphysical hit with\ndouble the damage.");
const u8 gMoveDescription_SeismicToss[] = _("A gravity-fed throw\nthat causes damage\nmatching the user's\nlevel.");
const u8 gMoveDescription_Strength[] = _("The remote is\nslugged at\nmaximum power.\nCan also be used\nto move boulders.");
const u8 gMoveDescription_Absorb[] = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_MegaDrain[] = _("A tough attack that\ndrains half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_LeechSeed[] = _("A seed is planted\non the remote to\nsteal some HP for\nthe user on every\nturn.");
const u8 gMoveDescription_Growth[] = _("The user's body is\nforced to grow,\nraising the SP.\nATK stat.");
const u8 gMoveDescription_RazorLeaf[] = _("The remote is hit\nwith a cutting\nleaf. It has a\nhigh critical-hit\nratio.");
const u8 gMoveDescription_SolarBeam[] = _("A 2-turn move that\nblasts the remote\nwith absorbed\nenergy in the 2nd\nturn.");
const u8 gMoveDescription_PoisonPowder[] = _("A cloud of toxic\ndust is scattered.\nIt may poison the\nremote.");
const u8 gMoveDescription_StunSpore[] = _("Paralyzing dust is\nscattered wildly.\nIt may paralyze\nthe remote.");
const u8 gMoveDescription_SleepPowder[] = _("A sleep-inducing\ndust is scattered\nin high volume\naround a remote.");
const u8 gMoveDescription_PetalDance[] = _("The user attacks\nwith petals for two\nto three turns,\nthen gets confused.");
const u8 gMoveDescription_StringShot[] = _("The remote is\nbound with strings\nshot from the\nmouth to reduce\nits SPEED.");
const u8 gMoveDescription_DragonRage[] = _("The remote is hit\nwith a shock wave\nthat always\ninflicts 40- HP\ndamage.");
const u8 gMoveDescription_FireSpin[] = _("The remote is\ntrapped in an\nintense spiral of\nfire that rages two\nto five turns.");
const u8 gMoveDescription_ThunderShock[] = _("An electric shock\nattack that may\nalso leave the\nremote paralyzed.");
const u8 gMoveDescription_Thunderbolt[] = _("A strong electrical\nattack that may\nalso leave the\nremote paralyzed.");
const u8 gMoveDescription_ThunderWave[] = _("A weak electric\nshock that is sure\nto cause paralysis\nif it hits.");
const u8 gMoveDescription_Thunder[] = _("A brutal lightning\nattack that may\nalso leave the\nremote paralyzed.");
const u8 gMoveDescription_RockThrow[] = _("The remote is\nattacked with a\nshower of small,\neasily thrown\nrocks.");
const u8 gMoveDescription_Earthquake[] = _("An earthquake that strikes all\nDAEMONS in battle excluding the\nuser.");
const u8 gMoveDescription_Fissure[] = _("The remote is dropped into a\nfissure. The remote HALTS if it\nhits.");
const u8 gMoveDescription_Dig[] = _("An attack that hits\non the 2nd turn.\nCan also be used\nto exit dungeons.");
const u8 gMoveDescription_Toxic[] = _("A move that badly\npoisons the remote.\nIts poison damage\nworsens every turn.");
const u8 gMoveDescription_Confusion[] = _("A weak telekinetic\nattack that may\nalso leave the\nremote confused.");
const u8 gMoveDescription_Psychic[] = _("A strong telekinetic\nattack. It may also\nlower the remote's\nSP. DEF stat.");
const u8 gMoveDescription_Hypnosis[] = _("Hypnotic suggestion\nis used to make the\nremote fall into a\ndeep sleep.");
const u8 gMoveDescription_Meditate[] = _("The user meditates\nto awaken its power\nand raise its\nATTACK stat.");
const u8 gMoveDescription_Agility[] = _("The user relaxes\nand lightens its\nbody to sharply\nboost its SPEED.");
const u8 gMoveDescription_QuickAttack[] = _("An almost invisibly\nfast attack that\nis certain to strike\nfirst.");
const u8 gMoveDescription_Rage[] = _("An attack that\nbecomes stronger\neach time the user\nis hit in battle.");
const u8 gMoveDescription_Teleport[] = _("Use it to DETACH from any wild\nDAEMON. Also warps to the last\nPOKé CENTER.");
const u8 gMoveDescription_NightShade[] = _("An attack with a\nmirage that inflicts\ndamage matching\nthe user's level.");
const u8 gMoveDescription_Mimic[] = _("The user copies the\nmove last used by\nthe remote for the\nrest of the battle.");
const u8 gMoveDescription_Screech[] = _("An ear-splitting\nscreech is emitted\nto sharply reduce\nthe remote's\nDEFENSE.");
const u8 gMoveDescription_DoubleTeam[] = _("The user creates\nillusory copies of\nitself to raise its\nevasiveness.");
const u8 gMoveDescription_Recover[] = _("A self-healing move\nthat restores HP by\nup to half of the\nuser's maximum HP.");
const u8 gMoveDescription_Harden[] = _("The user stiffens\nall the muscles in\nits body to raise\nits DEFENSE stat.");
const u8 gMoveDescription_Minimize[] = _("The user compresses\nall the cells in its\nbody to raise its\nevasiveness.");
const u8 gMoveDescription_Smokescreen[] = _("An obscuring cloud\nof smoke or ink\nreduces the\nremote's accuracy.");
const u8 gMoveDescription_ConfuseRay[] = _("The remote is\nexposed to a\nsinister ray that\ntriggers confusion.");
const u8 gMoveDescription_Withdraw[] = _("The user withdraws\nits body in its hard\nshell, raising its\nDEFENSE stat.");
const u8 gMoveDescription_DefenseCurl[] = _("The user curls up\nto conceal weak\nspots and raise its\nDEFENSE stat.");
const u8 gMoveDescription_Barrier[] = _("The user creates a\nsturdy wall that\nsharply raises its\nDEFENSE stat.");
const u8 gMoveDescription_LightScreen[] = _("A wall of light\ncuts damage from\nSP. ATK attacks\nfor five turns.");
const u8 gMoveDescription_Haze[] = _("Eliminates all stat changes among\nall DAEMONS engaged in battle.");
const u8 gMoveDescription_Reflect[] = _("A wall of light\ncuts damage from\nphysical attacks\nfor five turns.");
const u8 gMoveDescription_FocusEnergy[] = _("The user takes a\ndeep breath and\nfocuses to raise its\ncritical-hit ratio.");
const u8 gMoveDescription_Bide[] = _("The user endures\nattacks for two\nturns, then strikes\nback double.");
const u8 gMoveDescription_Metronome[] = _("Waggles a finger\nand stimulates the\nbrain into using any\nmove at random.");
const u8 gMoveDescription_MirrorMove[] = _("The user counters\nthe move last used\nby the remote with\nthe same move.");
const u8 gMoveDescription_SelfDestruct[] = _("The user blows up to inflict severe\ndamage, even making itself HALT.");
const u8 gMoveDescription_EggBomb[] = _("A large egg is\nhurled with great\nforce at the remote\nto inflict damage.");
const u8 gMoveDescription_Lick[] = _("The remote is\nlicked and hit with\na long tongue. It\nmay also paralyze.");
const u8 gMoveDescription_Smog[] = _("The remote is\nattacked with\nexhaust gases. It\nmay also poison the\nremote.");
const u8 gMoveDescription_Sludge[] = _("Toxic sludge is\nhurled at the\nremote. It may\npoison the target.");
const u8 gMoveDescription_BoneClub[] = _("The remote is\nclubbed with a\nbone held in hand.\nIt may make the\nremote flinch.");
const u8 gMoveDescription_FireBlast[] = _("The remote is hit\nwith an intense\nflame. It may\nleave the target\nwith a burn.");
const u8 gMoveDescription_Waterfall[] = _("A powerful charge\nattack. It can also\nbe used to climb\na waterfall.");
const u8 gMoveDescription_Clamp[] = _("The remote is\nclamped and\nsqueezed by the\nuser's shell for two\nto five turns.");
const u8 gMoveDescription_Swift[] = _("Star-shaped rays\nthat never miss are\nfired at all remote\nin battle.");
const u8 gMoveDescription_SkullBash[] = _("The user raises its\nDEFENSE in the 1st\nturn, then attacks\nin the 2nd turn.");
const u8 gMoveDescription_SpikeCannon[] = _("Sharp spikes are\nfired at the remote\nto strike two to\nfive times.");
const u8 gMoveDescription_Constrict[] = _("The remote is\nattacked with long\ntentacles or vines.\nIt may lower\nSPEED.");
const u8 gMoveDescription_Amnesia[] = _("Forgets about\nsomething and\nsharply raises\nSP. DEF.");
const u8 gMoveDescription_Kinesis[] = _("The user distracts\nthe remote by\nbending a spoon.\nIt may lower\naccuracy.");
const u8 gMoveDescription_SoftBoiled[] = _("Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.");
const u8 gMoveDescription_HiJumpKick[] = _("A strong jumping\nknee kick. If it\nmisses, the user is\nhurt.");
const u8 gMoveDescription_Glare[] = _("The user intimidates\nthe remote with the\ndesign on its belly\nto cause paralysis.");
const u8 gMoveDescription_DreamEater[] = _("Absorbs half the\ndamage it inflicted\non a sleeping\nremote to restore\nHP.");
const u8 gMoveDescription_PoisonGas[] = _("The remote is\nsprayed with a\ncloud of toxic gas\nthat may poison\nthe remote.");
const u8 gMoveDescription_Barrage[] = _("Round objects are\nhurled at the\nremote to strike\ntwo to five times.");
const u8 gMoveDescription_LeechLife[] = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_LovelyKiss[] = _("The user forces a\nkiss on the remote\nwith a scary face\nthat induces sleep.");
const u8 gMoveDescription_SkyAttack[] = _("A 2nd-turn attack\nmove with a high\ncritical-hit ratio.\nThe remote may\nflinch.");
const u8 gMoveDescription_Transform[] = _("The user transforms\ninto a copy of the\nremote with even\nthe same move set.");
const u8 gMoveDescription_Bubble[] = _("A spray of bubbles\nhits the remote.\nIt may lower the\nremote's SPEED\nstat.");
const u8 gMoveDescription_DizzyPunch[] = _("The remote is hit\nwith a rhythmic\npunch that may\nleave it confused.");
const u8 gMoveDescription_Spore[] = _("The user scatters\nbursts of fine\nspores that induce\nsleep.");
const u8 gMoveDescription_Flash[] = _("A blast of light\nthat cuts the\nremote's accuracy.\nIt also\nilluminates caves.");
const u8 gMoveDescription_Psywave[] = _("The remote is\nattacked with an\nodd, hot energy\nwave that varies in\nintensity.");
const u8 gMoveDescription_Splash[] = _("The user just flops\nand splashes around\nwithout having any\neffect.");
const u8 gMoveDescription_AcidArmor[] = _("The user alters its\ncells to liquefy\nitself and sharply\nraise DEFENSE.");
const u8 gMoveDescription_Crabhammer[] = _("A large pincer is\nused to hammer the\nremote. It has a\nhigh critical-hit\nratio.");
const u8 gMoveDescription_Explosion[] = _("The user explodes\nto inflict terrible\ndamage even while\nfainting itself.");
const u8 gMoveDescription_FurySwipes[] = _("The remote is\nraked with sharp\nclaws or scythes\ntwo to five times.");
const u8 gMoveDescription_Bonemerang[] = _("The user throws a\nbone that hits the\nremote once, then\nonce again on\nreturn.");
const u8 gMoveDescription_Rest[] = _("The user sleeps for\ntwo turns to fully\nrestore HP and heal\nany status problem.");
const u8 gMoveDescription_RockSlide[] = _("Large boulders are\nhurled at the\nremote. It may\nmake the remote\nflinch.");
const u8 gMoveDescription_HyperFang[] = _("The remote is\nattacked with sharp\nfangs. It may make\nthe remote flinch.");
const u8 gMoveDescription_Sharpen[] = _("The user reduces\nits polygon count\nto sharpen edges\nand raise ATTACK.");
const u8 gMoveDescription_Conversion[] = _("The user changes\nits type to match\nthe type of one of\nits moves.");
const u8 gMoveDescription_TriAttack[] = _("A simultaneous\n3-beam attack that\nmay paralyze, burn,\nor freeze the\nremote.");
const u8 gMoveDescription_SuperFang[] = _("The user attacks\nwith sharp fangs\nand halves the\nremote's HP.");
const u8 gMoveDescription_Slash[] = _("The remote is\nslashed with\nclaws, etc. It has\na high\ncritical-hit ratio.");
const u8 gMoveDescription_Substitute[] = _("The user creates a\ndecoy using one-\nquarter of its full\nHP.");
const u8 gMoveDescription_Struggle[] = _("An attack that is\nused only if there\nis no PP. It also\nhurts the user.");
const u8 gMoveDescription_Sketch[] = _("This move copies\nthe move last used\nby the remote,\nthen disappears.");
const u8 gMoveDescription_TripleKick[] = _("A 3-kick attack\nthat becomes more\npowerful with each\nsuccessive hit.");
const u8 gMoveDescription_Thief[] = _("An attack that may\ntake the remote's\nheld item if the\nuser isn't holding\none.");
const u8 gMoveDescription_SpiderWeb[] = _("Ensnares the\nremote with\nsticky string so\nit doesn't DETACH\nor switch out.");
const u8 gMoveDescription_MindReader[] = _("The user predicts\nthe remote's action\nto ensure its next\nattack hits.");
const u8 gMoveDescription_Nightmare[] = _("A sleeping remote\nis shown a\nnightmare that\ninflicts some\ndamage every turn.");
const u8 gMoveDescription_FlameWheel[] = _("The user makes a\nfiery charge at the\nremote. It may\ncause a burn.");
const u8 gMoveDescription_Snore[] = _("An attack that can\nbe used only while\nasleep. It may\ncause flinching.");
const u8 gMoveDescription_Curse[] = _("A move that works\ndifferently for the\nGHOST-type and all\nthe other types.");
const u8 gMoveDescription_Flail[] = _("A desperate attack\nthat becomes more\npowerful the less\nHP the user has.");
const u8 gMoveDescription_Conversion2[] = _("The user changes\ntype to make itself\nresistant to the\nlast attack it took.");
const u8 gMoveDescription_Aeroblast[] = _("A vortex of air is\nshot at the\nremote. It has a\nhigh critical-hit\nratio.");
const u8 gMoveDescription_CottonSpore[] = _("Cotton-like spores\ncling to the\nremote, sharply\nreducing its\nSPEED stat.");
const u8 gMoveDescription_Reversal[] = _("An all-out attack\nthat becomes more\npowerful the less\nHP the user has.");
const u8 gMoveDescription_Spite[] = _("A move that cuts 2\nto 5 PP from the\nmove last used by\nthe remote.");
const u8 gMoveDescription_PowderSnow[] = _("Blasts the remote\nwith a snowy gust.\nIt may cause\nfreezing.");
const u8 gMoveDescription_Protect[] = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_MachPunch[] = _("A punch thrown at\nblinding speed.\nIt is certain to\nstrike first.");
const u8 gMoveDescription_ScaryFace[] = _("Frightens the\nremote with a\nscary face to\nsharply reduce\nits SPEED.");
const u8 gMoveDescription_FaintAttack[] = _("The user draws up\nclose to the\nremote\ndisarmingly, then\nhits without fail.");
const u8 gMoveDescription_SweetKiss[] = _("The user kisses\nthe remote with\nsweet cuteness\nthat causes\nconfusion.");
const u8 gMoveDescription_BellyDrum[] = _("The user maximizes\nits ATTACK stat at\nthe cost of half\nits full HP.");
const u8 gMoveDescription_SludgeBomb[] = _("Filthy sludge is\nhurled at the\nremote. It may\npoison the target.");
const u8 gMoveDescription_MudSlap[] = _("Mud is hurled in\nthe remote's face\nto inflict damage\nand lower its\naccuracy.");
const u8 gMoveDescription_Octazooka[] = _("Ink is blasted in\nthe remote's face\nor eyes to damage\nand lower\naccuracy.");
const u8 gMoveDescription_Spikes[] = _("A trap of spikes is\nlaid around the\nremote's party to\nhurt remote\nswitching in.");
const u8 gMoveDescription_ZapCannon[] = _("An electric blast is\nfired like a cannon\nto inflict damage\nand paralyze.");
const u8 gMoveDescription_Foresight[] = _("Completely negates\nthe remote's efforts\nto heighten its\nability to evade.");
const u8 gMoveDescription_DestinyBond[] = _("If the user HALTS, the\nremote delivering the final\nhit also HALTS.");
const u8 gMoveDescription_PerishSong[] = _("Any battler that hears this HALTS\nin three turns unless it switches.");
const u8 gMoveDescription_IcyWind[] = _("A chilling wind is\nused to attack.\nIt also lowers the\nSPEED stat.");
const u8 gMoveDescription_Detect[] = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_BoneRush[] = _("The user strikes\nthe remote with a\nbone in hand two to\nfive times.");
const u8 gMoveDescription_LockOn[] = _("The user locks on\nto the remote,\nmaking the next\nmove sure to hit.");
const u8 gMoveDescription_Outrage[] = _("The user thrashes\nabout for two to\nthree turns, then\nbecomes confused.");
const u8 gMoveDescription_Sandstorm[] = _("A 5-turn sandstorm\nthat damages all\ntypes except ROCK,\nGROUND, and STEEL.");
const u8 gMoveDescription_GigaDrain[] = _("A harsh attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_Endure[] = _("The user endures\nany hit with 1 HP\nleft. It may fail if\nused in succession.");
const u8 gMoveDescription_Charm[] = _("The remote is\ncharmed by the\nuser's cute\nappeals, sharply\ncutting its ATTACK.");
const u8 gMoveDescription_Rollout[] = _("A 5-turn rolling\nattack that becomes\nstronger each time\nit hits.");
const u8 gMoveDescription_FalseSwipe[] = _("A restrained attack\nthat always leaves\nthe remote with at\nleast 1 HP.");
const u8 gMoveDescription_Swagger[] = _("A move that makes\nthe remote\nconfused, but\nalso sharply\nraises its ATTACK.");
const u8 gMoveDescription_MilkDrink[] = _("Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.");
const u8 gMoveDescription_Spark[] = _("An electrically\ncharged tackle that\nmay also paralyze\nthe remote.");
const u8 gMoveDescription_FuryCutter[] = _("An attack that\ngrows stronger on\neach successive\nhit.");
const u8 gMoveDescription_SteelWing[] = _("The remote is hit\nwith wings of\nsteel. It may also\nraise the user's\nDEFENSE.");
const u8 gMoveDescription_MeanLook[] = _("The remote is\nfixed with a\nmean look that\nprevents it from\nescaping.");
const u8 gMoveDescription_Attract[] = _("If it is the other\ngender, the remote\nis made infatuated\nand unlikely to\nattack.");
const u8 gMoveDescription_SleepTalk[] = _("While asleep, the\nuser randomly uses\none of the moves it\nknows.");
const u8 gMoveDescription_HealBell[] = _("A soothing bell\nchimes to heal the\nstatus problems of\nall allies.");
const u8 gMoveDescription_Return[] = _("This attack move grows more\npowerful the more the user likes\nits USER.");
const u8 gMoveDescription_Present[] = _("The remote is given\na booby-trapped\ngift. It restores\nHP sometimes,\nhowever.");
const u8 gMoveDescription_Frustration[] = _("This attack move grows more\npowerful the less the user likes\nits USER.");
const u8 gMoveDescription_Safeguard[] = _("It protects the\nuser's party from\nall status problems\nfor five turns.");
const u8 gMoveDescription_PainSplit[] = _("The user adds its\nHP to the remote's\nHP, then equally\nshares the total\nHP.");
const u8 gMoveDescription_SacredFire[] = _("A mystical and\npowerful fire\nattack that may\ninflict a burn.");
const u8 gMoveDescription_Magnitude[] = _("A ground-shaking attack against all\nstanding DAEMON. Its power varies.");
const u8 gMoveDescription_DynamicPunch[] = _("The remote is\npunched with the\nuser's full power.\nIt confuses the\nremote if it hits.");
const u8 gMoveDescription_Megahorn[] = _("A brutal ramming\nattack delivered\nwith a tough and\nimpressive horn.");
const u8 gMoveDescription_DragonBreath[] = _("The remote is hit\nwith an incredible\nblast of breath\nthat may also\nparalyze.");
const u8 gMoveDescription_BatonPass[] = _("The user switches\nout, passing along\nany stat changes\nto the new battler.");
const u8 gMoveDescription_Encore[] = _("Makes the remote\nuse the move it\nlast used\nrepeatedly for two\nto six turns.");
const u8 gMoveDescription_Pursuit[] = _("An attack move that\nworks especially\nwell on a remote\nthat is switching\nout.");
const u8 gMoveDescription_RapidSpin[] = _("An attack that\nfrees the user from\nBIND, WRAP, LEECH\nSEED, and SPIKES.");
const u8 gMoveDescription_SweetScent[] = _("Allures the remote to reduce\nevasiveness. It also attracts wild\nDAEMON.");
const u8 gMoveDescription_IronTail[] = _("An attack with a\nsteel-hard tail.\nIt may lower the\nremote's DEFENSE\nstat.");
const u8 gMoveDescription_MetalClaw[] = _("The remote is\nattacked with steel\nclaws. It may also\nraise the user's\nATTACK.");
const u8 gMoveDescription_VitalThrow[] = _("Makes the user\nattack after the\nremote. In\nreturn, it will\nnot miss.");
const u8 gMoveDescription_MorningSun[] = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_Synthesis[] = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_Moonlight[] = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_HiddenPower[] = _("An attack that\nvaries in type and\nintensity depending\non the user.");
const u8 gMoveDescription_CrossChop[] = _("The remote is hit\nwith double chops.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Twister[] = _("A vicious twister\nattacks the\nremote. It may\nmake the remote\nflinch.");
const u8 gMoveDescription_RainDance[] = _("A heavy rain falls\nfor five turns,\npowering up WATER-\ntype moves.");
const u8 gMoveDescription_SunnyDay[] = _("The sun blazes for\nfive turns, powering\nup FIRE-type\nmoves.");
const u8 gMoveDescription_Crunch[] = _("The remote is\ncrunched with sharp\nfangs. It may lower\nthe remote's SP.\nDEF.");
const u8 gMoveDescription_MirrorCoat[] = _("A retaliation move\nthat pays back the\nremote's special\nattack double.");
const u8 gMoveDescription_PsychUp[] = _("The user hypnotizes\nitself into copying\nany stat change\nmade by the\nremote.");
const u8 gMoveDescription_ExtremeSpeed[] = _("A blindingly speedy\ncharge attack that\nalways goes before\nany other.");
const u8 gMoveDescription_AncientPower[] = _("An ancient power is\nused to attack. It\nmay also raise all\nthe user's stats.");
const u8 gMoveDescription_ShadowBall[] = _("A shadowy blob is\nhurled at the\nremote. May also\nlower the remote's\nSP. DEF.");
const u8 gMoveDescription_FutureSight[] = _("Two turns after\nthis move is used,\nthe remote is\nattacked\npsychically.");
const u8 gMoveDescription_RockSmash[] = _("An attack that may\nalso cut DEFENSE.\nIt can also smash\ncracked boulders.");
const u8 gMoveDescription_Whirlpool[] = _("The remote is\ntrapped in a fast,\nvicious whirlpool\nfor two to five\nturns.");
const u8 gMoveDescription_BeatUp[] = _("All party DAEMON join in the\nattack. The more allies, the more\ndamage.");
const u8 gMoveDescription_FakeOut[] = _("An attack that hits\nfirst and causes\nflinching. Usable\nonly on 1st turn.");
const u8 gMoveDescription_Uproar[] = _("The user attacks in\nan uproar that\nprevents sleep for\ntwo to five turns.");
const u8 gMoveDescription_Stockpile[] = _("The user charges\nup power for use\nlater. It can be\nused three times.");
const u8 gMoveDescription_SpitUp[] = _("The power built\nusing STOCKPILE is\nreleased at once\nfor attack.");
const u8 gMoveDescription_Swallow[] = _("The energy it built\nusing STOCKPILE is\nabsorbed to restore\nHP.");
const u8 gMoveDescription_HeatWave[] = _("The user exhales a\nheated breath to\nattack. It may also\ninflict a burn.");
const u8 gMoveDescription_Hail[] = _("A hailstorm lasting five turns\ndamages all DAEMONS except the\nICE-type.");
const u8 gMoveDescription_Torment[] = _("It enrages the\nremote, making it\nincapable of using\nthe same move\nsuccessively.");
const u8 gMoveDescription_Flatter[] = _("Flattery is used to\nconfuse the\nremote, but its SP.\nATK also rises.");
const u8 gMoveDescription_WillOWisp[] = _("A sinister, bluish\nwhite flame is shot\nat the remote to\ninflict a burn.");
const u8 gMoveDescription_Memento[] = _("The user HALTS, but sharply lowers\nthe remote's ATTACK and SP. ATK.");
const u8 gMoveDescription_Facade[] = _("An attack that is\nboosted if user is\nburned, poisoned,\nor paralyzed.");
const u8 gMoveDescription_FocusPunch[] = _("An attack that is\nexecuted last.\nThe user flinches\nif hit beforehand.");
const u8 gMoveDescription_SmellingSalt[] = _("Doubly effective on\na paralyzed\nremote, but it also\ncures the remote's\nparalysis.");
const u8 gMoveDescription_FollowMe[] = _("The user draws\nattention to itself,\nmaking remote\nattack only the\nuser.");
const u8 gMoveDescription_NaturePower[] = _("An attack that\nchanges type\ndepending on the\nuser's location.");
const u8 gMoveDescription_Charge[] = _("The user charges\npower to boost the\nELECTRIC move it\nuses next.");
const u8 gMoveDescription_Taunt[] = _("The remote is\ntaunted into a\nrage that allows\nit to use only\nattack moves.");
const u8 gMoveDescription_HelpingHand[] = _("A move that boosts\nthe power of the\nally's attack in a\nbattle.");
const u8 gMoveDescription_Trick[] = _("A move that tricks\nthe remote into\ntrading held items\nwith the user.");
const u8 gMoveDescription_RolePlay[] = _("The user mimics the\nremote completely\nand copies the\nremote's ability.");
const u8 gMoveDescription_Wish[] = _("A self-healing move\nthat restores half\nthe full HP on the\nnext turn.");
const u8 gMoveDescription_Assist[] = _("The user randomly picks and uses a\nmove of an allied DAEMON.");
const u8 gMoveDescription_Ingrain[] = _("The user lays roots\nthat restore HP on\nevery turn.\nIt can't switch out.");
const u8 gMoveDescription_Superpower[] = _("A powerful attack,\nbut it also lowers\nthe user's ATTACK\nand DEFENSE stats.");
const u8 gMoveDescription_MagicCoat[] = _("Reflects back the\nremote's LEECH\nSEED and any\nstatus- damaging\nmove.");
const u8 gMoveDescription_Recycle[] = _("A move that\nrecycles a used\nitem for use once\nmore.");
const u8 gMoveDescription_Revenge[] = _("An attack move that\ngains in intensity if\nthe target has hurt\nthe user.");
const u8 gMoveDescription_BrickBreak[] = _("An attack that also\nbreaks any barrier\nlike LIGHT SCREEN\nand REFLECT.");
const u8 gMoveDescription_Yawn[] = _("A huge yawn lulls\nthe remote into\nfalling asleep on\nthe next turn.");
const u8 gMoveDescription_KnockOff[] = _("Knocks down the\nremote's held item\nto prevent its use\nduring the battle.");
const u8 gMoveDescription_Endeavor[] = _("Gains power the\nfewer HP the user\nhas compared with\nthe remote.");
const u8 gMoveDescription_Eruption[] = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_SkillSwap[] = _("The user employs\nits psychic power\nto swap abilities\nwith the remote.");
const u8 gMoveDescription_Imprison[] = _("Prevents remote\nfrom using any\nmove that is also\nknown by the\nuser.");
const u8 gMoveDescription_Refresh[] = _("A self-healing move\nthat cures the user\nof a poisoning,\nburn, or paralysis.");
const u8 gMoveDescription_Grudge[] = _("If the user HALTS, this move\ndeletes the PP of the move that\nfinished it.");
const u8 gMoveDescription_Snatch[] = _("Steals the effects\nof the remote's\nhealing or status-\nchanging move.");
const u8 gMoveDescription_SecretPower[] = _("An attack that may\nhave an additional\neffect that varies\nwith the terrain.");
const u8 gMoveDescription_Dive[] = _("The user dives\nunderwater on the\nfirst turn and\nstrikes next turn.");
const u8 gMoveDescription_ArmThrust[] = _("A quick flurry of\nstraight-arm\npunches that hit\ntwo to five times.");
const u8 gMoveDescription_Camouflage[] = _("Alters the user's\ntype depending on\nthe location's\nterrain.");
const u8 gMoveDescription_TailGlow[] = _("The user flashes a\nlight that sharply\nraises its SP. ATK\nstat.");
const u8 gMoveDescription_LusterPurge[] = _("A burst of light\ninjures the remote.\nIt may also lower\nthe remote's SP.\nDEF.");
const u8 gMoveDescription_MistBall[] = _("A flurry of down\nhits the remote.\nIt may also lower\nthe remote's SP.\nATK.");
const u8 gMoveDescription_FeatherDance[] = _("The remote is\ncovered with a\nmass of down that\nsharply cuts the\nATTACK stat.");
const u8 gMoveDescription_TeeterDance[] = _("A wobbly dance that confuses all\nthe DAEMON in battle.");
const u8 gMoveDescription_BlazeKick[] = _("A fiery kick with a\nhigh critical-hit\nratio. It may also\nburn the remote.");
const u8 gMoveDescription_MudSport[] = _("Weakens ELECTRIC-\ntype attacks while\nthe user is in the\nbattle.");
const u8 gMoveDescription_IceBall[] = _("A 5-turn rolling\nattack that becomes\nstronger each time\nit rolls.");
const u8 gMoveDescription_NeedleArm[] = _("An attack using\nthorny arms. It\nmay make the\nremote flinch.");
const u8 gMoveDescription_SlackOff[] = _("The user slacks off\nand restores its HP\nby half its full\nHP.");
const u8 gMoveDescription_HyperVoice[] = _("The user lets loose\na horribly loud\nshout with the\npower to damage.");
const u8 gMoveDescription_PoisonFang[] = _("The remote is\nbitten with toxic\nfangs. It may\nalso badly poison\nthe remote.");
const u8 gMoveDescription_CrushClaw[] = _("The remote is\nattacked with sharp\nclaws. It may also\nlower the remote's\nDEFENSE.");
const u8 gMoveDescription_BlastBurn[] = _("The remote is hit\nwith a huge\nexplosion. The\nuser can't move on\nthe next turn.");
const u8 gMoveDescription_HydroCannon[] = _("The remote is hit\nwith a watery\ncannon. The user\ncan't move on the\nnext turn.");
const u8 gMoveDescription_MeteorMash[] = _("The remote is hit\nwith a hard, fast\npunch. It may also\nraise the user's\nATTACK.");
const u8 gMoveDescription_Astonish[] = _("An attack using a\nstartling shout.\nIt also may make\nthe remote\nflinch.");
const u8 gMoveDescription_WeatherBall[] = _("An attack that\nvaries in power and\ntype depending on\nthe weather.");
const u8 gMoveDescription_Aromatherapy[] = _("A soothing scent is\nreleased to heal\nall status problems\nin the user's party.");
const u8 gMoveDescription_FakeTears[] = _("The user feigns\ncrying to sharply\nlower the\nremote's SP. DEF\nstat.");
const u8 gMoveDescription_AirCutter[] = _("The remote is hit\nwith razor-like\nwind. It has a\nhigh critical-hit\nratio.");
const u8 gMoveDescription_Overheat[] = _("An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.");
const u8 gMoveDescription_OdorSleuth[] = _("Completely negates\nthe remote's efforts\nto heighten its\nability to evade.");
const u8 gMoveDescription_RockTomb[] = _("Boulders are hurled\nat the remote. It\nalso lowers the\nremote's SPEED if it\nhits.");
const u8 gMoveDescription_SilverWind[] = _("The remote is\nattacked with a\nsilver dust. It may\nraise all the user's\nstats.");
const u8 gMoveDescription_MetalSound[] = _("A horrible metallic\nscreech is used to\nsharply lower the\nremote's SP. DEF.");
const u8 gMoveDescription_GrassWhistle[] = _("A pleasant melody\nis played to lull\nthe remote into a\ndeep sleep.");
const u8 gMoveDescription_Tickle[] = _("The remote is made\nto laugh, reducing\nits ATTACK and\nDEFENSE stats.");
const u8 gMoveDescription_CosmicPower[] = _("The user absorbs a\nmystic power to\nraise its DEFENSE\nand SP. DEF.");
const u8 gMoveDescription_WaterSpout[] = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_SignalBeam[] = _("The remote is hit\nwith a flashing\nbeam that may also\ncause confusion.");
const u8 gMoveDescription_ShadowPunch[] = _("The user throws a\npunch from the\nshadows. It cannot\nbe evaded.");
const u8 gMoveDescription_Extrasensory[] = _("The user attacks\nwith an odd power\nthat may make the\nremote flinch.");
const u8 gMoveDescription_SkyUppercut[] = _("The user attacks\nwith an uppercut\nthrown skywards\nwith force.");
const u8 gMoveDescription_SandTomb[] = _("The remote is\ntrapped inside a\npainful sandstorm\nfor two to five\nturns.");
const u8 gMoveDescription_SheerCold[] = _("The remote is\nattacked with\nultimate cold that\ncauses fainting if\nit hits.");
const u8 gMoveDescription_MuddyWater[] = _("The user attacks\nwith muddy water.\nIt may also lower\nthe remote's\naccuracy.");
const u8 gMoveDescription_BulletSeed[] = _("The user shoots\nseeds at the\nremote. Two to\nfive seeds are\nshot at once.");
const u8 gMoveDescription_AerialAce[] = _("An extremely fast\nattack against one\ntarget. It can't be\nevaded.");
const u8 gMoveDescription_IcicleSpear[] = _("Sharp icicles are\nfired at the\nremote. It\nstrikes two to\nfive times.");
const u8 gMoveDescription_IronDefense[] = _("The user hardens\nits body's surface\nto sharply raise its\nDEFENSE stat.");
const u8 gMoveDescription_Block[] = _("The user blocks the\nremote's way with\narms spread wide to\nprevent escape.");
const u8 gMoveDescription_Howl[] = _("The user howls to\nraise its spirit and\nboost its ATTACK\nstat.");
const u8 gMoveDescription_DragonClaw[] = _("Sharp, huge claws\nhook and slash the\nremote quickly and\nwith great power.");
const u8 gMoveDescription_FrenzyPlant[] = _("The remote is hit\nwith an enormous\nbranch. The user\ncan't move on the\nnext turn.");
const u8 gMoveDescription_BulkUp[] = _("The user bulks up\nits body to boost\nboth its ATTACK and\nDEFENSE stats.");
const u8 gMoveDescription_Bounce[] = _("The user bounces\non the remote on\nthe 2nd turn. It\nmay paralyze the\nremote.");
const u8 gMoveDescription_MudShot[] = _("The user attacks by\nhurling mud. It\nalso reduces the\nremote's SPEED.");
const u8 gMoveDescription_PoisonTail[] = _("An attack with a\nhigh critical-hit\nratio. It may also\npoison the remote.");
const u8 gMoveDescription_Covet[] = _("A cutely executed\nattack that also\nsteals the\nremote's hold\nitem.");
const u8 gMoveDescription_VoltTackle[] = _("The user throws an\nelectrified tackle.\nIt hurts the user\na little.");
const u8 gMoveDescription_MagicalLeaf[] = _("The remote is\nattacked with a\nstrange leaf that\ncannot be evaded.");
const u8 gMoveDescription_WaterSport[] = _("Weakens FIRE-type\nattacks while the\nuser is in the\nbattle.");
const u8 gMoveDescription_CalmMind[] = _("The user focuses\nits mind to raise\nthe SP. ATK and\nSP. DEF stats.");
const u8 gMoveDescription_LeafBlade[] = _("The remote is\nslashed with a\nsharp leaf. It has\na high\ncritical-hit ratio.");
const u8 gMoveDescription_DragonDance[] = _("A mystic, powerful\ndance that boosts\nthe user's ATTACK\nand SPEED stats.");
const u8 gMoveDescription_RockBlast[] = _("The user hurls two\nto five hard rocks\nat the remote to\nattack.");
const u8 gMoveDescription_ShockWave[] = _("A rapid jolt of\nelectricity strikes\nthe remote. It\ncan't be evaded.");
const u8 gMoveDescription_WaterPulse[] = _("An attack with a\npulsing blast of\nwater. It may also\nconfuse the\nremote.");
const u8 gMoveDescription_DoomDesire[] = _("A move that attacks\nthe remote with a\nblast of light two\nturns after use.");
const u8 gMoveDescription_PsychoBoost[] = _("An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_PSYCHIC       - 1] = gMoveDescription_Psychic,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
};
