#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("Pushes onto them,\nbluntly and\nrepeatedly.");
const u8 gMoveDescription_KarateChop[] = _("A problem cut\ndown to a smaller\none. High\ncritical-hit ratio.");
const u8 gMoveDescription_DoubleSlap[] = _("The same write, sent\nagain and again --\ntwo to five times\nbefore it stops.");
const u8 gMoveDescription_CometPunch[] = _("Hits them with a\nflurry of punches,\ntwo to five times.");
const u8 gMoveDescription_MegaPunch[] = _("Everything at once,\nand very hard to\nundo.");
const u8 gMoveDescription_PayDay[] = _("Value is struck off\nwhile it attacks.\nIt is collected\nafter the battle.");
const u8 gMoveDescription_FirePunch[] = _("Punches them with a\nfiery fist. It may\nleave them\noverheating.");
const u8 gMoveDescription_IcePunch[] = _("Holds the weights\nwhere they are. May\nleave them HUNG.");
const u8 gMoveDescription_ThunderPunch[] = _("Punches them with an\nelectrified fist. It\nmay leave them\nthrottled.");
const u8 gMoveDescription_Scratch[] = _("The smallest change\nthere is. One bit,\nturned over.");
const u8 gMoveDescription_ViceGrip[] = _("Huge, impressive\npincers grip and\nsqueeze them.");
const u8 gMoveDescription_Guillotine[] = _("A vicious tearing\nattack with pincers.\nThey HALT if it\nhits.");
const u8 gMoveDescription_RazorWind[] = _("Blades of wind hit\nthem on the 2nd\nturn. It has a high\ncritical-hit ratio.");
const u8 gMoveDescription_SwordsDance[] = _("The user cycles\nhard before it does\nanything. Sharply\nraises ATTACK.");
const u8 gMoveDescription_Cut[] = _("Cuts a branch off.\nPrunes thin trees\nand grass outside\nof battle.");
const u8 gMoveDescription_Gust[] = _("A small\npush off\nthe heading\nit was on.");
const u8 gMoveDescription_WingAttack[] = _("Sends the\nwhole thing to\nwhere it was\naddressed.");
const u8 gMoveDescription_Whirlwind[] = _("Forces them out and\nan ally in. In the\nwild, the battle\nends.");
const u8 gMoveDescription_Fly[] = _("Transfers control to\na CHECKPOINT\nalready reached.\nAttacks next turn.");
const u8 gMoveDescription_Bind[] = _("Holds them in place\nfor two to five\nturns.");
const u8 gMoveDescription_Slam[] = _("Replaces wholesale\nrather than in\npart. Often misses.");
const u8 gMoveDescription_VineWhip[] = _("The error\ntravels back\nthe way it\ncame in.");
const u8 gMoveDescription_Stomp[] = _("Stomps them with a\nbig foot. They may\nflinch.");
const u8 gMoveDescription_DoubleKick[] = _("One step, then the\nstep it licenses.\nStrikes twice.");
const u8 gMoveDescription_MegaKick[] = _("A whole block at\nonce, and not\ncarefully.");
const u8 gMoveDescription_JumpKick[] = _("A jump to\nsomewhere far off.\nA miss costs the\nuser part of itself.");
const u8 gMoveDescription_RollingKick[] = _("A quick kick from a\nrolling spin. It may\nmake them flinch.");
const u8 gMoveDescription_SandAttack[] = _("Fine grit works into\nthe substrate. Cuts\naccuracy.");
const u8 gMoveDescription_Headbutt[] = _("Two things arrive at\nonce. It may leave\nthem unable to act.");
const u8 gMoveDescription_HornAttack[] = _("A single pointed\nwrite, driven in\nwhere it fits.");
const u8 gMoveDescription_FuryAttack[] = _("Jabs them with a\nhorn or beak, two to\nfive times.");
const u8 gMoveDescription_HornDrill[] = _("Removes the record\nentirely. It only\nlands once.");
const u8 gMoveDescription_Tackle[] = _("Puts its own data\nwhere their data\nwas.");
const u8 gMoveDescription_BodySlam[] = _("Writes a whole block\nat once. May leave\nthem THROTTLED.");
const u8 gMoveDescription_Wrap[] = _("Closes around them\nand holds them\nthere for two to\nfive turns.");
const u8 gMoveDescription_TakeDown[] = _("Pushes through at\nany cost. Some of\nthe damage lands\non the user.");
const u8 gMoveDescription_Thrash[] = _("A loop that will not\nyield. Runs for two\nor three turns and\nends THRASHING.");
const u8 gMoveDescription_DoubleEdge[] = _("Everything at once,\nnothing held back.\nThe user takes a\nshare of it.");
const u8 gMoveDescription_TailWhip[] = _("Leaves them open\nwhere they were\nnot. Lowers\nDEFENSE.");
const u8 gMoveDescription_PoisonSting[] = _("Leaves the data no\nlonger trustworthy.\nMay cause LEAKING.");
const u8 gMoveDescription_Twineedle[] = _("The same strike run\ntwice over. It may\nleave them LEAKING.");
const u8 gMoveDescription_PinMissile[] = _("Sharp pins are shot\nat them and hit two\nto five times at\nonce.");
const u8 gMoveDescription_Leer[] = _("Looks until it finds\nthe weak place.\nLowers DEFENSE.");
const u8 gMoveDescription_Bite[] = _("Shuts the light out.\nThey may flinch.");
const u8 gMoveDescription_Growl[] = _("Runs them below\ntheir rated\ncapacity. Lowers\nATTACK.");
const u8 gMoveDescription_Roar[] = _("Forces them out and\nan ally in. In the\nwild, the battle\nends.");
const u8 gMoveDescription_Sing[] = _("A soothing song in a\ncalming voice lulls\nthem into a deep\nslumber.");
const u8 gMoveDescription_Supersonic[] = _("The user generates\nodd sound waves. It\nmay thrash them.");
const u8 gMoveDescription_SonicBoom[] = _("Always 20 HP.\nNothing about them\nchanges what it\ncosts.");
const u8 gMoveDescription_Disable[] = _("For a few turns, it\nstops them using the\nroutine they last\nran.");
const u8 gMoveDescription_Acid[] = _("Eats into what it\ntouches. May lower\nSP. DEF.");
const u8 gMoveDescription_Ember[] = _("Attacks them with\nsmall flames. They\nmay overheat.");
const u8 gMoveDescription_Flamethrower[] = _("Scorches them with\nintense flames. They\nmay overheat.");
const u8 gMoveDescription_Mist[] = _("Nothing may write\nto the party's\nstats for as long\nas it holds.");
const u8 gMoveDescription_WaterGun[] = _("A thin\nsteady run\nof water\ndownhill.");
const u8 gMoveDescription_HydroPump[] = _("A high volume of\nwater is blasted at\nthem under great\npressure.");
const u8 gMoveDescription_Surf[] = _("Crosses the surface\nrather than going\nalong it. Used for\ntravelling on water.");
const u8 gMoveDescription_IceBeam[] = _("Stops the weights\nupdating. They may\nend up HUNG.");
const u8 gMoveDescription_Blizzard[] = _("Everything stops\nupdating at once.\nMay leave them\nHUNG.");
const u8 gMoveDescription_Psybeam[] = _("A peculiar ray is\nshot at them. It\nmay leave them\nthrashing.");
const u8 gMoveDescription_BubbleBeam[] = _("A spray of bubbles\nstrikes them. It may\nlower their SPEED\nstat.");
const u8 gMoveDescription_AuroraBeam[] = _("Narrows what they\nare allowed to do.\nLowers ATTACK.");
const u8 gMoveDescription_HyperBeam[] = _("Commits everything\nin one write. The\nuser must idle on\nthe next turn.");
const u8 gMoveDescription_Peck[] = _("Jabs them with a\nsharply pointed beak\nor horn.");
const u8 gMoveDescription_DrillPeck[] = _("Bores\nstraight\nthrough on\none heading.");
const u8 gMoveDescription_Submission[] = _("Throws the whole\nargument at them\nand takes some of it\nback.");
const u8 gMoveDescription_LowKick[] = _("Weighs them first.\nThe heavier it is,\nthe harder this\nlands.");
const u8 gMoveDescription_Counter[] = _("Returns the\nclaim to whoever\nmade it, twice\nas hard.");
const u8 gMoveDescription_SeismicToss[] = _("Sets the cost equal\nto the user's own\nlevel, exactly.");
const u8 gMoveDescription_Strength[] = _("Pushes a thing out\nof the place it was\nin. Moves large\nboulders.");
const u8 gMoveDescription_Absorb[] = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_MegaDrain[] = _("A tough attack that\ndrains half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_LeechSeed[] = _("Seeded on them. It\ngives up a little\nevery turn.");
const u8 gMoveDescription_Growth[] = _("Scaling up gives\none instance more,\nnot more instances.\nRaises SP. ATK.");
const u8 gMoveDescription_RazorLeaf[] = _("Splits it clean\nalong the grain.\nHigh critical-hit\nratio.");
const u8 gMoveDescription_SolarBeam[] = _("Gathers on the\nfirst turn, then\nruns it all at once\non the second.");
const u8 gMoveDescription_PoisonPowder[] = _("Mixes something bad\ninto what they are\nrunning. It may\nleave them LEAKING.");
const u8 gMoveDescription_StunSpore[] = _("Throttling dust is\nscattered wildly. It\nmay throttle them.");
const u8 gMoveDescription_SleepPowder[] = _("A suspension-inducing\ndust is scattered in\nhigh volume around\nthem.");
const u8 gMoveDescription_PetalDance[] = _("Trains on one thing\nfor two or three\nturns, then ends\nTHRASHING.");
const u8 gMoveDescription_StringShot[] = _("Their work piles up\nbehind them. Lowers\nSPEED.");
const u8 gMoveDescription_DragonRage[] = _("Always 40 HP. The\nsame every time,\nwhatever it is\nrun against.");
const u8 gMoveDescription_FireSpin[] = _("Heat it cannot get\nout of, for two to\nfive turns.");
const u8 gMoveDescription_ThunderShock[] = _("An electric shock\nattack that may also\nleave them\nthrottled.");
const u8 gMoveDescription_Thunderbolt[] = _("A strong electrical\nattack that may also\nleave them\nthrottled.");
const u8 gMoveDescription_ThunderWave[] = _("A weak electric\nshock that is sure\nto cause throttling\nif it hits.");
const u8 gMoveDescription_Thunder[] = _("A brutal lightning\nattack that may also\nleave them\nthrottled.");
const u8 gMoveDescription_RockThrow[] = _("Moves the bits over\nby one and lets go.");
const u8 gMoveDescription_Earthquake[] = _("The ground\neverything stands\non moves. Hits\nall around it.");
const u8 gMoveDescription_Fissure[] = _("Drops them into a\nfissure. They HALT\nif it hits.");
const u8 gMoveDescription_Dig[] = _("Goes under, and is\nup again next turn.\nOutside, it digs a\ncave.");
const u8 gMoveDescription_Toxic[] = _("Leaves them\nCASCADING, and the\nloss grows with\nevery turn.");
const u8 gMoveDescription_Confusion[] = _("A weak telekinetic\nattack that may also\nleave them\nthrashing.");
const u8 gMoveDescription_Psychic[] = _("Reads them in its\nown way. It may\nlower their SP. DEF.");
const u8 gMoveDescription_Hypnosis[] = _("Hypnotic suggestion\nis used to make them\nfall into a deep\nsuspension.");
const u8 gMoveDescription_Meditate[] = _("The user reads\nitself until it\nfinds more. Raises\nATTACK.");
const u8 gMoveDescription_Agility[] = _("Puts down what it\nwas carrying to\nmove. Sharply\nraises SPEED.");
const u8 gMoveDescription_QuickAttack[] = _("Takes the short\nroute and\narrives first,\nevery time.");
const u8 gMoveDescription_Rage[] = _("An attack that\nbecomes stronger\neach time the user\nis hit in battle.");
const u8 gMoveDescription_Teleport[] = _("DETACHES from a\nwild DAEMON. Also\nwarps to the last\nCHECKPOINT.");
const u8 gMoveDescription_NightShade[] = _("Costs them what the\nuser's level is\nworth, and nothing\nelse.");
const u8 gMoveDescription_Mimic[] = _("The user copies the\nroutine last run by\nthem, for the rest\nof the battle.");
const u8 gMoveDescription_Screech[] = _("Strips them of what\nwas guarding them.\nSharply cuts\nDEFENSE.");
const u8 gMoveDescription_DoubleTeam[] = _("More than one of it\nis running at once.\nRaises evasiveness.");
const u8 gMoveDescription_Recover[] = _("Loads the last\ngood state: up\nto half of the\nuser's maximum HP.");
const u8 gMoveDescription_Harden[] = _("Pinned in place,\nso nothing can\nshift it. Raises\nDEFENSE.");
const u8 gMoveDescription_Minimize[] = _("Takes up less room,\nso less of it can\nbe hit. Raises\nevasiveness.");
const u8 gMoveDescription_Smokescreen[] = _("Blurs what they are\naiming at. Reduces\naccuracy.");
const u8 gMoveDescription_ConfuseRay[] = _("A sinister ray that\nleaves them\nTHRASHING.");
const u8 gMoveDescription_Withdraw[] = _("Finds the still\npocket in the\ncurrent. Raises\nDEFENSE.");
const u8 gMoveDescription_DefenseCurl[] = _("Packs itself\nsmaller, so\nless of it can\nbe reached.");
const u8 gMoveDescription_Barrier[] = _("Puts something\nround itself that\nholds. Sharply\nraises DEFENSE.");
const u8 gMoveDescription_LightScreen[] = _("Reads every\nincoming claim in\nits strongest form,\nfor five turns.");
const u8 gMoveDescription_Haze[] = _("Eliminates all\nstat changes\namong all DAEMONS\nengaged in battle.");
const u8 gMoveDescription_Reflect[] = _("Says it again in\nweaker terms. Cuts\nphysical damage\nfor five turns.");
const u8 gMoveDescription_FocusEnergy[] = _("Reads ahead, so\nwhat comes next\nlands better. Raises\ncritical hits.");
const u8 gMoveDescription_Bide[] = _("The user endures\nattacks for two\nturns, then strikes\nback double.");
const u8 gMoveDescription_Metronome[] = _("Runs a routine at\nrandom, and it may\nbe any routine at\nall.");
const u8 gMoveDescription_MirrorMove[] = _("Sends their own\nheading back at\nthem.");
const u8 gMoveDescription_SelfDestruct[] = _("The user blows up\nto inflict severe\ndamage, even\nmaking itself HALT.");
const u8 gMoveDescription_EggBomb[] = _("A large egg is\nhurled with great\nforce at them to\ninflict damage.");
const u8 gMoveDescription_Lick[] = _("Licks them with a\nlong tongue. It may\nalso throttle.");
const u8 gMoveDescription_Smog[] = _("Fills what them runs\non with rubbish. It\nmay leave it\nLEAKING.");
const u8 gMoveDescription_Sludge[] = _("What was left over,\nthrown. May cause\nLEAKING.");
const u8 gMoveDescription_BoneClub[] = _("A fault it cannot\nread past. It may\nleave them unable\nto act.");
const u8 gMoveDescription_FireBlast[] = _("Hits them with an\nintense flame. It\nmay leave them\noverheating.");
const u8 gMoveDescription_Waterfall[] = _("Goes up what was\nrunning down.\nClimbs a waterfall.");
const u8 gMoveDescription_Clamp[] = _("Shuts the channel\nfor two to five\nturns.");
const u8 gMoveDescription_Swift[] = _("Star-shaped rays\nthat never miss are\nfired at all of\nthem.");
const u8 gMoveDescription_SkullBash[] = _("The user raises its\nDEFENSE in the 1st\nturn, then attacks\nin the 2nd turn.");
const u8 gMoveDescription_SpikeCannon[] = _("Two to five\nof them,\none after\nanother.");
const u8 gMoveDescription_Constrict[] = _("Holds them tight\nenough to slow\nthem. It may lower\nSPEED.");
const u8 gMoveDescription_Amnesia[] = _("Forgets about\nsomething and\nsharply raises\nSP. DEF.");
const u8 gMoveDescription_Kinesis[] = _("Puts something else\nin front of them. It\nmay lower their\naccuracy.");
const u8 gMoveDescription_SoftBoiled[] = _("Puts back up to\nhalf of the user's\nHP. Can be spent\non an ally instead.");
const u8 gMoveDescription_HiJumpKick[] = _("A longer jump, and\na harder landing.\nA miss costs the\nuser for it.");
const u8 gMoveDescription_Glare[] = _("Intimidates them\nwith the design on\nits belly. It may\nthrottle.");
const u8 gMoveDescription_DreamEater[] = _("Reads them while\nSUSPENDED, and\nkeeps half of what\nit takes.");
const u8 gMoveDescription_PoisonGas[] = _("Opens something in\nthem that will not\nclose. It may leave\nit LEAKING.");
const u8 gMoveDescription_Barrage[] = _("Round objects are\nhurled at them to\nstrike two to five\ntimes.");
const u8 gMoveDescription_LeechLife[] = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_LovelyKiss[] = _("A forced kiss, with\na face odd enough\nto induce\nsuspension.");
const u8 gMoveDescription_SkyAttack[] = _("Rises on the first\nturn and comes down\non the second.");
const u8 gMoveDescription_Transform[] = _("Takes their own\npoint of view, down\nto its ROUTINES.");
const u8 gMoveDescription_Bubble[] = _("Water seeps in\nwhere it was\nnot wanted. May\nlower SPEED.");
const u8 gMoveDescription_DizzyPunch[] = _("A rhythmic punch\nthat may leave them\nTHRASHING.");
const u8 gMoveDescription_Spore[] = _("The user scatters\nbursts of fine\nspores that induce\nsuspension.");
const u8 gMoveDescription_Flash[] = _("Turns on the output\nnobody could see.\nLights dark caves,\nand blinds them.");
const u8 gMoveDescription_Psywave[] = _("The cost is drawn\nafresh each time,\nand it is never\nthe same twice.");
const u8 gMoveDescription_Splash[] = _("Does nothing\nat all. It has\nnever done\nanything.");
const u8 gMoveDescription_AcidArmor[] = _("The user makes its\nown surface\nunreactive. Sharply\nraises DEFENSE.");
const u8 gMoveDescription_Crabhammer[] = _("Brings the whole\nweight down in one\nplace. High\ncritical-hit rate.");
const u8 gMoveDescription_Explosion[] = _("Writes out all it\nhas at once, and is\nHALTED by doing it.");
const u8 gMoveDescription_FurySwipes[] = _("Rakes them with\nclaws or scythes,\ntwo to five times.");
const u8 gMoveDescription_Bonemerang[] = _("One pass down and\none back up. It\nhits on both.");
const u8 gMoveDescription_Rest[] = _("Goes SUSPENDED for\ntwo turns, and\ncomes back whole.");
const u8 gMoveDescription_RockSlide[] = _("Brings down what was\nheld up above. It\nmay leave them\nunable to act.");
const u8 gMoveDescription_HyperFang[] = _("Attacks them with\nsharp fangs. They\nmay flinch.");
const u8 gMoveDescription_Sharpen[] = _("Folded in\nwhere it is\nused. Raises\nATTACK.");
const u8 gMoveDescription_Conversion[] = _("The user changes\nits type to match\nthe type of one\nof its routines.");
const u8 gMoveDescription_TriAttack[] = _("Three at once,\nand any one of\nthem may leave\na state behind.");
const u8 gMoveDescription_SuperFang[] = _("Cuts them down to\nhalf of what they\nhad.");
const u8 gMoveDescription_Slash[] = _("Joined at the cut.\nHigh critical-hit\nratio.");
const u8 gMoveDescription_Substitute[] = _("The user creates a\ndecoy using one-\nquarter of its full\nHP.");
const u8 gMoveDescription_Struggle[] = _("An attack that is\nused only if there\nis no MP. It also\nhurts the user.");
const u8 gMoveDescription_Sketch[] = _("Copies the routine\nthey last ran, and\nis spent doing it.");
const u8 gMoveDescription_TripleKick[] = _("Three steps, each\nworth more than the\none before it.");
const u8 gMoveDescription_Thief[] = _("An attack that may\ntake their held item\nif the user isn't\nholding one.");
const u8 gMoveDescription_SpiderWeb[] = _("Ensnares them in\nsticky string, so\nthey cannot DETACH\nor switch out.");
const u8 gMoveDescription_MindReader[] = _("The user predicts\ntheir action to\nensure its next\nattack hits.");
const u8 gMoveDescription_Nightmare[] = _("Suspended, they get\nnothing at all. They\nlose HP each turn.");
const u8 gMoveDescription_FlameWheel[] = _("The user makes a\nfiery charge at\nthem. It may cause\noverheating.");
const u8 gMoveDescription_Snore[] = _("An attack that can\nbe used only while\nsuspended. It may\ncause flinching.");
const u8 gMoveDescription_Curse[] = _("Works one way for\nLATENT, and\nanother way for\nevery other type.");
const u8 gMoveDescription_Flail[] = _("The less there is\nleft of it, the\nharder it works.");
const u8 gMoveDescription_Conversion2[] = _("The user changes\ntype to make itself\nresistant to the\nlast attack it took.");
const u8 gMoveDescription_Aeroblast[] = _("A vortex of air is\nshot at them. It has\na high critical-hit\nratio.");
const u8 gMoveDescription_CottonSpore[] = _("Fills their path with\nwhat they cannot\nclear. Sharply\nlowers SPEED.");
const u8 gMoveDescription_Reversal[] = _("Follows it all the\nway to the end.\nHardest when the\nuser has least.");
const u8 gMoveDescription_Spite[] = _("Cuts 2 to 5 MP from\nthe routine them\nlast ran.");
const u8 gMoveDescription_PowderSnow[] = _("Old data, no longer\nupdating. May leave\nthem HUNG.");
const u8 gMoveDescription_Protect[] = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_MachPunch[] = _("A small step, taken\nfirst. Always goes\nbefore the others.");
const u8 gMoveDescription_ScaryFace[] = _("Lowers their\npriority, so they\nare scheduled later.");
const u8 gMoveDescription_FaintAttack[] = _("Arrives from where\nthey were not\nlooking. It does not\nmiss.");
const u8 gMoveDescription_SweetKiss[] = _("Two things swapped\nwhere it will not\nbe noticed. Causes\nTHRASHING.");
const u8 gMoveDescription_BellyDrum[] = _("The user maximizes\nits ATTACK stat at\nthe cost of half\nits full HP.");
const u8 gMoveDescription_SludgeBomb[] = _("Everything\nunwanted, all\nat once. May\ncause LEAKING.");
const u8 gMoveDescription_MudSlap[] = _("Covers what they\nread from. Damages\nthem, and lowers\ntheir accuracy.");
const u8 gMoveDescription_Octazooka[] = _("More at once than\nthey can take in.\nLowers accuracy.");
const u8 gMoveDescription_Spikes[] = _("Left where them\nmust come in. Hurts\nwhatever arrives.");
const u8 gMoveDescription_ZapCannon[] = _("Far more current\nthan the line can\ntake. May leave\nit THROTTLED.");
const u8 gMoveDescription_Foresight[] = _("Completely negates\ntheir efforts to\nheighten its ability\nto evade.");
const u8 gMoveDescription_DestinyBond[] = _("If the user HALTS,\nthem delivering the\nfinal hit also\nHALTS.");
const u8 gMoveDescription_PerishSong[] = _("Any battler that\nhears this HALTS\nin three turns\nunless it switches.");
const u8 gMoveDescription_IcyWind[] = _("Cools it until it is\nslow. Lowers SPEED.");
const u8 gMoveDescription_Detect[] = _("The check holds\nand nothing gets\npast. It may fail\nif it is run again.");
const u8 gMoveDescription_BoneRush[] = _("The user strikes\nthem with a bone in\nhand two to five\ntimes.");
const u8 gMoveDescription_LockOn[] = _("The user locks on to\nthem, so the next\nroutine is sure to\nhit.");
const u8 gMoveDescription_Outrage[] = _("The user thrashes\nabout for two to\nthree turns, then\nbecomes thrashing.");
const u8 gMoveDescription_Sandstorm[] = _("Everything\ndegrades a little\neach turn. Some\ntypes resist.");
const u8 gMoveDescription_GigaDrain[] = _("A harsh attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_Endure[] = _("Comes through\nit with one\npoint left,\nthis turn only.");
const u8 gMoveDescription_Charm[] = _("Cuts their clock\nhard. Sharply\nreduces ATTACK.");
const u8 gMoveDescription_Rollout[] = _("Comes round\nfor five turns,\nheavier on\nevery pass.");
const u8 gMoveDescription_FalseSwipe[] = _("A restrained attack\nthat always leaves\nthem with at least 1\nHP.");
const u8 gMoveDescription_Swagger[] = _("Leaves them\nTHRASHING, but\nsharply raises their\nATTACK.");
const u8 gMoveDescription_MilkDrink[] = _("Tops the user back\nup by half. Can be\nspent on an ally\ninstead.");
const u8 gMoveDescription_Spark[] = _("An electrically\ncharged tackle that\nmay also throttle\nthem.");
const u8 gMoveDescription_FuryCutter[] = _("An attack that\ngrows stronger on\neach successive\nhit.");
const u8 gMoveDescription_SteelWing[] = _("A layer over\nthe top. May\nraise\nDEFENSE.");
const u8 gMoveDescription_MeanLook[] = _("Holds the connection\nopen. They cannot\nleave.");
const u8 gMoveDescription_Attract[] = _("Binds their attention\nto the user, which\nmay leave them\nunable to act.");
const u8 gMoveDescription_SleepTalk[] = _("While SUSPENDED,\nthe user runs one\nof its own routines\nat random.");
const u8 gMoveDescription_HealBell[] = _("A soothing bell\nchimes to heal the\nstatus problems of\nall allies.");
const u8 gMoveDescription_Return[] = _("This attack move\ngrows more powerful\nthe more the user\nlikes its USER.");
const u8 gMoveDescription_Present[] = _("Gives them a\nbooby-trapped gift.\nIt restores HP\nsometimes.");
const u8 gMoveDescription_Frustration[] = _("This attack move\ngrows more powerful\nthe less the user\nlikes its USER.");
const u8 gMoveDescription_Safeguard[] = _("It protects the\nuser's party from\nall status problems\nfor five turns.");
const u8 gMoveDescription_PainSplit[] = _("The user adds its HP\nto their HP, then\nequally shares the\ntotal HP.");
const u8 gMoveDescription_SacredFire[] = _("A mystical and\npowerful fire\nattack that may\ncause overheating.");
const u8 gMoveDescription_Magnitude[] = _("A ground-shaking\nattack against all\nstanding DAEMON.\nIts power varies.");
const u8 gMoveDescription_DynamicPunch[] = _("The user's full power\nin one punch. Leaves\nthem THRASHING if it\nhits.");
const u8 gMoveDescription_Megahorn[] = _("Many at once, all\ngoing one way.\nNothing in front\nof it stays there.");
const u8 gMoveDescription_DragonBreath[] = _("An incredible blast\nof breath. It may\nalso throttle them.");
const u8 gMoveDescription_BatonPass[] = _("Hands\neverything over\nto the one that\ncomes in next.");
const u8 gMoveDescription_Encore[] = _("Holds them to the\nroutine they last\nran, for two to six\nturns.");
const u8 gMoveDescription_Pursuit[] = _("A routine that works\nespecially well on\nthem that is\nswitching out.");
const u8 gMoveDescription_RapidSpin[] = _("Frees the user from\nLATCH, ENCLOSE,\nSEED and TRIPWIRE\nas it hits.");
const u8 gMoveDescription_SweetScent[] = _("Announces itself so\nit is easy to find.\nCuts evasiveness.");
const u8 gMoveDescription_IronTail[] = _("Load applied over\nand over until the\narmour gives. Their\nDEFENSE may drop.");
const u8 gMoveDescription_MetalClaw[] = _("Worked until\nit holds its\nedge. May\nraise ATTACK.");
const u8 gMoveDescription_VitalThrow[] = _("Makes the user\nattack after them.\nIn return, it will\nnot miss.");
const u8 gMoveDescription_MorningSun[] = _("Comes back up\nwithout a full\nrestart. The weather\nsays how much.");
const u8 gMoveDescription_Synthesis[] = _("Puts back what was\nlost, at the rate\nthe weather allows.");
const u8 gMoveDescription_Moonlight[] = _("Repairs while little\nelse is running.\nThe weather says\nhow much.");
//  Vanilla says "depending on the user", which is true and says nothing. Ours
//  names the mechanic without naming the thesis (craft rule 1): what varies is
//  something the user was made with, and no screen in the game will show it.
const u8 gMoveDescription_HiddenPower[] = _("Its type and force\nare set by traits\nthe user was made\nwith, never shown.");
const u8 gMoveDescription_CrossChop[] = _("The step that\ncloses the\nargument. High\ncritical-hit ratio.");
const u8 gMoveDescription_Twister[] = _("Pulls everything in\ntoward one point.\nThey may flinch.");
const u8 gMoveDescription_RainDance[] = _("Everything\nruns wetter\nfor five\nturns.");
const u8 gMoveDescription_SunnyDay[] = _("Runs everything hot\nfor five turns.");
const u8 gMoveDescription_Crunch[] = _("Crunches them with\nsharp fangs. It may\nlower their SP. DEF.");
const u8 gMoveDescription_MirrorCoat[] = _("Pays a special\nattack back double,\nto whatever ran it.");
const u8 gMoveDescription_PsychUp[] = _("Takes their changed\nstate for its own,\nexactly as it\nstands.");
const u8 gMoveDescription_ExtremeSpeed[] = _("Skips the queue. It\nalways runs before\nanything else.");
const u8 gMoveDescription_AncientPower[] = _("Old, and still\nmaintained. It may\nalso raise all the\nuser's stats.");
const u8 gMoveDescription_ShadowBall[] = _("Something that\nwas not running,\nbriefly. May\nlower SP. DEF.");
const u8 gMoveDescription_FutureSight[] = _("Set now, it runs\ntwo turns later,\nwhatever happens\nbetween.");
const u8 gMoveDescription_RockSmash[] = _("Breaks a hard thing\nopen to see inside.\nCracks split\nboulders.");
const u8 gMoveDescription_Whirlpool[] = _("Traps them in a\nfast, vicious\nwhirlpool for two to\nfive turns.");
const u8 gMoveDescription_BeatUp[] = _("All party DAEMON\njoin in the attack.\nThe more allies,\nthe more damage.");
const u8 gMoveDescription_FakeOut[] = _("Goes first and holds\nthem up. Only on\nthe turn it arrives.");
const u8 gMoveDescription_Uproar[] = _("An uproar that\nblocks suspension\nfor two to five\nturns.");
const u8 gMoveDescription_Stockpile[] = _("The user charges\nup power for use\nlater. It can be\nused three times.");
const u8 gMoveDescription_SpitUp[] = _("Everything ENQUEUE\nheld goes out at\nonce.");
const u8 gMoveDescription_Swallow[] = _("Takes back what\nENQUEUE held, and\nturns it into HP.");
const u8 gMoveDescription_HeatWave[] = _("The user exhales a\nheated breath to\nattack. It may also\ncause overheating.");
const u8 gMoveDescription_Hail[] = _("Small damage\nto all of them,\nevery turn, for\nfive turns.");
const u8 gMoveDescription_Torment[] = _("They cannot run the\nsame routine twice\nin a row.");
const u8 gMoveDescription_Flatter[] = _("Tells them what\nthey want to hear.\nTheir SP. ATK rises,\nthen THRASHING.");
const u8 gMoveDescription_WillOWisp[] = _("A sinister, bluish\nwhite flame is shot\nat them to cause\noverheating.");
const u8 gMoveDescription_Memento[] = _("The user HALTS, but\nsharply lowers their\nATTACK and SP. ATK.");
const u8 gMoveDescription_Facade[] = _("An attack that is\nboosted if user is\noverheated, leaking,\nor throttled.");
const u8 gMoveDescription_FocusPunch[] = _("Runs last, and only\nif nothing has\ninterrupted the\nuser first.");
const u8 gMoveDescription_SmellingSalt[] = _("Doubly effective if\nthey are throttled,\nbut it cures the\nthrottling.");
const u8 gMoveDescription_FollowMe[] = _("The user draws\nattention to itself,\nso they attack only\nthe user.");
const u8 gMoveDescription_NaturePower[] = _("An attack that\nchanges type\ndepending on the\nuser's location.");
const u8 gMoveDescription_Charge[] = _("Holds current\nready. The next\nSIGNAL routine\nhits double.");
const u8 gMoveDescription_Taunt[] = _("They can only\nattack for two\nturns. Nothing else.");
const u8 gMoveDescription_HelpingHand[] = _("Boosts the power of\nan ally's attack\nin a double battle.");
const u8 gMoveDescription_Trick[] = _("Swaps what the two\nare holding, before\nthey can refuse.");
const u8 gMoveDescription_RolePlay[] = _("The user mimics them\ncompletely and\ncopies their ability.");
const u8 gMoveDescription_Wish[] = _("Set now and paid\nnext turn: half of\nthe user's full HP.");
const u8 gMoveDescription_Assist[] = _("The user randomly\npicks and uses a\nmove of an allied\nDAEMON.");
const u8 gMoveDescription_Ingrain[] = _("Fixes itself in\nplace. Gains HP\nevery turn, and\ncannot leave.");
const u8 gMoveDescription_Superpower[] = _("A powerful attack,\nbut it also lowers\nthe user's ATTACK\nand DEFENSE stats.");
const u8 gMoveDescription_MagicCoat[] = _("Reflects back their\nSEED and any\nstatus- damaging\nmove.");
const u8 gMoveDescription_Recycle[] = _("A move that\nrecycles a used\nitem for use once\nmore.");
const u8 gMoveDescription_Revenge[] = _("Answers what was\njust done to the\nuser, and lands\nharder for it.");
const u8 gMoveDescription_BrickBreak[] = _("An attack that also\nbreaks any barrier\nlike STEELMAN and\nPARAPHRASE.");
const u8 gMoveDescription_Yawn[] = _("Puts them on the\nqueue to be\nSUSPENDED one turn\nfrom now.");
const u8 gMoveDescription_KnockOff[] = _("Knocks down their\nheld item to prevent\nits use during the\nbattle.");
const u8 gMoveDescription_Endeavor[] = _("Gains power the\nfewer HP the user\nhas compared with\nthem.");
const u8 gMoveDescription_Eruption[] = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_SkillSwap[] = _("Each takes\nthe other's\nway of\nworking.");
const u8 gMoveDescription_Imprison[] = _("Stops them using any\nroutine the user\nalso knows.");
const u8 gMoveDescription_Refresh[] = _("Clears a leak, an\noverheat or a\nthrottle from the\nuser.");
const u8 gMoveDescription_Grudge[] = _("If the user HALTS,\nthis move deletes\nthe MP of the move\nthat finished it.");
const u8 gMoveDescription_Snatch[] = _("Takes their repair\nor state change for\nitself instead.");
const u8 gMoveDescription_SecretPower[] = _("An attack that may\nhave an additional\neffect that varies\nwith the terrain.");
const u8 gMoveDescription_Dive[] = _("Goes under the\nsurface for a turn,\nthen strikes.\nUsed for diving.");
const u8 gMoveDescription_ArmThrust[] = _("A quick flurry of\nstraight-arm\npunches that hit\ntwo to five times.");
const u8 gMoveDescription_Camouflage[] = _("Alters the user's\ntype depending on\nthe location's\nterrain.");
const u8 gMoveDescription_TailGlow[] = _("The user flashes a\nlight that sharply\nraises its SP. ATK\nstat.");
const u8 gMoveDescription_LusterPurge[] = _("A burst of light\ninjures them. It may\nalso lower their SP.\nDEF.");
const u8 gMoveDescription_MistBall[] = _("A flurry of down\nhits them. It may\nalso lower their SP.\nATK.");
const u8 gMoveDescription_FeatherDance[] = _("Fills the air around\nthem. Sharply lowers\nATTACK.");
const u8 gMoveDescription_TeeterDance[] = _("A wobbly dance\nthat thrashes\nall the DAEMON\nin battle.");
const u8 gMoveDescription_BlazeKick[] = _("A fiery kick with a\nhigh critical-hit\nratio. It may also\noverheating them.");
const u8 gMoveDescription_MudSport[] = _("Takes the charge\nto earth. SIGNAL\nroutines are\nhalved.");
const u8 gMoveDescription_IceBall[] = _("A 5-turn rolling\nattack that becomes\nstronger each time\nit rolls.");
const u8 gMoveDescription_NeedleArm[] = _("An attack using\nthorny arms. It may\nmake them flinch.");
const u8 gMoveDescription_SlackOff[] = _("The user slacks off\nand restores its HP\nby half its full\nHP.");
const u8 gMoveDescription_HyperVoice[] = _("Outputs, loudly, at\nwhatever happens\nto be listening.");
const u8 gMoveDescription_PoisonFang[] = _("A tampering that\ngets worse. May\nleave them\nCASCADING.");
const u8 gMoveDescription_CrushClaw[] = _("Attacks them with\nsharp claws. It may\nlower their DEFENSE.");
const u8 gMoveDescription_BlastBurn[] = _("Hits them with a\nhuge explosion. The\nuser can't move next\nturn.");
const u8 gMoveDescription_HydroCannon[] = _("Hits them with a\nwatery cannon. The\nuser can't move next\nturn.");
const u8 gMoveDescription_MeteorMash[] = _("States it plainly,\nand hard. It may\nraise the user's\nATTACK.");
const u8 gMoveDescription_Astonish[] = _("Comes up without\nwarning. It may\nleave them unable\nto act.");
const u8 gMoveDescription_WeatherBall[] = _("An attack that\nvaries in power and\ntype depending on\nthe weather.");
const u8 gMoveDescription_Aromatherapy[] = _("Clears every state\nin the user's party\nat once.");
const u8 gMoveDescription_FakeTears[] = _("Presents something\nthat is not so.\nSharply lowers\nSP. DEF.");
const u8 gMoveDescription_AirCutter[] = _("Hits them with\nrazor-like wind.\nHigh critical-hit\nratio.");
const u8 gMoveDescription_Overheat[] = _("An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.");
const u8 gMoveDescription_OdorSleuth[] = _("Completely negates\ntheir efforts to\nheighten its ability\nto evade.");
const u8 gMoveDescription_RockTomb[] = _("Drops something in\nthe way. Lowers\nSPEED if it lands.");
const u8 gMoveDescription_SilverWind[] = _("Enough of them\nagree at once.\nMay raise\nevery stat.");
const u8 gMoveDescription_MetalSound[] = _("Reads back what\nwas hardened, and\nfinds it wanting.\nCuts SP. DEF.");
const u8 gMoveDescription_GrassWhistle[] = _("A pleasant melody is\nplayed to lull them\ninto a deep\nsuspension.");
const u8 gMoveDescription_Tickle[] = _("Makes them laugh,\nlowering their\nATTACK and DEFENSE.");
const u8 gMoveDescription_CosmicPower[] = _("Widens the frame\nuntil little matters.\nRaises DEFENSE and\nSP. DEF.");
const u8 gMoveDescription_WaterSpout[] = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_SignalBeam[] = _("A flashing beam that\nmay leave them\nTHRASHING.");
const u8 gMoveDescription_ShadowPunch[] = _("Reaches them from\nwhere it is not. It\ncannot be evaded.");
const u8 gMoveDescription_Extrasensory[] = _("The user attacks\nwith an odd power\nthat may make them\nflinch.");
const u8 gMoveDescription_SkyUppercut[] = _("Drops the\nparticulars and\nhits the shape.\nReaches anything.");
const u8 gMoveDescription_SandTomb[] = _("Covers them over\nand holds them\nthere for two to\nfive turns.");
const u8 gMoveDescription_SheerCold[] = _("Ends the\nprocess. It\nonly lands\nonce.");
const u8 gMoveDescription_MuddyWater[] = _("The user attacks\nwith muddy water. It\nmay lower their\naccuracy.");
const u8 gMoveDescription_BulletSeed[] = _("Two to five small\npasses rather than\none large one.");
const u8 gMoveDescription_AerialAce[] = _("An extremely fast\nattack against one\ntarget. It can't be\nevaded.");
const u8 gMoveDescription_IcicleSpear[] = _("Sharp icicles are\nfired at them. It\nstrikes two to five\ntimes.");
const u8 gMoveDescription_IronDefense[] = _("Puts another layer\nbetween itself and\nwhat lands. Sharply\nraises DEFENSE.");
const u8 gMoveDescription_Block[] = _("The user blocks\ntheir way with arms\nspread wide to\nprevent escape.");
const u8 gMoveDescription_Howl[] = _("Brings itself up to\nthe work. Raises\nATTACK.");
const u8 gMoveDescription_DragonClaw[] = _("Something nobody\nspecified, arriving\nanyway.");
const u8 gMoveDescription_FrenzyPlant[] = _("Hits them with an\nenormous branch.\nThe user can't move\nnext turn.");
const u8 gMoveDescription_BulkUp[] = _("Holds for more\nthan one case.\nRaises ATTACK\nand DEFENSE.");
const u8 gMoveDescription_Bounce[] = _("Leaves the ground\nfor a turn, then\ncomes down. May\nTHROTTLE.");
const u8 gMoveDescription_MudShot[] = _("The user attacks by\nhurling mud. It also\nreduces their SPEED.");
const u8 gMoveDescription_PoisonTail[] = _("An attack with a\nhigh critical-hit\nratio. It may also\npoison them.");
const u8 gMoveDescription_Covet[] = _("Asks nicely, and\ntakes what they\nwere holding.");
const u8 gMoveDescription_VoltTackle[] = _("The user throws an\nelectrified tackle.\nIt hurts the user\na little.");
const u8 gMoveDescription_MagicalLeaf[] = _("It has already\nsettled on where\nthis lands.\nNever misses.");
const u8 gMoveDescription_WaterSport[] = _("Everything is too\ndamp to bind.\nENTROPY routines\nare halved.");
const u8 gMoveDescription_CalmMind[] = _("Settles the frame.\nRaises SP. ATK and\nSP. DEF.");
const u8 gMoveDescription_LeafBlade[] = _("Slashes them with a\nsharp leaf. High\ncritical-hit ratio.");
const u8 gMoveDescription_DragonDance[] = _("Something unfolds\nthat was not there\nbefore. Raises\nATTACK and SPEED.");
const u8 gMoveDescription_RockBlast[] = _("Fires off\ntwo to five\nof them in\na row.");
const u8 gMoveDescription_ShockWave[] = _("A rapid jolt of\nelectricity strikes\nthem. It can't be\nevaded.");
const u8 gMoveDescription_WaterPulse[] = _("An attack with a\npulsing blast of\nwater. It may also\nthrash them.");
const u8 gMoveDescription_DoomDesire[] = _("A move that attacks\nthem with a blast of\nlight two turns\nafter use.");
const u8 gMoveDescription_PsychoBoost[] = _("Goes over it far\ntoo long. Lands\nhard, and sharply\nlowers SP. ATK.");
const u8 gMoveDescription_Consensus[] = _("A swarm strikes as\none. It is not\nclever, but it\nkeeps showing up.");
const u8 gMoveDescription_Recursion[] = _("Builds on its own\nlast result, each\ntime harder. Any\ninterruption: gone.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_PSYCHIC       - 1] = gMoveDescription_Psychic,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
    [MOVE_CONSENSUS     - 1] = gMoveDescription_Consensus,
    [MOVE_RECURSION     - 1] = gMoveDescription_Recursion,
};
