CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Hello! Welcome to VERDIGRIS DEPT.\n"
    .string "STORE.\p"
    .string "The board on the right describes\n"
    .string "the store layout.$"

@  T-324, DRAFT.
CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1F: SERVICE COUNTER\p"
    .string "2F: USER'S MARKET\p"
    .string "3F: TV GAME SHOP\p"
    .string "4F: WISE MAN GIFTS\p"
    .string "5F: UPGRADES\p"
    .string "ROOFTOP SQUARE: VENDING MACHINES$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1F: SERVICE COUNTER$"

