CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Hello! Welcome to VERDIGRIS DEPT.\n"
    .string "STORE.\p"
    .string "The board on the right describes\n"
    .string "the store layout.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1F: SERVICE\n"
    .string "COUNTER\p"
    .string "2F: USER'S\n"
    .string "MARKET\p"
    .string "3F: TV GAME SHOP\p"
    .string "4F: WISEMAN GIFTS\p"
    .string "5F: DRUG STORE\p"
    .string "ROOFTOP SQUARE:\n"
    .string "VENDING MACHINES$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1F: SERVICE COUNTER$"

