PewterCity_House1_Text_Nidoran::
    .string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "NIDORAN, sit!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Our DAEMON's an outsider, so it's\n"
    .string "finicky and hard to handle.\p"
    .string "An outsider is a DAEMON that you\n"
    .string "get in a trade.\p"
    .string "It grows fast, but it may ignore an\n"
    .string "unskilled USER in battle.\p"
    .string "If only we had some MARKS…$"

