ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Those USERBOXes at your waist! You\n"
    .string "have DAEMON!\p"
    .string "It's great that you can carry and\n"
    .string "use DAEMON any time, anywhere!$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "This DAEMON GYM is always closed.\p"
    .string "I wonder who the LEADER is?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "CALLOW GYM's LEADER returned!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "You want to know about the two\n"
    .string "kinds of caterpillar DAEMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CRAWLER has no poison, but SCRAPER\n"
    .string "does.\p"
    .string "Watch out for its POISON STING!$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "When I go shop in SLATE CITY, I\n"
    .string "have to take the winding trail in\l"
    .string "THE UNDERTONE.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "I absolutely forbid you from\n"
    .string "going through here!\p"
    .string "This is private property!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Hm? What is that red box you\n"
    .string "have?\p"
    .string "Ah, so you're working on your\n"
    .string "INDEX.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you bind a DAEMON, the\n"
    .string "INDEX automatically updates its\l"
    .string "data.\p"
    .string "…You don't know how to bind a\n"
    .string "DAEMON?\p"
    .string "I suppose I had better show you\n"
    .string "then!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?\p"
    .string "And here, take this, too.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a DAEMON USER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong. It gave\n"
    .string "me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "INDEX?\p"
    .string "At first, focus on weakening the\n"
    .string "DAEMON before trying to bind it.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, is my old TEACHY TV\n"
    .string "helping you?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign::
    .string "CALLOW CITY\n"
    .string "The Eternally\l"
    .string "Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "USER TIPS\p"
    .string "Bind DAEMONS and expand your\n"
    .string "collection!\p"
    .string "The more you have, the easier it\n"
    .string "is to fight!$"

ViridianCity_Text_MovesLimitedByPP::
    .string "USER TIPS\p"
    .string "The battle moves of DAEMONS are\n"
    .string "limited by their POWER POINTs, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "DAEMON at a DAEMON CENTER!$"

ViridianCity_Text_GymSign::
    .string "CALLOW CITY\n"
    .string "DAEMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "CALLOW GYM's doors are locked…$"

