@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .string "Ready? Boing!\p"
    .string "We're having a BODY SLAM match to\n"
    .string "see who wimps out first.\p"
    .string "If you were to join us, you'd be\n"
    .string "squashed like a bug, though…\p"
    .string "How about I teach BODY SLAM to a\n"
    .string "DAEMON of yours instead?$"

Text_BodySlamDeclined::
    .string "Come again!\n"
    .string "Boing!$"

Text_BodySlamWhichMon::
    .string "Which DAEMON wants to learn how to\n"
    .string "BODY SLAM?$"

Text_BodySlamTaught::
    .string "Boioing!$"

FourIsland_House1_Text_FatMan::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "There's a rare kind of ICE DAEMON\n"
    .string "that lives in the cave.\p"
    .string "We get a lot of visitors hoping to\n"
    .string "see that DAEMON.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "Oh? A DAEMON EGG? …I have no\n"
    .string "idea.\p"
    .string "…Oh, wait. The DAY-CARE people in\n"
    .string "town were saying something.\p"
    .string "They said that they'd found EGGS\n"
    .string "before on their property.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "What's this?\p"
    .string "The new DAEMON JOURNAL hasn't\n"
    .string "arrived on this island?$"

