PokemonLeague_AgathasRoom_Text_Intro::
    .string "I am AGATHA of the ELITE FOUR!\p"
    .string "CRYSTAL's taken a lot of interest in\n"
    .string "you, child!\p"
    .string "That old crank was once tough and\n"
    .string "handsome! That was decades ago!\p"
    .string "Now she just wants to fiddle with\n"
    .string "her INDEX! She's wrong! DAEMONS\l"
    .string "are for fighting!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "USER fights!$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .string "I am AGATHA of the ELITE FOUR.\p"
    .string "You're the child that CRYSTAL\n"
    .string "CLEAR's taken under her wing, aren't\l"
    .string "you?\p"
    .string "That old duff was once tough and\n"
    .string "striking.\p"
    .string "But that was decades ago. She's a\n"
    .string "shadow of her former self.\p"
    .string "Now she just wants to fiddle with\n"
    .string "her INDEX.\p"
    .string "She's wrong. DAEMONS are for\n"
    .string "battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "USER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "Oh, my!\n"
    .string "You're something special, child!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
    .string "You win! I see what the old crank\n"
    .string "sees in you now!\p"
    .string "I have nothing else to say! Run\n"
    .string "along now, child!$"

