PokemonLeague_AgathasRoom_Text_Intro::
    .string "I am AGATHA of the ELITE FOUR.\p"
    .string "I hear CRYSTAL CLEAR's taken a lot\n"
    .string "of interest in you, child.\p"
    .string "That old duff was once tough and\n"
    .string "striking.\p"
    .string "But that was decades ago. She's a\n"
    .string "shadow of her former self.\p"
    .string "Now she just wants to fiddle with\n"
    .string "her INDEX.\p"
    .string "She's wrong. DAEMONS are for\n"
    .string "battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "USER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .string "I am AGATHA of the ELITE FOUR.\p"
    .string "You're the child that CRYSTAL\n"
    .string "CLEAR's taken under her wing, aren't\l"
    .string "you?\p"
    .string "That old duff was once tough and\n"
    .string "striking.\p"
    .string "But that was decades ago. She's a\n"
    .string "shadow of her former self.\p"
    .string "Now she just wants to fiddle with\n"
    .string "her INDEX.\p"
    .string "She's wrong. DAEMONS are for\n"
    .string "battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "USER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "Oh, my!\n"
    .string "You're something special, child!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
    .string "You win!\p"
    .string "I see what the old duff sees in\n"
    .string "you now.\p"
    .string "I have nothing else to say.\n"
    .string "Run along now, child!$"

