ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey! You came from BLANCHE TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "You know CRYSTAL CLEAR, right?\p"
    .string "Her order came in. A CC-7. Will\n"
    .string "you run it out?\p"
    .string "{PLAYER} got the CC-7!$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received the COGNITIVE\n"
    .string "CLARIFIER from the DAEMON MART\l"
    .string "clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay! Say hi to CRYSTAL for me!$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your DAEMON\n"
    .string "will need quick healing.$"

