ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "You know CRYSTAL CLEAR, right?\p"
    .string "Her order came in. Can I get you\n"
    .string "to take it to her?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received the PACKAGE from\n"
    .string "the POKéMON MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, thanks! Please say hi to\n"
    .string "CRYSTAL CLEAR for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your POKéMON\n"
    .string "will need quick healing.$"

