VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Hey, kid! What do you think you're\n"
    .string "doing here?\p"
    .string "You won't live long in combat! Not\n"
    .string "with your puny power!\p"
    .string "I tell you, kid, electric DAEMON\n"
    .string "saved me during the war!\p"
    .string "They zapped my enemies into\n"
    .string "paralysis!\p"
    .string "The same as I'll do to you!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "A little word of advice, kid!\p"
    .string "Electricity is sure powerful!\p"
    .string "But, it's useless against GROUND-\n"
    .string "type DAEMON!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "The SENSE MARK cranks up your\n"
    .string "DAEMON's SPEED!\p"
    .string "It also lets your DAEMON FLY any\n"
    .string "time, kid!\p"
    .string "You're special, kid! Take this!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} received TM34\n"
    .string "from LT. SURGE.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "TM34 contains SHOCK WAVE!\p"
    .string "Teach it to an ELECTRIC DAEMON!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Yo, kid, make room in your BAG!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Whoa!\p"
    .string "You're the real deal, kid!\p"
    .string "Fine then, take the SENSE MARK!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "When I was in the Army, LT. SURGE\n"
    .string "was my strict CO.\p"
    .string "He was a hard taskmaster.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Stop!\n"
    .string "You're very good!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "It's not easy opening that door.\p"
    .string "LT. SURGE was always famous for\n"
    .string "his cautious nature in the Army.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "I'm a lightweight, but I'm good\n"
    .string "with electricity!\p"
    .string "That's why I joined this GYM.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Fried!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Okay, I'll talk!\p"
    .string "LT. SURGE said he hid door\n"
    .string "switches inside something.$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "This is no place for kids!\n"
    .string "Not even if you're good!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Wow!\n"
    .string "Surprised me!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "LT. SURGE installed the traps in\n"
    .string "the GYM himself.\p"
    .string "He set up double locks everywhere.\n"
    .string "Let me give you a hint.\p"
    .string "When you open the first lock, the\n"
    .string "second lock is right next to it.$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Yo! Champ in making!\p"
    .string "LT.SURGE has a nickname. People\n"
    .string "refer to him as the Lightning\l"
    .string "American!\p"
    .string "He's an expert on electric DAEMON!\p"
    .string "Birds and water DAEMONS are at\n"
    .string "risk! Beware of paralysis too!\p"
    .string "LT.SURGE is very cautious!\p"
    .string "You'll have to break a code to get\n"
    .string "to him!$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "Whew!\n"
    .string "That match was electric!$"

VermilionCity_Gym_Text_GymStatue::
    .string "ARDOR DAEMON GYM LEADER: LT.\n"
    .string "SURGE\p"
    .string "WINNING USERS: {RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "ARDOR DAEMON GYM LEADER: LT.\n"
    .string "SURGE\p"
    .string "WINNING USERS: {RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Nope!\n"
    .string "There's only trash here.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hey! There's a switch under the\n"
    .string "trash! Turn it on!\p"
    .string "The first electric lock opened!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "The second electric lock opened!\n"
    .string "The motorized door opened!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Nope!\n"
    .string "There's only trash here.\p"
    .string "Hey!\n"
    .string "The electric locks were reset!$"

