FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "Welcome to the SAFARI ZONE!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "For just ¥500, you can play the\n"
    .string "SAFARI GAME.\p"
    .string "You can roam the wide-open safari\n"
    .string "and bind what you like.\p"
    .string "Would you like to play?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "That'll be ¥500, please!\p"
    .string "We only use a special kind of POKé\n"
    .string "BOXES here.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "{PLAYER} received 30 GUESTBOXES\n"
    .string "from the attendant.$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "We'll call you on the PA when you\n"
    .string "run out of time or GUESTBOXES.\p"
    .string "Well, I'll wish you the best of\n"
    .string "luck!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "Okay.\n"
    .string "Please come again!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "Oops!\n"
    .string "Not enough money!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "Are you going to leave the\n"
    .string "SAFARI ZONE early?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "Please return any GUESTBOXES you\n"
    .string "may have left.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "Good luck!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "Did you bind your fair share? Come\n"
    .string "again!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "Hi! Is it your first time here at\n"
    .string "the SAFARI ZONE?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "The SAFARI ZONE actually has four\n"
    .string "zones in it.\p"
    .string "Each zone has different kinds of\n"
    .string "DAEMONS, even some rare ones.\p"
    .string "Use the supplied GUESTBOXES to\n"
    .string "bind them.\p"
    .string "You can also throw BAIT or ROCKS\n"
    .string "besides the GUESTBOXES.\p"
    .string "If you throw BAIT, the DAEMON\n"
    .string "becomes less likely to DETACH, but\l"
    .string "harder to bind.\p"
    .string "If you throw ROCKS, the DAEMON\n"
    .string "becomes more likely to DETACH, but\l"
    .string "easier to bind.\p"
    .string "When you run out of time or\n"
    .string "GUESTBOXES, it's game over for you!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "Sorry, you're a regular here!$"

