FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "Welcome to the SAFARI ZONE!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "For just ¥500, you can bind all\n"
    .string "the DAEMON you want in the park!\p"
    .string "Would you like to join the hunt?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "That'll be ¥500 please!\p"
    .string "We only use a special GUESTBOX\n"
    .string "here.\p"
    .string "{PLAYER} received 30 GUESTBOXes!$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "{PLAYER} received 30 GUESTBOXES\n"
    .string "from the attendant.$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "We'll call you on the PA when you\n"
    .string "run out of time or GUESTBOXes!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "Okay.\n"
    .string "Please come again!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "Oops!\n"
    .string "Not enough money!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "Are you going to leave the\n"
    .string "SAFARI ZONE early?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "Please return any GUESTBOXes you\n"
    .string "have left.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "Good luck!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "Did you bind your fair share? Come\n"
    .string "again!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "Hi! Is it your first time here at\n"
    .string "the SAFARI ZONE?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "SAFARI ZONE has 4 zones in it.\p"
    .string "Each zone has different kinds of\n"
    .string "DAEMONS. Use GUESTBOXes to bind\l"
    .string "them!\p"
    .string "When you run out of time or\n"
    .string "GUESTBOXes, it's game over for you!\p"
    .string "Before you go, open an unused\n"
    .string "DAEMON BOX so there's room for new\l"
    .string "DAEMON!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "Sorry, you're a regular here!$"

