CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "I'm getting a DECOY for my girl\n"
    .string "friend!$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "I heard something useful.\p"
    .string "You can run from wild DAEMON by\n"
    .string "distracting them with a DECOY!$"

@  T-324, DRAFT.
CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Say it with a gift!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "RECOMPILE SALE!\n"
    .string "AXIOM, AFFECT and the rest!$"
