CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "I'm getting a POKé DOLL for my girl\n"
    .string "friend!$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "I heard something useful.\p"
    .string "You can run from wild DAEMON by\n"
    .string "distracting them with a POKé DOLL!$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Express yourself with gifts!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution Special!\n"
    .string "Element STONES on sale now!$"
