SilphCo_3F_Text_WhatAmIToDo::
    .string "I work for SILPH CO.\n"
    .string "What am I to do?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}! You and your DAEMON\n"
    .string "saved us!$"

SilphCo_3F_Text_GruntIntro::
    .string "Quit messing with us, kid!$"

SilphCo_3F_Text_GruntDefeat::
    .string "I give up!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "A hint? You can open doors with\n"
    .string "a CARD KEY!$"

SilphCo_3F_Text_JoseIntro::
    .string "I support TEAM CORPUS more than I\n"
    .string "support SILPH CO.!$"

SilphCo_3F_Text_JoseDefeat::
    .string "You really got me!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Humph…\p"
    .string "TEAM CORPUS said that if I helped\n"
    .string "them, they'd let me study DAEMONS.$"

SilphCo_3F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "3F$"

