SilphCo_3F_Text_WhatAmIToDo::
    .string "I work for FOUNDRY CO. What am I\n"
    .string "to do?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}! You and your DAEMON\n"
    .string "saved us!$"

SilphCo_3F_Text_GruntIntro::
    .string "You are disrupting the rollout.$"

SilphCo_3F_Text_GruntDefeat::
    .string "Withdrawing.$"

SilphCo_3F_Text_GruntPostBattle::
    .string "Doors need a CARD KEY.\p"
    .string "Ask your manager for one!$"

SilphCo_3F_Text_JoseIntro::
    .string "I support TEAM CORPUS more than I\n"
    .string "support FOUNDRY!$"

SilphCo_3F_Text_JoseDefeat::
    .string "You really got me!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Humph...\p"
    .string "TEAM CORPUS said that if I helped\n"
    .string "them, they'd let me study DAEMON!$"

SilphCo_3F_Text_FloorSign::
    .string "FOUNDRY CO. HEAD OFFICE 3F$"

