//  GENERATED by tools/gbadreams.py from engineAi/server/progress_steps.json and docs/attendant_dreams.json.
//  Do not edit; edit the JSON and run the tool. T-347, DRAFT wording.

struct AttendantDream { u16 flag; const u8 *first; const u8 *second; };

static const u8 sDream_starter_pokemon_first[] = _("I dreamt of a white room with a\ntable, and three small boxes on it.\pEach one was humming to itself.\nI think one of them was yours.");
static const u8 sDream_starter_pokemon_second[] = _("I dreamt CRYSTAL CLEAR was waiting\nin her lab, back in BLANCHE.\pThere was something on her table\nshe meant for you to take.");
static const u8 sDream_get_pokedex_first[] = _("I dreamt of a parcel with someone\nelse's name on it.\pYou carried it, but it was never\nyours to open. It wanted home.");
static const u8 sDream_get_pokedex_second[] = _("I dreamt of a parcel at the shop\nin CALLOW, addressed to CRYSTAL.\pTake it back to her lab in\nBLANCHE. She has something for you.");
static const u8 sDream_callow_textbook_first[] = _("I dreamt of a tall building full of\nchalk dust, and stairs going up.\pAt the very top, someone held out\na heavy book and waited.");
static const u8 sDream_callow_textbook_second[] = _("I dreamt you climbed CALLOW SCHOOL\nall the way to the seventh floor.\pThe teacher there has a TEXTBOOK\nwith your name already on it.");
static const u8 sDream_callow_exam_first[] = _("I dreamt of a quiet hall with rows\nof desks, and a clock on the wall.\pThe paper was waiting. It did not\nmind how long the season took.");
static const u8 sDream_callow_exam_second[] = _("I dreamt of the exam at CALLOW\nSCHOOL, when its season comes.\pRead the boards and the TEXTBOOK\nfirst. Eighty earns the DIPLOMA.");
static const u8 sDream_boulder_badge_first[] = _("I dreamt of a forest to the north,\nand past it a grey city of stone.\pA man there writes everything down.\nHe was waiting to be tested.");
static const u8 sDream_boulder_badge_second[] = _("I dreamt of the BENCHMARK in SLATE,\npast THE UNDERTONE to the north.\pCAIRN is waiting there. Bring\nsomething his stone can't stop.");
static const u8 sDream_mt_moon_first[] = _("I dreamt of a mountain hollowed out\nlike a stack of old plates.\pYou went in on one side, in the\ndark, and came out by the water.");
static const u8 sDream_mt_moon_second[] = _("I dreamt you went east from SLATE,\nthrough DEADSTACK.\pDOLDRUM CITY is on the far side,\nwhere the water is.");
static const u8 sDream_cascade_badge_first[] = _("I dreamt of a pool so still it\nlooked like a floor.\pSomeone stood in it up to the\nwaist, waiting for you to step in.");
static const u8 sDream_cascade_badge_second[] = _("I dreamt of the BENCHMARK in\nDOLDRUM. BASIN is waiting there.\pSmall steps, she said. Keep going\ndown and you arrive.");
static const u8 sDream_ss_anne_first[] = _("I dreamt a ship was in the harbour,\nall lit up for a party.\pYour ticket came from a cottage at\nthe end of a long road north.");
static const u8 sDream_ss_anne_second[] = _("I dreamt of the S.S. ANNE, docked\nin ARDOR.\pThe cottage at the far end of the\nroad north of DOLDRUM had a ticket.");
static const u8 sDream_thunder_badge_first[] = _("I dreamt of a door behind a small\ntree, and a hum like a power line.\pYou needed something sharp to get\nthrough. The ship's captain had it.");
static const u8 sDream_thunder_badge_second[] = _("I dreamt of the BENCHMARK in ARDOR.\nGAUGE is in there, shouting.\pPRUNE clears the little tree at\nits door. DRIVER01 teaches it.");
static const u8 sDream_rock_tunnel_first[] = _("I dreamt of a tunnel with no light\nat all, east of the water.\pSomething had to speak up in there\nbefore you could see the way.");
static const u8 sDream_rock_tunnel_second[] = _("I dreamt of THE BLACKOUT, past\nDOLDRUM to the east.\pVERBOSE lights it. HALFTONE TOWN\nis on the other side.");
static const u8 sDream_rainbow_badge_first[] = _("I dreamt of a garden under glass,\nand a quiet woman tending vines.\pShe had been expecting a visitor\nwho could hold a thing up.");
static const u8 sDream_rainbow_badge_second[] = _("I dreamt of the BENCHMARK in\nVERDIGRIS CITY, west of HALFTONE.\pTRELLIS is waiting among her\nplants.");
static const u8 sDream_reading_room_first[] = _("I dreamt of a reading room with\nno windows, only shelves.\pThey would only let you in with\na paper in your hand.");
static const u8 sDream_reading_room_second[] = _("I dreamt of BRAZEN's READING ROOM.\nIt wants to see your DIPLOMA.\pThe guards at BRAZEN's gates\nwere thirsty. Bring them TEA.");
static const u8 sDream_rocket_hideout_first[] = _("I dreamt of a poster in a noisy\nroom, and stairs hidden behind it.\pUnderneath, someone was counting\nsomething that was not his.");
static const u8 sDream_rocket_hideout_second[] = _("I dreamt of the CORPUS HIDEOUT,\nunder the noisy hall in VERDIGRIS.\pSCORN is at the bottom. He has a\nRESOLVER you will need.");
static const u8 sDream_pokemon_tower_first[] = _("I dreamt of a tall grey tower full\nof things nobody could see.\pWith the right lens they had faces.\nSomeone at the top needed you.");
static const u8 sDream_pokemon_tower_second[] = _("I dreamt of the tower in HALFTONE.\nThe RESOLVER shows what haunts it.\pWhoever waits at the top will give\nyou the INTERRUPT.");
static const u8 sDream_soul_badge_first[] = _("I dreamt of a big sleeper lying\nacross the road.\pA short tune woke him. Past him,\nthe land ran south to a city.");
static const u8 sDream_soul_badge_second[] = _("I dreamt of the BENCHMARK in LURID\nCITY, far to the south.\pPlay the INTERRUPT at whatever\nsleeps across the road. TILT waits.");
static const u8 sDream_safari_zone_first[] = _("I dreamt of a wild park behind a\ngate, and a little house deep in it.\pSomeone there kept a way across\nthe water.");
static const u8 sDream_safari_zone_second[] = _("I dreamt of the SAFARI ZONE in\nLURID CITY.\pThe house at its far end holds\nDRIVER03.");
static const u8 sDream_silph_co_first[] = _("I dreamt of a tall office where\nevery door wanted a card.\pMen in the same coats filled every\nfloor. One sat at the very top.");
static const u8 sDream_silph_co_second[] = _("I dreamt of FOUNDRY CO. in BRAZEN.\nCORPUS has taken it over.\pThe CARD KEY is inside somewhere.\nSCORN is at the top.");
static const u8 sDream_marsh_badge_first[] = _("I dreamt of a room where one step\non the wrong tile put you elsewhere.\pSomeone in the middle had seen you\ncoming a long time ago.");
static const u8 sDream_marsh_badge_second[] = _("I dreamt of the BENCHMARK in\nBRAZEN. Its tiles move you around.\pMATTE is in the middle, waiting.");
static const u8 sDream_pokemon_mansion_first[] = _("I dreamt of a burnt house on an\nisland, and statues with switches.\pSomewhere in its cellar lay a key\nto a locked door nearby.");
static const u8 sDream_pokemon_mansion_second[] = _("I dreamt of the DAEMON MANSION on\nQUICKSILVER. TRAVERSE goes there.\pThe SECRET KEY in its basement\nopens the BENCHMARK.");
static const u8 sDream_volcano_badge_first[] = _("I dreamt of a hall full of heat,\nand quiz machines by every door.\pThe answers were all things you\nalready knew.");
static const u8 sDream_volcano_badge_second[] = _("I dreamt of the BENCHMARK on\nQUICKSILVER. ANNEAL is inside.\pAnswer the machines and you walk\nstraight to him.");
static const u8 sDream_earth_badge_first[] = _("I dreamt of a door that had been\nshut so long the dust had settled.\pIt was open now. Someone behind\nit had been counting the days.");
static const u8 sDream_earth_badge_second[] = _("I dreamt of the BENCHMARK in\nCALLOW. All seven MARKS open it.\pSCORN is inside.");
static const u8 sDream_victory_road_first[] = _("I dreamt of a road to the west with\na gate for every MARK.\pAt its end, a climb in the dark,\npushing stones out of the way.");
static const u8 sDream_victory_road_second[] = _("I dreamt of ROUTE 23, west of\nCALLOW. Every MARK opens a gate.\pThen UMBRAL ASCENT. DISPLACE\nmoves the boulders.");
static const u8 sDream_elite_four_first[] = _("I dreamt of four people at a long\ntable, reading about you.\pThey were waiting for you to come\nand answer for it.");
static const u8 sDream_elite_four_second[] = _("I dreamt of THE REVIEW BOARD at\nUMBRA PLATEAU.\pFour of them, one after another.\nBring everything you have.");
static const u8 sDream_champion_first[] = _("I dreamt of a chair at the very\ntop, and someone already in it.\pThey knew you better than anyone.\nThey had got there first.");
static const u8 sDream_champion_second[] = _("I dreamt that past THE REVIEW\nBOARD, {RIVAL} was waiting.\pOf course it was {RIVAL}.");

static const struct AttendantDream sAttendantDreams[] = {
    { FLAG_SYS_POKEMON_GET, sDream_starter_pokemon_first, sDream_starter_pokemon_second },   // Starter DAEMON
    { FLAG_SYS_POKEDEX_GET, sDream_get_pokedex_first, sDream_get_pokedex_second },   // Get the INDEX
    { FLAG_SCHOOL_GOT_TEXTBOOK, sDream_callow_textbook_first, sDream_callow_textbook_second },   // CALLOW SCHOOL: climb to 7F for the TEXTBOOK
    { FLAG_GOT_DIPLOMA, sDream_callow_exam_first, sDream_callow_exam_second },   // CALLOW SCHOOL: pass the exam (the DIPLOMA)
    { FLAG_BADGE01_GET, sDream_boulder_badge_first, sDream_boulder_badge_second },   // SLATE MARK
    { FLAG_WORLD_MAP_CERULEAN_CITY, sDream_mt_moon_first, sDream_mt_moon_second },   // DEADSTACK
    { FLAG_BADGE02_GET, sDream_cascade_badge_first, sDream_cascade_badge_second },   // SLOPE MARK
    { FLAG_HIDE_SS_ANNE, sDream_ss_anne_first, sDream_ss_anne_second },   // S.S. Anne
    { FLAG_BADGE03_GET, sDream_thunder_badge_first, sDream_thunder_badge_second },   // SENSE MARK
    { FLAG_WORLD_MAP_LAVENDER_TOWN, sDream_rock_tunnel_first, sDream_rock_tunnel_second },   // THE BLACKOUT
    { FLAG_BADGE04_GET, sDream_rainbow_badge_first, sDream_rainbow_badge_second },   // FIT MARK
    { FLAG_GOT_REVEAL, sDream_reading_room_first, sDream_reading_room_second },   // BRAZEN's Reading Room: REVEAL (needs the DIPLOMA)
    { FLAG_HIDE_HIDEOUT_GIOVANNI, sDream_rocket_hideout_first, sDream_rocket_hideout_second },   // CORPUS HIDEOUT
    { FLAG_GOT_POKE_FLUTE, sDream_pokemon_tower_first, sDream_pokemon_tower_second },   // HALFTONE TOWER
    { FLAG_BADGE05_GET, sDream_soul_badge_first, sDream_soul_badge_second },   // SKEW MARK
    { FLAG_GOT_HM03, sDream_safari_zone_first, sDream_safari_zone_second },   // Safari Zone
    { FLAG_HIDE_SAFFRON_ROCKETS, sDream_silph_co_first, sDream_silph_co_second },   // Silph Co.
    { FLAG_BADGE06_GET, sDream_marsh_badge_first, sDream_marsh_badge_second },   // FRAME MARK
    { FLAG_HIDE_POKEMON_MANSION_B1F_SECRET_KEY, sDream_pokemon_mansion_first, sDream_pokemon_mansion_second },   // DAEMON MANSION
    { FLAG_BADGE07_GET, sDream_volcano_badge_first, sDream_volcano_badge_second },   // HEAT MARK
    { FLAG_BADGE08_GET, sDream_earth_badge_first, sDream_earth_badge_second },   // TRUE MARK
    { FLAG_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR, sDream_victory_road_first, sDream_victory_road_second },   // UMBRAL ASCENT
    { FLAG_DEFEATED_LANCE, sDream_elite_four_first, sDream_elite_four_second },   // THE REVIEW BOARD
    { FLAG_DEFEATED_CHAMP, sDream_champion_first, sDream_champion_second },   // Champion
};
