// Generated by tools/gbadaytrim.py -- do not edit. T-275: the CHECKPOINT's trim, one colour a day,
// Sunday first; each 22+ (CIE76) from every type's hue (9.4).
static const u16 sDayTrims[] = {
    RGB(16, 6, 6),   // SUNDAY, C
    RGB(14, 8, 4),   // MONDAY, D
    RGB(22, 22, 7),   // TUESDAY, E
    RGB(8, 21, 8),   // WEDNESDAY, F
    RGB(6, 11, 12),   // THURSDAY, G
    RGB(7, 6, 18),   // FRIDAY, A
    RGB(15, 6, 18),   // SATURDAY, B
};
