// GENERATED by tools/gbagrove.py -- do not edit by hand.
//
// T-221: the trees that lead into a GROVE and out of one. src/reveal.c twinkles a bg_event whose script is
// one of these, as it does a hidden item.
#ifndef GUARD_DATA_GROVE_TREES_H
#define GUARD_DATA_GROVE_TREES_H

extern const u8 ViridianForest_EventScript_Grove[];
extern const u8 ViridianForest_Grove_EventScript_Leave[];

static const u8 *const sGroveTrees[] =
{
    ViridianForest_EventScript_Grove,
    ViridianForest_Grove_EventScript_Leave,
};

#endif // GUARD_DATA_GROVE_TREES_H
