// Generated by DAEMONS tools/genguide.py from docs/guide.md -- edit those, not this.
// T-300/T-301: THE PROGRAMMER'S GUIDE TO THE HUMAN MIND. DRAFT WORDING, every string, until the user
// approves it on the private field-test page. The four rules it keeps are in vision.md 4.36.

#define GUIDE_SECTIONS 9
#define GUIDE_ENTRIES  28

static const u8 sGuideLabel_0[] = _("INTRODUCTION");
static const u8 sGuideHeading_0[] = _("Introduction");
static const u8 sGuideShort_0[] = _("THE MIND AS CODE");
static const u8 sGuideTitle_0[] = _("Understanding the Mind as Software");
static const u8 sGuideText_0[] = _("A mind runs on patterns, routines and sequences that decide how we think, feel and act. They were written by experience, by where we grew up, by what we learned, and most of them run in the background where we never see them.\pThat makes them easy to compare to a program. Code can carry bugs, slow routines and functions nobody uses any more. So can a mind.\pRead that way, a stubborn habit is not a character flaw. It is a routine that can be found, understood and changed, the way any programmer would treat a fault: patiently, one line at a time.");
static const u8 sGuideShort_1[] = _("THE TOOLKIT");
static const u8 sGuideTitle_1[] = _("Overview of Tools and Techniques");
static const u8 sGuideText_1[] = _("This book borrows tools from psychology, from the study of the brain, and from older practices of attention.\pSome find faults, like a debugger. Some rewrite a routine, like refactoring. Some watch the system while it runs, like a monitor. Some keep a record, like a log file. Some rehearse a change before it is made, like a simulation. And some raise the load slowly, to see what holds, like a stress test.\pNo one tool is the answer. A programmer reaches for the one that fits the fault.");
static const u8 sGuideShort_2[] = _("THE PROGRAMMER");
static const u8 sGuideTitle_2[] = _("The Programmer's Role in Re-architecting the Mind");
static const u8 sGuideText_2[] = _("A programmer's habits of mind travel well. Break a large problem into small parts. Find where it actually fails before trying to fix it. Change one thing, then test.\pOld beliefs are like legacy code: still running, still depended on, and not safe to delete all at once. They are rewritten carefully, so nothing that relies on them breaks.\pAnd keep versions. Write down what changed and when, so that a change that makes things worse can be rolled back. Progress you can see is progress you keep making.");

static const u8 sGuideLabel_1[] = _("PART 1");
static const u8 sGuideHeading_1[] = _("Understanding the System");
static const u8 sGuideShort_3[] = _("HARDWARE");
static const u8 sGuideTitle_3[] = _("The Human Brain: Hardware for the Mind");
static const u8 sGuideText_3[] = _("The brain is like a processor built from billions of neurons, joined at synapses, passing signals.\pSome regions have jobs a programmer would recognise. The front of the brain plans, decides and holds back an impulse, like a central processor. The limbic system handles feeling, memory and drive, like a kernel. The cerebellum fine-tunes movement and attention, like a co-processor. The brainstem keeps breath and heartbeat going without being asked, like an operating system.\pAnd the hardware rewires itself. Connections used together grow stronger: cells that fire together wire together. That is how a skill is learned, and how a habit is.");
static const u8 sGuideShort_4[] = _("MENTAL PROGRAMS");
static const u8 sGuideTitle_4[] = _("The Mind as Software: An Introduction to Mental Programming");
static const u8 sGuideText_4[] = _("If the brain is like hardware, the mind is like what runs on it: memory, attention, reasoning, each a module handing its results to the next.\pSome of it runs in the foreground, where we can see it. Most of it runs in the background, and steers the foreground anyway.\pHabits are subroutines. They save effort, and they keep running long after the reason for them is gone. Feedback shapes all of it. What is rewarded runs again. What is corrected runs differently next time.");
static const u8 sGuideShort_5[] = _("IN PARALLEL");
static const u8 sGuideTitle_5[] = _("Feelings in Parallel: the Machine Learning Perspective");
static const u8 sGuideText_5[] = _("Thought tends to run in series: one step, then the next. Feeling runs in parallel. It takes in the sound, the memory, the pulse, the place and the people all at once, and answers before thought has finished its first step.\pPicture each feeling as an object. It holds the feeling itself, the moment that set it off, and the move it wants to make. A worry object leans every thought toward the worst case.\pObjects can be updated. A threat, looked at again, can become a challenge, and the thoughts that follow change with it.");
static const u8 sGuideShort_6[] = _("THE LOOP");
static const u8 sGuideTitle_6[] = _("Awareness as a Feedback Loop");
static const u8 sGuideText_6[] = _("Thoughts set off feelings, and feelings steer thoughts. Around and around.\pThis book's view is that awareness is not a thing but that cycle, running without a pause. Each turn takes in what came before and leans toward what might come next, which is why a life feels like one stream and not a pile of separate moments.\pA loop can run toward the good or toward the bad. Put one kinder thought into it, and the feeling that comes back is a little different, and so is the thought after that.");

static const u8 sGuideLabel_2[] = _("PART 2");
static const u8 sGuideHeading_2[] = _("Core Programming Techniques");
static const u8 sGuideShort_7[] = _("REWRITING");
static const u8 sGuideTitle_7[] = _("Rewriting the Mental Code (NLP)");
static const u8 sGuideText_7[] = _("Neuro-linguistic programming studies how the words we use, inside and out, shape what we do.\pAnchoring ties a state to a signal: a gesture, a word, a picture that brings the calm back when it is needed. Reframing keeps the event and changes what it means. The swish pattern pictures an old habit, then swaps it at once for the picture of the new one.\pEven the brightness and loudness of an inner picture matter. Turn a bad memory's volume down, and it weighs less.");
static const u8 sGuideShort_8[] = _("DEBUGGING");
static const u8 sGuideTitle_8[] = _("Debugging Thought Processes (CBT)");
static const u8 sGuideText_8[] = _("Cognitive behavioral therapy treats a thought like a line of code that can be inspected.\pAutomatic thoughts arrive before we choose them. Core beliefs sit underneath and shape how everything is read. Distortions are the classic bugs: all-or-nothing thinking, expecting the worst, one bad day read as every day.\pThe tools are a debugger's. A thought record logs the situation, the thought, the feeling, and the evidence on each side. An experiment tests a belief instead of trusting it. A good question, asked slowly, finds the assumption under the fault.");
static const u8 sGuideShort_9[] = _("MONITORING");
static const u8 sGuideTitle_9[] = _("Mindfulness: System Monitoring and Maintenance");
static const u8 sGuideText_9[] = _("Mindfulness is attention to the present, without judging what it finds.\pLike a system monitor, it shows a loop starting before it has taken over, and a feeling rising before it has to be obeyed. Like maintenance, it clears clutter the way a defragmenter clears a drive.\pThe practices are small. Follow a breath. Scan the body, part by part. Look at something ordinary as if for the first time. Listen without planning your reply. Wish yourself, and then others, well.");
static const u8 sGuideShort_10[] = _("POWER SUPPLY");
static const u8 sGuideTitle_10[] = _("Energy Flow and Chakras: Optimizing the Power Supply");
static const u8 sGuideText_10[] = _("Older traditions describe seven centers of energy running up the body: the root, the sacral, the solar plexus, the heart, the throat, the third eye and the crown.\pThis book gives each one a day. Sunday grounds the root, Monday the sacral, Tuesday the solar plexus, Wednesday the heart, Thursday the throat, Friday the third eye, and Saturday the crown.\pLike a steady power supply, a week that tends every center in turn leaves no part of the system running short.");

static const u8 sGuideLabel_3[] = _("PART 3");
static const u8 sGuideHeading_3[] = _("Advanced Mental Engineering");
static const u8 sGuideShort_11[] = _("SECURITY");
static const u8 sGuideTitle_11[] = _("Virtues and Sins: Securing the System");
static const u8 sGuideText_11[] = _("Each day's center has a virtue that protects it and a sin that exploits it, the way a patch closes a vulnerability.\pSunday: diligence against sloth. Monday: chastity against lust. Tuesday: charity against greed. Wednesday: kindness against envy. Thursday: temperance against gluttony. Friday: patience against wrath. Saturday: humility against pride.\pBegin each day by naming its pair. Practice the one, watch for the other. Like updates applied on a schedule, the week keeps the whole system patched.");
static const u8 sGuideShort_12[] = _("AUTOMATION");
static const u8 sGuideTitle_12[] = _("Habit Formation: Automating Positive Routines");
static const u8 sGuideText_12[] = _("A habit is like an automated routine: once set up, it runs with almost no attention.\pIt is built by a loop. A thought triggers an action, the action brings a feeling, and a good feeling makes the action more likely next time. Run that enough times and nobody is choosing any more.\pTo change a habit, find its trigger, then reframe the thought that fires it and put a better action in the old one's place. Stack a new habit onto one that already runs. Leave the book on the nightstand.");
static const u8 sGuideShort_13[] = _("INTEGRATION");
static const u8 sGuideTitle_13[] = _("Thought and Emotion Integration");
static const u8 sGuideText_13[] = _("Thought works through the details, one at a time. Feeling takes in the whole at once, and changes how the details are read.\pWhen feeling runs everything, we act on impulse. When thought runs everything, we act correctly and coldly. Neither alone is enough.\pBalance is not a midpoint between them. It is the two passing their results to each other, quickly and honestly: pausing to notice, reframing, breathing, writing it down.");

static const u8 sGuideLabel_4[] = _("PART 4");
static const u8 sGuideHeading_4[] = _("System Failures and Recovery");
static const u8 sGuideShort_14[] = _("CRASHES");
static const u8 sGuideTitle_14[] = _("Recovering from System Crashes");
static const u8 sGuideText_14[] = _("Some events overwhelm the system all at once, like a crash. Afterwards it does not run as it did. It may stay on alert, or go numb, or replay the moment in a loop that will not close.\pRecovery is like a careful reboot. First, admit the crash happened. Then reprocess it slowly, with help, until the memory can be held without taking over. Then rewrite the rules the crash left behind, rebuild what steadies the system, and keep checking in.\pA crash is something that happened to the system. It is not what the system is.");
static const u8 sGuideShort_15[] = _("DIRECT ACCESS");
static const u8 sGuideTitle_15[] = _("Hypnotherapy: Direct Access Programming");
static const u8 sGuideText_15[] = _("Hypnosis is described as reaching below the conscious layer, like working in a system's root directory.\pA calm, focused state quiets the part of the mind that filters every suggestion. In that state, a new picture or a kinder instruction can reach the routines underneath. Repeated over sessions, it can change an old fear or an old habit.\pRoot access is powerful, so it has rules: informed consent, respect for the person's own goals, and a trained practitioner watching how the change settles in.");
static const u8 sGuideShort_16[] = _("OVERHAULS");
static const u8 sGuideTitle_16[] = _("System Overhauls and Safe Operating");
static const u8 sGuideText_16[] = _("Sometimes the fix is not a patch but an overhaul: a rare, deep experience that loosens every routine at once.\pThe self can seem to dissolve for a while, like a programmer stepping back from single lines of code to see the whole architecture. What was hidden can show itself as images.\pSuch things are serious, so they are approached with care: the right mindset, a safe setting, a trusted guide, and the law respected. The real work is afterwards. Integration means testing what was learned in ordinary life, and keeping only what holds.");

static const u8 sGuideLabel_5[] = _("PART 5");
static const u8 sGuideHeading_5[] = _("Ongoing Maintenance and Optimization");
static const u8 sGuideShort_17[] = _("THE ZONE");
static const u8 sGuideTitle_17[] = _("Flow States: Optimizing the Processor");
static const u8 sGuideText_17[] = _("Flow is being so absorbed in a task that time goes missing.\pIt comes when the challenge matches the skill. Too easy is boring and too hard is frightening, but just past what you can already do is where the zone is. Clear goals and quick feedback help, and so does a quiet space and the sense that the choices are your own.\pLike a processor running at its best, a mind in flow does more with less, and comes back from it better rested than it went in.");
static const u8 sGuideShort_18[] = _("LOGS");
static const u8 sGuideTitle_18[] = _("Journaling: System Logs and Version Control");
static const u8 sGuideText_18[] = _("A journal is like a system log. It records what happened, what it felt like, and what came of it, so patterns can be found later.\pIt is also version control. Read last year's pages and you can see exactly what changed.\pWrite at the same time each day. Use prompts: what went well, what was hard, how did it feel. Draw if words will not come. Nobody else reads it, so it does not have to be good. It only has to be true.");
static const u8 sGuideShort_19[] = _("DREAMS");
static const u8 sGuideTitle_19[] = _("Lucid Dreaming: Nighttime Debugging and Testing");
static const u8 sGuideText_19[] = _("A lucid dream is one where you know you are dreaming.\pIt can be learned. Notice dream signs, the impossible things that only happen asleep. Do reality checks while awake: look at your hands, or read a line of text, look away and read it again. In a dream the words will not stay the same.\pOnce lucid, the dream is a safe test environment. Face a fear at your own pace. Rehearse a skill. Try the idea that would not come by day. Then write it down before it fades.");

static const u8 sGuideLabel_6[] = _("PART 6");
static const u8 sGuideHeading_6[] = _("Real-World Applications");
static const u8 sGuideShort_20[] = _("NETWORKS");
static const u8 sGuideTitle_20[] = _("Interpersonal Dynamics: Networking Protocols");
static const u8 sGuideText_20[] = _("People connect the way machines do, by protocol.\pA first meeting is like a handshake. Trust is like a secure channel, built from consistency and honesty. A connection that is never used times out, so stay in touch.\pRelationships run in layers, like a network: signals at the bottom, then shared feelings, then shared history, then something that can carry almost anything. Protect what is private, respect the other side's limits, and send what you would want received.");
static const u8 sGuideShort_21[] = _("CONFLICTS");
static const u8 sGuideTitle_21[] = _("Conflict Resolution: Debugging Relationships");
static const u8 sGuideText_21[] = _("A conflict is like an error in the system between two people, and it can be debugged the same way.\pIsolate the one issue at hand, not every old grievance with it. Reproduce it: when does it happen, and what sets it off? Find the need or the expectation underneath. Agree a fix that reaches the cause. Then test it over the weeks that follow.\pWhen it is too tangled, bring in someone neutral. Sometimes a relationship needs a reboot. Sometimes a feature cannot be saved, and is retired with care.");

static const u8 sGuideLabel_7[] = _("CONCLUSION");
static const u8 sGuideHeading_7[] = _("Conclusion");
static const u8 sGuideShort_22[] = _("THE FUTURE");
static const u8 sGuideTitle_22[] = _("The Future of Mental Programming");
static const u8 sGuideText_22[] = _("The field is young. As the study of the brain grows, tools that watch and answer back in real time will be joined to these old methods, and help will fit each person the way good software fits its user.\pThe same ideas can reach further than one mind. A school could teach attention and feeling alongside reading. A community could notice the loops it runs together, and choose which ones to keep.\pThat is exactly why the next section matters.");
static const u8 sGuideShort_23[] = _("ETHICS");
static const u8 sGuideTitle_23[] = _("Ethical Considerations");
static const u8 sGuideText_23[] = _("The power to change a mind must never be used without that person's informed consent.\pBe open about the method and the goal. Never use these tools to manipulate, to exploit, or to make people the same. Take special care of those who cannot easily say no.\pAnd not every part of a mind needs fixing. Quirks, differences and imperfections are part of what a person is. The aim is well-being, not a standard model. Change that lasts is slow, and it needs support long after the first step.");
static const u8 sGuideShort_24[] = _("THE PATH FORWARD");
static const u8 sGuideTitle_24[] = _("The Path Forward: Continuous Development");
static const u8 sGuideText_24[] = _("There is no final release. Like any system that is still in use, a mind is maintained for as long as it runs.\pKeep learning. Check in with yourself regularly, the way a system runs a self-test. Tend to feelings the way you would tend to your hands: routinely, not only when something hurts. Try new methods, and keep the ones that work for you.\pFind others on the same path. And whatever you learn about changing a mind, use it on your own first, and on anyone else only with their yes.");

static const u8 sGuideLabel_8[] = _("APPENDICES");
static const u8 sGuideHeading_8[] = _("Appendices");
static const u8 sGuideShort_25[] = _("GLOSSARY");
static const u8 sGuideTitle_25[] = _("Glossary of Terms");
static const u8 sGuideText_25[] = _("Algorithm: a set of steps for a task. Feedback loop: a process whose output becomes its own next input. Emotion object: a feeling held together with the moment that set it off and the move it wants to make. Flow: absorption so complete that time goes missing. Habit: a routine that runs itself. Lucid dream: a dream you know you are in. Neuroplasticity: the brain rewiring itself with use. Reframing: keeping an event and changing what it means.");
static const u8 sGuideShort_26[] = _("CASE STUDIES");
static const u8 sGuideTitle_26[] = _("Case Studies");
static const u8 sGuideText_26[] = _("Case 1: an engineer who expected any mistake to end everything. He asked, each time, how likely the worst really was. The fear lost its grip.\pCase 2: a designer whose inner voice said “not good enough”. She pictured the words shrinking and blurring, and replaced them with a clear, bright picture.\pCase 3: an owner who could not feel what he had. A week of daily practice gave him the day back.\pCase 4: a writer going round the same loop. She took the problem into her dreams.\pCase 5: a teacher still running an old crash. He revisited it, with help, until it could be held.");
static const u8 sGuideShort_27[] = _("FURTHER READING");
static const u8 sGuideTitle_27[] = _("Further Reading and Resources");
static const u8 sGuideText_27[] = _("On a brain that changes itself. On thinking, fast and slow. On the power of habit. On training the mind's rhythms. On the essentials of neuro-linguistic programming. On seeing the mind from the inside.\pCourses in mindfulness and stress. Practitioner training in cognitive behavioral therapy and in neuro-linguistic programming. Institutes that study lucid dreaming, flow, and the way the brain rewires itself.\pRead widely. Keep what works. Put the rest down without guilt.");

static const struct GuideSection sGuideSections[GUIDE_SECTIONS] =
{
    { sGuideLabel_0, sGuideHeading_0, 0, 3 },
    { sGuideLabel_1, sGuideHeading_1, 3, 4 },
    { sGuideLabel_2, sGuideHeading_2, 7, 4 },
    { sGuideLabel_3, sGuideHeading_3, 11, 3 },
    { sGuideLabel_4, sGuideHeading_4, 14, 3 },
    { sGuideLabel_5, sGuideHeading_5, 17, 3 },
    { sGuideLabel_6, sGuideHeading_6, 20, 2 },
    { sGuideLabel_7, sGuideHeading_7, 22, 3 },
    { sGuideLabel_8, sGuideHeading_8, 25, 3 },
};

static const struct GuideEntry sGuideEntries[GUIDE_ENTRIES] =
{
    { sGuideShort_0, sGuideTitle_0, sGuideText_0 },
    { sGuideShort_1, sGuideTitle_1, sGuideText_1 },
    { sGuideShort_2, sGuideTitle_2, sGuideText_2 },
    { sGuideShort_3, sGuideTitle_3, sGuideText_3 },
    { sGuideShort_4, sGuideTitle_4, sGuideText_4 },
    { sGuideShort_5, sGuideTitle_5, sGuideText_5 },
    { sGuideShort_6, sGuideTitle_6, sGuideText_6 },
    { sGuideShort_7, sGuideTitle_7, sGuideText_7 },
    { sGuideShort_8, sGuideTitle_8, sGuideText_8 },
    { sGuideShort_9, sGuideTitle_9, sGuideText_9 },
    { sGuideShort_10, sGuideTitle_10, sGuideText_10 },
    { sGuideShort_11, sGuideTitle_11, sGuideText_11 },
    { sGuideShort_12, sGuideTitle_12, sGuideText_12 },
    { sGuideShort_13, sGuideTitle_13, sGuideText_13 },
    { sGuideShort_14, sGuideTitle_14, sGuideText_14 },
    { sGuideShort_15, sGuideTitle_15, sGuideText_15 },
    { sGuideShort_16, sGuideTitle_16, sGuideText_16 },
    { sGuideShort_17, sGuideTitle_17, sGuideText_17 },
    { sGuideShort_18, sGuideTitle_18, sGuideText_18 },
    { sGuideShort_19, sGuideTitle_19, sGuideText_19 },
    { sGuideShort_20, sGuideTitle_20, sGuideText_20 },
    { sGuideShort_21, sGuideTitle_21, sGuideText_21 },
    { sGuideShort_22, sGuideTitle_22, sGuideText_22 },
    { sGuideShort_23, sGuideTitle_23, sGuideText_23 },
    { sGuideShort_24, sGuideTitle_24, sGuideText_24 },
    { sGuideShort_25, sGuideTitle_25, sGuideText_25 },
    { sGuideShort_26, sGuideTitle_26, sGuideText_26 },
    { sGuideShort_27, sGuideTitle_27, sGuideText_27 },
};
