// GENERATED by tools/gbadocs.py -- do not edit by hand.
//
// T-224: the NOTEBOOK's documents that are placed in the world. The words come from the user's approved
// drafts (tools/gbadocs.py --text), which are never kept in the docs repo. Each NB_DOC_<KEY> is one row of
// src/notebook.c's table, at its authored position, or nothing while the document is held.
#ifndef GUARD_DATA_NOTEBOOK_DOCUMENTS_H
#define GUARD_DATA_NOTEBOOK_DOCUMENTS_H

#define NB_DOC_LOOSE_PAGES_2

#define NB_DOC_LOOSE_PAGES_4

#define NB_DOC_LOOSE_PAGES_6

#define NB_DOC_LAB_NOTES_1

#define NB_DOC_LAB_NOTES_4

#define NB_DOC_LAB_NOTES_6

#define NB_DOC_RUN_LOGS_5

#define NB_DOC_RUN_LOGS_6

#define NB_DOC_CORRESPONDENCE_1

#define NB_DOC_CORRESPONDENCE_2

#define NB_DOC_CORRESPONDENCE_3

#define NB_DOC_CORRESPONDENCE_4

#define NB_DOC_CORRESPONDENCE_5

#define NB_DOC_CORRESPONDENCE_6

#define NB_DOC_THE_FILE_4

#define NB_DOC_THE_FILE_5

#define NB_DOC_THE_FILE_6

#define NB_DOC_PROSPECTUS_1

#define NB_DOC_PROSPECTUS_3

#define NB_DOC_PROSPECTUS_4

#define NB_DOC_PROSPECTUS_5

#define NB_DOC_PROSPECTUS_6

#define NB_DOC_PEER_REVIEW_3

#define NB_DOC_PEER_REVIEW_4

#endif // GUARD_DATA_NOTEBOOK_DOCUMENTS_H
