// GENERATED by tools/gbadocs.py -- do not edit by hand.
//
// T-297: where the NOTEBOOK's placed pages lie. src/reveal.c shimmers a spot while a page there, its gate open,
// is unread -- the lens shows where you have not been yet. {spot's script, read flag, gate flag, gate wanted}.
#ifndef GUARD_DATA_NOTEBOOK_FINDS_H
#define GUARD_DATA_NOTEBOOK_FINDS_H

extern const u8 NotebookDoc_CeladonCity_Condominiums_RoofRoom_8_2[];
extern const u8 NotebookDoc_CinnabarIsland_PokemonLab_Lounge_3_1[];
extern const u8 NotebookDoc_CinnabarIsland_PokemonLab_ResearchRoom_3_6[];
extern const u8 NotebookDoc_CinnabarIsland_PokemonLab_ResearchRoom_8_6[];
extern const u8 NotebookDoc_FiveIsland_RocketWarehouse_25_4[];
extern const u8 NotebookDoc_MtMoon_B2F_30_11[];
extern const u8 NotebookDoc_PokemonTower_2F_15_10[];
extern const u8 NotebookDoc_PokemonTower_3F_11_10[];
extern const u8 NotebookDoc_PokemonTower_5F_14_11[];
extern const u8 NotebookDoc_SaffronCity_Gym_14_9[];
extern const u8 NotebookDoc_SaffronCity_MrPsychicsHouse_5_5[];
extern const u8 NotebookDoc_SilphCo_1F_15_3[];
extern const u8 NotebookDoc_SilphCo_3F_6_13[];
extern const u8 NotebookDoc_SilphCo_4F_29_14[];
extern const u8 NotebookDoc_SilphCo_6F_17_12[];
extern const u8 NotebookDoc_ViridianForest_Grove_11_15[];
extern const u8 PewterCity_Museum_2F_EventScript_TheSortingFrame[];

static const struct { const u8 *script; u16 readFlag; u16 gateFlag; bool8 gateSet; } sNotebookFinds[] =
{
    { NotebookDoc_ViridianForest_Grove_11_15, FLAG_NOTEBOOK_DOC_LOOSE_PAGES_2, 0, FALSE },
    { NotebookDoc_CinnabarIsland_PokemonLab_Lounge_3_1, FLAG_NOTEBOOK_DOC_LOOSE_PAGES_4, 0, FALSE },
    { NotebookDoc_CinnabarIsland_PokemonLab_ResearchRoom_3_6, FLAG_NOTEBOOK_DOC_LAB_NOTES_1, 0, FALSE },
    { PewterCity_Museum_2F_EventScript_TheSortingFrame, FLAG_NOTEBOOK_DOC_LAB_NOTES_4, 0, FALSE },
    { NotebookDoc_CinnabarIsland_PokemonLab_ResearchRoom_8_6, FLAG_NOTEBOOK_DOC_LAB_NOTES_6, 0, FALSE },
    { NotebookDoc_PokemonTower_2F_15_10, FLAG_NOTEBOOK_DOC_CORRESPONDENCE_1, 0, FALSE },
    { NotebookDoc_CeladonCity_Condominiums_RoofRoom_8_2, FLAG_NOTEBOOK_DOC_CORRESPONDENCE_2, 0, FALSE },
    { NotebookDoc_SilphCo_3F_6_13, FLAG_NOTEBOOK_DOC_CORRESPONDENCE_3, 0, FALSE },
    { NotebookDoc_FiveIsland_RocketWarehouse_25_4, FLAG_NOTEBOOK_DOC_CORRESPONDENCE_4, 0, FALSE },
    { NotebookDoc_SaffronCity_MrPsychicsHouse_5_5, FLAG_NOTEBOOK_DOC_CORRESPONDENCE_6, FLAG_OWL_CONCEDED, TRUE },
    { NotebookDoc_SilphCo_4F_29_14, FLAG_NOTEBOOK_DOC_THE_FILE_4, 0, FALSE },
    { NotebookDoc_SilphCo_6F_17_12, FLAG_NOTEBOOK_DOC_THE_FILE_5, 0, FALSE },
    { NotebookDoc_PokemonTower_3F_11_10, FLAG_NOTEBOOK_DOC_THE_FILE_6, 0, FALSE },
    { NotebookDoc_MtMoon_B2F_30_11, FLAG_NOTEBOOK_DOC_PROSPECTUS_1, 0, FALSE },
    { NotebookDoc_SilphCo_1F_15_3, FLAG_NOTEBOOK_DOC_PROSPECTUS_3, 0, FALSE },
    { NotebookDoc_PokemonTower_5F_14_11, FLAG_NOTEBOOK_DOC_PROSPECTUS_5, 0, FALSE },
    { NotebookDoc_SaffronCity_Gym_14_9, FLAG_NOTEBOOK_DOC_PROSPECTUS_6, FLAG_DEFEATED_SABRINA, TRUE },
    { NotebookDoc_SaffronCity_MrPsychicsHouse_5_5, FLAG_NOTEBOOK_DOC_PEER_REVIEW_3, FLAG_OWL_CONCEDED, FALSE },
    { NotebookDoc_SaffronCity_MrPsychicsHouse_5_5, FLAG_NOTEBOOK_DOC_PEER_REVIEW_4, FLAG_OWL_CONCEDED, TRUE },
};

#endif // GUARD_DATA_NOTEBOOK_FINDS_H
