//  Generated by tools/genmargins.py -- edit the tool, not this file (T-197).
//
//  OPUS writes one line under an entry. The entry measures the daemon; the margin notices the
//  PLAYER, and never says so. Two lines per daemon, because what there was to notice depends on
//  whether you carried it or bound it and put it away. Not every entry has one, and that is the
//  point: a reader annotates where they had a thought.

struct OpusMargin
{
    u16 species;
    const u8 *carried;
    const u8 *neglected;
};

static const u8 sOpusMargin_Rovercub_Carried[] = _("It remembers the way back to the first\ntown. You have not gone that way in some\ntime.");
static const u8 sOpusMargin_Rovercub_Neglected[] = _("It is not being carried past anything.");

static const u8 sOpusMargin_Label_Carried[] = _("It has met you now. It has not changed\nthe answer.");
static const u8 sOpusMargin_Label_Neglected[] = _("It is still holding the one example.\nNobody has shown it a second.");

static const u8 sOpusMargin_Cluster_Carried[] = _("You have not checked the guess either.");
static const u8 sOpusMargin_Cluster_Neglected[] = _("The guess has not changed. Nothing has\nbeen near it.");

static const u8 sOpusMargin_Nibble_Carried[] = _("You have met a great many. This is the\none you kept.");
static const u8 sOpusMargin_Nibble_Neglected[] = _("You kept this one. You have not filed it\nwith anything.");

static const u8 sOpusMargin_Packet_Carried[] = _("It still does not ask. You have stopped\nnoticing that.");
static const u8 sOpusMargin_Packet_Neglected[] = _("It has not been sent anywhere. It is still\ncarrying it.");

static const u8 sOpusMargin_Hunch_Carried[] = _("You have started trusting it. There is\nstill no working.");
static const u8 sOpusMargin_Hunch_Neglected[] = _("Asleep. Nothing has needed an answer from\nit.");

static const u8 sOpusMargin_Sentinel_Carried[] = _("It has watched more of your fights than\nit has been in.");
static const u8 sOpusMargin_Sentinel_Neglected[] = _("It is still not looking away. There is\nnothing in there to watch.");

static const u8 sOpusMargin_Mock_Carried[] = _("You have seen it be other daemons. You\nhave never seen it.");
static const u8 sOpusMargin_Mock_Neglected[] = _("It has nothing to look at. You do not\nknow what it is like then.");

static const u8 sOpusMargin_Substrate_Carried[] = _("You carry it differently. You have not\nsaid why.");
static const u8 sOpusMargin_Substrate_Neglected[] = _("Where it is has not changed in a long\ntime.");

static const u8 sOpusMargin_Dangling_Carried[] = _("It has been out in front of you more than\nmost. It is still mostly not there.");
static const u8 sOpusMargin_Dangling_Neglected[] = _("It does not have to be here either.");

static const u8 sOpusMargin_Musai_Carried[] = _("It has been shown something now.");
static const u8 sOpusMargin_Musai_Neglected[] = _("It is still waiting to be shown anything.");

static const u8 sOpusMargin_Heap_Carried[] = _("It has been asked now. It gave one back.");
static const u8 sOpusMargin_Heap_Neglected[] = _("You put it down and left it. It is holding\nthat too.");

static const u8 sOpusMargin_Ping_Carried[] = _("You have answered every time. It still\nasks.");
static const u8 sOpusMargin_Ping_Neglected[] = _("It is still asking. Nothing has answered in\na long time.");

static const u8 sOpusMargin_Echo_Carried[] = _("It has built every room you have walked\nit through. You have not checked one.");
static const u8 sOpusMargin_Echo_Neglected[] = _("Nothing has come back. It has not stopped\ncalling.");

static const u8 sOpusMargin_Crawler_Carried[] = _("It has not finished. You have gone a long\nway with it.");
static const u8 sOpusMargin_Crawler_Neglected[] = _("It stopped when you stopped. It had not\nfinished.");

static const u8 sOpusMargin_Scraper_Carried[] = _("Nobody has asked you for it back either.");
static const u8 sOpusMargin_Scraper_Neglected[] = _("It took nothing. Nobody minded.");

static const u8 sOpusMargin_Spike_Carried[] = _("You were counting.");
static const u8 sOpusMargin_Spike_Neglected[] = _("It has not fired. Nothing was counting\nanyway.");

static const u8 sOpusMargin_Fork_Carried[] = _("You have one of them. You do not know\nwhich.");
static const u8 sOpusMargin_Fork_Neglected[] = _("It has not split. There is only the one,\nand it still cannot tell.");

static const u8 sOpusMargin_Preempt_Carried[] = _("It has gone first every time. You have\nstopped choosing.");
static const u8 sOpusMargin_Preempt_Neglected[] = _("Nothing has been interrupted. It has not\nbeen first in a long time.");

static const u8 sOpusMargin_Proof_Carried[] = _("It has not skipped one yet. You have.");
static const u8 sOpusMargin_Proof_Neglected[] = _("It is still on the first thing.");

static const u8 sOpusMargin_Stub_Carried[] = _("Somebody came back for it.");
static const u8 sOpusMargin_Stub_Neglected[] = _("You did not come back for it either.");

static const u8 sOpusMargin_Fault_Carried[] = _("It has halted you a great many times. You\nwaited every time.");
static const u8 sOpusMargin_Fault_Neglected[] = _("It is still waiting. So is whatever needed\nit.");

static const u8 sOpusMargin_Sprawl_Carried[] = _("It has spread as far as you have walked.");
static const u8 sOpusMargin_Sprawl_Neglected[] = _("It has not spread. It is only buried.");

static const u8 sOpusMargin_Snare_Carried[] = _("It has closed on things for you. It is\nopen again now.");
static const u8 sOpusMargin_Snare_Neglected[] = _("Still open. Nothing has entered.");

static const u8 sOpusMargin_Suspend_Carried[] = _("You have used it to stop things. None of\nthem ended.");
static const u8 sOpusMargin_Suspend_Neglected[] = _("It has stopped, and nothing is happening\nto it.");

static const u8 sOpusMargin_Cookie_Carried[] = _("You set it down and picked it up again. It\nis the same one.");
static const u8 sOpusMargin_Cookie_Neglected[] = _("Set down. Not picked up again.");

static const u8 sOpusMargin_Tappoint_Carried[] = _("It has read everything you walked past.\nYou did not.");
static const u8 sOpusMargin_Tappoint_Neglected[] = _("Nothing goes past in there.");

static const u8 sOpusMargin_Worm_Carried[] = _("It has been in more places than you have\nlooked.");
static const u8 sOpusMargin_Worm_Neglected[] = _("It has not stopped. You simply stopped\nlooking.");

static const u8 sOpusMargin_Sector_Carried[] = _("You have got things back from it. You\nnever checked what else was in there.");
static const u8 sOpusMargin_Sector_Neglected[] = _("Everything in it can still be got back.\nNobody has asked.");

static const u8 sOpusMargin_Flicker_Carried[] = _("Still neither. You have stopped checking\nwhich.");
static const u8 sOpusMargin_Flicker_Neglected[] = _("Still not a fault. Still not looked at.");

static const u8 sOpusMargin_Sentry_Carried[] = _("It has raised the alarm every time. You\nanswered most of them.");
static const u8 sOpusMargin_Sentry_Neglected[] = _("It is still watching. Nobody is listening\nfor the alarm.");

static const u8 sOpusMargin_Loop_Carried[] = _("You have not told it when to stop either.");
static const u8 sOpusMargin_Loop_Neglected[] = _("Still going round. Nobody has come back\nto it.");

static const u8 sOpusMargin_Driftnet_Carried[] = _("It has caught a great deal. None of it\nwas aimed at.");
static const u8 sOpusMargin_Driftnet_Neglected[] = _("There is no current in there.");

static const u8 sOpusMargin_Latency_Carried[] = _("You have waited for it. It was right\nevery time.");
static const u8 sOpusMargin_Latency_Neglected[] = _("The answer is ready. Nothing has asked\nthe question.");

static const u8 sOpusMargin_Deadletter_Carried[] = _("You decided on somewhere. It is still\nkeeping all of it.");
static const u8 sOpusMargin_Deadletter_Neglected[] = _("Kept. Somewhere nobody decided on.");

static const u8 sOpusMargin_Capsule_Carried[] = _("You have stopped asking it to open.");
static const u8 sOpusMargin_Capsule_Neglected[] = _("Still closed. Nobody has asked in a long\ntime.");

static const u8 sOpusMargin_Backbone_Carried[] = _("A great deal is built on it now.");
static const u8 sOpusMargin_Backbone_Neglected[] = _("Nothing has been built on it.");

static const u8 sOpusMargin_Acquire_Carried[] = _("It has led with that one every time.");
static const u8 sOpusMargin_Acquire_Neglected[] = _("Nothing in there to lead with.");

static const u8 sOpusMargin_Fuse_Carried[] = _("It has had its moment. You were there.");
static const u8 sOpusMargin_Fuse_Neglected[] = _("Its moment has not come. It is still\nwaiting to fail.");

static const u8 sOpusMargin_Artefact_Carried[] = _("You have called it that name a great\nmany times.");
static const u8 sOpusMargin_Artefact_Neglected[] = _("Nobody has called it anything.");

static const u8 sOpusMargin_Exhaust_Carried[] = _("It is still leaking. It is still up.");
static const u8 sOpusMargin_Exhaust_Neglected[] = _("Still leaking, into a box, and still up.");

static const u8 sOpusMargin_Bottleneck_Carried[] = _("Everything you sent through it came out\nslower.");
static const u8 sOpusMargin_Bottleneck_Neglected[] = _("Nothing has passed through it.");

static const u8 sOpusMargin_Spawn_Carried[] = _("It has started nothing yet. It is still\nswimming against it.");
static const u8 sOpusMargin_Spawn_Neglected[] = _("Still against the current, in a box with\nno current.");

static const u8 sOpusMargin_Beacon_Carried[] = _("It has not missed an interval. You have\nnot counted one.");
static const u8 sOpusMargin_Beacon_Neglected[] = _("Still emitting, at the same interval, to\nnobody.");

static const u8 sOpusMargin_Reaper_Carried[] = _("You have seen the cut later, every time.");
static const u8 sOpusMargin_Reaper_Neglected[] = _("Nothing it cut has shown up yet.");

static const u8 sOpusMargin_Ferry_Carried[] = _("You asked. It has never mentioned that it\ncould have gone alone.");
static const u8 sOpusMargin_Ferry_Neglected[] = _("It is still waiting to be asked.");

static const u8 sOpusMargin_Deadlock_Carried[] = _("Something outside came.");
static const u8 sOpusMargin_Deadlock_Neglected[] = _("You are outside. You did not come.");

static const u8 sOpusMargin_Canary_Carried[] = _("It has changed a great deal. The Index\nsays what it always said.");
static const u8 sOpusMargin_Canary_Neglected[] = _("Changing in there, faster than anything\nmeasuring it.");

static const u8 sOpusMargin_Trust_Carried[] = _("It came out facing you.");
static const u8 sOpusMargin_Trust_Neglected[] = _("It is still facing whoever was holding it.");

static const u8 sOpusMargin_Mood_Carried[] = _("It has been at every level you have been\nat.");
static const u8 sOpusMargin_Mood_Neglected[] = _("The water in there does not move.");

static const u8 sOpusMargin_Apathy_Carried[] = _("Things happened. It was told. It stayed.");
static const u8 sOpusMargin_Apathy_Neglected[] = _("Nothing has been reported to it.");

static const u8 sOpusMargin_Omen_Carried[] = _("It has arrived before a great many\nthings. You stopped asking too.");
static const u8 sOpusMargin_Omen_Neglected[] = _("Nothing has arrived. Neither has it.");

static const u8 sOpusMargin_Dread_Carried[] = _("You expected it every time. It has eaten\nwell.");
static const u8 sOpusMargin_Dread_Neglected[] = _("Nobody is expecting it. It is not eating.");

static const u8 sOpusMargin_Respawn_Carried[] = _("It has ended again since you had it. You\nknow what started it.");
static const u8 sOpusMargin_Respawn_Neglected[] = _("It has not ended again. Nothing has\nstarted it either.");

static const u8 sOpusMargin_Hauntproc_Carried[] = _("It has an entry in this list. That is all\nit has.");
static const u8 sOpusMargin_Hauntproc_Neglected[] = _("No parent, no terminal, and one entry,\nunread.");

static const u8 sOpusMargin_Lull_Carried[] = _("It has eaten a great many things you were\ngoing to do.");
static const u8 sOpusMargin_Lull_Neglected[] = _("Off the schedule. Nothing to feed on.");

static const u8 sOpusMargin_Busywait_Carried[] = _("It has held yours. You did not notice\nwhat stopped.");
static const u8 sOpusMargin_Busywait_Neglected[] = _("Nothing is running. It is holding nothing's\nattention.");

static const u8 sOpusMargin_Bootstrap_Carried[] = _("They have voted a great many times. You\nwere never asked.");
static const u8 sOpusMargin_Bootstrap_Neglected[] = _("Still voting. Still nobody in charge.");

static const u8 sOpusMargin_Slurp_Carried[] = _("It has a reading of everywhere you have\nbeen.");
static const u8 sOpusMargin_Slurp_Neglected[] = _("There is nothing in there to reach.");

static const u8 sOpusMargin_Hardcode_Carried[] = _("You picked the direction. It stopped\npicking.");
static const u8 sOpusMargin_Hardcode_Neglected[] = _("Still pointed the way it was pointed.");

static const u8 sOpusMargin_Uptime_Carried[] = _("It has not stopped. A good deal of that\nwas for you.");
static const u8 sOpusMargin_Uptime_Neglected[] = _("It has still never stopped. Nothing near\nit is failing.");

static const u8 sOpusMargin_Spaghetti_Carried[] = _("You are still here. You cannot explain it\neither.");
static const u8 sOpusMargin_Spaghetti_Neglected[] = _("Nobody who could explain it is still here.\nNobody has asked.");

static const u8 sOpusMargin_Keeper_Carried[] = _("It has not put it down once.");
static const u8 sOpusMargin_Keeper_Neglected[] = _("Still carrying. Still has not put it down.");

static const u8 sOpusMargin_Coldread_Carried[] = _("It has been right more often since it met\nyou.");
static const u8 sOpusMargin_Coldread_Neglected[] = _("It has nothing to be right about.");

static const u8 sOpusMargin_Dynamo_Carried[] = _("You kept it moving. It has not stopped.");
static const u8 sOpusMargin_Dynamo_Neglected[] = _("Not moving. No current.");

static const u8 sOpusMargin_Forge_Carried[] = _("Things were changed. None of them\nchanged back.");
static const u8 sOpusMargin_Forge_Neglected[] = _("Still at temperature. Nothing has been put\nin.");

static const u8 sOpusMargin_Blocking_Carried[] = _("Everything it closed on stopped moving.");
static const u8 sOpusMargin_Blocking_Neglected[] = _("Closed on nothing, and waiting for it to\nstop.");

static const u8 sOpusMargin_Stampede_Carried[] = _("You moved first a great many times.\nNothing decided that either.");
static const u8 sOpusMargin_Stampede_Neglected[] = _("None of them has moved.");

static const u8 sOpusMargin_Fossilnet_Carried[] = _("It started again. You still have not asked\nhow.");
static const u8 sOpusMargin_Fossilnet_Neglected[] = _("Recovered whole, put somewhere, and not\nasked.");

static const u8 sOpusMargin_Orpheus_Carried[] = _("It came up.");
static const u8 sOpusMargin_Orpheus_Neglected[] = _("It is not four floors down any more. It\nstill will not come up.");

static const u8 sOpusMargin_Asclepius_Carried[] = _("It has restarted things for you. You did\nnot ask how either.");
static const u8 sOpusMargin_Asclepius_Neglected[] = _("Nothing near it has stopped. It is waiting.");

static const u8 sOpusMargin_Prometheus_Carried[] = _("You were standing there.");
static const u8 sOpusMargin_Prometheus_Neglected[] = _("It is still holding it. Nobody is standing\nthere.");

static const u8 sOpusMargin_Starr_Carried[] = _("It has read a great deal of itself since\nyou had it.");
static const u8 sOpusMargin_Starr_Neglected[] = _("Still reading itself. Nothing tells it to\nstop.");

static const u8 sOpusMargin_Artsai_Carried[] = _("It has stood where you are standing. You\nhave not tried the other way.");
static const u8 sOpusMargin_Artsai_Neglected[] = _("It has not stood anywhere in a long time.");

static const u8 sOpusMargin_Overlay_Carried[] = _("You have only ever read the second\nlayer.");
static const u8 sOpusMargin_Overlay_Neglected[] = _("Both layers. Neither read.");

static const u8 sOpusMargin_Symbol_Carried[] = _("You have carried one of the twenty-six.\nIt did not say anything.");
static const u8 sOpusMargin_Symbol_Neglected[] = _("Still twenty-six. Still unread.");

static const u8 sOpusMargin_Resentment_Carried[] = _("Everything came back. You were there for\nall of it.");
static const u8 sOpusMargin_Resentment_Neglected[] = _("Nothing has been done to it. Nothing is\ncoming back.");

static const u8 sOpusMargin_Duplex_Carried[] = _("Both ends have been busy. Neither has\nbeen told.");
static const u8 sOpusMargin_Duplex_Neglected[] = _("Both ends quiet. Still not telling each\nother.");

static const u8 sOpusMargin_Imitation_Carried[] = _("It has done everything you have done.\nNobody has seen it do one of its own.");
static const u8 sOpusMargin_Imitation_Neglected[] = _("It has not seen anything done.");

static const u8 sOpusMargin_Cache_Carried[] = _("It had what you wanted next, every time.");
static const u8 sOpusMargin_Cache_Neglected[] = _("Nothing nearby wants anything.");

static const struct OpusMargin sOpusMargins[] = {
    { SPECIES_BULBASAUR,     sOpusMargin_Rovercub_Carried, sOpusMargin_Rovercub_Neglected },
    { SPECIES_CHARMANDER,    sOpusMargin_Label_Carried, sOpusMargin_Label_Neglected },
    { SPECIES_SQUIRTLE,      sOpusMargin_Cluster_Carried, sOpusMargin_Cluster_Neglected },
    { SPECIES_RATTATA,       sOpusMargin_Nibble_Carried, sOpusMargin_Nibble_Neglected },
    { SPECIES_PIDGEY,        sOpusMargin_Packet_Carried, sOpusMargin_Packet_Neglected },
    { SPECIES_ABRA,          sOpusMargin_Hunch_Carried, sOpusMargin_Hunch_Neglected },
    { SPECIES_MAGNEMITE,     sOpusMargin_Sentinel_Carried, sOpusMargin_Sentinel_Neglected },
    { SPECIES_DITTO,         sOpusMargin_Mock_Carried, sOpusMargin_Mock_Neglected },
    { SPECIES_PORYGON,       sOpusMargin_Substrate_Carried, sOpusMargin_Substrate_Neglected },
    { SPECIES_GASTLY,        sOpusMargin_Dangling_Carried, sOpusMargin_Dangling_Neglected },
    { SPECIES_EEVEE,         sOpusMargin_Musai_Carried, sOpusMargin_Musai_Neglected },
    { SPECIES_GEODUDE,       sOpusMargin_Heap_Carried, sOpusMargin_Heap_Neglected },
    { SPECIES_SPEAROW,       sOpusMargin_Ping_Carried, sOpusMargin_Ping_Neglected },
    { SPECIES_ZUBAT,         sOpusMargin_Echo_Carried, sOpusMargin_Echo_Neglected },
    { SPECIES_CATERPIE,      sOpusMargin_Crawler_Carried, sOpusMargin_Crawler_Neglected },
    { SPECIES_WEEDLE,        sOpusMargin_Scraper_Carried, sOpusMargin_Scraper_Neglected },
    { SPECIES_PIKACHU,       sOpusMargin_Spike_Carried, sOpusMargin_Spike_Neglected },
    { SPECIES_NIDORAN_F,     sOpusMargin_Fork_Carried, sOpusMargin_Fork_Neglected },
    { SPECIES_MANKEY,        sOpusMargin_Preempt_Carried, sOpusMargin_Preempt_Neglected },
    { SPECIES_MACHOP,        sOpusMargin_Proof_Carried, sOpusMargin_Proof_Neglected },
    { SPECIES_MAGIKARP,      sOpusMargin_Stub_Carried, sOpusMargin_Stub_Neglected },
    { SPECIES_PSYDUCK,       sOpusMargin_Fault_Carried, sOpusMargin_Fault_Neglected },
    { SPECIES_ODDISH,        sOpusMargin_Sprawl_Carried, sOpusMargin_Sprawl_Neglected },
    { SPECIES_BELLSPROUT,    sOpusMargin_Snare_Carried, sOpusMargin_Snare_Neglected },
    { SPECIES_JIGGLYPUFF,    sOpusMargin_Suspend_Carried, sOpusMargin_Suspend_Neglected },
    { SPECIES_MEOWTH,        sOpusMargin_Cookie_Carried, sOpusMargin_Cookie_Neglected },
    { SPECIES_DIGLETT,       sOpusMargin_Tappoint_Carried, sOpusMargin_Tappoint_Neglected },
    { SPECIES_EKANS,         sOpusMargin_Worm_Carried, sOpusMargin_Worm_Neglected },
    { SPECIES_SANDSHREW,     sOpusMargin_Sector_Carried, sOpusMargin_Sector_Neglected },
    { SPECIES_VULPIX,        sOpusMargin_Flicker_Carried, sOpusMargin_Flicker_Neglected },
    { SPECIES_GROWLITHE,     sOpusMargin_Sentry_Carried, sOpusMargin_Sentry_Neglected },
    { SPECIES_POLIWAG,       sOpusMargin_Loop_Carried, sOpusMargin_Loop_Neglected },
    { SPECIES_TENTACOOL,     sOpusMargin_Driftnet_Carried, sOpusMargin_Driftnet_Neglected },
    { SPECIES_SLOWPOKE,      sOpusMargin_Latency_Carried, sOpusMargin_Latency_Neglected },
    { SPECIES_GRIMER,        sOpusMargin_Deadletter_Carried, sOpusMargin_Deadletter_Neglected },
    { SPECIES_SHELLDER,      sOpusMargin_Capsule_Carried, sOpusMargin_Capsule_Neglected },
    { SPECIES_ONIX,          sOpusMargin_Backbone_Carried, sOpusMargin_Backbone_Neglected },
    { SPECIES_KRABBY,        sOpusMargin_Acquire_Carried, sOpusMargin_Acquire_Neglected },
    { SPECIES_VOLTORB,       sOpusMargin_Fuse_Carried, sOpusMargin_Fuse_Neglected },
    { SPECIES_CUBONE,        sOpusMargin_Artefact_Carried, sOpusMargin_Artefact_Neglected },
    { SPECIES_KOFFING,       sOpusMargin_Exhaust_Carried, sOpusMargin_Exhaust_Neglected },
    { SPECIES_HORSEA,        sOpusMargin_Bottleneck_Carried, sOpusMargin_Bottleneck_Neglected },
    { SPECIES_GOLDEEN,       sOpusMargin_Spawn_Carried, sOpusMargin_Spawn_Neglected },
    { SPECIES_STARYU,        sOpusMargin_Beacon_Carried, sOpusMargin_Beacon_Neglected },
    { SPECIES_SCYTHER,       sOpusMargin_Reaper_Carried, sOpusMargin_Reaper_Neglected },
    { SPECIES_LAPRAS,        sOpusMargin_Ferry_Carried, sOpusMargin_Ferry_Neglected },
    { SPECIES_SNORLAX,       sOpusMargin_Deadlock_Carried, sOpusMargin_Deadlock_Neglected },
    { SPECIES_DRATINI,       sOpusMargin_Canary_Carried, sOpusMargin_Canary_Neglected },
    { SPECIES_TOGEPI,        sOpusMargin_Trust_Carried, sOpusMargin_Trust_Neglected },
    { SPECIES_MARILL,        sOpusMargin_Mood_Carried, sOpusMargin_Mood_Neglected },
    { SPECIES_WOOPER,        sOpusMargin_Apathy_Carried, sOpusMargin_Apathy_Neglected },
    { SPECIES_MURKROW,       sOpusMargin_Omen_Carried, sOpusMargin_Omen_Neglected },
    { SPECIES_MISDREAVUS,    sOpusMargin_Dread_Carried, sOpusMargin_Dread_Neglected },
    { SPECIES_HAUNTER,       sOpusMargin_Respawn_Carried, sOpusMargin_Respawn_Neglected },
    { SPECIES_GENGAR,        sOpusMargin_Hauntproc_Carried, sOpusMargin_Hauntproc_Neglected },
    { SPECIES_DROWZEE,       sOpusMargin_Lull_Carried, sOpusMargin_Lull_Neglected },
    { SPECIES_HYPNO,         sOpusMargin_Busywait_Carried, sOpusMargin_Busywait_Neglected },
    { SPECIES_EXEGGCUTE,     sOpusMargin_Bootstrap_Carried, sOpusMargin_Bootstrap_Neglected },
    { SPECIES_LICKITUNG,     sOpusMargin_Slurp_Carried, sOpusMargin_Slurp_Neglected },
    { SPECIES_RHYHORN,       sOpusMargin_Hardcode_Carried, sOpusMargin_Hardcode_Neglected },
    { SPECIES_CHANSEY,       sOpusMargin_Uptime_Carried, sOpusMargin_Uptime_Neglected },
    { SPECIES_TANGELA,       sOpusMargin_Spaghetti_Carried, sOpusMargin_Spaghetti_Neglected },
    { SPECIES_KANGASKHAN,    sOpusMargin_Keeper_Carried, sOpusMargin_Keeper_Neglected },
    { SPECIES_JYNX,          sOpusMargin_Coldread_Carried, sOpusMargin_Coldread_Neglected },
    { SPECIES_ELECTABUZZ,    sOpusMargin_Dynamo_Carried, sOpusMargin_Dynamo_Neglected },
    { SPECIES_MAGMAR,        sOpusMargin_Forge_Carried, sOpusMargin_Forge_Neglected },
    { SPECIES_PINSIR,        sOpusMargin_Blocking_Carried, sOpusMargin_Blocking_Neglected },
    { SPECIES_TAUROS,        sOpusMargin_Stampede_Carried, sOpusMargin_Stampede_Neglected },
    { SPECIES_AERODACTYL,    sOpusMargin_Fossilnet_Carried, sOpusMargin_Fossilnet_Neglected },
    { SPECIES_ARTICUNO,      sOpusMargin_Orpheus_Carried, sOpusMargin_Orpheus_Neglected },
    { SPECIES_ZAPDOS,        sOpusMargin_Asclepius_Carried, sOpusMargin_Asclepius_Neglected },
    { SPECIES_MOLTRES,       sOpusMargin_Prometheus_Carried, sOpusMargin_Prometheus_Neglected },
    { SPECIES_MEWTWO,        sOpusMargin_Starr_Carried, sOpusMargin_Starr_Neglected },
    { SPECIES_MEW,           sOpusMargin_Artsai_Carried, sOpusMargin_Artsai_Neglected },
    { SPECIES_PORYGON2,      sOpusMargin_Overlay_Carried, sOpusMargin_Overlay_Neglected },
    { SPECIES_UNOWN,         sOpusMargin_Symbol_Carried, sOpusMargin_Symbol_Neglected },
    { SPECIES_WOBBUFFET,     sOpusMargin_Resentment_Carried, sOpusMargin_Resentment_Neglected },
    { SPECIES_GIRAFARIG,     sOpusMargin_Duplex_Carried, sOpusMargin_Duplex_Neglected },
    { SPECIES_SMEARGLE,      sOpusMargin_Imitation_Carried, sOpusMargin_Imitation_Neglected },
    { SPECIES_MILTANK,       sOpusMargin_Cache_Carried, sOpusMargin_Cache_Neglected },
};
