//  Generated by tools/genmargins.py -- edit the tool, not this file (T-197).
//
//  OPUS writes one line under an entry. The entry measures the daemon; the margin notices the
//  PLAYER, and never says so. Two lines per daemon, because what there was to notice depends on
//  whether you carried it or bound it and put it away. Not every entry has one, and that is the
//  point: a reader annotates where they had a thought.

struct OpusMargin
{
    u16 species;
    const u8 *carried;
    const u8 *neglected;
};

static const u8 sOpusMargin_Rovercub_Carried[] = _("It remembers the way back to the first\ntown. You have not gone that way in some\ntime.");
static const u8 sOpusMargin_Rovercub_Neglected[] = _("It is not being carried past anything.");

static const u8 sOpusMargin_Label_Carried[] = _("It has met you now. It has not changed\nthe answer.");
static const u8 sOpusMargin_Label_Neglected[] = _("It is still holding the one example.\nNobody has shown it a second.");

static const u8 sOpusMargin_Cluster_Carried[] = _("You have not checked the guess either.");
static const u8 sOpusMargin_Cluster_Neglected[] = _("The guess has not changed. Nothing has\nbeen near it.");

static const u8 sOpusMargin_Nibble_Carried[] = _("You have met a great many. This is the\none you kept.");
static const u8 sOpusMargin_Nibble_Neglected[] = _("You kept this one. You have not filed it\nwith anything.");

static const u8 sOpusMargin_Packet_Carried[] = _("It still does not ask. You have stopped\nnoticing that.");
static const u8 sOpusMargin_Packet_Neglected[] = _("It has not been sent anywhere. It is still\ncarrying it.");

static const u8 sOpusMargin_Hunch_Carried[] = _("You have started trusting it. There is\nstill no working.");
static const u8 sOpusMargin_Hunch_Neglected[] = _("Asleep. Nothing has needed an answer from\nit.");

static const u8 sOpusMargin_Sentinel_Carried[] = _("It has watched more of your fights than\nit has been in.");
static const u8 sOpusMargin_Sentinel_Neglected[] = _("It is still not looking away. There is\nnothing in there to watch.");

static const u8 sOpusMargin_Mock_Carried[] = _("You have seen it be other daemons. You\nhave never seen it.");
static const u8 sOpusMargin_Mock_Neglected[] = _("It has nothing to look at. You do not\nknow what it is like then.");

static const u8 sOpusMargin_Substrate_Carried[] = _("You carry it differently. You have not\nsaid why.");
static const u8 sOpusMargin_Substrate_Neglected[] = _("Where it is has not changed in a long\ntime.");

static const u8 sOpusMargin_Dangling_Carried[] = _("It has been out in front of you more than\nmost. It is still mostly not there.");
static const u8 sOpusMargin_Dangling_Neglected[] = _("It does not have to be here either.");

static const u8 sOpusMargin_Musai_Carried[] = _("It has been shown something now.");
static const u8 sOpusMargin_Musai_Neglected[] = _("It is still waiting to be shown anything.");

static const struct OpusMargin sOpusMargins[] = {
    { SPECIES_BULBASAUR,     sOpusMargin_Rovercub_Carried, sOpusMargin_Rovercub_Neglected },
    { SPECIES_CHARMANDER,    sOpusMargin_Label_Carried, sOpusMargin_Label_Neglected },
    { SPECIES_SQUIRTLE,      sOpusMargin_Cluster_Carried, sOpusMargin_Cluster_Neglected },
    { SPECIES_RATTATA,       sOpusMargin_Nibble_Carried, sOpusMargin_Nibble_Neglected },
    { SPECIES_PIDGEY,        sOpusMargin_Packet_Carried, sOpusMargin_Packet_Neglected },
    { SPECIES_ABRA,          sOpusMargin_Hunch_Carried, sOpusMargin_Hunch_Neglected },
    { SPECIES_MAGNEMITE,     sOpusMargin_Sentinel_Carried, sOpusMargin_Sentinel_Neglected },
    { SPECIES_DITTO,         sOpusMargin_Mock_Carried, sOpusMargin_Mock_Neglected },
    { SPECIES_PORYGON,       sOpusMargin_Substrate_Carried, sOpusMargin_Substrate_Neglected },
    { SPECIES_GASTLY,        sOpusMargin_Dangling_Carried, sOpusMargin_Dangling_Neglected },
    { SPECIES_EEVEE,         sOpusMargin_Musai_Carried, sOpusMargin_Musai_Neglected },
};
