//  Generated by tools/gbaseasons.py -- edit the tool (and the looks, in tools/seasonmock.py), not this file.
//  T-359: the seasons, by palette (vision.md 9.21). Each table is gTileset_General's palette 0 in that season;
//  sSeasonFollow names the entries of General's rows 1..6 that copy one of its greens, and which slot they copy.

#define SEASON_SLOT_MASK 0xFF1E   // palette 0's slots a season replaces: 1, 2, 3, 4, 8, 9, 10, 11, 12, 13, 14, 15

static const u16 sSeasonRow0[SEASON_COUNT][16] =
{
    [SEASON_WINTER] = { 0x0000, 0x73DA, 0x6B76, 0x5B14, 0x3E0D, 0x2590, 0x14E9, 0x7C1F, 0x73BA, 0x6F99, 0x6F99, 0x6F99, 0x77BB, 0x6F99, 0x6B78, 0x6736 },
    [SEASON_SPRING] = { 0x0000, 0x3FBB, 0x2713, 0x1E2A, 0x1987, 0x2590, 0x14E9, 0x7C1F, 0x3B33, 0x32FF, 0x2DDD, 0x1899, 0x4776, 0x3311, 0x268C, 0x1A26 },
    [SEASON_SUMMER] = { 0 },
    [SEASON_AUTUMN] = { 0x0000, 0x335F, 0x1E18, 0x1510, 0x108A, 0x2590, 0x14E9, 0x7C1F, 0x4316, 0x3B1F, 0x361D, 0x20D8, 0x4F58, 0x3AF3, 0x326F, 0x260A },
};

static const u8 sSeasonFollow[][2] =   // { BG palette index, the row 0 slot it copies }
{
    { 31, 13 },
    { 63, 13 },
    { 95, 13 },
};
