// GENERATED by tools/gbamovemenu.py -- do not edit by hand.
//
// EIGHTEEN TYPES AS EIGHTEEN WORDS. vision.md 9.4 says colour carries the argument; this is the
// table that lets a screen say so in TEXT rather than in a sprite. Each is step 4 of the type's ramp.
//
// Read by the move menu (battle_move_menu.h) and by the Index entry (pokedex_screen.c). A type
// cannot be one colour in battle and another in the Index, so there is one table and not two.
#ifndef GUARD_DATA_TYPE_COLOURS_H
#define GUARD_DATA_TYPE_COLOURS_H

#include "constants/pokemon.h"

static const u16 sTypeTextColor[] =
{
    [TYPE_NORMAL  ] = RGB(12, 12, 11), // CONTENT
    [TYPE_FIGHTING] = RGB( 6,  8, 10), // LOGIC
    [TYPE_FLYING  ] = RGB(13,  4,  4), // VECTOR
    [TYPE_POISON  ] = RGB( 5,  6,  3), // CORRUPT
    [TYPE_GROUND  ] = RGB(10,  8,  5), // STRATUM
    [TYPE_ROCK    ] = RGB( 8,  8,  9), // LEGACY
    [TYPE_BUG     ] = RGB( 8,  9,  4), // SWARM
    [TYPE_GHOST   ] = RGB( 6,  4,  7), // LATENT
    [TYPE_FIRE    ] = RGB(14, 10,  3), // ENTROPY
    [TYPE_WATER   ] = RGB( 4,  7, 11), // FLOW
    [TYPE_GRASS   ] = RGB( 6, 10,  6), // GROWTH
    [TYPE_ELECTRIC] = RGB( 5, 12, 12), // SIGNAL
    [TYPE_PSYCHIC ] = RGB(11,  5, 10), // CONTEXT
    [TYPE_ICE     ] = RGB(10, 13, 14), // FROZEN
    [TYPE_DRAGON  ] = RGB( 3,  8,  7), // EMERGENT
    [TYPE_MYSTERY ] = RGB( 9,  9,  9), // ORACLE -- no hue: the box's grey
    [TYPE_STEEL   ] = RGB(12, 11,  6), // HARDENED
    [TYPE_DARK    ] = RGB( 2,  2,  3), // OPAQUE
};

#endif // GUARD_DATA_TYPE_COLOURS_H
