// GENERATED by tools/gbamovemenu.py -- do not edit by hand.
//
// T-201: THE INDEX'S CATEGORY PAGE PULSES THE TYPE. The selection ring around a bound daemon cycles
// through its type's hue -- first type, dark, second type, dark -- so the page that shows a family
// together teaches the chart by pulsing it. [0] is the ring at its brightest, [1] its inner line.
#ifndef GUARD_DATA_TYPE_RING_COLOURS_H
#define GUARD_DATA_TYPE_RING_COLOURS_H

#include "constants/pokemon.h"

static const u16 sTypeRingColor[][2] =
{
    [TYPE_NORMAL  ] = { RGB(24, 23, 20), RGB(28, 27, 26) }, // CONTENT
    [TYPE_FIGHTING] = { RGB(12, 15, 19), RGB(22, 24, 26) }, // LOGIC
    [TYPE_FLYING  ] = { RGB(25,  9,  9), RGB(28, 21, 21) }, // VECTOR
    [TYPE_POISON  ] = { RGB(10, 11,  6), RGB(22, 22, 20) }, // CORRUPT
    [TYPE_GROUND  ] = { RGB(19, 15,  9), RGB(26, 24, 21) }, // STRATUM
    [TYPE_ROCK    ] = { RGB(16, 16, 17), RGB(24, 24, 25) }, // LEGACY
    [TYPE_BUG     ] = { RGB(16, 18,  9), RGB(24, 25, 21) }, // SWARM
    [TYPE_GHOST   ] = { RGB(11,  9, 14), RGB(22, 21, 23) }, // LATENT
    [TYPE_FIRE    ] = { RGB(27, 19,  6), RGB(29, 26, 19) }, // ENTROPY
    [TYPE_WATER   ] = { RGB( 9, 13, 21), RGB(21, 23, 27) }, // FLOW
    [TYPE_GRASS   ] = { RGB(11, 19, 12), RGB(22, 26, 22) }, // GROWTH
    [TYPE_ELECTRIC] = { RGB(10, 23, 23), RGB(22, 27, 27) }, // SIGNAL
    [TYPE_PSYCHIC ] = { RGB(21, 10, 19), RGB(27, 22, 26) }, // CONTEXT
    [TYPE_ICE     ] = { RGB(20, 25, 27), RGB(26, 28, 29) }, // FROZEN
    [TYPE_DRAGON  ] = { RGB( 6, 15, 13), RGB(20, 24, 23) }, // EMERGENT
    [TYPE_MYSTERY ] = { RGB( 9,  9,  9), RGB(21, 21, 21) }, // ORACLE -- no hue: the box's grey
    [TYPE_STEEL   ] = { RGB(24, 21, 12), RGB(28, 26, 22) }, // HARDENED
    [TYPE_DARK    ] = { RGB( 5,  5,  6), RGB(19, 19, 19) }, // OPAQUE
};

#endif // GUARD_DATA_TYPE_RING_COLOURS_H
