// Generated by tools/genbrain.py -- do not edit. T-271: the USER card's brain, one drawing and two states.
// '.' fill, 'f' fold, 'o' outline, 'h' halo (lit only), ' ' nothing.
#define BRAIN_W 26
#define BRAIN_H 22
static const char sUnderstandingBrain[BRAIN_H][BRAIN_W + 1] = {
    "       hhhhoooohhhh       ",
    "     hhoooo....oooohh     ",
    "    hoo............ooh    ",
    "   ho......f...f.....oh   ",
    "  ho........f.f.......oh  ",
    " ho...f.....fff..f.....oh ",
    "ho..ff.ff.........ff....oh",
    "ho......f...........f...oh",
    "ho.......f...ff.....f...oh",
    "ho.....f.......f........oh",
    "ho...ff.fff.....f.......oh",
    "ho.........f....f.......oh",
    " ho......fff...........oh ",
    "  ho....f...f..........oh ",
    "   ho............ffff..oh ",
    "    hoo................oh ",
    "     hhoooo......ffff..oh ",
    "       hhhhoo...o....ooh  ",
    "           ho...ooooohh   ",
    "           ho...ohhhh     ",
    "            hoooh         ",
    "             hhh          ",
};
