// Generated by tools/genbrain.py -- do not edit. T-331: the USER card's brain, a lobe per understanding.
// '1'-'7' a lobe (genbrain.py has the map), 'f' fold, 'o' outline, 'h' halo (all seven held), ' ' nothing.
#define BRAIN_W 26
#define BRAIN_H 22
static const char sUnderstandingBrain[BRAIN_H][BRAIN_W + 1] = {
    "       hhhhoooohhhh       ",
    "     hhoooo5555oooohh     ",
    "    hoo445555555553ooh    ",
    "   ho444455f555f55333oh   ",
    "  ho44444555f5f5553333oh  ",
    " ho444f44555fff55f33333oh ",
    "ho44ff4ff555555555ff3333oh",
    "ho444444f55555555533f333oh",
    "ho4444444f2666622233f333oh",
    "ho44444f4266666622333333oh",
    "ho444ff4ff66666622333333oh",
    "ho44444442266662f2333333oh",
    " ho444444ff2222f2233333oh ",
    "  ho4444f22f22222233337oh ",
    "   ho444422222222ffff77oh ",
    "    hoo4422222222237777oh ",
    "     hhoooo222277ffff77oh ",
    "       hhhhoo111o7777ooh  ",
    "           ho111ooooohh   ",
    "           ho111ohhhh     ",
    "            hoooh         ",
    "             hhh          ",
};
