// GENERATED by DAEMONS tools/gbawisdom.py from docs/wisdom.json -- do not edit by hand.
// T-390 (bible 0.7, Wisdom): the seven insights, one for each MARK and its understanding held together.
// Every word DRAFT. Included once, by notebook.c.
#ifndef GUARD_DATA_WISDOM_H
#define GUARD_DATA_WISDOM_H

static const u8 sInsightTitle_Diligence[] = _("DILIGENCE");
static const u8 sInsightText_Diligence[] = _("Learned twice, the names were a record. Used once, they were mine.");
static const u8 sInsightArrival_Diligence[] = _("An insight arrives.\p“Learned twice, the names were a\nrecord. Used once, they were mine.”\pYou write it down in the NOTEBOOK.");
static const u8 sInsightTitle_Chastity[] = _("CHASTITY");
static const u8 sInsightText_Chastity[] = _("Small steps find a bottom. Only stillness tells me it is the right one.");
static const u8 sInsightArrival_Chastity[] = _("An insight arrives.\p“Small steps find a bottom. Only\nstillness tells me it is the right\lone.”\pYou write it down in the NOTEBOOK.");
static const u8 sInsightTitle_Charity[] = _("CHARITY");
static const u8 sInsightText_Charity[] = _("What comes back is not what left. Listen to what arrives, not what I expected.");
static const u8 sInsightArrival_Charity[] = _("An insight arrives.\p“What comes back is not what left.\nListen to what arrives, not what I\lexpected.”\pYou write it down in the NOTEBOOK.");
static const u8 sInsightTitle_Kindness[] = _("KINDNESS");
static const u8 sInsightText_Kindness[] = _("A line through the points is a theory. Walking it is the part no book can do.");
static const u8 sInsightArrival_Kindness[] = _("An insight arrives.\p“A line through the points is a\ntheory. Walking it is the part no\lbook can do.”\pYou write it down in the NOTEBOOK.");
static const u8 sInsightTitle_Temperance[] = _("TEMPERANCE");
static const u8 sInsightText_Temperance[] = _("The score was right. It never counted the middle, and the middle is where I stood.");
static const u8 sInsightArrival_Temperance[] = _("An insight arrives.\p“The score was right. It never\ncounted the middle, and the middle is\lwhere I stood.”\pYou write it down in the NOTEBOOK.");
static const u8 sInsightTitle_Patience[] = _("PATIENCE");
static const u8 sInsightText_Patience[] = _("A frame shows what it holds. Patience shows what was there all along, just outside it.");
static const u8 sInsightArrival_Patience[] = _("An insight arrives.\p“A frame shows what it holds.\nPatience shows what was there all\lalong, just outside it.”\pYou write it down in the NOTEBOOK.");
static const u8 sInsightTitle_Humility[] = _("HUMILITY");
static const u8 sInsightText_Humility[] = _("Every step made sense on its own. Knowing which to keep means stepping out of the loop.");
static const u8 sInsightArrival_Humility[] = _("An insight arrives.\p“Every step made sense on its own.\nKnowing which to keep means stepping\lout of the loop.”\pYou write it down in the NOTEBOOK.");

//  The INSIGHT section's entries, in the MARKS' order (notebook.c rule 2: the authored order, never the order found).
#define NB_INSIGHT_ENTRIES \
    { NB_INSIGHT, NB_KIND_TEXT, 0, FLAG_INSIGHT_DILIGENCE, 0, sInsightTitle_Diligence, sInsightText_Diligence }, \
    { NB_INSIGHT, NB_KIND_TEXT, 0, FLAG_INSIGHT_CHASTITY, 0, sInsightTitle_Chastity, sInsightText_Chastity }, \
    { NB_INSIGHT, NB_KIND_TEXT, 0, FLAG_INSIGHT_CHARITY, 0, sInsightTitle_Charity, sInsightText_Charity }, \
    { NB_INSIGHT, NB_KIND_TEXT, 0, FLAG_INSIGHT_KINDNESS, 0, sInsightTitle_Kindness, sInsightText_Kindness }, \
    { NB_INSIGHT, NB_KIND_TEXT, 0, FLAG_INSIGHT_TEMPERANCE, 0, sInsightTitle_Temperance, sInsightText_Temperance }, \
    { NB_INSIGHT, NB_KIND_TEXT, 0, FLAG_INSIGHT_PATIENCE, 0, sInsightTitle_Patience, sInsightText_Patience }, \
    { NB_INSIGHT, NB_KIND_TEXT, 0, FLAG_INSIGHT_HUMILITY, 0, sInsightTitle_Humility, sInsightText_Humility }, \


//  What makes each arrive: the MARK, the understanding, and the flag that says it has.
struct WisdomPair { u16 mark; u16 root; u16 insight; const u8 *arrival; };
static const struct WisdomPair sWisdomPairs[] =
{
    { FLAG_BADGE01_GET, FLAG_UNDERSTANDING_SCHOOL, FLAG_INSIGHT_DILIGENCE, sInsightArrival_Diligence },
    { FLAG_BADGE02_GET, FLAG_UNDERSTANDING_FIRST, FLAG_INSIGHT_CHASTITY, sInsightArrival_Chastity },
    { FLAG_BADGE03_GET, FLAG_UNDERSTANDING_RETURN, FLAG_INSIGHT_CHARITY, sInsightArrival_Charity },
    { FLAG_BADGE04_GET, FLAG_UNDERSTANDING_GUIDE, FLAG_INSIGHT_KINDNESS, sInsightArrival_Kindness },
    { FLAG_BADGE05_GET, FLAG_UNDERSTANDING_SCORN, FLAG_INSIGHT_TEMPERANCE, sInsightArrival_Temperance },
    { FLAG_BADGE06_GET, FLAG_UNDERSTANDING_READING, FLAG_INSIGHT_PATIENCE, sInsightArrival_Patience },
    { FLAG_BADGE07_GET, FLAG_UNDERSTANDING_NOTES, FLAG_INSIGHT_HUMILITY, sInsightArrival_Humility },
};

#endif // GUARD_DATA_WISDOM_H
