PalletTown_Text_OakDontGoOut::
    .string "CRYSTAL: Hey! Wait! Don't go out!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "CRYSTAL: It's unsafe! UNBOUND\n"
    .string "DAEMONS run loose out here!\p"
    .string "You need your own DAEMON for your\n"
    .string "protection. I know!\p"
    .string "Here, come with me!$"

PalletTown_Text_RaisingMonsToo::
    .string "The QUICKSILVER thing? Night, it\n"
    .string "was. Two of them in the room.\p"
    .string "A surge, they said.\p"
    .string "White, I heard. Like an ordinary\n"
    .string "hare.\p"
    .string "Far room. The one past the stairs.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and DAEMON as data via PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "CRYSTAL DAEMON\n"
    .string "RESEARCH LAB$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s house$"

PalletTown_Text_TownSign::
    .string "BLANCHE TOWN\n"
    .string "Shades of your\l"
    .string "journey await!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "CRYSTAL: Ah, {PLAYER}! You're back,\n"
    .string "are you?\p"
    .string "How much have you filled in your\n"
    .string "INDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've bound {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting in\n"
    .string "an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've bound… {STR_VAR_2}!? Now, this\n"
    .string "is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come. Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "CRYSTAL: Ah, {PLAYER}! You seem to\n"
    .string "be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"

