FourIsland_Text_IslandSign::
    .string "FOUR ISLAND\n"
    .string "Warm all the way round,\l"
    .string "and one cold room in it$"

FourIsland_Text_LoreleiHasReturned::
    .string "PHLEGMATIC has returned.\p"
    .string "Did she find the city life too\n"
    .string "stressful, I wonder?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
	.string "PHLEGMATIC has gone back.\p"
	.string "She told the CORPUS people in\n"
	.string "STILLFALL CAVE to keep their hands\l"
	.string "off the DAEMON there.\p"
	.string "She didn't raise her voice. They\n"
	.string "left anyway.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{RIVAL}: Hey! {PLAYER}!\p"
    .string "What are you doing here in THE\n"
    .string "MARGINS?\p"
    .string "You should quit copying me, you\n"
    .string "know?\p"
    .string "Anyways, I already got my DAEMONS\n"
    .string "EGG, so I'm done with this island.\p"
    .string "Heh, I bet you don't even know\n"
    .string "about DAEMON EGGS.\p"
    .string "You'll never fill your GLOBAL INDEX\n"
    .string "that way.\p"
    .string "By the way, I saw someone we both\n"
    .string "know on this island.\p"
    .string "Why don't you go look around if it\n"
    .string "makes you curious?\p"
    .string "Me, I don't have the time to waste.\p"
    .string "Be smelling ya!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
	.string "Oh, you found me!\p"
	.string "PHLEGMATIC sits by the water a\n"
	.string "whole day when she comes home.\p"
	.string "Grown-ups say she's wasting time.\n"
	.string "She says the water isn't.$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Ooh, chilly!\p"
    .string "I made a slushie using ice I\n"
    .string "shaved inside STILLFALL CAVE.\p"
    .string "It's chilly and tasty!$"

FourIsland_Text_LoreleisHouse::
    .string "PHLEGMATIC'S HOUSE$"

