FourIsland_Text_IslandSign::
    .string "FOUR ISLAND\n"
    .string "The Warm, Blue, Floe Island$"

FourIsland_Text_LoreleiHasReturned::
    .string "PHLEGMATIC has returned.\p"
    .string "Did she find the city life too\n"
    .string "stressful, I wonder?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "PHLEGMATIC has gone back.\p"
    .string "The FERRY she has, I imagine it to\n"
    .string "be the one she met as a child.\p"
    .string "I believe it was in ICEFALL CAVE\n"
    .string "that she bound it.\p"
    .string "Perhaps that DAEMON has been with\n"
    .string "her ever since.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{RIVAL}: Hey! {PLAYER}!\p"
    .string "What are you doing here in the\n"
    .string "SEVII ISLANDS?\p"
    .string "You should quit copying me, you\n"
    .string "know?\p"
    .string "Anyways, I already got my DAEMONS\n"
    .string "EGG, so I'm done with this island.\p"
    .string "Heh, I bet you don't even know\n"
    .string "about DAEMON EGGS.\p"
    .string "You'll never fill your GLOBAL INDEX\n"
    .string "that way.\p"
    .string "By the way, I saw someone we both\n"
    .string "know on this island.\p"
    .string "Why don't you go look around if it\n"
    .string "makes you curious?\p"
    .string "Me, I don't have the time to waste.\p"
    .string "Be smelling ya!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
	.string "Oh, you found me! Please don't\n"
    .string "tell PHLEGMATIC.\p"
    .string "Did you know that PHLEGMATIC has\n"
    .string "lots and lots of stuffed dolls?\p"
    .string "Every time she comes back to FOUR\n"
    .string "ISLAND, her collection grows!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Ooh, chilly!\p"
    .string "I made a slushie using ice I\n"
    .string "shaved inside ICEFALL CAVE.\p"
    .string "It's chilly and tasty!$"

FourIsland_Text_LoreleisHouse::
    .string "PHLEGMATIC'S HOUSE$"

